### ISSUE TITLE
Issues of handling Measurement Summary Hash

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#100]
There seems to be some issues for the Responder to deal with Measurement Summary Hash.

1) Invalid "Requested measurement hash type" (values other than 0x0, 0x1, 0xff) now returns Unspecified error instead of InvalidRequest or UnsupportedRequest.
```
Requested measurement summary hash Type:
0x0 . No measurement summary hash.
0x1 . TCB measurement hash.
0xFF . All measurements hash.
All other values reserved.
```
2) Only CHALLENGE handler will verify Measurement Capability. KEY_EXCHANGE and PSK_EXCHANGE should also apply it?
https://github.com/DMTF/libspdm/commit/37798f00071935cef81d729ccd0953fabc224a21

3) return value of spdm_hash_all was not checked in spdm_generate_measurement_summary_hash (and some other places in crypto_service.c)

**Comment by jyao1** [comment]
agree

**Comment by steven-bellock** [comment]
Approved.
1. Should (probably) use InvalidRequest. Also need to flesh out error codes to make them less ambiguous. @raghuncstate will file an issue with the security task force to clarify.
2. Agree. @raghuncstate will file an issue with security task force to include KEY_EXCHANGE and PSK_EXCHANGE in the MEAS_CAP section of CAPABILITIES response.
3. Is covered by https://github.com/DMTF/libspdm/issues/75

**Comment by raghuncstate** [comment]
Filed https://github.com/DMTF/Security-TF/issues/1473 and https://github.com/DMTF/Security-TF/issues/1472.

**Comment by liyi77** [comment]
@rw8896 
1. Invalid "Requested measurement hash type" (values other than 0x0, 0x1, 0xff) now returns Unspecified error instead of InvalidRequest or UnsupportedRequest.

Does it means the return value check of spdm_generate_measurement_summary_hash()?
https://github.com/DMTF/libspdm/blob/50c2b1a389f45c3060aa040148cdd1384214a074/library/spdm_responder_lib/challenge_auth.c#L166-L172

The return value will be related to internal hash calculation fail or spdm_measurement_collection(), these cases seems need to return Unspecified.
How about adding some pre-check such if (spdm_request->header.param2 != 0 && spdm_request->header.param2 != 1 ...)
instead of modifying the existing check？

**Comment by rw8896** [comment]
> @rw8896
> 
> 1. Invalid "Requested measurement hash type" (values other than 0x0, 0x1, 0xff) now returns Unspecified error instead of InvalidRequest or UnsupportedRequest.
> 
> Does it means the return value check of spdm_generate_measurement_summary_hash()?
> 
> https://github.com/DMTF/libspdm/blob/50c2b1a389f45c3060aa040148cdd1384214a074/library/spdm_responder_lib/challenge_auth.c#L166-L172
> 
> The return value will be related to internal hash calculation fail or spdm_measurement_collection(), these cases seems need to return Unspecified. How about adding some pre-check such if (spdm_request->header.param2 != 0 && spdm_request->header.param2 != 1 ...) instead of modifying the existing check？

@liyi77 I'm so sorry that I missed your question.
Yes, we could check param2 but my checking is a little bit different than yours.

In challenge_auth.c, spdm_get_measurement_summary_hash_size will also check param2.
`	measurement_summary_hash_size = spdm_get_measurement_summary_hash_size( `

So you could check measurement_summary_hash_size against param2 after that
```

if ((measurement_summary_hash_size == 0) && (SpdmRequest->Header.Param2 != SPDM_CHALLENGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH)) {
    /* return invalid request */
}
```
This way avoids duplicated codes.
Hope this makes sense.

**Comment by rw8896** [comment]
Sync with @jyao1 since I saw you just closed this issue (and that's when I found @liyi77 's question).

**Comment by jyao1** [comment]
Yeah, we close it after we merge the patch.

Please review the latest code, and feel free to file a new issue if you see something wrong.

**Comment by rw8896** [comment]
@jyao1 Thanks, @liyi77 is also correct.
My suggestion is just to avoid the duplicated code in https://github.com/liyi77/libspdm/commit/555961e9a8beeb3f360f72434aa26112b9e3f465.
One day if we would like to support more types of measurement, we only need to update spdm_get_measurement_summary_hash_size.

But for current spec this change is no problem.
Will leave it for @liyi77 to decide how to follow up.

Thanks a lot,
Ray
