### ISSUE TITLE
Build errors with LIBSPDM_ENABLE_CAPABILITY_KEY_EX_CAP and LIBSPDM_ENABLE_CAPABILITY_PSK_EX_CAP  disabled

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#1019]
Will encounter the following unused variable errors when LIBSPDM_ENABLE_CAPABILITY_KEY_EX_CAP and LIBSPDM_ENABLE_CAPABILITY_PSK_EX_CAP are disabled.

libspdm/library/spdm_requester_lib/libspdm_req_communication.c: In function ‘libspdm_start_session’:
**libspdm/library/spdm_requester_lib/libspdm_req_communication.c:77:24: error: variable ‘spdm_context’ set but not used [-Werror=unused-but-set-variable]**
     libspdm_context_t *spdm_context;
                        ^~~~~~~~~~~~
libspdm/library/spdm_requester_lib/libspdm_req_communication.c: In function ‘libspdm_start_session_ex’:
**libspdm/library/spdm_requester_lib/libspdm_req_communication.c:222:24: error: variable ‘spdm_context’ set but not used [-Werror=unused-but-set-variable]**
     libspdm_context_t *spdm_context;
                        ^~~~~~~~~~~~
**libspdm/library/spdm_requester_lib/libspdm_req_communication.c:221:22: error: variable ‘status’ set but not used [-Werror=unused-but-set-variable]**
     libspdm_return_t status;
                      ^~~~~~
cc1: all warnings being treated as errors

**Comment by steven-bellock** [comment]
I am going to first add a configuration to CI that disables all capabilities : https://github.com/DMTF/libspdm/pull/1021 We can then use that to fix up the code.

**Comment by steven-bellock** [comment]
> /home/runner/work/libspdm/libspdm/library/spdm_requester_lib/libspdm_req_encap_request.c:230:16: error: use of undeclared identifier 'RETURN_UNSUPPORTED'
