### ISSUE TITLE
OpaqueData in MEASUREMENTS

### ISSUE THREAD

**Issue by hiption** [DMTF/libspdm#1030]
There are redundant code for inserting OpaqueData.

https://github.com/DMTF/libspdm/blob/af332d221e58f99b3e9b6a32e8950e255ae6d887/library/spdm_responder_lib/libspdm_rsp_measurements.c#L54-L60

https://github.com/DMTF/libspdm/blob/af332d221e58f99b3e9b6a32e8950e255ae6d887/library/spdm_responder_lib/libspdm_rsp_measurements.c#L102-L108

**Comment by steven-bellock** [comment]
This has been in the code base for a very long time.
