### ISSUE TITLE
libspdm_init_context to allocate the context memory and return it

### ISSUE THREAD

**Issue by vbodired** [DMTF/libspdm#1033]
Can libspdm_init_context() in library/spdm_common_lib/libspdm_com_context_data.c is made to allocate the memory for context and return the context? And to free the context in libspdm_reset_context()
We face some issues while integrating libspdm with applications written in C++, while exchanging the memory allocated by C++ APIs.

**Comment by steven-bellock** [comment]
Can you describe in more detail the issue you're having? I don't see how `libspdm` mallocing memory would solve much.
