### ISSUE TITLE
content_changed field in MEASUREMENT

### ISSUE THREAD

**Issue by hiption** [DMTF/libspdm#1034]
I want to know a scenario where the measurement log changes.
current implementation does not cover the case.

**Comment by steven-bellock** [comment]
1. Requester issues `GET_MEASUREMENT` with no signature to read the Responder's fuse values.
2. Responder blows a few fuses.
3. Requester issues `GET_MEASUREMENT` with signature and Responder sets `content changed` to `01b` to indicate that the fuse values in step 1 have changed.

**Comment by hiption** [comment]
Thank you for your quick reply.
Does the meaning of "blow" you written mean that the L1/L2 buffer that stores the measurements log exceeded the capacity?

**Comment by steven-bellock** [comment]
No, the fuse values are just something to be measured. Blowing or burning a fuse changes the value.

**Comment by hiption** [comment]
How does the device know if the fuse is blowing or burning?
Is it out of scope?

**Comment by steven-bellock** [comment]
Pretty much everything pertaining to measurements such as their meaning, their freshness, their expected values, etc, are outside the scope of the SPDM specification. It's up to other groups such as [TCG](https://trustedcomputinggroup.org/) to define the specifics of what gets measured.
