### ISSUE TITLE
spdm_device_secret_lib.h should probably live in include\hal\library

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1039]
Functions that `libspdm` requires the integrator to implement usually live in `include\hal\library`.

**Comment by jyao1** [comment]
agree.

**Comment by steven-bellock** [comment]
Looking through the file I'd say :

`libspdm_write_certificate_to_nvm` should move to https://github.com/DMTF/libspdm/blob/main/include/hal/library/platform_lib.h.

`libspdm_responder_data_sign` and `libspdm_requester_data_sign` can probably be deleted. See #1574.

`libspdm_measurement_collection`, `libspdm_generate_measurement_summary_hash`, `libspdm_psk_handshake_secret_hkdf_expand`, `libspdm_psk_master_secret_hkdf_expand`, and `libspdm_gen_csr` can go to `include/hal/library/device_secret_lib.h`

**Comment by steven-bellock** [comment]
Also, it might be good to have a Requester `platform_lib` and a Responder `platform_lib`.

Requester `platform_lib` would have
- `libspdm_sleep`
- `libspdm_write_certificate_to_nvm`

Responder `platform_lib` would have
- `libspdm_start_watchdog`
- `libspdm_stop_watchdog`
- `libspdm_reset_watchdog`
