### ISSUE TITLE
Can challenge be authenticated if requestor doesn't have the certificate of the responder, it just have the public key alone?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1046]
SPDM spec clearly has a case where the raw public key is provisioned without any certificate. 
From para 10.5 - The GET_DIGESTS and GET_CERTIFICATE messages are not applicable if the public key of the Responder was provisioned to the Requester in a trusted environment.
Table 13 - If set, the public key of the Requester was provisioned to the Responder. The transport layer is responsible for identifying the Responder. In this case, the CERT_CAP of the Requester shall be 0 .
Table 14 - If set, the public key of the Responder was provisioned to the Requester. The transport layer is responsible for identifying the Requester. In this case, CERT_CAP and ALIAS_CERT_CAP of the Responder shall both be 0 .
So there is a specific configuration for this case. If that configuration is done properly, can this be supported with no code changes in LIBSPDM?

**Comment by steven-bellock** [comment]
@jyao1 can correct me, but I believe for the raw public key case libspdm expects the Responder's leaf certificate to be provisioned on the Requester and Responder, so that `CHALLENGE_AUTH.CertChainHash` is the hash of the leaf certificate rather than the entire certificate chain. Note that  the SPDM specification does not specify the format of the raw public key
>The format of the provisioned public key is out of scope of this specification. Vendors can use proprietary formats or public key formats that other standards define, such as [RFC7250](https://github.com/DMTF/Security-TF/blob/master/docs/DSP0274/SPDMSpecification.md#ietf-rfc7250) and [RFC4716](https://github.com/DMTF/Security-TF/blob/master/docs/DSP0274/SPDMSpecification.md#ietf-rfc4716).

Related issue : https://github.com/DMTF/libspdm/issues/26

**Comment by jyao1** [comment]
Agree with @steven-bellock . Currently, we support provisioning the leaf cert as raw pub key format.

**Comment by PrakashK94** [comment]
Can't we provision the public key itself instead of leaf certificate and use LIBSPDM code to authenticate the challenge response?

**Comment by jyao1** [comment]
The format of public key is not standardized.

@PrakashK94 , Can you take this issue and make a proposal?
