### ISSUE TITLE
Need help with selecting the correct version of SPDM 1.1

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#1056]
Hello,

Completed implementing the SPDM 1.0 and the plan is to implement 1.1 version (not 1.2 version). I noticed there is 1.1.0c / 1.1.0b / 1.1.1. 
Can you guide me on which one to select and what is the difference?

Thanks

**Comment by steven-bellock** [comment]
You'll want to look at https://www.dmtf.org/dsp/DSP0274, as that has the official releases. The ones that end in `a` or `b` are intermediate snapshots that were released to get feedback.

**Comment by goutham23** [comment]
Thank you
