### ISSUE TITLE
Can we have multiple spdm contexts at the same time for multiple devices?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1074]
Is the spdm context somehow associated with a specific device we are talking to? The problem is this, if the OS and the BMC are both acting as requestor, then each can send any spdm command at any time.

So that both requesters will fail if the messages get intermingled.

What happens if we do get version, then get capabilities from one device say D1 to broadcom, and then do get version from rasp pi, and then do neg algo from D1, in that order?

**Comment by steven-bellock** [comment]
If a Responder expects to communicate with multiple Requesters where the messages are intermingled then the Responder should have multiple contexts. If the Requesters can sort it out amongst themselves, say Requester 1 only talks to the Responder during boot stage 1, and Requester 2 only talks to the Responder during boot stage 2, and the messages never intermingle, then the Responder can probably get away with having only one context.
