### ISSUE TITLE
Does LIBSPDM supports these features?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1075]
Support for Authenticated and Encrypted messages
• Sessions
— Key Exchange
• Session Establishment using Key Exchange
• Session Establishment using a Pre-shared Key
— Key Confirmation
— Key Update
— Key Schedule
• Mutual Authentication
— Deprecating Basic Mutual Authentication in SPDM1.2. SPDM1.2 removes
mutual authentication in CHALLENGE and CHALLENGE_AUTH.
— Mutual Authentication still need to be supported during Session establishment.
• Derivation of Additional Keys
• MCTP Type 6 messages.
• Provisioning
— Allows installation of device certificate in manufacturing.
• Message Fragmentation
Miscellaneous:
— Added SM2, SM3, SM4 algorithms to supported list.
— New OIDs added
• Enhanced measurement
— Define format of measurement manifest

**Comment by jyao1** [comment]
I feel the questions are too vague. What "support" means?
Also I am not clear where those are defined? Some seems from SPDM spec, but not all of them.

It is hard to say YES/NO for this question.

May I recommend you to go to the SPDM code TF meeting the discuss ?
