### ISSUE TITLE
Does LIBSPDM supports processing vendor defined request messages?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1078]

**Comment by steven-bellock** [comment]
Not right now, but it would not be difficult to add that support to libspdm, since all libspdm would do is populate the layout of the VDM.

**Comment by jyao1** [comment]
I would say: libspdm supports it, but does not include it.

You may find examples at https://github.com/DMTF/spdm-emu/tree/main/library, such as IDE_KM.

**Comment by steven-bellock** [comment]
@jyao1 My expectation would be that https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_receive_send.c#L26 would handle VDMs by eventually calling into an integrator-provided function to process the `VendorDefinedReqPayload`. libspdm would handle the layout of the VDM message itself and transport.

**Comment by jyao1** [comment]
That is right. the c-code will eventually call into that those libraries.

Start from https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_receive_send.c#L26  is a good idea.
