### ISSUE TITLE
test_spdm_requester_end_session and test_spdm_requester_heartbeat hang with the AFL generated specific mutation seed

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/libspdm#1084]
1.  Verified on https://github.com/DMTF/libspdm/commit/55fe909231070a13d91a87ac28861df0c535e95f
Ubuntu 18.04.5 LTS

cd libspdm
mkdir build_afl
cd build_afl
export AFL_PATH=~/afl-2.52b/
export PATH=$PATH:$AFL_PATH
cmake -DARCH=x64 -DTOOLCHAIN=AFL -DTARGET=Release -DCRYPTO=mbedtls ..
make copy_sample_key
make
cd bin
./test_spdm_requester_end_session ./test_spdm_requester_end_session_hang1 
libspdm_send_spdm_request[ffffffff] (0x4): 
0000: 11 ec 00 00 
LIBSPDM_ASSERT: /home/yzhu52/libspdm_Yaohui/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c(198): *secured_message_size >= total_secured_message_size
^C

./test_spdm_requester_heartbeat ./test_spdm_requester_heartbeat_hang1
libspdm_send_spdm_request[ffffffff] (0x4): 
0000: 11 e8 00 00 
LIBSPDM_ASSERT: /home/yzhu52/libspdm_Yaohui/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c(198): *secured_message_size >= total_secured_message_size
^C

2. the AFL generated specific mutation seed files:
[test_spdm_requester_end_session_hang1.zip](https://github.com/DMTF/libspdm/files/9177408/test_spdm_requester_end_session_hang1.zip)
[test_spdm_requester_heartbeat_hang1.zip](https://github.com/DMTF/libspdm/files/9177410/test_spdm_requester_heartbeat_hang1.zip)

**Comment by Xiaohanjlll** [comment]
I will check it.
