### ISSUE TITLE
test_spdm_responder_csr occur heap-buffer-overflow with the LibFuzzer generated specific mutation seed

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/libspdm#1085]
1. Verified on https://github.com/DMTF/libspdm/commit/e288c30df793be6cdbd798cfff440a5a2a09d980
Ubuntu 20.04.4 LTS

    cd libspdm
mkdir build_libfuzzer
cd build_libfuzzer
cmake -DARCH=x64 -DTOOLCHAIN=LIBFUZZER -DTARGET=Release -DCRYPTO=mbedtls ..
make copy_sample_key
make
cd bin
./test_spdm_responder_csr ./test_spdm_responder_csr_crash1
INFO: Seed: 257951414
INFO: Loaded 1 modules   (10905 inline 8-bit counters): 10905 [0x72f493, 0x731f2c), 
INFO: Loaded 1 PC tables (10905 PCs): 10905 [0x731f30,0x75c8c0), 
./test_spdm_responder_csr: Running 1 inputs 1 time(s) each.
Running: ./test_spdm_responder_csr_crash1
=================================================================
==1174739==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000005911 at pc 0x0000005c40f5 bp 0x7ffea1359e60 sp 0x7ffea1359e58
READ of size 1 at 0x621000005911 thread T0
    #0 0x5c40f4 in mbedtls_asn1_get_tag (/home/gyh/libspdm/build_libfuzz_mbedtls_e288c30d-2022-07-22_10-21-14/bin/test_spdm_responder_csr+0x5c40f4)

    Address 0x621000005911 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/gyh/libspdm/build_libfuzz_mbedtls_e288c30d-2022-07-22_10-21-14/bin/test_spdm_responder_csr+0x5c40f4) in mbedtls_asn1_get_tag
Shadow bytes around the buggy address:
  0x0c427fff8ad0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8ae0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8af0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c427fff8b20: fa fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==1174739==ABORTING

[test_spdm_responder_csr_crash1.zip](https://github.com/DMTF/libspdm/files/9177476/test_spdm_responder_csr_crash1.zip)

**Comment by Xiaohanjlll** [comment]
I will check it.
