### ISSUE TITLE
Debugging issue of libspdm_verify_cert_signature_algo_OID

### ISSUE THREAD

**Issue by taku202107** [DMTF/libspdm#1093]
In `libspdm_verify_cert_signature_algo_OID`, the process of /* get signature algo OID from cert */ (line #4178 of `libspdm_crypt_crypt.c`) should be fixed based on the result of our discussion about section 8.4 of SPDM White Paper on PMCI reflector. 

The process of /* get signature algo OID from cert */ should be deleted, or should compare the `base_asym_algo` with the algorithm indicated by subjectPublicKeyInfo field of X.509 formatted certificate.

**Comment by Wenxing-hou** [comment]
Thanks. It is a good issue. I have submitted the PR. 

For consistency check between base_aysm_algo and leaf cert public key aysm algo, I think the old code in get certificate command can check:
```
libspdm_verify_peer_cert_chain_buffer              //will call  libspdm_x509_certificate_check
|
V
libspdm_get_leaf_cert_public_key_from_cert_chain   //will try get public key from leaf cert by using base_aysm_algo
```

**Comment by jyao1** [comment]
Please replace `libspdm_verify_cert_signature_algo_OID` with `libspdm_verify_cert_subject_public_key_info`.
