### ISSUE TITLE
Compiling SPDM with KLEE toolchain with concrete value of "spdm_context"

### ISSUE THREAD

**Issue by TR174** [DMTF/libspdm#1100]
We were trying to get SPDM (commit **8b7140dbc632bae82b216aa8a00fd17c43c13247**) built with KLEE toolchain. The goal is to start with some concrete input and gradually move towards symbolic. Instead of passing the unit test generated by cmocka, we tried to construct  a concrete input for spdm_context in [https://github.com/DMTF/libspdm/blob/main/unit_test/test_spdm_requester/get_version.c](url)

`spdm_context = {version, p1 ( NULL, 0, NULL, 0),  p2 ( NULL, NULL, NULL, 0 ),  p3 ( NULL, NULL, false, false, 0, NULL,  NULL, NULL ) , p4 ( NULL, &NULL, &false, false, 0, NULL,  NULL, NULL ) , error_state,  {last_spdm_request[0]}, last_spdm_request_size, last_spdm_request_session_id, last_spdm_request_session_id_valid, last_spdm_error, get_response_func, get_encap_response_func, encap_context, spdm_session_state_callback, spdm_connection_state_callback, local_context, connection_info, transcript, session_info, latest_session_id, response_state, error_data, cache_spdm_request, cache_spdm_request_size, current_token, retry_times, crypto_request, app_context_data_ptr, last_update_request, request_response, handle_error_return_policy }; 
    status = libspdm_get_version(spdm_context, NULL, NULL);
    assert_int_equal(status, RETURN_DEVICE_ERROR);`

 and got the following error while building spdm:

libspdm/unit_test/test_spdm_requester/get_version.c:1051:16: error: expected expression
spdm_context = {version, p1 ( NULL, 0, NULL, 0),  p2 ( NULL, NULL, NULL, 0 ),  p3 ( NULL, NULL, false, false, 0, NULL,  NULL, NULL ) , p4 ( NULL, &NULL, &false, false, 0, NULL,  NULL, NULL ) , error_state,  {last_spdm_request[0]}, last_spdm_request_size, last_spdm_request_session_id, last_spdm_request_session_id_valid, last_spdm_error, get_response_func, get_encap_response_func, encap_context, spdm_session_state_callback, spdm_connection_state_callback, local_context, connection_info, transcript, session_info, latest_session_id, response_state, error_data, cache_spdm_request, cache_spdm_request_size, current_token, retry_times, crypto_request, app_context_data_ptr, last_update_request, request_response, handle_error_return_policy };

Maybe we are passing the inputs wrong. Could you please provide any suggestion on how we should be constructing valid inputs for spdm_context?

**Comment by jyao1** [comment]
First, glad to hear you are using KLEE.

Second, sorry, KLEE work was done long time ago, but it is out of maintenance for a long time. Especially, we have added lots of new features/code.

You may try https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/test_requester/test_spdm_requester_get_version/get_version.c, but I do not provide any guarantee.

Instead of using existing test code, I recommend you write small code at first to test a specific function.

**Comment by steven-bellock** [comment]
@TR174 We will close this issue for now. Please file a new issue if you need further help.
