### ISSUE TITLE
check for reserved parameters(param1 and param2)

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#1107]
Each commands have reserved parameters 
![image](https://user-images.githubusercontent.com/95281374/182575384-50613d9a-260b-4a86-aa56-bc704d27f46c.png)

Before responding to the commands, checks needs to be added for param1 and param2. Expected values for param1 and param2 are 0(as they are reserved)

Requester sending non-zero value needs to be responded with Error

**Comment by steven-bellock** [comment]
The SPDM Responder Validator and libspdm's unit tests can check that, but a Responder / Requester can't check that as the specification says
> Unless otherwise specified, field values marked as Reserved shall be written as zero (0), ignored when read, not modified and not interpreted as an error if not zero, and used in transcript hash calculations as is.

**Comment by PrithviAPai** [comment]
@steven-bellock  thanks a lot for this info. Closing the issue
