### ISSUE TITLE
ALGORITHM message process for SPDM 1.0

### ISSUE THREAD

**Issue by LeeTroy** [DMTF/libspdm#1108]
`NEGOTIATE_ALGORITHM` of SPDM 1.0 supports `BaseAsymSel` field in response message, but `spdm_context->connection_info.algorithm.req_base_asym_alg` will be set to zero if the protocol version is less than SPDM 1.1.

https://github.com/DMTF/libspdm/blob/7c04eb4b34e8ec7bd85d4c23c3be388b9c914654/library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c#L445-L450

Should `spdm_context->connection_info.algorithm.req_base_asym_alg` be set to zero here?

Thanks,
Troy

**Comment by jyao1** [comment]
req_base_asym_alg is defined in SPDM 1.1, not SPDM 1.0.

**Comment by LeeTroy** [comment]
Got it, thanks!
