### ISSUE TITLE
Can we please include signature as part of libspdm_get_measurement

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#1110]
This is a request to include signature as part of libspdm_get_measurement parameters. 
The applications using the library can make use of the signature for different use case.

Can this request be accommodated please ?

**Comment by vbodired** [comment]
Yes, it's needed to have another API that returns the signature along with measurements to the caller. Because the measurements response can go through different layers in software before it actually reaches the end user and its prone to get manipulated by in between software modules. At the user end the signature is definitely needed to validate and trust the measurements received.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/discussions/929 should do what you want. It's scheduled to be implemented before the end of August-2022. Feel free to leave questions and comments in the discussion.

**Comment by jyao1** [comment]
@vbodired  just adding signature might not be enough.

If the purpose is to verify the signature, then you need to know more, such as VCA and all previous measurement record.

**Comment by vbodired** [comment]
@jyao1 Yes, the requester application need to have the VCA, they have to collect GET_VERSION, GET_CERT & NEG_ALGO. The problem here is that when the measurement blocks are passed from one module to another inside BMC, there is no trust on the measurement received by end module so they are requiring the signature of the response. Why do you think, it also need to have previous measurement record to verify current measurements?

**Comment by steven-bellock** [comment]
@vbodired The signature is over the L1/L2 transcript which, for SPDM 1.2, includes the `VCA` messages and possibly multiple `GET_MEASUREMENTS / MEASUREMENTS` messages as well. The Verifier needs the entire transcript to verify that the signature is correct.

>L1/L2 = Concatenate(VCA, GET_MEASUREMENTS_REQUEST1, MEASUREMENTS_RESPONSE1, GET_MEASUREMENTS_REQUESTn-1, MEASUREMENTS_RESPONSEn-1, GET_MEASUREMENTS_REQUESTn, MEASUREMENTS_RESPONSEn)

**Comment by vbodired** [comment]
@jyao1 @steven-bellock As per below code, every time after verifying the signature on the measurement, the code flow is resetting the cached messages, in that case there is no cache of  previous measurements right and it's as good as current HASH verification not accounting the previous messages. Can you clarify if my understanding is correct?

result = libspdm_verify_measurement_signature(
            spdm_context, session_info, signature, signature_size);
        if (!result) {
            libspdm_reset_message_m(spdm_context, session_info);
            status = LIBSPDM_STATUS_VERIF_FAIL;
            goto receive_done;
        }

        libspdm_reset_message_m(spdm_context, session_info);

**Comment by steven-bellock** [comment]
Correct. Signing the measurement log starts a new measurement log and the old one is discarded.

**Comment by steven-bellock** [comment]
But I see where you're going with that. For Requesters that have `LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT` enabled the measurement log could be retrieved from the `message_a` (for SPDM 1.2) and `message_m` buffers and passed to the caller. So `libspdm_get_measurement_ex` could be expanded to
```
libspdm_return_t libspdm_get_measurement_ex(void *context, const uint32_t *session_id,
                                            uint8_t request_attribute,
                                            uint8_t measurement_operation,
                                            uint8_t slot_id_param,
                                            uint8_t *content_changed,
                                            uint8_t *number_of_blocks,
                                            uint32_t *measurement_record_length,
                                            void *measurement_record,
                                            const void *requester_nonce_in,
                                            void *requester_nonce,
                                            void *responder_nonce,
                                            uint32_t *measurement_log_length,
                                            void *measurement_log
                                            )
```
and if `measurement_log` is non-NULL then it would return the measurement log and size. @jyao1 Do you see any issues with that?

**Comment by jyao1** [comment]
The biggest problem of measurement_log is that this API will be available only if LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT is TRUE.

If it is FALSE, then libspdm does not have such info.

**Comment by vbodired** [comment]
We are actually in need of an unconditional dedicated API that provides the requester applications with the whole of GET_MEASUREMENTS response as it receives from Responder. Can we go with an additional API like libspdm_get_measurement_ex_ex (as steven said earlier) ? Do you see any issue with adding new API?

**Comment by jyao1** [comment]
@vbodired, I recommend you attend our SPDM Code TF meeting to discuss the issue.

**Comment by jyao1** [comment]
Discussed with @vbodired.
We agree to use https://github.com/DMTF/libspdm/discussions/929.

**Comment by JakubLedworowski** [comment]
I tried to follow the resolution and the #929 but got lost.
@jyao1 are you able to provide guidance how to retrieve signature after `libspdm_get_measurement`?

**Comment by steven-bellock** [comment]
@JakubLedworowski https://github.com/DMTF/libspdm/blob/main/doc/user_guide.md#message-logging details how messages are logged to a buffer so that they may be verified by the Verifier. The signature would be the last x bytes of the message log, assuming the last message is the signed `MEASUREMENTS` response.
