### ISSUE TITLE
Need remove /wd4819 introduced in #1106

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1116]
According to https://github.com/DMTF/libspdm/pull/1106#issuecomment-1203417552, we should remove /wd4819.

@lbbxsxlz, would you please follow up on that?

**Comment by steven-bellock** [comment]
@lbbxsxlz Please assign this to yourself if you can pick it up.

**Comment by jyao1** [comment]
Unicode issue is resolved at https://github.com/DMTF/libspdm/pull/1129

**Comment by lbbxsxlz** [comment]
> Unicode issue is resolved at #1129

It is effective.

But it is no effective by using add_compile_option to add "/wd4819"  in cmockalib, if we remove the "/wd4819" from the CMakeLists.txt in root path.

I am trying to skip the unicode warning in cmocka by other ways.

**Comment by lbbxsxlz** [comment]
bypass the unicode warning from cmocka.h at #1130

**Comment by steven-bellock** [comment]
Closing as fixed by #1130.
