### ISSUE TITLE
Crypto Confusion

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1117]
Although libspdm defines functions like `libspdm_rsa_new` in `cryptlib.h` to create an RSA context, nothing in `libspdm/library` actually calls these functions and uses the context. Instead, what I think happens, is that libspdm assumes that the format of the public key returned by the x.509 parser matches the format of the public key that is consumed by the cryptography library, for example `libspdm_rsa_pkcs1_sign_with_nid`. This is troubling for a few reasons:
1. The poor implementer of `cryptlib.h` functions is spending time coding up functions that aren't used.
2. There is an implicit binding between the x.509 parser and the cryptography library. In many libraries these functions are bundled together but that is not always the case.

Ways to improve this include : 
1. Have libspdm use an (industry) standard encoding for public keys and signatures such that someone could implement, for example, `libspdm_rsa_pkcs1_sign_with_nid` without knowing the underlying x.509 parser that formatted the public key.
2. Ensure that the x.509 parser is independent of the cryptography library. For example compile libspdm with an OpenSSL X.509 parser and an MbedTLS cryptography library.

**Comment by liyi77** [comment]
libspdm_rsa_new with libspdm_rsa_set_key can create public key context when Responder provided raw public key (SPDM spec 7.2.2).

>Have libspdm use an (industry) standard encoding for public keys and signatures such that someone could implement
I think this case is similar with raw key case, s.t. get raw pubkey from x.509 parser and use it create context by cryptography library?
Maybe can assume raw pubkey format is ASN.1 encoding? both openssl and mbedtls have 'ASN.1-encode-key to context' function, s.t. d2i_PublicKey(), mbedtls_pk_parse_subpubkey().

**Comment by steven-bellock** [comment]
Maybe, but I don't want the cryptography library to have to parse ASN. So a flow I'm imagining is
1. libspdm calls the x.509 parser to parse an x.509 certificate to get the public key. The parser returns the public key to libspdm in an industry-defined (PKCS?) or libspdm-defined C data structure.
2. libspdm calls, for example, `libspdm_rsa_new` and calls `libspdm_rsa_set_key` with the C data structure for the public key.

Now the implementer of `libspdm_rsa_set_key` knows exactly what needs to be implemented and the format of the key and whatnot, and it can be implemented independently of the x.509 parsing library.

**Comment by liyi77** [comment]
I'm thinking, since we are going to decouple the parser and the crypto library, why don't we let the parser consume the crypto module, so as to avoid introducing new APIs and structures or modifying existed APIs, you can see this demo: https://github.com/liyi77/libspdm/pull/12.

The another benefit as you mentioned at #534 :
>Also, we should have the requirement that if decoupling the cryptography and certificate libraries causes performance or code size issues, that selecting a single library for both cryptography and certificates should bring in the expected optimizations like we're doing now.

We can use macro and build defines to separate 'combined parser case' and 'independent parser case'  .

**Comment by steven-bellock** [comment]
Will move to Discussion forum with a proposal on how to handle raw public keys and splitting the certificate parsing library from the cryptography library.
