### ISSUE TITLE
CHUNK support

### ISSUE THREAD

**Issue by ChungShienChai** [DMTF/libspdm#1118]
When two endpoints support CHUNK capabilities, we shall use large message transfer mechanism where the offset should be 0 and length should be 0xFFFF

![image](https://user-images.githubusercontent.com/86744262/183544452-1c5ab393-ee4b-4779-804c-8f217926960e.png)

But this is not the case for current implementation

![image](https://user-images.githubusercontent.com/86744262/183544493-19117d91-a6bd-4292-b194-484468438197.png)

**Comment by jyao1** [comment]
@steven-bellock , I remember you said that you will submit spec issue to clarify.
Do you think it should be fixed now or we should wait for spec clarification?

**Comment by jyao1** [comment]
I think one problem is that: If we mandate length to be 0xFFFF, then the whole certificate will be sent in one SPDM response (with chunking). It we assume the `MaxSPDMmsgSize` can cover the whole certificate. I am not sure if that assumption is TRUE.

**Comment by ChungShienChai** [comment]
We should not assume the size can cover the whole certificate chain.

Per the spec:

a. If it can cover, that is great, then responder should just return the whole chain

b. If it cannot cover, then responder should return error with chunk handle no. Base on this chunk handle no, requester need to exercise CHUNK capability, sending the CHUNK_GET to get the cert in multiple chunks.

**Comment by jyao1** [comment]
> We should not assume the size can cover the whole certificate chain.

Which size are you referring to? `MaxSPDMmsgSize` or `DataTransferSize` ?

**Comment by steven-bellock** [comment]
The issue that needs to be clarified is whether the specification and/or libspdm allows the Requester to set the `length` field to a value that is less than `0xffff` when both Requester and Responder support chunking. So can an integrator call `libspdm_get_certificate_choose_length` if both Requester and Responder support chunking? In 1.2.2 I will (attempt to) make the answer "yes", but 1.2.2 won't be published for a while.

**Comment by steven-bellock** [comment]
But whether the answer is yes or no we can still add chunking support to get the entire certificate chain.

**Comment by ChungShienChai** [comment]
What I refer about CHUNK_GET is DataTransferSize.

If requester cannot handle the response due to MaxSPDMmsgSize, then responder should return ResponseTooLarge error (I would prefer this over just silently discard the error). The spec already mentioned this in:

![image](https://user-images.githubusercontent.com/86744262/186046829-b271e78d-9edc-43a4-86b8-f55b3281acac.png)

**Comment by jyao1** [comment]
We have below case, if 0xFFFF is set and `PortionLength` is expected,
1) If cert <= DataTransferSize, then one GET_CERT msg without chunking.
2) if DataTransferSize < cert <= MaxSPDMmsgSize, then one GET_CERT msg with chunking
3) if MaxSPDMmsgSize < cert, then the responder will return "ResponseTooLarge" instead of return the cert with `PortionLength` being whole cert chain length. How does it work?

**Comment by ChungShienChai** [comment]
i think that is correct behavior.

**Comment by jyao1** [comment]
> i think that is correct behavior.

Then how the requester get the whole cert by setting offset to 0xFFFF ?

**Comment by jyao1** [comment]
Anyway, I filed an issue on SPDM spec. We will discuss detail later.

**Comment by ChungShienChai** [comment]
I do not understand what do you mean "setting offset to 0xFFFF"

The spec said "The Requester shall set **Offset to 0** and **Length to 0xFFFF** in the GET_CERTIFICATE request"

**Comment by jyao1** [comment]
Typo. fixed.

**Comment by jyao1** [comment]
Filed https://github.com/DMTF/SPDM-WG/issues/2156

**Comment by jyao1** [comment]
Discussed in the meeting. We agree that this requirement should not be there. It will be removed in errata.
We can close this issue.
