### ISSUE TITLE
Test failed when requester (DATA_SUPPORT = 0) <=> responder (DATA_SUPPORT = 1) 

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1121]
When open `LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT` in requester and close `LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT` in responder, the emu will fail.

Both `requester (DATA_SUPPORT = 0) <=> responder (DATA_SUPPORT = 1)`   and   `requester (DATA_SUPPORT = 1) <=> responder (DATA_SUPPORT = 0) ` case will fail.

The failed reason is The failed reason is gen_sign and verify_sign message is different.

![image](https://user-images.githubusercontent.com/87060980/183571280-b0135b0d-cfef-4242-8e64-97988413d009.png)

**Comment by jyao1** [comment]
There is pareameter - `is_data_hash`. Have you checked that?

**Comment by Wenxing-hou** [comment]
Thanks. I have checked the `is_data_hash` and find the reason: the `mut_hash` is different between requester and responder.
