### ISSUE TITLE
Code scan alert - Potentially uninitialized local variable "hash_size" in library/spdm_common_lib/libspdm_com_context_data.c

### ISSUE THREAD

**Issue by liuw1** [DMTF/libspdm#1140]
Alert: 
https://github.com/liuw1/libspdm/security/code-scanning/12
https://github.com/liuw1/libspdm/security/code-scanning/13
https://github.com/liuw1/libspdm/security/code-scanning/14
https://github.com/liuw1/libspdm/security/code-scanning/15

**Comment by Xiaohanjlll** [comment]
I will check it.
