### ISSUE TITLE
Code scan alert - Potentially uninitialized local variable in os_stub/cryptlib_mbedtls/pk/x509.c

### ISSUE THREAD

**Issue by liuw1** [DMTF/libspdm#1141]
Alerts:
https://github.com/liuw1/libspdm/security/code-scanning/16
https://github.com/liuw1/libspdm/security/code-scanning/17
https://github.com/liuw1/libspdm/security/code-scanning/18
https://github.com/liuw1/libspdm/security/code-scanning/19
https://github.com/liuw1/libspdm/security/code-scanning/20

**Comment by Xiaohanjlll** [comment]
I will check it.
