### ISSUE TITLE
libspdm_get_data returns wrong values for LIBSPDM_DATA_CAPABILITY_FLAGS

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#1142]
When used libspdm_get_data to get the capability flag values using the following method
status = libspdm_get_data(spdmResponder.pspdmContext,
                              LIBSPDM_DATA_CAPABILITY_FLAGS, &parameter,
                              &u32Value, &data_size);
The value is always 6 even though the capability transaction says otherwise

Transactions:
spdm_send_spdm_request[0] (0x4):
0000: 10 e1 00 00
spdm_receive_spdm_response[0] (0xc):
0000: 10 61 00 00 00 00 00 00 f7 fb 00 00

**Comment by jyao1** [comment]
which parameter you use?
```
        if (parameter->location == LIBSPDM_DATA_LOCATION_CONNECTION) {
            target_data =
                &spdm_context->connection_info.capability.flags;
        } else {
            target_data =
                &spdm_context->local_context.capability.flags;
        }
```

**Comment by steven-bellock** [comment]
On the Responder side `libspdm_set_data` shouldn't allow those capabilities. The last three bytes are reserved. But that's a different issue.

**Comment by PrithviAPai** [comment]
After using LIBSPDM_DATA_LOCATION_CONNECTION I was able to get the Caps info accurately. 
Thank you
