### ISSUE TITLE
Many codes style don't conform  uncrustify

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1148]
Some codes without compile don't conform uncrustify.

For example: about `LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT` macro, some code line is too long.
https://github.com/DMTF/libspdm/blob/320f7c878d004d5757fda9dbc828ab915c7fcbd9/library/spdm_common_lib/libspdm_com_context_data_session.c#L70-L78

**Comment by jyao1** [comment]
Code is updated in https://github.com/DMTF/libspdm/pull/1152.
