### ISSUE TITLE
Potential unalignment access solution proposal

### ISSUE THREAD

**Issue by b0riskleiman** [DMTF/libspdm#1160]
Please consider the following as a solution of the problem referred here: https://github.com/DMTF/spdm-emu/issues/70

Instead of
*(uint16_t *)ptr = (uint16_t)spdm_context->local_context

use
typedef uint16_t 	__attribute__ ((aligned(1))) uint16_t_ua; //declare 1 byte aligned (unaligned) uint16_t type
*(uint16_t_ua *)ptr = (uint16_t)spdm_context->local_context

**Comment by steven-bellock** [comment]
@b0riskleiman Is this issue preventing you from using libspdm on your target platform?

**Comment by b0riskleiman** [comment]
Yes. And this approach is working (I see byte accesses in debugger)

**Comment by steven-bellock** [comment]
Ah that's good in the sense that we've been waiting for someone to run into this issue to spur us to actually fix it. But we'll want to fix both the alignment issue as well as the endianness issue (libspdm currently assumes little-endian architecture) at the same time. So it would probably be accessor functions like `uint16_t read16 (void *num)` that return both an aligned integer as well as one in the appropriate endianness. We also need a way to test that this works on big-endian systems and systems that don't support unaligned access. In Github Actions we could use PPC running in QEMU for a big-endian system.

**Comment by jyao1** [comment]
I would just use a libspdm_copy_mem() to avoid direct assignment.

**Comment by jyao1** [comment]
Also possible to define libspdm_{read|write}_uint{16|32}, since we already have libspdm_{read|write}_uint24.

**Comment by b0riskleiman** [comment]
Also see no big deal with endianness, htonl/ntohl could be used

**Comment by steven-bellock** [comment]
The files in `libspdm/library` are restricted to the C99 freestanding headers, so we can't use POSIX functions. But they're easy enough to make ourselves.

**Comment by b0riskleiman** [comment]
@jyao1 This approach has some drawbacks unless you're not going to use a different inline functions for aligned and unaligned accesses. Else you'll get a huge performance degradation and code size growth

**Comment by steven-bellock** [comment]
@b0riskleiman We'll have macros that default to little-endian and unaligned access and shouldn't impact performance or code size.

**Comment by jyao1** [comment]
We just need this for potential unaligned access. For the aligned access, we don't need to change.
