### ISSUE TITLE
Transcript Hashing Confusion (SPDM 1.1)

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1170]
`libspdm_asym_verify`, which is only called when `LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT==1` contains the code
```
    if (need_hash) {
        hash_size = libspdm_get_hash_size(base_hash_algo);
        result = libspdm_hash_all(base_hash_algo, message, message_size,
                                  message_hash);
        if (!result) {
            return false;
        }
        return verify_function(context, hash_nid, param, param_size, message_hash,
                               hash_size, signature, sig_size);
    } else {
        return verify_function(context, hash_nid, param, param_size, message, message_size,
                               signature, sig_size);
    }
``` 
However my reading of the specification tells me that, in `Sign(SK, Hash(M1))`, the message to be signed by the signing algorithm (for example RSASSA-PKCS1-v1_5) is already hashed, regardless of whether or not the signing algorithm will hash that again. So I think it should just be an unconditional `libspdm_hash_all()` and `return verify_function()`.

**Comment by jyao1** [comment]
`M` shall be the concatenation of `combined_spdm_prefix` and `message_hash` . `M` is the input message.

The `need_hash` is for eddsa, See https://github.com/DMTF/libspdm/blob/main/library/spdm_crypt_lib/libspdm_crypt_crypt.c#L2048

**Comment by steven-bellock** [comment]
I am talking about the 1.1 case. It seems like `*message` only gets hashed once sometimes. For example `RSA_sign` expected `*in` to already be hashed.

**Comment by jyao1** [comment]
All algorithms in 1.1 will return `need_hash=true`.

**Comment by steven-bellock** [comment]
Right but doesn't `RSA_sign` and `RSA_verify` expect the input message to already be hashed? If so then it's only being hashed once.

**Comment by steven-bellock** [comment]
@steven-bellock to clarify, with the SPDM Working group, what the 1.0/1.1 specification says regarding the signing algorithm and its expectations on the format of the message to be signed; is it hashed or not?

**Comment by steven-bellock** [comment]
@jyao1 I have the filed the issue as https://github.com/DMTF/SPDM-WG/issues/2168.

**Comment by jyao1** [comment]
9/5/2022, discussed. No change is required.
