### ISSUE TITLE
How does Responder identify the connection?

### ISSUE THREAD

**Issue by yh36** [DMTF/libspdm#118]
In spdm_responder_dispatch_message(), the current Responder code just waits for a request, processes it and sends back the generated response. How does Responder know that it talks to the same Requester? Do we have any identifier for Responder to track the Requester per connection?

**Comment by jyao1** [comment]
you need register transport method to the SPDM context. (e.g. PMCI over Smbus, PCI-DOE, etc)

Within this context, only one SPDM connection is allowed based upon current spec.

**Comment by jyao1** [comment]
We also clarified that the SPDM protocol transport layer cannot detect if an entity is changed during connection.
1) If the entity is change, it is impossible to detect if the changed entity use the same CVA.
2) If the changed entity uses different CVA, then it can be detected during transcript calculation.
3) If the changed entity intercepts a session, then it can be detected on session data decryption.
