### ISSUE TITLE
Document libspdm's expectations / requirements for the send and receive buffers

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1180]
In particular : 
- If libspdm never writes to the receive buffer then it should be ok for it to be a read-only buffer. I'm not sure if there are any write-only buffers out there.
- libspdm does not copy the receive buffer to a more secure region of memory. So if the receive buffer could possibly be written to by an attacker while libspdm is processing the message then it's up to the integrator to copy the data to a more secure region before handing it off to libspdm.

**Comment by jyao1** [comment]
9/5/2022. We expect the integrator passes the secure region of memory (send/receive/scratch buffer). No TOC-TOU issue.
Agree to document that.
