### ISSUE TITLE
Incorrect enum value in test_spdm_responder_capabilities

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1182]
https://github.com/DMTF/libspdm/blob/0e2079143f733856fac404d1b37af94f44679caf/unit_test/fuzzing/test_responder/test_spdm_responder_capabilities/capabilities.c#L67

It should use an enum from `libspdm_response_state_t`.

**Comment by Xiaohanjlll** [comment]
I will check it.
