### ISSUE TITLE
Response size compared to exact value with inequality operator

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1183]
There are multiple instances in the Requester library where the response size is exactly checked, for instance
https://github.com/DMTF/libspdm/blob/0e2079143f733856fac404d1b37af94f44679caf/library/spdm_requester_lib/libspdm_req_finish.c#L245-L248

However the response size as returned by the transport layer may be larger than the actual SPDM message size.

**Comment by jyao1** [comment]
This is in-session message. NO padding is expected.

**Comment by steven-bellock** [comment]
@jyao1 This seems to be everywhere on the Responder side. For example : https://github.com/DMTF/libspdm/blob/68cbe6df93cc0c06480e783e0b3f965a41d359d4/library/spdm_responder_lib/libspdm_rsp_certificate.c#L93-L97 Is this expected?

**Comment by jyao1** [comment]
> Is this expected?
No. It should be equal or greater than.

**Comment by jyao1** [comment]
9/19/2022 - not need to put to Q3 stable, per meeting.
