### ISSUE TITLE
How does libspdm_get_public_key_oid handle a leaf cert with a signature of different bit size than the upper certificate's hash's bit size

### ISSUE THREAD

**Issue by jcahill0** [DMTF/libspdm#1188]
When a full certificate is obtained through the CERTIFICATE response to a GET_CERTIFICATE request, the certificate chain is validated.  Eventually it reaches the function libspdm_verify_cert_subject_public_key_info, which is to verify the public key encryption algorithm matches the negotiated base asymmetric algorithm from NEGOTIATE_ALGORITHMS-ALGORITHMS request-response pair.

An SPDM responder could have its CSR use a hash and signing algorithm of a certain bit size.  Then the CSR's public key is signed and hashed by the CA with an intermediate certificate that uses a signing algorithm and hash of a different size.

How does libspdm_get_public_key_oid handle a leaf cert with a signature of different bit size than the upper certificate's hash's bit size, or how should it?
The OIDs defined for signing-hashing algorithm pairs don't really seem to describe this situation.

Shouldn't the check make sure the negotiated base asymmetric algorithm matches the subject public key info of the leaf certificate, instead of the OID?

This came up after some discussion with @bhenning10.

**Comment by steven-bellock** [comment]
This is (somewhat) related to issue #1093.

**Comment by jyao1** [comment]
The problem does not exist. libspdm_get_public_key_oid() only handle the leaf_cert

The calling flow is:
libspdm_verify_cert_chain_data()/libspdm_verify_certificate_chain_buffer()
-> libspdm_x509_certificate_check(leaf_cert) // <= here the caller only input cert check for leaf_cert
----> libspdm_verify_cert_subject_public_key_info()
------> libspdm_get_public_key_oid()

**Comment by jyao1** [comment]
9/5/2022, if the libspdm integrator uses a crypto lib cannot handle the algorithm in the upper cert of the certificate chain. (which mean, the cert chain cannot be verified), the libspdm will fail.

**Comment by jcahill0** [comment]
Thanks @jyao1 .  It appears I misunderstood the behavior crossing multiple versions of libspdm
