### ISSUE TITLE
Base Hash Algorithm selected is mandated to be non-zero  

### ISSUE THREAD

**Issue by mct-sparky** [DMTF/libspdm#1189]
The following lines of code mandate that the base hash algorithm selected be non-zero, without any prior checks for capabilities:

https://github.com/DMTF/libspdm/blob/3ed56c7f11d5e405562d145418a7ae3ce0cc241b/library/spdm_responder_lib/libspdm_rsp_algorithms.c#L539-L545

According to the DMTF Validator Case 3.5, Assertion 3.5.10:

"Assertion 3.5.10: SpdmMessage.BaseHashSel only has one bit at most. if (CHAL_CAP == 1 || MEAS_CAP == 2) then (BaseHashSel == one of {TPM_ALG_SHA_256, TPM_ALG_SHA_384, TPM_ALG_SHA_512, TPM_ALG_SHA3_256, TPM_ALG_SHA3_384, TPM_ALG_SHA3_512}) if (CHAL_CAP == 0 && MEAS_CAP != 2) then (BaseHashSel == 0)"

The selected base hash algorithm should be allowable to be zero in the case that CHAL_CAP is 0 and MEAS_CAP !=2 (or other capabilities that require it be not supported).

**Comment by jyao1** [comment]
I think we need update the assertion, to add the condition of CERT_CAP (because cert chain also requires digest for root cert) and KEY_EX_CAP/PSK_EX_CAP (requires HMAC for verification)

**Comment by jyao1** [comment]
9/5/2022. Agree
