### ISSUE TITLE
Segfault on write to errno when using libspdm as a part of dynamically loaded library

### ISSUE THREAD

**Issue by antkorczak** [DMTF/libspdm#1193]
When using libspdm to create a shared object that is loaded by dlopen() our application segfaults in openSSL code that writes to errno. This doesn’t happen when the same function is used in executable (no intermediate .so). I think that the problem is due to the overriding system provided errno here: [crt_support.h](https://github.com/DMTF/libspdm/blob/main/os_stub/openssllib/include/crt_support.h#L270)
This declares errno as an extern int, but system provided errno provides a macro that expands to a call to __errno_location()
After removing this line and [custom errno.h](https://github.com/DMTF/libspdm/blob/main/os_stub/openssllib/include/errno.h) the problem no longer exists. Currently I workaround this issue by building my own OpenSSL binaries without custom CRT defines.

I think that the library shouldn't overwrite system provided CRT

x86_64
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Ubuntu GLIBC 2.27-3ubuntu1.3) 2.27

**Comment by steven-bellock** [comment]
This issue is part of a larger issue where we should migrate libspdm's usage of OpenSSL from the edk2/UEFI profile (OPENSSL_SYS_UEFI) to something more "normal" (OPENSSL_SYS_UNIX / OPENSSL_SYS_WINDOWS). In particular libspdm shouldn't be declaring and defining all the standard library symbols (including `errno`) in https://github.com/DMTF/libspdm/tree/main/os_stub/openssllib/include.

**Comment by jyao1** [comment]
Eventually, we hope to support shared object. But so far, it is not supported yet.
Maybe we can resolve it in Q4 release.

**Comment by liuw1** [comment]
After using latest binary build method,  new conflicts  can be found during build as below:

```[  0%] Building C object os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/cipher/aead_aes_gcm.c.o
In file included from /usr/include/sched.h:31,
                 from /usr/include/pthread.h:22,
                 from /home/liuwei/openssl/include/openssl/crypto.h:415,
                 from /home/liuwei/openssl/include/openssl/bio.h:20,
                 from /home/liuwei/openssl/include/openssl/evp.h:16,
                 from /home/liuwei/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:16:
/usr/include/x86_64-linux-gnu/bits/types/time_t.h:10:18: error: conflicting types for ‘time_t’; have ‘__time_t’ {aka ‘long int’}
   10 | typedef __time_t time_t;
      |                  ^~~~~~
In file included from /home/liuwei/libspdm/os_stub/cryptlib_openssl/internal_crypt_lib.h:20,
                 from /home/liuwei/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:14:
/home/liuwei/libspdm/os_stub/openssllib/include/crt_support.h:237:16: note: previous declaration of ‘time_t’ with type ‘time_t’ {aka ‘long unsigned int’}
  237 | typedef size_t time_t; /* time_t is 4 bytes for 32bit machine and 8 bytes for 64bit machine */
      |                ^~~~~~
make[2]: *** [os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/build.make:82: os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/cipher/aead_aes_gcm.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1912: os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/all] Error 2
make: *** [Makefile:103: all] Error 2```

**Comment by steven-bellock** [comment]
#289 changed the type of `time_t` to `intn` which in a subsequent pull request was changed to `size_t`.
