### ISSUE TITLE
rename keywords in libspdm 

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#1212]
Currently we have some functions which have c++ keywords as variables
example:
bool libspdm_ecx_generate_key(void *ecx_context, uint8_t *public,
                               size_t *public_size);
bool libspdm_sm2_dsa_generate_key(void *sm2_context, uint8_t *public,
                                   size_t *public_size);
bool libspdm_sm2_key_exchange_generate_key(void *sm2_context, uint8_t *public,
                                            size_t *public_size);
This generates some issues as all public is a c++ keyword. 
Can we please rename public in this case?

**Comment by jyao1** [comment]
please submit PR.

**Comment by jyao1** [comment]
I think we can use public_data instead of public.
