### ISSUE TITLE
test_spdm_responder_csr occur heap-buffer-overflow with the LibFuzzer generated specific mutation seed

### ISSUE THREAD

**Issue by Xiaohanjlll** [DMTF/libspdm#1214]
Verified on ce2f118f93d5f757b61aaa8bf7c6778985a05ec6
Ubuntu 20.04.4 LTS

cd libspdm
mkdir build_libfuzzer
cd build_libfuzzer
cmake -DARCH=x64 -DTOOLCHAIN=LIBFUZZER -DTARGET=Release -DCRYPTO=openssl..
make copy_sample_key
make
cd bin

./test_spdm_responder_csr ./../../test_spdm_responder_csr_crash 

> =================================================================
==2695961==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62100000590f at pc 0x000000638e91 bp 0x7ffef5049e70 sp 0x7ffef5049e68
READ of size 1 at 0x62100000590f thread T0
    #0 0x638e90 in ASN1_get_object /home/test/libspdm_XiaoHan/os_stub/openssllib/openssl/crypto/asn1/asn1_lib.c:55:12
    #1 0x5ea684 in libspdm_asn1_get_tag /home/test/libspdm_XiaoHan/os_stub/cryptlib_openssl/pk/x509.c:269:5
    #2 0x60e0a9 in libspdm_verify_req_info /home/test/libspdm_XiaoHan/library/spdm_crypt_lib/libspdm_crypt_crypt.c:5172:11
    #3 0x5866df in libspdm_get_response_csr /home/test/libspdm_XiaoHan/library/spdm_responder_lib/libspdm_rsp_csr.c:131:14
    #4 0x581f89 in libspdm_test_responder_csr_case1 /home/test/libspdm_XiaoHan/unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c:41:5
    #5 0x5829ac in libspdm_run_test_harness /home/test/libspdm_XiaoHan/unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c:107:5
    #6 0x58492e in LLVMFuzzerTestOneInput /home/test/libspdm_XiaoHan/unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c:124:5
    #7 0x48c761 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x48c761)
    #8 0x477ed2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x477ed2)
    #9 0x47d986 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x47d986)
    #10 0x4a6642 in main (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x4a6642)
    #11 0x7f24458380b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
    #12 0x45259d in _start (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x45259d)

Address 0x62100000590f is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow /home/test/libspdm_XiaoHan/os_stub/openssllib/openssl/crypto/asn1/asn1_lib.c:55:12 in ASN1_get_object
Shadow bytes around the buggy address:
  0x0c427fff8ad0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8ae0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8af0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c427fff8b20: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c427fff8b70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2695961==ABORTING

[test_spdm_responder_csr_crash.zip](https://github.com/DMTF/libspdm/files/9596466/test_spdm_responder_csr_crash.zip)

**Comment by Xiaohanjlll** [comment]
I will check it.

**Comment by liuw1** [comment]
Hi @Xiaohanjlll, please help to analysis if this is a regression issue.
