### ISSUE TITLE
Need enhance the fuzzing test cases to improve the target code coverage

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1215]
Test with https://github.com/DMTF/libspdm/commit/ce2f118f93d5f757b61aaa8bf7c6778985a05ec6
1.	The test is based on Ubuntu 20.04.4 LTS, Using AFL as the Fuzzer. 
2.	AFL Every fuzzing test case run about 30 minutes.
3.	Collect the Code Coverage data. 
4.	Some fuzzing test have **low** target code coverage ( less than 75%)
        libspdm_req_finish.c : 66.9 %
        libspdm_req_key_exchange.c : 74.1 %
        libspdm_req_psk_exchange.c : 72.3 %
        libspdm_req_psk_finish.c : 73.6 %
        libspdm_rsp_finish.c : 62.3 %
        libspdm_rsp_psk_finish.c : 63.4 %
5.	The attached is the code coverage log file.
[coverage_log.zip](https://github.com/DMTF/libspdm/files/9596668/coverage_log.zip)
6.	After investigating, we found the following PR lead to it.
https://github.com/DMTF/libspdm/pull/1152

**Comment by Xiaohanjlll** [comment]
I will check it.
