### ISSUE TITLE
Pointer 'spdm_session_info' checked for NULL at line 1344 may be dereferenced at line 1424.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1216]
Pointer 'spdm_session_info' checked for NULL at line 1344 may be dereferenced at line 1424.
https://github.com/DMTF/libspdm/blob/ce2f118f93d5f757b61aaa8bf7c6778985a05ec6/library/spdm_common_lib/libspdm_com_context_data.c#L1344
https://github.com/DMTF/libspdm/blob/ce2f118f93d5f757b61aaa8bf7c6778985a05ec6/library/spdm_common_lib/libspdm_com_context_data.c#L1422-L1427

**Comment by Xiaohanjlll** [comment]
I will check it.
