### ISSUE TITLE
unit test fail with mbedtls

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#124]
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\home\DMTF\libspdm\unit_test\test_spdm_requester\get_certificate.c:2046: error: Failure!

Finally failed at mbedtls: x509_crt.c:

        /* Look for a parent in trusted CAs or up the chain */
        ret = x509_crt_find_parent( child, trust_ca, &parent,
                                       &parent_is_trusted, &signature_is_good,
                                       ver_chain->len - 1, self_cnt, rs_ctx );

        /* No parent? We're done here */
        if( parent == NULL )
        {
            *flags |= MBEDTLS_X509_BADCERT_NOT_TRUSTED;
            return( 0 );
        }

**Comment by rkongintel** [comment]
I've noticed a bunch of failures when building with the following option as well: x64, VS201,Release, openssl

**Comment by steven-bellock** [comment]
Also need to include Mbed TLS to the CI.

**Comment by rkongintel** [comment]
Here are the errors I see with x64,VS2019, Debug, openssl:

C:\code\dmtf_libspdm\build\bin>git log -1
commit df3db1ba161f4164d5aca21dd394a940411b156b (HEAD -> main, origin/main, origin/HEAD)
Author: yi1 li <yi1.li@intel.com>
Date:   Thu Sep 2 14:31:41 2021 +0800

    Add test case about first returned cert is not root.

    Signed-off-by: yi1 li <yi1.li@intel.com>

C:\code\dmtf_libspdm\build\bin>git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

C:\code\dmtf_libspdm\build\bin>test_spdm_responder.exe > NULL
[  PASSED  ] 6 test(s).
[  PASSED  ] 22 test(s).
[  PASSED  ] 19 test(s).
[  PASSED  ] 9 test(s).
[  ERROR   ] --- 0x4 != 0x408
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\certificate.c:78: error: Failure!
[  ERROR   ] --- 0x4 != 0x8
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\certificate.c:391: error: Failure!
[  ERROR   ] --- 0x5 != 0x1
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\certificate.c:476: error: Failure!
[  ERROR   ] --- 0x5 != 0x1
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\certificate.c:587: error: Failure!
[  ERROR   ] --- 0x4 != 0x408
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\certificate.c:716: error: Failure!
[  ERROR   ] --- 0x4 != 0x8
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\certificate.c:825: error: Failure!
[  PASSED  ] 6 test(s).
[  FAILED  ] spdm_responder_certificate_tests: 6 test(s), listed below:
[  FAILED  ] test_spdm_responder_certificate_case1
[  FAILED  ] test_spdm_responder_certificate_case7
[  FAILED  ] test_spdm_responder_certificate_case8
[  FAILED  ] test_spdm_responder_certificate_case9
[  FAILED  ] test_spdm_responder_certificate_case10
[  FAILED  ] test_spdm_responder_certificate_case11

 6 FAILED TEST(S)
[  ERROR   ] --- 0x4 != 0x86
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\challenge_auth.c:107: error: Failure!
[  ERROR   ] --- 0x4 != 0x86
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\challenge_auth.c:584: error: Failure!
[  ERROR   ] --- 0x4 != 0x8e
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\challenge_auth.c:681: error: Failure!
[  ERROR   ] --- 0x4 != 0xa6
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\challenge_auth.c:730: error: Failure!
[  ERROR   ] --- 0x4 != 0xa6
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\challenge_auth.c:779: error: Failure!
[  PASSED  ] 9 test(s).
[  FAILED  ] spdm_responder_challenge_auth_tests: 5 test(s), listed below:
[  FAILED  ] test_spdm_responder_challenge_auth_case1
[  FAILED  ] test_spdm_responder_challenge_auth_case9
[  FAILED  ] test_spdm_responder_challenge_auth_case11
[  FAILED  ] test_spdm_responder_challenge_auth_case12
[  FAILED  ] test_spdm_responder_challenge_auth_case13

 5 FAILED TEST(S)
[  ERROR   ] --- 0x4 != 0x6a
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\measurements.c:454: error: Failure!
[  ERROR   ] --- 0x4 != 0x91
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\measurements.c:509: error: Failure!
[  ERROR   ] --- 0x4 != 0x18d
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\measurements.c:672: error: Failure!
[  ERROR   ] --- 0x4 != 0x91
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\measurements.c:1100: error: Failure!
[  ERROR   ] --- 0x5 != 0x1
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\measurements.c:1211: error: Failure!
[  PASSED  ] 17 test(s).
[  FAILED  ] spdm_responder_measurements_tests: 5 test(s), listed below:
[  FAILED  ] test_spdm_responder_measurements_case7
[  FAILED  ] test_spdm_responder_measurements_case8
[  FAILED  ] test_spdm_responder_measurements_case11
[  FAILED  ] test_spdm_responder_measurements_case18
[  FAILED  ] test_spdm_responder_measurements_case20

 5 FAILED TEST(S)
[  ERROR   ] --- 0x4 != 0x408
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\respond_if_ready.c:370: error: Failure!
[  ERROR   ] --- 0x4 != 0x86
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\respond_if_ready.c:434: error: Failure!
[  ERROR   ] --- 0x4 != 0xda
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\respond_if_ready.c:573: error: Failure!
[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

To debug in Visual Studio...
1. Select menu item File->Open Project
2. Change 'Files of type' to 'Executable Files'
3. Open this executable.
4. Select menu item Debug->Start

Alternatively, set the environment variable
UNIT_TESTING_DEBUG to 1 and rebuild this executable,
then click 'Debug' in the popup dialog box.


[  ERROR   ] --- 0xfffe != 0xffff
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\respond_if_ready.c:766: error: Failure!
[  ERROR   ] --- 0x7f != 0x67
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\respond_if_ready.c:867: error: Failure!
[  PASSED  ] 8 test(s).
[  FAILED  ] spdm_responder_respond_if_ready_tests: 6 test(s), listed below:
[  FAILED  ] test_spdm_responder_respond_if_ready_case2
[  FAILED  ] test_spdm_responder_respond_if_ready_case3
[  FAILED  ] test_spdm_responder_respond_if_ready_case5
[  FAILED  ] test_spdm_responder_respond_if_ready_case6
[  FAILED  ] test_spdm_responder_respond_if_ready_case7
[  FAILED  ] test_spdm_responder_respond_if_ready_case8

 6 FAILED TEST(S)
[  ERROR   ] --- 0x0 != 0x1
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\key_exchange.c:107: error: Failure!
[  ERROR   ] --- 0x0 != 0x1
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_responder\key_exchange.c:601: error: Failure!
[  PASSED  ] 5 test(s).
[  FAILED  ] spdm_responder_key_exchange_tests: 2 test(s), listed below:
[  FAILED  ] test_spdm_responder_key_exchange_case1
[  FAILED  ] test_spdm_responder_key_exchange_case7

 2 FAILED TEST(S)
[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF717E2AA94.

[  PASSED  ] 2 test(s).
[  FAILED  ] spdm_responder_finish_tests: 14 test(s), listed below:
[  FAILED  ] test_spdm_responder_finish_case1
[  FAILED  ] test_spdm_responder_finish_case2
[  FAILED  ] test_spdm_responder_finish_case3
[  FAILED  ] test_spdm_responder_finish_case4
[  FAILED  ] test_spdm_responder_finish_case5
[  FAILED  ] test_spdm_responder_finish_case6
[  FAILED  ] test_spdm_responder_finish_case7
[  FAILED  ] test_spdm_responder_finish_case8
[  FAILED  ] test_spdm_responder_finish_case9
[  FAILED  ] test_spdm_responder_finish_case10
[  FAILED  ] test_spdm_responder_finish_case13
[  FAILED  ] test_spdm_responder_finish_case14
[  FAILED  ] test_spdm_responder_finish_case15
[  FAILED  ] test_spdm_responder_finish_case16

 14 FAILED TEST(S)
[  PASSED  ] 7 test(s).
[  PASSED  ] 7 test(s).
[  PASSED  ] 7 test(s).
[  PASSED  ] 7 test(s).

C:\code\dmtf_libspdm\build\bin>test_spdm_requester.exe > NULL
[  PASSED  ] 15 test(s).
[  PASSED  ] 29 test(s).
[  PASSED  ] 31 test(s).
[  PASSED  ] 17 test(s).
[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

To debug in Visual Studio...
1. Select menu item File->Open Project
2. Change 'Files of type' to 'Executable Files'
3. Open this executable.
4. Select menu item Debug->Start

Alternatively, set the environment variable
UNIT_TESTING_DEBUG to 1 and rebuild this executable,
then click 'Debug' in the popup dialog box.


[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A57395D1.

[  PASSED  ] 0 test(s).
[  FAILED  ] spdm_requester_get_certificate_tests: 18 test(s), listed below:
[  FAILED  ] test_spdm_requester_get_certificate_case1
[  FAILED  ] test_spdm_requester_get_certificate_case2
[  FAILED  ] test_spdm_requester_get_certificate_case3
[  FAILED  ] test_spdm_requester_get_certificate_case4
[  FAILED  ] test_spdm_requester_get_certificate_case5
[  FAILED  ] test_spdm_requester_get_certificate_case6
[  FAILED  ] test_spdm_requester_get_certificate_case7
[  FAILED  ] test_spdm_requester_get_certificate_case8
[  FAILED  ] test_spdm_requester_get_certificate_case9
[  FAILED  ] test_spdm_requester_get_certificate_case10
[  FAILED  ] test_spdm_requester_get_certificate_case11
[  FAILED  ] test_spdm_requester_get_certificate_case12
[  FAILED  ] test_spdm_requester_get_certificate_case13
[  FAILED  ] test_spdm_requester_get_certificate_case14
[  FAILED  ] test_spdm_requester_get_certificate_case15
[  FAILED  ] test_spdm_requester_get_certificate_case16
[  FAILED  ] test_spdm_requester_get_certificate_case17
[  FAILED  ] test_spdm_requester_get_certificate_case18

 18 FAILED TEST(S)
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\challenge.c:1063: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\challenge.c:1282: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\challenge.c:1444: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\challenge.c:1735: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\challenge.c:1830: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\challenge.c:1877: error: Failure!
[  PASSED  ] 14 test(s).
[  FAILED  ] spdm_requester_challenge_tests: 6 test(s), listed below:
[  FAILED  ] test_spdm_requester_challenge_case2
[  FAILED  ] test_spdm_requester_challenge_case6
[  FAILED  ] test_spdm_requester_challenge_case9
[  FAILED  ] test_spdm_requester_challenge_case16
[  FAILED  ] test_spdm_requester_challenge_case18
[  FAILED  ] test_spdm_requester_challenge_case19

 6 FAILED TEST(S)
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\get_measurements.c:2496: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\get_measurements.c:2712: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\get_measurements.c:2875: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\get_measurements.c:3277: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\get_measurements.c:3829: error: Failure!
[  PASSED  ] 25 test(s).
[  FAILED  ] spdm_requester_get_measurements_tests: 5 test(s), listed below:
[  FAILED  ] test_spdm_requester_get_measurements_case2
[  FAILED  ] test_spdm_requester_get_measurements_case6
[  FAILED  ] test_spdm_requester_get_measurements_case9
[  FAILED  ] test_spdm_requester_get_measurements_case16
[  FAILED  ] test_spdm_requester_get_measurements_case25

 5 FAILED TEST(S)
[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A575F4E4.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A575F4E4.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A575F4E4.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A575F4E4.

[  PASSED  ] 7 test(s).
[  FAILED  ] spdm_requester_key_exchange_tests: 4 test(s), listed below:
[  FAILED  ] test_spdm_requester_key_exchange_case2
[  FAILED  ] test_spdm_requester_key_exchange_case6
[  FAILED  ] test_spdm_requester_key_exchange_case9
[  FAILED  ] test_spdm_requester_key_exchange_case11

 4 FAILED TEST(S)
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1351: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1427: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1581: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000010
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1656: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1732: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1812: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1889: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:1965: error: Failure!
[ERRCODE:00] [  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:2030: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:2124: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:2363: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x0
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:2527: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:2793: error: Failure!
[  ERROR   ] --- 0x800000000000001a != 0x8000000000000007
[   LINE   ] --- C:\code\dmtf_libspdm\unit_test\test_spdm_requester\finish.c:2881: error: Failure!
[  PASSED  ] 6 test(s).
[  FAILED  ] spdm_requester_finish_tests: 14 test(s), listed below:
[  FAILED  ] test_spdm_requester_finish_case1
[  FAILED  ] test_spdm_requester_finish_case2
[  FAILED  ] test_spdm_requester_finish_case4
[  FAILED  ] test_spdm_requester_finish_case5
[  FAILED  ] test_spdm_requester_finish_case6
[  FAILED  ] test_spdm_requester_finish_case7
[  FAILED  ] test_spdm_requester_finish_case8
[  FAILED  ] test_spdm_requester_finish_case9
[  FAILED  ] test_spdm_requester_finish_case10
[  FAILED  ] test_spdm_requester_finish_case11
[  FAILED  ] test_spdm_requester_finish_case14
[  FAILED  ] test_spdm_requester_finish_case16
[  FAILED  ] test_spdm_requester_finish_case19
[  FAILED  ] test_spdm_requester_finish_case20

 14 FAILED TEST(S)
[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A575F4E4.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A575F4E4.

[  ERROR   ] --- EXCEPTION_ACCESS_VIOLATION occurred at 00007FF7A575F4E4.

[  PASSED  ] 7 test(s).
[  FAILED  ] spdm_requester_psk_exchange_tests: 3 test(s), listed below:
[  FAILED  ] test_spdm_requester_psk_exchange_case2
[  FAILED  ] test_spdm_requester_psk_exchange_case6
[  FAILED  ] test_spdm_requester_psk_exchange_case9

 3 FAILED TEST(S)
[  PASSED  ] 11 test(s).
[  PASSED  ] 11 test(s).
[  PASSED  ] 11 test(s).

C:\code\dmtf_libspdm\build\bin>

**Comment by jyao1** [comment]
The error is not related this mbedtls issue. Can you please report a new issue ? It is really confusing here.

BTW: Have you run "nmake copy_sample_key" before test?

**Comment by rkongintel** [comment]
Sorry. I may have forgotten the run the "nmake copy_sample_key". I'll try again and create a new issue if I still see it. Thanks.

**Comment by liyi77** [comment]
@jyao1 
This bug will occur when verifying the integrity of a certificate chain without root certificate.
For openssl, one cert can verify itself even that it is not a self-signed cert, but this is an error case for mbedtls.
I think we can skip the first cert for the certificate chain without root certificate.
