### ISSUE TITLE
Any pointers to test the SPDM responder code

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#1250]
Hello,

I'm implementing the SPDM responder code and completed SPDM 1.0, one of the vendors/customers had implemented the SPDM 1.0 requester code and it was easy for us to test all the commands. SPDM->MCTP->PCIe

Now, I'm working on implementing SPDM 1.1 responder code and I'm looking for any pointers to plug in open-source SPDM requester code to test 1.1 commands,  as the vendor/customer is not ready yet to develop SPDM 1.1 requester code.

Thanks in Advance!!

**Comment by steven-bellock** [comment]
We are working on https://github.com/DMTF/SPDM-Responder-Validator , and while it is currently incomplete it can test some 1.1 features like key exchange.

**Comment by goutham23** [comment]
Thank you
