### ISSUE TITLE
Export Master Secret is mistakenly cleared as a part of the handshake context

### ISSUE THREAD

**Issue by taprinz** [DMTF/libspdm#1259]
Export Master Secret is an application secret derived in the application phase.

However, it is stored as a part of the handshake secret:
```
typedef struct {
[...]
    uint8_t export_master_secret[LIBSPDM_MAX_HASH_SIZE];
[...]
} libspdm_session_info_struct_handshake_secret_t;
```
When the session establishment is complete, the handshake secret structure is cleared. Therefore, any implementation which relies on the Export Master Secret will see all 0's when trying to use it.

To resolve, the Export Master Secret should be moved to be a part of the libspdm_session_info_struct_application_secret_t.

**Comment by steven-bellock** [comment]
There should also be a function that extracts and erases the EMS so that it doesn't linger in the context.
