### ISSUE TITLE
Add compile-time checking of macros

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1261]
For example if `LIBSPDM_ENABLE_CAPABILITY_KEY_EX_CAP` is enabled then at least one of `LIBSPDM_FFDHE_SUPPORT` / `LIBSPDM_ECDHE_SUPPORT` / etc needs to be enabled. I think this would be disabled by default, so if an Integrator wants to enable checking they would set `LIBSPDM_CHECK_MACROS` to `1`. 

This is related to #1027 which checks the context at runtime.

**Comment by jyao1** [comment]
In general, I agree.
And I think we need a list of "If _CAP is enabled, at least one of _SUPPORT need to be enabled.", for
1. Hash
2. Digital Signature
3. Key Exchange
