### ISSUE TITLE
openssllib - include folder' crt_support.h

### ISSUE THREAD

**Issue by moshe8931** [DMTF/libspdm#1267]
hi
you need to change params in line 323:
char *strncpy(char *destinin, const char *source, int maxlen);
the last parameter should be size_t instead of int.

you can see definition:
https://cplusplus.com/reference/cstring/strncpy/

not all compilers support int as size_t.

**Comment by steven-bellock** [comment]
@moshe8931 Would you like to submit a pull request to fix this? If not we can do it.
