### ISSUE TITLE
Enable CLANG compilation in CI/CD

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1270]
And set warnings as errors.

**Comment by Xiaohanjlll** [comment]
I will check it.

**Comment by steven-bellock** [comment]
We can probably swap CLANG for VS2015.

**Comment by liuw1** [comment]
@steven-bellock Do you still want to enable CLANG compilation in CI/CD?

**Comment by steven-bellock** [comment]
Yes please. In particular
1. Swap out VS2015 for CLANG. Probably only need to run CLANG in Linux.
2. Fix #1269.
3. Enable warnings-as-errors for CLANG.

**Comment by jyao1** [comment]
Reopen.

Clang build is unstable.

https://github.com/DMTF/libspdm/actions/runs/3400474669/jobs/5654924810
https://github.com/DMTF/libspdm/actions/runs/3400474669/jobs/5654925222
https://github.com/DMTF/libspdm/actions/runs/3391492847/jobs/5636706693

I suggest reduce the clang test to only one configuration.

**Comment by jyao1** [comment]
clang is so unstable, and caused failure almost on every PR.

It is really annoying.
