### ISSUE TITLE
Code coverage documentation is confusing

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1295]
The code coverage documentation states
>Goto libspdm/Build/\<TARGET>_\<TOOLCHAIN>/\<ARCH>. mkdir log and cd log.
* This directory is not created by CMake nor are there instructions to create this directory.
* `Build` should be `build` to be consistent with the rest of the documentation.
* In "Code Coverage in Linux with GCC and [lcov](http://ltp.sourceforge.net/coverage/lcov.php)." we can remove "in Linux" since these steps would work on Windows with MinGW or a BSD OS.

**Comment by steven-bellock** [comment]
Also
* The Linux Test Project has moved from Sourceforge to GitHub.

**Comment by liuw1** [comment]
I will take it

**Comment by liuw1** [comment]
> Also
> 
> * The Linux Test Project has moved from Sourceforge to GitHub.

@steven-bellock Sorry, Could you show more details? I didn't get you.

**Comment by steven-bellock** [comment]
https://github.com/linux-test-project/lcov/releases is the active url for lcov releases.

**Comment by liuw1** [comment]
Thank you!
