### ISSUE TITLE
`CERTIFICATE` response when requested length is zero

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1297]
If the Requester sets `GET_CERTIFICATE.Length` to `0` the Responder returns an error. See https://github.com/DMTF/libspdm/blob/f66b0953f1d1f55a8839d9e1f34cfcca016b632b/library/spdm_responder_lib/libspdm_rsp_certificate.c#L115-L119 However there is nothing in the specification that forbids this, so this should probably be a legal Request.

**Comment by steven-bellock** [comment]
@steven-bellock To file issue with SPDM WG.

**Comment by jyao1** [comment]
I agree that we can add support to libspdm.

But the requester cannot assume the responder will implement this in SPDM 1.2 and previous.
