### ISSUE TITLE
libspdm_req_get_measurements.c to support parsing measurement_record

### ISSUE THREAD

**Issue by xiaoyuruan** [DMTF/libspdm#1307]
The current libspdm requester code supports processing MEASUREMENTS response and outputting measurement_record (concatenation of measurement blocks).  

static libspdm_return_t libspdm_try_get_measurement(void *context, const uint32_t *session_id,
                                                    uint8_t request_attribute,
                                                    uint8_t measurement_operation,
                                                    uint8_t slot_id_param,
                                                    uint8_t *content_changed,
                                                    uint8_t *number_of_blocks,
                                                    uint32_t *measurement_record_length,
                                                    void *measurement_record,
                                                    const void *requester_nonce_in,
                                                    void *requester_nonce,
                                                    void *responder_nonce)

Can libspdm implement parser for measurement_record and output, for every measurement:

- index
- measurement specification
- measurement size
- DMTF measurement value type
- DMTF measurement value

**Comment by steven-bellock** [comment]
It can. The question is what would the format of the parsed output be, and does it offer advantages over the raw measurement record? For example libspdm will not parse the measurement record and convert it to XML / JSON, which is what a Verifier really wants. At NVIDIA we pass the raw measurement record to a Verifier written in Python. So a possible direction would be to bring SPDM parsing to higher-level languages like Python / Go / Java / etc. For example the [Veraison Project](https://github.com/veraison).

**Comment by jyao1** [comment]
We have sample https://github.com/DMTF/spdm-emu/tree/main/spdm_emu/spdm_device_verifier_tool.
Please take a look if that meets the requirement.

**Comment by jyao1** [comment]
synced with @xiaoyuruan. We agree that current spdm-emu example is enough. Close this one.
