### ISSUE TITLE
KEY_UPDATE should have callbacks similar to session_state_callbacks

### ISSUE THREAD

**Issue by taprinz** [DMTF/libspdm#1312]
The existence of the libspdm_trigger_session_state_callback allows an integrator to take action whenever the SPDM session keys are derived, changed, or deleted (handshake, app phase, and end session).

This would allow an integrator to take action in securing, updating, or deleting these keys - especially if they are desired to be used in secure key storage.

To follow along with the above usage - libspdm should provide a similar set of callbacks for KEY_UPDATE functionality, whether a new set of states, or an extension of libspdm_trigger_session_state_callback.

For example, the following callbacks/states could be set:
- Update Key
- Update Finished
- Rollback Key

In the case of the integrator storing the SPDM keys in secure key storage, it could allow for the following behavior:
- Update Key callback tells integrator to put new updated key in secure storage, and backup previous key
- Update Finished callback tells integrator they can discard backup key
- Rollback Key callback tells integrator to replace key in secure storage with backup key.

Open to modifications on the above - but in general, would like some way for the integrator to be aware that the keys are being updated.

**Comment by steven-bellock** [comment]
This issue was fixed by #1463.
