### ISSUE TITLE
Conditional compilation switch for each optional request/response

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#132]
In some measurements, I'm seeing that the code/rodata of the spdm library is 50+KB.  Many of the spdm requests/responses are optional. 

I would like to enable users to reduce this space by providing them a compile time switch to individually conditionally compile out the associated code for each of the optional requests/responses.  

For example, for the optional GET_DIGESTS request/response, we could add a compilation flag SPDM_ENABLE_GET_DIGESTS.  

We would wrap (with #if SPDM_ENABLE_GET_DIGESTS/#endif pairs) around the spdm_get_digests_request_t and spdm_digest_response_t structures in spdm.h and any associated code within the library and unit tests that uses these structures.  

Similarly, we could do this with the optional GET_CERTIFICATE, CHALLENGE, GET_MEASUREMENT, etc, commands.

Thoughts?

**Comment by steven-bellock** [comment]
See https://github.com/DMTF/libspdm/issues/2

**Comment by steven-bellock** [comment]
Closing as duplicate.
