### ISSUE TITLE
Unable to build when code coverage is enabled

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1334]
See https://github.com/DMTF/libspdm/actions/runs/3372264103/jobs/5595487418#step:3:414

This is with `cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=mbedtls -DGCOV=ON ..`

**Comment by steven-bellock** [comment]
@jyao1 This was probably introduced with something like https://github.com/DMTF/libspdm/pull/1314 where the linker flags were changed. On a side note we should enable GCOV for at least one build configuration to flag any issues like this on a pull request.

**Comment by jyao1** [comment]
I think we may exclude `test_size_*` if GCOV is on.

**Comment by Xiaohanjlll** [comment]
I will check this
