### ISSUE TITLE
Enable GCOV=ON in CI/CD

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1335]
In https://github.com/DMTF/libspdm/blob/main/.github/workflows/build.yml have at least one build configuration where GCOV is enabled. Probably `-DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DGCOV=ON ..`

**Comment by jyao1** [comment]
11/7/2022 - Agree to enable just one.

**Comment by Xiaohanjlll** [comment]
I will check this
