### ISSUE TITLE
GetMeasurements message transcript separated into different context

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#1338]
Libspdm stores the GetMeasurements/Measurements message transcript to different context according to given pointers of context and session_info in
 `libspdm_return_t libspdm_append_message_m(void *context, void *session_info, const void *message, size_t message_size);`
- Save messages to transcript in normal spdm_context if it goes without session
- Save messages to session_transcript in session_info if it goes with session

I have another SPDM implementation that stores the message trascript in one context, that doesn't work with libspdm in below scenario:

> GetMeasurements req_1, no_signature_required, go without session
> GetMeasurements req_2, no_signature_required, go with session
> GetMeasurements req_3, no_signature_required, go without session
> GetMeasurements req_4, signature_required, go with session

According to SPDM v1.2.1 section 10.11.2 MEASUREMENTS signature generation
the L1/L2 for signature generation should be 
 `L1/L2 = Concatenate(VCA, GET_MEASUREMENTS_REQUEST1, MEASUREMENTS_RESPONSE1, ...,
                                     GET_MEASUREMENTS_REQUESTn-1, MEASUREMENTS_RESPONSEn-1,
                                     GET_MEASUREMENTS_REQUESTn, MEASUREMENTS_RESPONSEn)`

So I got a miss-match from libspdm:
Because req_4 goes with session thus the transcript for it to generate signature is concatenation of `(VCA, GET_MEASUREMENTS_REQUEST2, MEASUREMENTS_RESPONSE2, GET_MEASUREMENTS_REQUEST4, MEASUREMENTS_RESPONSE4)` (no req_1 and req_3 records).

Would you explain the reason why the transcript separation is needed here?

**Comment by steven-bellock** [comment]
The specifications says, regarding the `Application Phase`: 
>During this phase, a Requester can send SPDM messages such as GET_MEASUREMENTS. These messages might involve transcript calculations and if such calculations are required, they shall be calculated on a per session basis.

So the intent is that message transcripts don't bleed between secure sessions. I would imagine the intent is also that the transcripts don't bleed between secure sessions and unsecure connections. I can file an issue against the specification to get that clarified.

**Comment by jyao1** [comment]
We have fixed this issue long time - https://github.com/DMTF/libspdm/issues/91

@xiangfeima , would you please let us know which version you are using?

**Comment by steven-bellock** [comment]
@jyao1 They are using a non-libspdm implementation.

**Comment by steven-bellock** [comment]
@xiangfeima We discussed this in the SPDM Working Group today and we'll clarify the specification, that transcripts don't bleed between sessions or between a session and an unsecure connection.

**Comment by xiangfeima** [comment]
Thank you very much @steven-bellock and @jyao1. This one can be closed I think.
