### ISSUE TITLE
rename the ARM_CLANG to ARM_DS2022

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1340]
I think calling ARM_CLANG might be confusing, since that requires [Arm Development Studio 2022](https://developer.arm.com/downloads/-/arm-development-studio-downloads)

We need use rename the `ARM_CLANG` to `ARM_DS2022`, to distinguish the LLVM tool chain from https://releases.llvm.org/

**Comment by Wenxing-hou** [comment]
I will check it.
