### ISSUE TITLE
Need create API document for stable

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#135]

**Comment by jyao1** [comment]
defer to next stable, because we still have some pending API discussion - error code, dynamic function pointer, crypto api, etc

**Comment by steven-bellock** [comment]
For the Responder API I think, for the functions that are currently in https://github.com/DMTF/libspdm/blob/main/include/library/spdm_responder_lib.h
### Public Functions
- `libspdm_responder_dispatch_message`
- `libspdm_register_get_response_func`
- `libspdm_register_session_state_callback_func`
- `libspdm_register_connection_state_callback_func`
- `libspdm_register_key_update_callback_func`
- `libspdm_generate_error_response`
- `libspdm_generate_extended_error_response`

### Internal Functions
- `libspdm_init_key_update_encap_state`
- `libspdm_trigger_key_update_callback`

@jyao1 Do you agree?

**Comment by steven-bellock** [comment]
This was completed in https://github.com/DMTF/libspdm/tree/main/doc/api.
