### ISSUE TITLE
Add 1.2 BinConcat Version to spdm.h

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1379]
And consider refactoring `libspdm_bin_concat()` so that it uses a generic label like `SPDM_VERSION_GENERIC_BIN_CONCAT_LABEL "spdmx.x "` since the version numbers are overwritten in the function. At first glance it looks like the function uses `SPDM_VERSION_1_1_BIN_CONCAT_LABEL` even if the negotiated version is 1.2.

**Comment by jyao1** [comment]
11/14/2022 - seems good idea.
