### ISSUE TITLE
Can LIBSPDM returns opaque data with measurements when acting as responder?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1393]

**Comment by steven-bellock** [comment]
Yes, but looking at it it has some issues.
1. The Responder's opaque data currently resides in the SPDM context, but there's no way to set it with `libspdm_set_data`.
2. In the case of `MEASUREMENTS` the opaque data may change based on the parameters in the `GET_MEASUREMENTS` request. For example the opaque data may be different depending on if the Requester wants a signature or not. In such a case the opaque data should come through the `spdm_device_secret_lib`.

@jyao1 can also give his opinion.

**Comment by jyao1** [comment]
11/21/2022 - It seems option 2 is good idea - support return opaque data in `spdm_device_secret_lib`.
