### ISSUE TITLE
Remove assertions from managed buffer functions

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1395]
The managed buffer functions are very opinionated on the maximum size of the buffer. For example see https://github.com/DMTF/libspdm/blob/37e58c70fb213c73d2572b1846dbeb87133b79d4/library/spdm_common_lib/libspdm_com_support.c#L285-L296 However there's no reason these can't be general purpose functions, and we can safely remove the assertions. If assertions are needed then they should be on the caller's side.

**Comment by jyao1** [comment]
11/21/2022 - need remove all ASSERT in other managed buffer function as well.
