### ISSUE TITLE
Command Issuance Allowance Issue

### ISSUE THREAD

**Issue by KwonHyunSoo** [DMTF/libspdm#1398]
Hi all, 

I have a question about _8.6 SPDM request and response code issuance allowance_ in SPDM v.1.2.1 specification.
It says that GET_DIGESTS command can be transmitted via secure session with both handshake and application phases (that is, all phases.)
However, the implementation rejects GET_DIGESTS command when the session is not established (that is, application phase) as follows:
https://github.com/DMTF/libspdm/blob/37e58c70fb213c73d2572b1846dbeb87133b79d4/library/spdm_responder_lib/libspdm_rsp_digests.c#L89

GET_CSR, SET_CERTIFICATE, and GET_CERTIFICATE command also have same issue in implementations.

I agree with the logic of implementations that reject those command when receiving them via session under handshake phase. 
Could you let me know which one I should follow?

Thanks.

**Comment by steven-bellock** [comment]
libspdm should support `GET_DIGESTS` and `GET_CERTIFICATE` in the handshake phase. So I would call the current behavior, in both the Requester and Responder, a bug. When a Responder should allow `GET_CSR` and `SET_CERTIFICATE` depends on the Responder's security and authorization policy, and libspdm should be flexible in supporting that. So any changes there would be an enhancement.

**Comment by jyao1** [comment]
11/21/2022 - file an issue to SPDM spec to clarify.

**Comment by jyao1** [comment]
We clarify that current code behavior is correct. We will fix the spec in errata.
