### ISSUE TITLE
Multiple Callback Functions

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1409]
This is related to #1408. libspdm allows an Integrator to register multiple callback functions : https://github.com/DMTF/libspdm/blob/d858bede17ca36f95023728741075aa37c786de3/include/library/spdm_responder_lib.h#L197-L210

@jyao1 (or anyone else) Is there a real use case for needing multiple callback functions, instead of just one?

**Comment by jyao1** [comment]
11/21/2022 - close now. We may revisit for 3.0.
