### ISSUE TITLE
Requester's session ID is not checked

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1414]
See https://github.com/DMTF/libspdm/blob/2eead62d192d436c5e238624a46851cf6009d352/library/spdm_requester_lib/libspdm_req_key_exchange.c#L363-L364

If `libspdm_allocate_req_session_id` fails then it returns `0` to indicate that all allocations have been exhausted. Note that this will eventually be caught by `libspdm_assign_session_id` but this occurs after the `KEY_EXCHANGE_RSP` response.

**Comment by jyao1** [comment]
11/21/2022 - make sense. currently only responder does the check. We need add check for requester as well.
