### ISSUE TITLE
Requester's measurement_hash_type needs to be checked

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1415]
`measurement_hash_type` is sent unconditionally from the Integrator to the Responder. For example see https://github.com/DMTF/libspdm/blob/2eead62d192d436c5e238624a46851cf6009d352/library/spdm_requester_lib/libspdm_req_key_exchange.c#L341-L344 Its value should be checked.

**Comment by jyao1** [comment]
11/21/2022 - if measurement is not supported, this should be 0. The check is done in responder, we should add check for requester as well.

**Comment by steven-bellock** [comment]
This was fixed by #1726.
