### ISSUE TITLE
KEY_EXCHANGE_RSP's SlotIDParam is checked against reserved bits

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1426]
The specification defines the upper four bits of `KEY_EXCHANGE_RSP.SlotIDParam` as Reserved. However libspdm assumes they are zero and checks them. See https://github.com/DMTF/libspdm/blob/8a5f88b4425539a0b3b5aa22bdd8c91c89fd6068/library/spdm_requester_lib/libspdm_req_key_exchange.c#L504-L512 The upper four bits need to be masked before checking the lower four bits.

**Comment by steven-bellock** [comment]
In addition unit / fuzz tests should be setting reserved bits to random values.

**Comment by hiption** [comment]
https://github.com/DMTF/libspdm/blob/8a5f88b4425539a0b3b5aa22bdd8c91c89fd6068/library/spdm_requester_lib/libspdm_req_key_exchange.c#L514-L519

**Comment by steven-bellock** [comment]
Yes, that too.
