### ISSUE TITLE
Build error when MUT_AUTH_CAP and ENCAP_CAP are disabled

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#1442]
Encountered the error below when MUT_AUTH_CAP and ENCAP_CAP are disabled.

`spdm_requester_lib/libspdm_req_challenge.c:310:18: error: implicit declaration of function ‘libspdm_encapsulated_request’`

libspdm_encapsulated_request() is declared in https://github.com/DMTF/libspdm/blob/0c0348623c76daabd81b9e91986e585c116ff2c4/include/internal/libspdm_requester_lib.h#L286
and wrapped by
#if (LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP) || (LIBSPDM_ENABLE_CAPABILITY_ENCAP_CAP)

We might need to also add the following?
#if (LIBSPDM_ENABLE_CAPABILITY_MUT_AUTH_CAP)
https://github.com/DMTF/libspdm/blob/9579c296218d9b06147f32010656f6df1d99f904/library/spdm_requester_lib/libspdm_req_challenge.c#L305-L319
#endif

**Comment by steven-bellock** [comment]
I was just looking into sweeping through all the capability bits with Github Actions, which would hopefully have caught this.
