### ISSUE TITLE
Move dump functions to debug_lib?

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#1455]
It would useful for integrators to reuse the existing platform dump functions or customize the dump functions (e.g. to only dump the first N bytes to avoid flushing the logs).

https://github.com/DMTF/libspdm/blob/4f8f99005368cb0e0091ef07b693631593af9b97/include/internal/libspdm_common_lib.h#L399-L431

**Comment by steven-bellock** [comment]
You would like these exposed through `include/library/spdm_common_lib.h`? In this particular case that should work since I don't expect these functions to ever change and I don't mind making them part of the public API.

Also `LIBSPDM_INTERNAL_DUMP_HEX_str` needs to be renamed to all lower-case. I'll file a separate issue for that.

**Comment by rw8896** [comment]
@steven-bellock
I am not intending to make these APIs public so for example integrators could also call a LIBSPDM_DUMP_HEX to dump data.

Instead, I would like to request to move these APIs to debug library so integrator could implement/customize the dump function like the libspdm_debug_print function.
https://github.com/DMTF/libspdm/blob/bc8101d6e890001dd13b09edca9d7e7482b6fc6a/os_stub/debuglib/debuglib.c#L59

**Comment by steven-bellock** [comment]
@rw8896 Would it be ok for the functions to default to the ones in `spdm_common_lib`, but we provide a way for you to override the implementation?

**Comment by rw8896** [comment]
@steven-bellock Yes, that will be great. Thank you so much.

**Comment by jyao1** [comment]
@rw8896, would you please propose a patch?

**Comment by rw8896** [comment]
> @rw8896, would you please propose a patch?

Sure, will do.
