### ISSUE TITLE
The public key context may have memory leak

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1460]
For `spdm_context->connection_info.peer_used_cert_chain[slot_id].leaf_cert_public_key`, the public key can be set in two places: 
https://github.com/DMTF/libspdm/blob/c9aed77adfc8eaf1d15e4514acb8a3a58a70c4bb/library/spdm_common_lib/libspdm_com_context_data.c#L338-L365

https://github.com/DMTF/libspdm/blob/c9aed77adfc8eaf1d15e4514acb8a3a58a70c4bb/library/spdm_requester_lib/libspdm_req_get_certificate.c#L341-L350
And the public key can be used in many places, such as: verify challenge/measurement/finish signature.
**But the public key context was not free, when all the flow is over. So this patch is fixing this issue.**
There are two options:

1. Add a new function `libspdm_end_context`, and the `libspdm_end_context` function will be called in 
https://github.com/DMTF/spdm-emu/blob/161880069a1f9c0a789fe1ec92a0213965237582/spdm_emu/spdm_requester_emu/spdm_requester_emu.c#L206-L217

2. Free memory in `libspdm_reset_context`, and the `libspdm_reset_context` will be called in the same place.

**Comment by jyao1** [comment]
Please add to libspdm_reset_context().
