### ISSUE TITLE
cache peer_used_cert_chain_buffer_hash instead of peer_used_cert_chain_buffer to save context size

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#147]
REF: https://github.com/DMTF/libspdm/blob/main/library/spdm_common_lib/spdm_common_lib_internal.h

We can use uint8 peer_used_cert_chain_buffer_hash[MAX_HASH_SIZE] to replace uint8 peer_used_cert_chain_buffer[MAX_SPDM_CERT_CHAIN_SIZE];

**Comment by jyao1** [comment]
NOTE: We need the leaf cert public key to validate the digital signature.

**Comment by jyao1** [comment]
We can also consider how to optimize large_managed_buffer_t certificate_chain_buffer in spdm_encap_context_t.

**Comment by qizhangz** [comment]
I will check it.
