### ISSUE TITLE
test_crypt does not function as a test

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1473]
Follow-up to my comment in #1350. `test_crypt` has multiple issues.
1. Tests fail if the backing cryptography library does not support the algorithm. For example, currently (our) MbedTLS does not support HMAC-SHA3 which is reported as a failure rather than skipped.
2. Some of the tests do not return a status on pass / fail, rendering them useless in CI/CD. For example : https://github.com/DMTF/libspdm/blob/beee7bd85a4f0961a5773aefc4dcab0408d538d1/unit_test/test_crypt/hash_verify.c#L420-L439
3. Return status confusion. In particular https://github.com/DMTF/libspdm/blob/3337da5d52c32d4bf3585506c67d8c92b587b256/unit_test/test_crypt/test_crypt.c#L149-L158 is incorrect. `libspdm_cryptest_main` returns `true (1)` if all the tests pass and `false (0)` if one of them fails. `main` should return `0` if all tests pass and `!= 0` if one of them fails.

Due to 3, `test_crypt` has failing tests but it is being reported as a pass to CI/CD. We should disable `test_crypt` in CI/CD until these issues are resolved.

**Comment by jyao1** [comment]
once you fix it issue, please re-enable test_crypt in CI.
