### ISSUE TITLE
Allow Integrator to specify ResponseNotReady policy

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1478]
The Integrator should be able to specify how a Requester handles a `ResponseNotReady` error from the Responder. The options include
- The Requester does not support `RESPOND_IF_READY` at compile time. A `ResponseNotReady` response is reported as an error to the Integrator.
- The Requester does not support `RESPOND_IF_READY` at run time (communicated through the SPDM context). A `ResponseNotReady` response is reported as an error to the Integrator.
- The Integrator registers a callback function that is called by libspdm when `ResponseNotReady` is received. The function can then determine what should be done and can communicate that to libspdm.
- After receiving a `ResponseNotReady` error from the Responder the Requester waits some amount of time before issuing a `RESPOND_IF_READY` request. This is the current behavior.

**Comment by hiption** [comment]
@steven-bellock  What is the difference between first and second?
Please explain in detail.

**Comment by steven-bellock** [comment]
In the first case `RESPOND_IF_READY` code is removed from Requester. In the second case `RESPOND_IF_READY` code is present in the Requester and it can decide at run time whether to enable or disable it. We'll start with the first case and add the second and/or third if folks are interested.
