### ISSUE TITLE
remove LIBSPDM_MAX_MEASUREMENT_BLOCK_COUNT

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1491]
we have LIBSPDM_MAX_MEASUREMENT_BLOCK_COUNT in config.h.
there is no need to add such restriction. we should remove it.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/b4b7474f64fedec25a0ce028f71c65bf3e936879/library/spdm_requester_lib/libspdm_req_get_measurements.c#L16-L18

**Comment by jyao1** [comment]
I dont think we need have such restriction, since we already have response buffer.

Those code should be removed.
