### ISSUE TITLE
Pointer checked for NULL will be dereferenced in libspdm_com_msg_log.c

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1497]
**1. Pointer 'spdm_context' checked for NULL at line 14 will be dereferenced at line 18.**

https://github.com/DMTF/libspdm/blob/b4b7474f64fedec25a0ce028f71c65bf3e936879/library/spdm_common_lib/libspdm_com_msg_log.c#L14-L18

**2. The following are similar as the above one.**
Pointer 'spdm_context' checked for NULL at line 29 will be dereferenced at line 32.
Pointer 'spdm_context' checked for NULL at line 39 will be dereferenced at line 43.
Pointer 'spdm_context' checked for NULL at line 50 will be dereferenced at line 54.
Pointer 'spdm_context' checked for NULL at line 61 will be dereferenced at line 65.
Pointer 'spdm_context' checked for NULL at line 74 will be dereferenced at line 78.

**Comment by steven-bellock** [comment]
@Zhiqiang520 I think what you're looking for is the ability to enable assertions when the CMake target is Release, correct?

**Comment by Zhiqiang520** [comment]
@steven-bellock No. The issue is reported by static analysis tool, I just report it.

**Comment by steven-bellock** [comment]
Understood. Feel free to waive these issues (and #1495 and #1496) since these are pre-conditions that the Integrator needs to honor.

I do think that the Integrator should be able to enable assertions on a Release build. I'll file a separate issue.

**Comment by jyao1** [comment]
I dont think we should "waive" the issue here.

Assuming the static analysis tool will check the final integrated image instead of individual function, we have two ways to fix the issue.
 * fix the caller
 * fix the callee

It seems the patch fixes the callee. But if we use ASSERT, then we should fix caller.

@Zhiqiang520 , would you please evaluate the fist option?

**Comment by Zhiqiang520** [comment]
waive this issue since these are pre-conditions that the Integrator needs to honor.
