### ISSUE TITLE
Support multiple root cert provision

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#151]
Current SPDM_DATA_PEER_PUBLIC_ROOT_CERT and peer_root_cert_provision only supports 1 root cert.

REF: https://github.com/DMTF/libspdm/blob/main/include/library/spdm_common_lib.h
REF: https://github.com/DMTF/libspdm/blob/main/library/spdm_common_lib/spdm_common_lib_internal.h

However, we need support use case to have multiple root cert enrolled.

**Comment by Wenxing-hou** [comment]
I will check it.
