### ISSUE TITLE
no way to provision provisioned_slot_id

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1518]
Current libspdm uses cert_chain as public key.

The `provisioned_slot_id` is used when the slot_id 0xFF is required.

However, the code does not have a way to set `provisioned_slot_id` . It is also 0.

We may need add `LIBSPDM_DATA_LOCAL_PUBLIC_CERT_CHAIN_DEFAULT_SLOT_ID` to `libspdm_data_type_t` .
The valid value is uint8_t from 0 to 7, when local_cert_chain is provisioned.

That will match existing logic such as :
```
    if (slot_id == 0xFF) {
        spdm_response->header.param2 = 0;

        slot_id = spdm_context->local_context.provisioned_slot_id;
```

**Comment by jyao1** [comment]
Also need fix spdm_emu to provision the default SLOT_ID.

**Comment by steven-bellock** [comment]
When the Requester has the raw public key of the Responder, then ideally the `slot_id` parameter would be ignored. For example in https://github.com/DMTF/libspdm/blob/052ea76c8d7bae021e26f620901a4607c6d8a1b0/include/library/spdm_requester_lib.h#L468-L474 This would also prevent `0xf` versus `0xff` confusion.
