### ISSUE TITLE
checking the size of the request

### ISSUE THREAD

**Issue by hiption** [DMTF/libspdm#1526]
The logic for checking the size of the request in the recent PR (https://github.com/DMTF/libspdm/pull/1512) seems to have been changed as follows.

![image](https://user-images.githubusercontent.com/6868066/208321217-60f9eb63-c94c-43a2-be0d-4379b3119bfc.png)

Why bigger is not problem?
I am curious about the reason for the change.
Do you have a plan to add some fields of `GET_VERSION` and `GET_CAPABILITIES` in version 1.3?

**Comment by jyao1** [comment]
> Why bigger is not problem?

Because the transport layer may add padding. For example, PCI_DOE requires 4 Bytes alignment.

**Comment by hiption** [comment]
Thank you for your reply.
In my understanding, SPDM can use MCTP or PCI_DOE as a transport layer.
In terms of `layered architecture`, each layer should complete processing their own messages.
Although PCI_DOE uses 4 bytes alignment, the message could be re-aligned before transmission to SPDM. 
why does SPDM depends on the certain lower layer?

**Comment by hiption** [comment]
Thank you for your reply.

BTW, I don't understand why DOE doesn't have padding length field.

**Comment by steven-bellock** [comment]
Also in #397, for unencrypted messages the transport does not need to know the size of the message, since SPDM allows the message to be parsed from top to bottom. We rely on the transport to perform basic size checks.

**Comment by steven-bellock** [comment]
Yes, those need to be fixed as well.

**Comment by hiption** [comment]
OK. I will fix it.

**Comment by xiangfeima** [comment]
Fix #1778 is proposed because I'm now facing the failure due to strict message size check while using PCI-DOE transport.
