### ISSUE TITLE
Compilation issue on linux in unit_test/test_spdm_requeter/get_certificate.c

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#153]
Seeing this compilation issue on ubuntu.

87%] Building C object unit_test/test_spdm_requester/CMakeFiles/test_spdm_requester.dir/get_certificate.c.o
/home/rkong/code/libspdm/unit_test/test_spdm_requester/get_certificate.c: In function ‘test_spdm_requester_get_certificate_case17’:
/home/rkong/code/libspdm/unit_test/test_spdm_requester/get_certificate.c:2015:8: error: variable ‘count’ set but not used [-Werror=unused-but-set-variable]
 2015 |  uintn count;
      |        ^~~~~
/home/rkong/code/libspdm/unit_test/test_spdm_requester/get_certificate.c: In function ‘test_spdm_requester_get_certificate_case18’:
/home/rkong/code/libspdm/unit_test/test_spdm_requester/get_certificate.c:2065:8: error: variable ‘count’ set but not used [-Werror=unused-but-set-variable]
 2065 |  uintn count;
      |        ^~~~~
cc1: all warnings being treated as errors

**Comment by jyao1** [comment]
Fixed in https://github.com/DMTF/libspdm/pull/154
