### ISSUE TITLE
Add check no more than one bit shall be set for the opaque data format in ALGORITHMS response message.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1542]
1. Refer to https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf
At paragraph 261 
Table 21 — Successful **ALGORITHMS response** message format
**OtherParamsSelection** field :
Selected Parameter Bit Mask. The Responder shall select one of the opaque data
formats supported by the Requester. Thus, **no more than one bit shall be set for
the opaque data format.**
• Bit [3:0]. See Opaque Data Format Support and Selection Table.
• Bit [7:4]. Reserved.

2. I think we should add check for **OtherParamsSelection** field like the following **MeasurementSpecificationSel** at line 192.
https://github.com/DMTF/libspdm/blob/a732e90c4df1863e4fe6e8c75a8559a036fefa5c/library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c#L192-L195

**Comment by steven-bellock** [comment]
This also needs a unit test to trigger the check in https://github.com/DMTF/libspdm/blob/main/unit_test/test_spdm_requester/error_test/negotiate_algorithms_err.c

**Comment by Zhiqiang520** [comment]
I will check it.
