### ISSUE TITLE
When SPDM requester uses libspdm_aead_encryption/decryption(), where is secured_message_context->secured_message_version copied from

### ISSUE THREAD

**Issue by jcahill0** [DMTF/libspdm#1549]
When debugging, we had a need to temporarily print out the parameters used when calling libspdm_aead_encryption() and libspdm_aead_decryption().  I noticed secured_message_context->secured_message_version was always 0 even though the messages clearly used 0x10.

        result = libspdm_aead_encryption(
            secured_message_context->secured_message_version,
            secured_message_context->aead_cipher_suite, key,
            aead_key_size, salt, aead_iv_size, (uint8_t *)a_data,
            record_header_size, dec_msg, cipher_text_size, tag,
            aead_tag_size, enc_msg, &cipher_text_size);

And

        result = libspdm_aead_decryption(
            secured_message_context->secured_message_version,
            secured_message_context->aead_cipher_suite, key,
            aead_key_size, salt, aead_iv_size, a_data,
            record_header_size, enc_msg, cipher_text_size, tag,
            aead_tag_size, dec_msg, &cipher_text_size);

Walking through the code, I can see libspdm_try_send_receive_key_exchange() calling libspdm_assign_session_id(spdm_context), down into libspdm_session_info_init(), and this attempts to initialize secured_message_context->secured_message_version, but using spdm_context->connection_info.secured_message_version.

    libspdm_secured_message_set_algorithms(
        session_info->secured_message_context,
        spdm_context->connection_info.version,
        spdm_context->connection_info.secured_message_version,
        spdm_context->connection_info.algorithm.base_hash_algo,
        spdm_context->connection_info.algorithm.dhe_named_group,
        spdm_context->connection_info.algorithm.aead_cipher_suite,
        spdm_context->connection_info.algorithm.key_schedule);

When I tried to find the location that spdm_context->connection_info.secured_message_version was initialized from, I could not find its source.  There were limited references to connection_info.secured_message_version outside the unit test code:
* libspdm_set_data(), which would be used by the application and isn't specified in the manual section as a required step
* libspdm_get_data(), which doesn't set the value
* libspdm_process_opaque_data_supported_version_data(), which is only used by responder code for handling KEY_EXCHANGE but does set the value
* libspdm_build_opaque_data_version_selection_data(), which only reads the value to build part of the KEY_EXCHANGE message

So my question really boils down to, where is spdm_context->connection_info.secured_message_version initialized from?

My current analysis shows spdm_context->connection_info.secured_message_version isn't ever initialized beyond 0, let alone to the value used in the KEY_EXCHANGE message.  Is this correct?

If this is correct, the behavior isn't a problem now, but it will be a problem once the libspdm_aead_encryption/decryption() functions need to support multiple versions within the opaque data.

**Comment by jyao1** [comment]
@jcahill0, It is a bug, please help to review the PR.

**Comment by jyao1** [comment]
Ideally, responder's libspdm_process_opaque_data_supported_version_data() and requester's libspdm_process_opaque_data_version_selection_data() should set spdm_context->connection_info.secured_message_version, before libspdm_assign_session_id().
