### ISSUE TITLE
Use libspdm_ or lspdm_ prefix to prevent collisions

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#155]
To prevent collisions, all libspdm symbols that are exposed via spdm_requester_lib.h and spdm_responder_lib.h should have a libspdm_ (preferred) or lspdm_ prefix.

**Comment by rkongintel** [comment]
Is it possible to have a prefix for all the functions, including those under the os_stub directory as well. They can be different prefixes depending on where they live. If a vendor chooses to only implement a subset of functionality, a prefix would make it easier to search map files, to determine what supporting functions need to be implemented.
