### ISSUE TITLE
libspdm_sleep() should use microsecond

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1555]
Currently, libspdm_sleep() is used RDTExponent.

According to the spec, RDTExponent is microsecond unit.

But libspdm_sleep is milliseconds unit. It should be changed to microsecond unit.

For the implementation that only supports millisecond unit, it may use below:
```
void libspdm_sleep(uint64_t microsecond)
{
    uint64_t milliseconds;

    milliseconds = (microsecond + 999) / 1000;
    Sleep((DWORD)milliseconds);
}
```

**Comment by steven-bellock** [comment]
At this time I think the main requirement is that libspdm can support sensible values of WT<sub>Max</sub>, which is `(RDT * RDTM) - RTT`. I can't imagine WT<sub>Max</sub> would ever be less than a millisecond, so for now it should be fine to keep `libspdm_sleep` at milliseconds.
