### ISSUE TITLE
remove code coverage related build option for GCC by default

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#157]
Currently, the gcov related build option is added by default - such as --coverage, -ftest-coverage, -lgcov -fprofile-arcs, which causes problem in embedded system build with GCC, because the std might not have such support.

Need add gcov as an option and disable by default.

**Comment by steven-bellock** [comment]
@jyao1 to provide a solution. We can add a new build type (Release, Debug, Test) or just add a new flag to enable / disable code coverage.
