### ISSUE TITLE
memlib enhancements

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1585]
Proposal for the following changes to `memlib`.

```
int libspdm_copy_mem(void *dst_buf, size_t dst_len, const void *src_buf, size_t src_len);

becomes

void libspdm_copy_mem(void *dst_buf, size_t dst_len, const void *src_buf, size_t src_len);
```
libspdm does not currently check the return value. 
```
void *libspdm_zero_mem(void *buffer, size_t length);

becomes

void libspdm_zero_mem(void *buffer, size_t length);
```
libspdm has no need for the return value.
```
int32_t libspdm_const_compare_mem(const void *destination_buffer, const void *source_buffer, size_t length);

becomes

bool libspdm_const_compare_mem(const void *destination_buffer, const void *source_buffer, size_t length);
```
bool is the appropriate return type.
```
void *libspdm_set_mem(void *buffer, size_t length, uint8_t value);

becomes

...nothing...
```
`libspdm_set_mem` is not used by any of the core libraries.

**Comment by steven-bellock** [comment]
@richkong88 @xiaoyuruan

**Comment by jyao1** [comment]
libspdm_copy_mem() -> need assert and deadloop in the function.
libspdm_zero_mem() -> OK
libspdm_const_compare_mem() -> comply with linux. OK.
libspdm_set_mem() -> 1.3 may use it. keep it.

**Comment by steven-bellock** [comment]
For `libspdm_const_compare_mem`
- BSD returns `1` if the strings are the same and `0` if they are not. https://man.freebsd.org/cgi/man.cgi?query=consttime_memequal&manpath=NetBSD+7.0
- Linux returns `0` if the strings are the same and `1` if they are not. https://elixir.bootlin.com/linux/latest/source/include/crypto/algapi.h#L280
- And regular C standard library `memcmp` is `0` if they are the same.

So a `bool` doesn't make sense for Linux and C standard. But we can change the `int32_t` to an `int`.

**Comment by jyao1** [comment]
libspdm_const_compare_mem() -> that is too confusing. Do we have to change?
This will bring big impact - all existing code must be changed. Now I would prefer to keep it as is.

**Comment by jyao1** [comment]
3/13/2023 - to avoid misuse of `compare_mem`, we can introduce `bool libspdm_const_is_mem_equal()`.
Then `true` means the memory is equal.
