### ISSUE TITLE
libspdm_deinit_context should free all allocated memory tied to the spdm_context

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1586]
Similiar to what is done in `libspdm_reset_context` : https://github.com/DMTF/libspdm/blob/21ef77cf5d94747f939737b05060ccdec0d0aaf9/library/spdm_common_lib/libspdm_com_context_data.c#L2207-L2213

**Comment by taprinz** [comment]
It seems that when we are using running-hash based transcript buffers, those are not reset in these functions. Like `libspdm_reset_message_b` is never called if we don't complete session establishment, causing a memory leak.
