### ISSUE TITLE
It seems that bin_str0 is not needed in libspdm_generate_session_handshake_key

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1589]
The `bin_str0` is not needed in `libspdm_generate_session_handshake_key`.

In  `libspdm_generate_session_handshake_key`, the `bin_str0`  is just dumped.
https://github.com/DMTF/libspdm/blob/702be53a73bd1cf962bf89ede58a16607e289a1b/library/spdm_secured_message_lib/libspdm_secmes_session.c#L176-L201

**Reference: In SPDM 1.2.1 spec Figure 27 — Key schedule**
![image](https://user-images.githubusercontent.com/87060980/210921823-d6281e48-b6c7-4e7e-b801-02bc24bfb366.png)

**Comment by jyao1** [comment]
we can move bin_str0 dump to libspdm_generate_session_data_key().

**Comment by Wenxing-hou** [comment]
I will check it.
