### ISSUE TITLE
add conditional check for EKU

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1594]
https://github.com/DMTF/libspdm/issues/1592 removed the mandatory check for EKU according to the latest spec.

See 10.8.2.1 Extended Key Usage authentication OIDs

We need add conditional check for EKU. E.g. a responder should NOT send a cert with requester auth EKU only.

**Comment by steven-bellock** [comment]
You could argue that that check should be left up to the Verifier, especially since libspdm doesn't do anything with most (or all) of the OIDs. Either way we should be explicit about what libspdm checks in a certificate and what is left to the Integrator / Verifier.

**Comment by xiangfeima** [comment]
@jyao1 @steven-bellock 
please assign this one to me, I think I can look into it sometime next week.
