### ISSUE TITLE
Calculate shared key according to RFC8446

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#16]
Responder authentication multiple key exchange example
The DHE secrets are computed as specified in clause 7.4 of RFC 8446.

in RFC 8446, 7.4:
The negotiated key (Z) is converted to a
byte string by encoding in big-endian form and left-padded with zeros
up to the size of the prime.

**Comment by steven-bellock** [comment]
Related issue in specification: https://github.com/DMTF/Security-TF/issues/1351
