### ISSUE TITLE
libspdm_check_request_flag_compability() wrongly checked cert_cap 

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1603]
https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L99
```
        if ((cert_cap == 1) || (pub_key_id_cap == 1)) {
...
        } else {
            /* If certificates or public keys are not enabled then these capabilities
             * cannot be enabled. */
            if ((chal_cap == 1) || (key_ex_cap == 1) || (mut_auth_cap == 1)) {
                return false;
            }
        }
    }
```

I dont think `key_ex_cap == 1` should be there.  `cert_cap == 1` is only for mutual auth.

**Comment by mcsmonk** [comment]
I guess that such flag check should be needed since the slotID field is included in key_ex request and challenge although the slotID field is used only when mutual authentication is performed. Is it right?

**Comment by mcsmonk** [comment]
Additionally, I think some flag check should be changed
In request capability compability check [https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L48](https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L48),

```
-        if ((key_ex_cap == 0) && (psk_cap == 1)) {
-            if (handshake_in_the_clear_cap == 1) {
+        if ((key_ex_cap == 0) && (handshake_in_the_clear_cap == 1)) {
                 return false;
-            }
         }
```
becasue handshake_in_the_clear_cap is ignored in PSK case.

And, ((mut_auth_cap == 1) && (encap_cap == 0)) should also be checked in version 1.2 because mutual authentication is included in Session-based mutual authentication although basic mutual authentication is deprecated.

Then, ((meas_cap != 0) || (meas_fresh_cap != 0)) checking should be added for version 1.1

**Comment by mcsmonk** [comment]
In responder's compability check, I have some suggestions.
[https://github.com/DMTF/libspdm/blob/main/library/spdm_requester_lib/libspdm_req_get_capabilities.c#L18](https://github.com/DMTF/libspdm/blob/main/library/spdm_requester_lib/libspdm_req_get_capabilities.c#L18)

 The first is 
``` C
     if (version == SPDM_MESSAGE_VERSION_10) {
-        /* If measurements are not signed then CERT_CAP must equal CHAL_CAP.
-         * If measurements are signed then CERT_CAP must be set. */
-        if ((meas_cap == 0) || (meas_cap == 1)) {
-            if (cert_cap != chal_cap) {
+        if (cert_cap == 0) {
+            if ((meas_cap == 2) || (chal_cap == 1)) {
                 return false;
             }
-        } else if (meas_cap == 2) {
-            if (cert_cap == 0) {
+        }
+        else {
+            if ((meas_cap != 2) && (chal_cap == 0)) {
                 return false;
             }
         }
```

The second is also
``` C
-        if ((key_ex_cap == 0) && (psk_cap == 1)) {
-            if (handshake_in_the_clear_cap == 1) {
+        if ((key_ex_cap == 0) && (handshake_in_the_clear_cap == 1)) {
                 return false;
-            }
         }
```

Lastly, for version 1.2
``` C
+        if ((pub_key_id_cap == 1) && (alias_cert_cap == 1)) {
+            return false;
+        }
```
should be added

**Comment by steven-bellock** [comment]
@mcsmonk Feel free to open a new issue for those enhancements.

**Comment by steven-bellock** [comment]
In https://github.com/DMTF/libspdm/blob/5de7be03b0ef17c3c8865f313e5b06d687b56daf/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L70-L80 the `(mut_auth_cap == 1)` is also a bug, since `chal_cap == 1 && key_ex_cap == 0 && psk_cap == 0 && mut_auth_cap == 1)` is a legal combination, even if it is deprecated.

**Comment by mcsmonk** [comment]
> In
> 
> https://github.com/DMTF/libspdm/blob/5de7be03b0ef17c3c8865f313e5b06d687b56daf/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L70-L80
> 
> the `(mut_auth_cap == 1)` is also a bug, since `chal_cap == 1 && key_ex_cap == 0 && psk_cap == 0 && mut_auth_cap == 1)` is a legal combination, even if it is deprecated.

I totally agree with this.

But, in below case,

> https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L99
> 
> ```
>         if ((cert_cap == 1) || (pub_key_id_cap == 1)) {
> ...
>         } else {
>             /* If certificates or public keys are not enabled then these capabilities
>              * cannot be enabled. */
>             if ((chal_cap == 1) || (key_ex_cap == 1) || (mut_auth_cap == 1)) {
>                 return false;
>             }
>         }
>     }
> ```
> 
> I dont think `key_ex_cap == 1` should be there. `cert_cap == 1` is only for mutual auth.

although `cert_cap` means only that requester support `DIGEST` and `CERTIFICATE` response message, responder's `pub_key_id_cap` must be needed to set for requester to verify the signature of the `KEY_EXCHANGE` response message and this implies that requester support to capability which treats certification related to `cert_cap` or `pub_key_id_cap` literally

**Comment by steven-bellock** [comment]
This was fixed by #1616.

**Comment by mcsmonk** [comment]
@steven-bellock  Can I get the answer of why `key_ex_cap` be excludede?

> > https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L99
> > ```
> >         if ((cert_cap == 1) || (pub_key_id_cap == 1)) {
> > ...
> >         } else {
> >             /* If certificates or public keys are not enabled then these capabilities
> >              * cannot be enabled. */
> >             if ((chal_cap == 1) || (key_ex_cap == 1) || (mut_auth_cap == 1)) {
> >                 return false;
> >             }
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I dont think `key_ex_cap == 1` should be there. `cert_cap == 1` is only for mutual auth.
> 
> although `cert_cap` means only that requester support `DIGEST` and `CERTIFICATE` response message, certificate-related capability must be needed for requester to verify the signature of the `KEY_EXCHANGE` response message and this implies that requester support to capability which treats certification related to `cert_cap` or `pub_key_id_cap` literally

**Comment by steven-bellock** [comment]
Requester's `CERT_CAP==1` means that the Responder can `GET_CERTIFICATE` from the Requester. There's no Requester capability that states the Requester can `GET_CERTIFICATE` from the Responder.
