### ISSUE TITLE
private_pem should explicitly zeroize before free

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1605]
1. in `libspdm_responder_data_sign` function, `private_pem` at line 1769 and 1784 should explicitly zeroize before free.
https://github.com/DMTF/libspdm/blob/178bb19c58e40747def7f494d03a62b57d406d06/os_stub/spdm_device_secret_lib_sample/lib.c#L1766-L1771
https://github.com/DMTF/libspdm/blob/178bb19c58e40747def7f494d03a62b57d406d06/os_stub/spdm_device_secret_lib_sample/lib.c#L1784
2. similar case in `libspdm_requester_data_sign` function, `private_pem` at line 1704 and 1719 should explicitly zeroize before free.
https://github.com/DMTF/libspdm/blob/178bb19c58e40747def7f494d03a62b57d406d06/os_stub/spdm_device_secret_lib_sample/lib.c#L1699-L1706
https://github.com/DMTF/libspdm/blob/178bb19c58e40747def7f494d03a62b57d406d06/os_stub/spdm_device_secret_lib_sample/lib.c#L1719
3. similar case in `libspdm_gen_csr` function, `prikey` at line 1099 and 1112 should explicitly zeroize before free.
https://github.com/DMTF/libspdm/blob/178bb19c58e40747def7f494d03a62b57d406d06/os_stub/spdm_device_secret_lib_sample/lib.c#L1096-L1101
https://github.com/DMTF/libspdm/blob/178bb19c58e40747def7f494d03a62b57d406d06/os_stub/spdm_device_secret_lib_sample/lib.c#L1112

**Comment by Wenxing-hou** [comment]
I will check it.
