### ISSUE TITLE
libspdm_try_send_receive_key_exchange function should call libspdm_release_receiver_buffer function before return error.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1613]
I think line 668 should be changed like line 674~675 `goto receive_done;`, call `libspdm_release_receiver_buffer` function before return error.
https://github.com/DMTF/libspdm/blob/de3c5030ed37cc68717aa4e41d6c33f73028476c/library/spdm_requester_lib/libspdm_req_key_exchange.c#L665-L676
https://github.com/DMTF/libspdm/blob/de3c5030ed37cc68717aa4e41d6c33f73028476c/library/spdm_requester_lib/libspdm_req_key_exchange.c#L716-L718

**Comment by steven-bellock** [comment]
A check for this should be incorporated into the Requester / Responder unit tests as well. Once the function-under-test returns then it should check that the buffers have been released. I'll file a separate issue for that.

**Comment by Xiaohanjlll** [comment]
I will check this
