### ISSUE TITLE
Incorrect debug information in responder key_update

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#162]
[libspdm/blob/main/library/spdm_responder_lib/key_update.c](https://github.com/DMTF/libspdm/blob/main/library/spdm_responder_lib/key_update.c)

The string '**Responder**' in line 107 does not match with the key update action 'SPDM_KEY_UPDATE_ACTION_**REQUESTER** 'in line 111.
I think the string '**Responder**' in line 107 should be '**Requester**'.

https://github.com/DMTF/libspdm/blob/50c2b1a389f45c3060aa040148cdd1384214a074/library/spdm_responder_lib/key_update.c#L106-L111

**Comment by jyao1** [comment]
Agree. Typo.
