### ISSUE TITLE
The code is duplicate in libspdm_aead_encryption and libspdm_aead_decryption

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1626]
The follow code is duplicate:
https://github.com/DMTF/libspdm/blob/1026c953d6032e1a2ca4f29af52e30f1bea9e05d/library/spdm_crypt_lib/libspdm_crypt_aead.c#L67-L84

https://github.com/DMTF/libspdm/blob/1026c953d6032e1a2ca4f29af52e30f1bea9e05d/library/spdm_crypt_lib/libspdm_crypt_aead.c#L119-L136

The code should be changed to:
```
    case SPDM_ALGORITHMS_AEAD_CIPHER_SUITE_AES_128_GCM:
    case SPDM_ALGORITHMS_AEAD_CIPHER_SUITE_AES_256_GCM:
#if LIBSPDM_AEAD_GCM_SUPPORT
        return libspdm_aead_aes_gcm_decrypt(key, key_size, iv, iv_size, a_data,
                                            a_data_size, data_in, data_in_size, tag,
                                            tag_size, data_out, data_out_size);
#else
        LIBSPDM_ASSERT(false);
        return false;
#endif
```

**Comment by xiangfeima** [comment]
I'd take this if no one is working on it.

**Comment by steven-bellock** [comment]
Go for it. And check out some of the issues assigned to @steven-bellock and see if any are interesting.
