### ISSUE TITLE
Version of ERROR response to invalid GET_VERSION must be 1.0

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#163]
This was recently clarified by the Security TF. Similar to how `GET_VERSION.SPDMVersion` must always be `1.0 (0x10)`, so too must `ERROR.SPDMVersion` be `1.0` when an invalid `GET_VERSION` request is sent.

**Comment by steven-bellock** [comment]
Related issue https://github.com/DMTF/libspdm/issues/41

**Comment by jyao1** [comment]
agree
