### ISSUE TITLE
need rename OPENSPDM_* to LIBSPDM_*

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#164]
#define OPENSPDM_RSA_SSA_SUPPORT 1
#define OPENSPDM_RSA_PSS_SUPPORT 1
#define OPENSPDM_ECDSA_SUPPORT 1

#define OPENSPDM_FFDHE_SUPPORT 1
#define OPENSPDM_ECDHE_SUPPORT 1

#define OPENSPDM_AEAD_GCM_SUPPORT 1
#define OPENSPDM_AEAD_CHACHA20_POLY1305_SUPPORT 1

#define OPENSPDM_SHA256_SUPPORT 1
#define OPENSPDM_SHA384_SUPPORT 1
#define OPENSPDM_SHA512_SUPPORT 1

**Comment by steven-bellock** [comment]
Closing as duplicate.
