### ISSUE TITLE
Requester-generated nonce protects the challenge-response from replay attacks, whereas a Responder-generated nonce prevents the Responder from signing over arbitrary data that the Requester dictates

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1662]
Could you please clarify? This is present in SPDM spec.

**Comment by steven-bellock** [comment]
If the Requester can get the Responder to sign arbitrary data using its private key, then maybe the Requester can figure out the value of the secret key. The Responder's nonce stymies that.

**Comment by steven-bellock** [comment]
@PrakashK94 If this answers your question please close the issue.
