### ISSUE TITLE
libspdm supporting key, certificate generation 

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#1663]
Does libspdm exposes wrapper/support to create the following programmatically ? 

openssl genpkey -genparam -out param.pem -algorithm EC -pkeyopt ec_paramgen_curve:P-384
openssl req -nodes -x509 -days 3650 -newkey ec:param.pem -keyout ca.key -out ca.cert -sha384 -subj "/CN=intel test ECP256 CA"
openssl pkey -in ca.key -outform der -out ca.key.der
openssl req -nodes -newkey ec:param.pem -keyout inter.key -out inter.req -sha384 -batch -subj "/CN=intel test ECP256 intermediate cert"
openssl req -nodes -newkey ec:param.pem -keyout end_requester.key -out end_requester.req -sha384 -batch -subj "/CN=intel test ECP256 requseter cert"
openssl req -nodes -newkey ec:param.pem -keyout end_responder.key -out end_responder.req -sha384 -batch -subj "/CN=intel test ECP256 responder cert"
openssl x509 -req -in inter.req -out inter.cert -CA ca.cert -CAkey ca.key -sha384 -days 3650 -set_serial 1 -extensions v3_inter -extfile ../openssl.cnf
openssl x509 -req -in end_requester.req -out end_requester.cert -CA inter.cert -CAkey inter.key -sha384 -days 3650 -set_serial 2 -extensions v3_end -extfile ../openssl.cnf
openssl x509 -req -in end_responder.req -out end_responder.cert -CA inter.cert -CAkey inter.key -sha384 -days 3650 -set_serial 3 -extensions v3_end -extfile ../openssl.cnf
openssl asn1parse -in ca.cert -out ca.cert.der
openssl asn1parse -in inter.cert -out inter.cert.der
openssl asn1parse -in end_requester.cert -out end_requester.cert.der
openssl asn1parse -in end_responder.cert -out end_responder.cert.der
cat ca.cert.der inter.cert.der end_requester.cert.der > bundle_requester.certchain.der
cat ca.cert.der inter.cert.der end_responder.cert.der > bundle_responder.certchain.der
openssl ec -inform PEM -outform DER -in end_responder.key -out end_responder.key.der
openssl pkcs8 -in end_responder.key.der -inform DER -topk8 -nocrypt -outform DER > end_responder.key.p8
openssl ec -inform PEM -outform DER -in end_requester.key -out end_requester.key.der
openssl pkcs8 -in end_requester.key.der -inform DER -topk8 -nocrypt -outform DER > end_requester.key.p8
openssl pkey -in end_requester.key -inform PEM -pubout -outform PEM -out end_requester.key.pub
openssl pkey -in end_requester.key -inform PEM -pubout -outform DER -out end_requester.key.pub.der
openssl pkey -in end_responder.key -inform PEM -pubout -outform PEM -out end_responder.key.pub
openssl pkey -in end_responder.key -inform PEM -pubout -outform DER -out end_responder.key.pub.der
openssl req -nodes -x509 -days 3650 -newkey ec:param.pem -keyout ca1.key -out ca1.cert -sha384 -subj "/CN=intel test ECP384 CA"
openssl pkey -in ca1.key -outform der -out ca1.key.der
openssl x509 -req -in inter.req -out inter1.cert -CA ca1.cert -CAkey ca1.key -sha384 -days 3650 -set_serial 1 -extensions v3_inter -extfile ../openssl.cnf
openssl x509 -req -in end_requester.req -out end_requester1.cert -CA inter1.cert -CAkey inter.key -sha384  -days 3650 -set_serial 2 -extensions v3_end -extfile ../openssl.cnf
openssl x509 -req -in end_responder.req -out end_responder1.cert -CA inter1.cert -CAkey inter.key -sha384 -days 3650 -set_serial 3 -extensions v3_end -extfile ../openssl.cnf
openssl asn1parse -in ca1.cert -out ca1.cert.der
openssl asn1parse -in inter1.cert -out inter1.cert.der
openssl asn1parse -in end_requester1.cert -out end_requester1.cert.der
openssl asn1parse -in end_responder1.cert -out end_responder1.cert.der
cat ca1.cert.der inter1.cert.der end_requester1.cert.der > bundle_requester.certchain1.der
cat ca1.cert.der inter1.cert.der end_responder1.cert.der > bundle_responder.certchain1.der

**Comment by steven-bellock** [comment]
Yeah it seems like it would be good to have in a script rather than a text file. Also those instances of `intel` should be changed to `DMTF`. I'll file a separate issue.

**Comment by steven-bellock** [comment]
Also that `RECOMMEND: Use openssl 1.1.1k` seems stale.

**Comment by PrithviAPai** [comment]
Thank you 
I will close the issue
