### ISSUE TITLE
Build failure with CRYPTO=mbedtls on Ubuntu 18.04?

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#1670]
Failure happened on Ubuntu 18.04 with cmake version 3.10.2

**Build command:**
`cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=mbedtls ..`

**Errors:**
ENABLE_BINARY_BUILD=0; Building mbedtls library from source.
CMake Error at os_stub/mbedtlslib/mbedtls/library/CMakeLists.txt:232 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "mbedcrypto".

CMake Error at os_stub/mbedtlslib/mbedtls/library/CMakeLists.txt:232 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "mbedx509".

CMake Error at os_stub/mbedtlslib/mbedtls/library/CMakeLists.txt:232 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "mbedtls".

**Does anyone see the same errors?**

It seems that https://github.com/DMTF/libspdm/blob/main/os_stub/mbedtlslib/CMakeLists.txt missed to define LIB_INSTALL_DIR as in 
mbedtls's CMakeLists.txt but I am not sure.

https://github.com/Mbed-TLS/mbedtls/blob/dd79db10014d85b26d11fe57218431f2e5ede6f2/CMakeLists.txt#L254-L257

**Comment by steven-bellock** [comment]
Seems to work on Github : https://github.com/steven-bellock/libspdm/actions/runs/4056260825

**Comment by rw8896** [comment]
@steven-bellock Thanks, following your link I am not sure about the version of cmake.
Do you know if its cmake is also 3.10.2?

It works on my another Ubuntu 20.04 with cmake 3.16.3.
Comparing the cmake manuals of both versions, 3.16 seemed to add some descriptions about empty destination.
`For regular executables, static libraries and shared libraries, the DESTINATION argument is not required. `
https://cmake.org/cmake/help/v3.16/command/install.html

**Comment by steven-bellock** [comment]
> cmake version 3.25.1

As a side issue I'll update the CI/CD so that it prints out the CMake version in the logs.

**Comment by rw8896** [comment]
@steven-bellock Thanks, so I checked the cmake version history and it looks like [3.14](https://cmake.org/cmake/help/latest/release/3.14.html#commands) or above could accept empty DESTINATION.

_The [install(TARGETS)](https://cmake.org/cmake/help/latest/command/install.html#command:install) command learned how to install to an appropriate default directory for a given target type, based on variables from the [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#module:GNUInstallDirs) module and built-in defaults, in lieu of a DESTINATION argument._

To build libspdm with cmake lower than 3.14, should we set LIB_INSTALL_DIR in https://github.com/DMTF/libspdm/blob/main/os_stub/mbedtlslib/CMakeLists.txt ? (since it's minimum required version is just 2.8.12)

if(LIB_INSTALL_DIR)
else()
    set(LIB_INSTALL_DIR lib)
endif()

**Comment by steven-bellock** [comment]
Yes if that's all there is to it and it works with both old and new versions of CMake.
