### ISSUE TITLE
`libspdm_{read/write}_uint*` functions should be `static inline`

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1674]
The `libspdm_read_uint*` and `libspdm_write_uint*` functions currently have external linkage within `common_lib`. They should be `static inline` with their implementations in the header.

**Comment by steven-bellock** [comment]
@steven-bellock to provide size data.

**Comment by steven-bellock** [comment]
At least on Visual Studio I did not see the optimizations I was expecting, so closing this issue.

**Comment by lsun100** [comment]
FYI. Potential code size impact on x86_64 and riscv_64 I did earlier for this one.

============
#define FUNC(name, offset) \
void name(uint8_t *buffer) \
{ \
    uint16_t val16; \
    uint32_t val32; \
 \
    __asm__ __volatile__ ("" : : : "memory"); \
    val16 = libspdm_read_uint16(buffer); \
    libspdm_write_uint16(buffer + 2, val16); \
 \
    val32 = libspdm_read_uint16(buffer + 4); \
    libspdm_write_uint32(buffer + 8 + offset, val32); \
}

FUNC(func1, 1)
FUNC(func2, 2)
FUNC(func3, 3)
FUNC(func4, 4)
FUNC(func5, 5)
============

Compiled with -O2.

x86_64:
no-inline:  0x14b bytes
inline:        0x134 bytes

riscv_64:
no-inline:   0x198 bytes
inline:         0x1d6 bytes

The advantage seems not very obvious.
