### ISSUE TITLE
libspdm_asym_get_private_key_from_pem fails before responder going to generate signatures and send it back to the requestor

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1688]
I see that in the LIBSPDM 2.0.0 code base, in this file, libspdm/os_stub/spdm_device_secret_lib_sample/lib.c

libspdm_responder_data_sign
•	libspdm_read_responder_private_certificate – Pass- It reads the responder private key in a file. I tried providing leaf.key as well as leaf.pem but nothing works for the below function.
•	libspdm_asym_get_private_key_from_pem – fails.

Could you please share your suggestion on this?

**Comment by steven-bellock** [comment]
@PrakashK94 Can you add more information?

**Comment by PrakashK94** [comment]
I am able to get rid of this issue.

Thanks.
