### ISSUE TITLE
question regarding to the timing of reset_message_b

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#1697]
Hi all,
I don't understand why message_b is reset upon GET_DIGESTS execution.
There seems no description in SPDM spesification says we should do so...
Could you please explain the reason? Thank you very much!
https://github.com/DMTF/libspdm/blob/87241dc8ada4de09aef14be4247c4b2ad6f407e9/library/spdm_common_lib/libspdm_com_context_data.c#L981-L983

**Comment by steven-bellock** [comment]
See #916.

**Comment by xiangfeima** [comment]
Thank you! Let's close the question.
