### ISSUE TITLE
Is libspdm intended to become production quality reference implementation?

### ISSUE THREAD

**Issue by ayj** [DMTF/libspdm#17]
Looking forward in time as libspdm matures, is the intent to be more than just a sample implementation? 

The [README.md](https://github.com/DMTF/libspdm/blob/main/README.md) says:

> Support to be included in UEFI host environment EDKII, such as edkii_spdm_requester
> Support to be included in OpenBMC. It is in planning, see SPDM Integration.

... but it also says:

> This openspdm is a **sample** implementation for the DMTF SPDM specification

and 

> Known limitation: This package is only the sample code to show the concept. It does not have a full validation such as robustness functional test and fuzzing test. It does not meet the production quality yet. Any codes including the API definition, the libary and the drivers are subject to change.

One interpretation of these statements is that libspdm isn't production quality **yet**, and that possibly the author's intent is to make libspdm a reference implementation instead of just a sample implementation. As someone relatively new to the libspdm project, it wasn't clear whether the goal of libspdm is to remain a sample (non-production) or serve as a reference implementation for vendors / implementers.

**Comment by Google-Autofuzz** [comment]
Would you be interested in having libspdm integrated with [OSS-Fuzz]( https://github.com/google/oss-fuzz ), since you alrady have [a couple of fuzzers](https://github.com/DMTF/libspdm/tree/main/unit_test/fuzzing)?

**Comment by jyao1** [comment]
Seems good idea.
Could you please submit a Pull-Request to enable OSS-Fuzz?

**Comment by jyao1** [comment]
create #241 to handle OSS-Fuzz.

Close this one, because the question is answered.
