### ISSUE TITLE
SPDM 1.1 : ALGORITHMS response, MeasurementHashAlgo field usage

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#1703]
Hello @steven-bellock @jyao1 @rw8896 ,

In the ALGORITHMS response, have a question about MeasurementHashAlgo field...

Measurement of firmware/software is nothing but a hash of an fw/sw , in short measurement is the hash (could be any hash type)

From the Spec... for MeasurementHashAlgo field...
***********************************************************************************************
Bit mask indicating the SPDM-enumerated hashing algorithm selected for
measurements.
Bit 0. Raw Bit Stream Only
Bit 1. TPM_ALG_SHA_256
Bit 2. TPM_ALG_SHA_384
Bit 3. TPM_ALG_SHA_512
Bit 4. TPM_ALG_SHA3_256
Bit 5. TPM_ALG_SHA3_384
Bit 6. TPM_ALG_SHA3_512
If the Responder supports GET_MEASUREMENTS , exactly one bit in this bit
field shall be set. Otherwise, the Responder shall set this field to 0
***********************************************************************************************

**My Question:**
<FW_MEASUREMENT> - I will be storing SHA2_384 of a firmware image as the measurement
As a responder, I'm setting bit0 which is RAW_STREAM - So I have to send the above <FW_MEASUREMENT> as raw stram - Is my understanding correct?

If we set Bit2 (TPM_ALG_SHA_384), then the responder should be sending SHA2_384of <FW_MEASUREMENT> and then send this hash in GET_MEASUREMENTS response - Is my understanding correct?

In the GET_MEASUREMENT response - measurement block format, I'm selecting DMTF and DMTFSpecMeasurementValueType has raw bit stream.

**Comment by steven-bellock** [comment]
>Measurement of firmware/software is nothing but a hash of an fw/sw , in short measurement is the hash (could be any hash type)

No. In the case of firmware, the firmware image itself is the measurement. The Responder can return this measurement as either a raw bit stream (the bytes of the firmware ELF file for example) or it can provide a hash over the firmware using the algorithm specified in `MeasurementHashAlgo`. Note what the specification says regarding `MeasurementHashAlgo`.
>A Responder shall only select bit 0 if the Responder supports raw bit streams as the only form of measurement; otherwise, it shall select one of the other bits.

**Comment by goutham23** [comment]
Thanks for the clarification.

Its not clear to me about DMTFSpecMeasurementValueType value needs to be set.

For the below scenario... 
<FW_MEASUREMENT> - I will be storing SHA2_384 of a firmware image as the measurement
As a responder, I'm setting bit2 which is TPM_ALG_SHA_384- and I'm sending <FW_MEASUREMENT> 

Measurement field format when MeasurementSpecification field is bit 0 = DMTF
For, DMTFSpecMeasurementValueType - Should I set this to Digest or raw stream?
 [Bit7]=0b . Digest.
[Bit7]=1b . Raw bit stream.

**Comment by steven-bellock** [comment]
If it's a hash of the firmware it should be `Digest`. If it's the firmware itself it should be `Raw bit stream`.

**Comment by goutham23** [comment]
Thanks
