### ISSUE TITLE
DIGESTS and CERTIFICATE should return ERROR message when GET_DIGESTS and GET_CERTIFICATE not applicable

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1707]
1. Refer to paragraph 282 10.5 Responder identity authentication in
https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf

The GET_DIGESTS and GET_CERTIFICATE messages are **not applicable** if the public key of the Responder was
provisioned to the Requester in a trusted environment.

2. Refer to paragraph 174 Table 6 — SPDM request and response messages validity in
https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf
![image](https://user-images.githubusercontent.com/90754803/219284778-9b36cf21-2593-4635-a9f3-24f4299ef741.png)

3. I think when the public key of the Responder was provisioned to the Requester in a trusted environment, GET_DIGESTS and GET_CERTIFICATE messages are **not applicable** Request, then DIGESTS and CERTIFICATE response should return
ERROR message.

**Comment by steven-bellock** [comment]
If Responder's `PUB_KEY_ID_CAP == 1` then it's `CERT_CAP == 0` and `DIGESTS` and `CERTIFICATE` will error with `UnsupportedRequest`.

**Comment by Zhiqiang520** [comment]
> If Responder's `PUB_KEY_ID_CAP == 1` then its `CERT_CAP == 0` and `DIGESTS` and `CERTIFICATE` will error with `UnsupportedRequest`.

Yes, you are right. There is no need to do extra check for its `PUB_KEY_ID_CAP == 1`. Thanks for your clarification.
https://github.com/DMTF/libspdm/blob/261177e48ab42542d339f95e893a9ac11c88ee3c/library/spdm_responder_lib/libspdm_rsp_digests.c#L44-L50
https://github.com/DMTF/libspdm/blob/261177e48ab42542d339f95e893a9ac11c88ee3c/library/spdm_responder_lib/libspdm_rsp_certificate.c#L65-L71
