### ISSUE TITLE
Can we send any kind of data or only SPDM request/response through secure session?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1708]

**Comment by steven-bellock** [comment]
If the underlying transport knows how to distinguish between SPDM and non-SPDM messages, then yes, the secrets, and session id, derived by the SPDM secure session can also be used for non-SPDM messages. If the underlying transport doesn't know how to distinguish between SPDM and non-SPDM messages, then you're better off using the `Export Master Secret` to derive a separate set of secrets, and session id, for these non-SPDM messages.

Separate from transport concerns, there are also security concerns. Ie, a secret key should only be used for one purpose, and overloading that key to be used for both SPDM and non-SPDM messages may violate that.

**Comment by steven-bellock** [comment]
@PrakashK94 If this answers your question please close the issue.

**Comment by jyao1** [comment]
@PrakashK94 , please refer to `libspdm_send_request`

https://github.com/DMTF/libspdm/blob/main/include/library/spdm_requester_lib.h#L30-L33
