### ISSUE TITLE
Propose using AFL++ to instead AFL/AFL_TURBO for libspdm fuzzing

### ISSUE THREAD

**Issue by liuw1** [DMTF/libspdm#1709]
The fuzzer afl++ is afl with community patches, qemu 5.1 upgrade, collision-free coverage, enhanced laf-intel & redqueen, AFLfast++ power schedules, MOpt mutators, unicorn_mode, and a lot more!

AFL++ is a superior fork to Google's AFL - more speed, more and better mutations, more and better instrumentation, custom module support, etc. And it is well maintained by google.
Repository: https://github.com/AFLplusplus/AFLplusplus

**Comment by liuw1** [comment]
[afl_turbo](https://github.com/sleicasper/aflturbo) is an experimental project, few people are using this tool for fuzzing test currently.

**Comment by jyao1** [comment]
Would you please propose a patch to https://github.com/DMTF/libspdm/blob/main/doc/test.md?

Is there any data on code coverage?

**Comment by liuw1** [comment]
@Xiaohanjlll Please help to submitted the patch and collect the data. Thanks!
