### ISSUE TITLE
OpaqueData field shall conform to the selected opaque data format in OtherParamsSelection.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1712]
Currently there is **no format check** for `OpaqueData` Field in CHALLENGE_AUTH response message, MEASUREMENTS response message and GET_CSR request message.

1. Refer to paragraph 353 Table 36 — Successful CHALLENGE_AUTH response message format in
https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf
**OpaqueData** Field:
The Responder can include Responder-specific information and/or
information that its transport defines. If present, this field **shall
conform** to the selected opaque data format in
`OtherParamsSelection` .

2. Refer to paragraph 806 in
https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf
If the `OpaqueDataFmt1` bit is selected in `OtherParamsSelection` of `ALGORITHMS` , then all opaque data fields in SPDM messages shall use the format that Table 92 — General opaque data format defines.

**Comment by steven-bellock** [comment]
What can be checked?

**Comment by Zhiqiang520** [comment]
> What can be checked?

For example,
Refer to paragraph 808 Table 93 — Opaque element defines the format for each element in OpaqueList.
1. `ID` Field: **Shall be one of the values** in the ID column of Table 50 — Registry or standards body ID. 

Need add check if `ID` Field is one of the values  in the ID column of Table 50 — Registry or standards body ID.

2. `AlignPadding` Field: If 4 + VendorIDLen + OpaqueElementDataLen **does not fall on a 4-byte boundary**, this field shall be present and of the correct length to ensure 4 + VendorIDLen +OpaqueElementDataLen + AlignPaddingSize is a multiple
of 4. The value of this field shall be all zeros and the size of this field shall be 0, 1, 2 or 3.

Need add check if 4 + VendorIDLen + OpaqueElementDataLen fall on a 4-byte boundary.
