### ISSUE TITLE
compile failed under MSYS2 with DS2022

### ISSUE THREAD

**Issue by rayling** [DMTF/libspdm#1716]
Hi there,

I am evaluating the libspdm, I followed through the build procedure from the link below
https://github.com/DMTF/libspdm/blob/main/doc/build.md
I used ARM Developerment Studio 2022 under MSYS2, please note that I am using DS2022 evaluation license.

Please check below build MARCO
export PATH=$PATH:/c/ArmStudio/sw/ARMCompiler6.19/bin
export CC=/c/ArmStudio/sw/ARMCompiler6.19/bin/armclang.exe
export ARM_PRODUCT_DEF=/c/ArmStudio/sw/mappings/eval.elmap
export ARMLMD_LICENSE_FILE=/c/Users/RAYMOND.LING/AppData/Roaming/arm/ds/licenses/DS000-EV-31030.lic

I run the cmake command and found. see below
RAYMOND.LING@HKG-2SZG0Z2 MINGW64 ~/gitrepo/libspdm-ARM/build
$ cmake -G"MSYS Makefiles" -DARCH=ARM -DTOOLCHAIN=ARM_DS2022 -DTARGET=Release -DCRYPTO=mbedtls ..
-- The C compiler identification is ARMClang 6.19.4
CMake Warning (dev) at C:/msys64/mingw64/share/cmake/Modules/Compiler/ARMClang.cmake:92 (message):
Policy CMP0123 is not set: ARMClang cpu/arch compile and link flags must be
set explicitly. Run "cmake --help-policy CMP0123" for policy details. Use
the cmake_policy command to set the policy and suppress this warning.

For compatibility, CMake will automatically add cpu/arch flags based on the
CMAKE_SYSTEM_PROCESSOR and/or CMAKE_SYSTEM_ARCH variables.
Call Stack (most recent call first):
C:/msys64/mingw64/share/cmake/Modules/Compiler/ARMClang-C.cmake:3 (__compiler_armclang)
C:/msys64/mingw64/share/cmake/Modules/CMakeCInformation.cmake:25 (include)
CMakeLists.txt:3 (project)
This warning is for project developers. Use -Wno-dev to suppress it.

-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/ArmStudio/sw/ARMCompiler6.19/bin/armclang.exe
-- Check for working C compiler: C:/ArmStudio/sw/ARMCompiler6.19/bin/armclang.exe - broken
CMake Error at C:/msys64/mingw64/share/cmake/Modules/CMakeTestCCompiler.cmake:70 (message):
The C compiler

"C:/ArmStudio/sw/ARMCompiler6.19/bin/armclang.exe"
is not able to compile a simple test program.

It fails with the following output:

Change Dir: C:/Users/RAYMOND.LING/gitrepo/libspdm-ARM/build/CMakeFiles/CMakeScratch/TryCompile-hd5o2a

Run Build Command(s):C:/msys64/usr/bin/make.exe -f Makefile cmTC_8f51d/fast && /usr/bin/make  -f CMakeFiles/cmTC_8f51d.dir/b
uild.make CMakeFiles/cmTC_8f51d.dir/build
make[1]: Entering directory '/c/Users/RAYMOND.LING/gitrepo/libspdm-ARM/build/CMakeFiles/CMakeScratch/TryCompile-hd5o2a'
Building C object CMakeFiles/cmTC_8f51d.dir/testCCompiler.o
/C/ArmStudio/sw/ARMCompiler6.19/bin/armclang.exe --target=arm-arm-none-eabi -MD -MT CMakeFiles/cmTC_8f51d.dir/testCCompil
er.o -MF CMakeFiles/cmTC_8f51d.dir/testCCompiler.o.d -o CMakeFiles/cmTC_8f51d.dir/testCCompiler.o -c /C/Users/RAYMOND.LING/gitre
po/libspdm-ARM/build/CMakeFiles/CMakeScratch/TryCompile-hd5o2a/testCCompiler.c
armclang: warning: Your license for feature ds_suite_eval will expire in 20 days [-Wlicense-management]
armclang: warning: Your license for feature ds_compiler_eval20222 will expire in 20 days [-Wlicense-management]
warning: 'armv4t' is unsupported in this version of the product
warning: 'arm7tdmi' is unsupported in this version of the product
Linking C executable cmTC_8f51d.exe
/C/msys64/mingw64/bin/ld.exe "CMakeFiles/cmTC_8f51d.dir/testCCompiler.o" -o cmTC_8f51d.exe -Xlinker --list=cmTC_8f51d.map
C:\msys64\mingw64\bin\ld.exe: Error: unable to disambiguate: -Xlinker (did you mean --Xlinker ?)
make[1]: *** [CMakeFiles/cmTC_8f51d.dir/build.make:99: cmTC_8f51d.exe] Error 1
make[1]: Leaving directory '/c/Users/RAYMOND.LING/gitrepo/libspdm-ARM/build/CMakeFiles/CMakeScratch/TryCompile-hd5o2a'
make: *** [Makefile:127: cmTC_8f51d/fast] Error 2

CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/RAYMOND.LING/gitrepo/libspdm-ARM/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/RAYMOND.LING/gitrepo/libspdm-ARM/build/CMakeFiles/CMakeError.log".

Please help

**Comment by jyao1** [comment]
I am not sure. MSYS2 with DS2022 is not well supported per our experience.

Could you try the Linux version directly?

**Comment by rayling** [comment]
Thanks for reply, I tried, work fine on Linux, I wonder would this issue will be fixed soon since our working environment is on MS Window?

**Comment by Wenxing-hou** [comment]
Yes. I also met the compile error before. Have you  tried to use the Readme work around to fix the error?
https://github.com/DMTF/libspdm/blob/main/doc/build.md#:~:text=Apply%20below%20work,a%20real%20system.

If you haven't tried, maybe you can try. If you have tested or the error still exits, please let me know. I will debug it agian.

**Comment by rayling** [comment]
Thanks for the reply @Wenxing-hou.
I have already tried the rework around below that you are referring to
  - Apply below work around for Windows ARM DS2022 build
    - Add set(CMAKE_SYSTEM_ARCH "armv8-a") on the top of `C:\msys64\mingw64\share\cmake\Modules\Compiler\ARMClang.cmake`. The CMAKE_SYSTEM_ARCH is the target arch.
    - Change `set(libs ${libs} ws2_32)` to `#set(libs ${libs} ws2_32)` in `libspdm\os_stub\mbedtlslib\mbedtls\library\CMakeLists.txt`. ws2_32 is the socket lib, and the armclang does not support it.

However, I still experience the issue.
I believe the issue is below (capture from the compile log)
Linking C executable cmTC_8f51d.exe
**/C/msys64/mingw64/bin/ld.exe** "CMakeFiles/cmTC_8f51d.dir/testCCompiler.o" -o cmTC_8f51d.exe -Xlinker --list=cmTC_8f51d.map
C:\msys64\mingw64\bin\ld.exe: Error: unable to disambiguate: -Xlinker (did you mean --Xlinker ?)

I am not sure why it is using ld.exe?

**Comment by Wenxing-hou** [comment]
Hi, @rayling .  I build the libspdm under MSYS2 with DS2022 on my own environment again. I don't meet the issue. Have you changed some thing? 
But I think the final reason may be the use of ld.exe.  I am investigating it. Thanks.

**Comment by rayling** [comment]
Hi @Wenxing-hou, I did not change anything.. just wonder are all packages which you are using is the latest one? Please advise.

**Comment by rayling** [comment]
Hi @Wenxing-hou, thanks for your help, the one MSYS2 that I am using for while ago, MSYS2 has been updated to the latest revision, and experiencing this error. From your comment above, I just reinstalled the latest MSYS2, CMAKE configure passed. see below log.

However, I am experiencing another issue on make. please check below log.

- **CMAKE PASSED**

```
RAYMOND.LING@HKG-2SZG0Z2 MINGW64 ~/gitrepo/libspdm-ARM/build
$ cmake -G"MSYS Makefiles" -DARCH=arm -DTOOLCHAIN=ARM_DS2022 -DTARGET=Debug -DCRYPTO=mbedtls ..
-- The C compiler identification is ARMClang 6.19.4
CMake Warning (dev) at C:/msys64-2/mingw64/share/cmake/Modules/Compiler/ARMClang.cmake:92 (message):
  Policy CMP0123 is not set: ARMClang cpu/arch compile and link flags must be
  set explicitly.  Run "cmake --help-policy CMP0123" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility, CMake will automatically add cpu/arch flags based on the
  CMAKE_SYSTEM_PROCESSOR and/or CMAKE_SYSTEM_ARCH variables.
Call Stack (most recent call first):
  C:/msys64-2/mingw64/share/cmake/Modules/Compiler/ARMClang-C.cmake:3 (__compiler_armclang)
  C:/msys64-2/mingw64/share/cmake/Modules/CMakeCInformation.cmake:25 (include)
  CMakeLists.txt:3 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/ArmStudio/sw/ARMCompiler6.19/bin/armclang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
#########################
Build Configuration 
#########################
CMAKE_GENERATOR = MSYS Makefiles
ARCH = arm
TOOLCHAIN = ARM_DS2022
TARGET = Debug
CRYPTO = mbedtls
ENABLE_BINARY_BUILD=0; Building mbedtls library from source.
CMake Deprecation Warning at os_stub/platform_lib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at os_stub/platform_lib_null/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at os_stub/armbuild_lib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/RAYMOND.LING/gitrepo/libspdm-ARM/build
```



- **MAKE failed**. (checkout libspdm 2.3.1 release)

```
[ 62%] Linking C static library ../../lib/malloclib.lib
[ 62%] Built target malloclib
[ 62%] Building C object os_stub/spdm_device_secret_lib_sample/CMakeFiles/spdm_device_secret_lib_sampl
e.dir/lib.o
C:/Users/RAYMOND.LING/gitrepo/libspdm-DS2022/os_stub/spdm_device_secret_lib_sample/lib.c:15:14: fatal
error:
      'fcntl.h' file not found
    #include <fcntl.h>
             ^~~~~~~~~
1 error generated.
make[2]: *** [os_stub/spdm_device_secret_lib_sample/CMakeFiles/spdm_device_secret_lib_sample.dir/build.make:76: os_stub/spdm_device_secret_lib_sample/CMakeFiles/spdm_device_secret_lib_sample.dir/lib.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1271: os_stub/spdm_device_secret_lib_sample/CMakeFiles/spdm_device_secret_lib_sample.dir/all] Error 2
make: *** [Makefile:124: all] Error 2
```

**Comment by Wenxing-hou** [comment]
Yes. I found the error before. And I has submitted a issue:  https://github.com/DMTF/libspdm/issues/1721. Then I have submitted a PR to fix it.
You can update your local branch. The error has be fixed.

**Comment by rayling** [comment]
@Wenxing-hou 
Thanks for the help! It works and passed 62%  on make
However, I saw another build error
```
[ 63%] Built target malloclib
[ 63%] Built target spdm_device_secret_lib_sample
[ 64%] Built target spdm_device_secret_lib_null
[ 65%] Built target spdm_transport_test_lib
[ 65%] Building C object unit_test/cmockalib/CMakeFiles/cmockalib.dir/cmocka/src/cmocka.o
C:/Users/RAYMOND.LING/gitrepo/libspdm-DS2022/unit_test/cmockalib/cmocka/src/cmocka.c:2660:19: error:
      call to undeclared library function 'strdup' with type 'char *(const char *)'; ISO C99 and later
      do not support implicit function declarations [-Wimplicit-function-declaration]
            msg = strdup(error_message);
                  ^
C:/Users/RAYMOND.LING/gitrepo/libspdm-DS2022/unit_test/cmockalib/cmocka/src/cmocka.c:2660:19: note:
      include the header <string.h> or explicitly provide a declaration for 'strdup'
1 error generated.
make[2]: *** [unit_test/cmockalib/CMakeFiles/cmockalib.dir/build.make:76: unit_test/cmockalib/CMakeFiles/cmockalib.dir/cmocka/src/cmocka.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1367: unit_test/cmockalib/CMakeFiles/cmockalib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
any idea? Please note that I am using main branch to build.

**Comment by jyao1** [comment]
@rayling, can you try to disable the cmocka related unit test in your build?

**Comment by rayling** [comment]
@jyao1 @Wenxing-hou 
thanks for the feedback. I removed all cmocka related unit tests from the makefile. those are 
- cmockalib
- test_spdm_common
- test_spdm_crypt
- test_spdm_fips
- test_spdm_requester
- test_spdm_responder

and finally it is completed. 
```
$ make
[  6%] Built target cryptlib_mbedtls
[ 27%] Built target mbedcrypto
[ 29%] Built target mbedx509
[ 32%] Built target mbedtls
[ 34%] Built target spdm_common_lib
[ 41%] Built target spdm_requester_lib
[ 49%] Built target spdm_responder_lib
[ 54%] Built target spdm_crypt_lib
[ 55%] Built target spdm_crypt_ext_lib
[ 56%] Built target spdm_secured_message_lib
[ 57%] Built target spdm_transport_mctp_lib
[ 58%] Built target spdm_transport_pcidoe_lib
[ 60%] Built target memlib
[ 60%] Built target debuglib
[ 61%] Built target debuglib_null
[ 62%] Built target rnglib
[ 62%] Built target platform_lib
[ 63%] Built target platform_lib_null
[ 63%] Built target malloclib
[ 64%] Built target spdm_device_secret_lib_sample
[ 64%] Built target spdm_device_secret_lib_null
[ 65%] Built target spdm_transport_test_lib
[ 65%] Built target armbuild_lib
[ 70%] Built target test_crypt
[ 76%] Built target cryptlib_null
[ 77%] Built target cryptstublib_dummy
[ 78%] Built target intrinsiclib
[ 79%] Built target malloclib_null
[ 79%] Built target malloclib_simple
[ 79%] Built target rnglib_null
```

**Comment by steven-bellock** [comment]
@rayling Please close the issue if it has been resolved.
