### ISSUE TITLE
incorrect error data

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#1720]
Hi
There is incorrect assert in digests unittest case7.
Error data of error code 'unspecified' should be 0x00.
plz check it.

https://github.com/DMTF/libspdm/blob/db735a85ded19f6500133d4504351444bf87b3a3/unit_test/test_spdm_responder/digests.c#L377

**Comment by Zhiqiang520** [comment]
There are similar issues in other codes, for example :
https://github.com/DMTF/libspdm/blob/444c268fe36583927386baf9bf3f1d2cf11d6910/library/spdm_responder_lib/libspdm_rsp_challenge_auth.c#L74-L75
https://github.com/DMTF/libspdm/blob/444c268fe36583927386baf9bf3f1d2cf11d6910/library/spdm_responder_lib/libspdm_rsp_key_exchange.c#L232-L234
