### ISSUE TITLE
arm_clang build failed because processor_bind remove

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1721]
When [remove processor_bind,](https://github.com/DMTF/libspdm/commit/63bb0429c6e418320cd29f696f9461bb4b948233#diff-4f366055d9cb74476858613f79c68c9a332c46ce60e416ba971dd6e4c9ebf69b) the `LIBSPDM_CPU_ARM` MACRO is deleted.

The missing `LIBSPDM_CPU_ARM` MACRO will make the armclang build error:
![image](https://user-images.githubusercontent.com/87060980/220860245-e6d25f6a-3ca1-4ce3-9c07-9b1b69b532ef.png)

**Comment by steven-bellock** [comment]
Can we add armclang build to CI/CD?
