### ISSUE TITLE
Integrator-visible functions for the encapsulated flow

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1724]
@jyao1 Out of the following functions, which need to be Integrator-visible and which can we make internal, or get rid of? 

https://github.com/DMTF/libspdm/blob/2c5571377ae330263435ec925b5f18868c4170a3/include/library/spdm_requester_lib.h#L469-L563

**Comment by steven-bellock** [comment]
@jyao1 thinks most of these can be moved to internal header.

**Comment by jyao1** [comment]
It is already done.
