### ISSUE TITLE
Responder-size memory requirements

### ISSUE THREAD

**Issue by leonardosala** [DMTF/libspdm#1729]
Hello,
can anybody comment on the code/data memory requirements for the Responder part of the library in the following cases:
- ARM0 without crypto acceleration IP
- ARM0 with      crypto acceleration IP

Thanks,

Leonardo

**Comment by jyao1** [comment]
Per my experience, the size heavily depends on
* which feature you choose in https://github.com/DMTF/libspdm/blob/main/include/library/spdm_lib_config.h
* which compiler you choose

Also, you can build libspdm and use https://github.com/DMTF/libspdm/tree/main/unit_test/test_size/test_size_of_spdm_responder to evaluate.

Here is some basic info:
1) https://github.com/DMTF/libspdm/discussions/603

2) https://github.com/DMTF/libspdm/pull/1339

**Comment by leonardosala** [comment]
Hello @jyao1 , thanks a lot. I'll start from here.
