### ISSUE TITLE
Questions regarding to `content_changed` in `MEASUREMENTS` response

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#1735]
Hello,
I got 3 questions about the `content_changed` in `MEASUREMENTS` response, 

> Bit [5:4]. content changed. If this message contains a
signature, this field indicates if one or more entries in the
measurement log being signed have changed.

1. Why does `content_changed` only work for signature required case? Could you elaborate why it is not needed when the measurements signature is not required? 

> 01b : the Responder detected that one or more entries
in the measurement log being signed have changed. The
Requester might consider issuing GET_MEASUREMENTS
again to acquire current measurements.

2. Even with a `content _changed` flag, the new measurement seems will be returned along with the `MEASUREMENT` response, why a re-gain of measurements is needed?

3. Basically, why  `Responder detected that one or more entries
in the measurement log being signed have changed` is needed?
I think the integrator can check if the measurements is changed by himself from response anyway.

Thanks.

**Comment by steven-bellock** [comment]
For Q1 I think @xiaoyuruan introduced this field so I'll let him answer that.

For Q2 and Q3, consider the sequence
1. `GET_MEASUREMENTS` - measurement block 1 - without signature.
2. Value of measurement block 1 changes.
3. `GET_MEASUREMENTS` - measurement block 2 - with signature.

The measurement log signed by step 2 includes measurement block 1 whose value, by step 3, has changed. Note that the Requester doesn't know which measurement blocks changed values. An enhancement may be that the Responder reports which measurements blocks have changed in the signed `MEASUREMENTS` response.

**Comment by xiaoyuruan** [comment]
Regarding Q1, the thinking is that: when a signature is generated, the Responder is endorsing the measurement log that is being signed.  If something in the log is expired / no longer current, it's the Responder's responsibility to notify the Requester.  

Without generating a signature, the Responder is not endorsing any expired content in the log, hence no need to notify the Requester.

**Comment by xiangfeima** [comment]
@steven-bellock @xiaoyuruan much appreciated to your elaboration.
