### ISSUE TITLE
Question regarding to dmtf_spec_measurement_value_type

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#1736]
According to SPDM specification 1.2.1, Table 45 — DMTF measurement specification format,
the 7th bit of the 1st byte (**DMTFSpecMeasurementValueType**) would be:

> Composed of:
> • Bit [7]. Indicates the representation in DMTFSpecMeasurementValue .
> • Bit [6:0]. Indicates what is being measured by DMTFSpecMeasurementValue .

and

> These values are set independently and are interpreted as follows:
> • [7]=0b . Digest.
> • [7]=1b . Raw bit stream. The Responder should ensure the raw bit stream does not contain secrets.

Would you explain why in the device secret example the value is filled with the value `measurements_index - 1` ?

https://github.com/DMTF/libspdm/blob/03c9cb91495fc05d8353ee9413cdee775372f832/os_stub/spdm_device_secret_lib_sample/lib.c#L1260-L1263

Thanks.

**Comment by jyao1** [comment]
No special reason, just make coding simpler. 
Index 1 -> type 0
Index 2 -> type 1
Index 3 -> type 2
Index 4 -> type 3

**Comment by xiangfeima** [comment]
Hi @jyao1 , thank you very much. Let's close the question.
