### ISSUE TITLE
Extra sleep for busy retry?

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#1746]
#1714 seemed to insert the sleep where retry could be zero (i.e. no more retry) and hence caused one extra sleep.

    retry_delay_time = context->retry_delay_time;
    do {
        status = libspdm_try_challenge(context, slot_id,
                                       measurement_hash_type,
                                       measurement_hash, slot_mask, NULL, NULL, NULL);
        if (LIBSPDM_STATUS_BUSY_PEER != status) {
            return status;
        }

        libspdm_sleep_in_us(retry_delay_time);
    } while (retry-- != 0);

**Comment by steven-bellock** [comment]
Yeah needs
```
if (retry != 0) {
    libspdm_sleep_in_us(retry_delay_time);
}
```
@xiangfeima

**Comment by xiangfeima** [comment]
Thank you very much @rw8896 @steven-bellock , I'll get this fixed asap.
