### ISSUE TITLE
cmake-run-error

### ISSUE THREAD

**Issue by tujc** [DMTF/libspdm#1750]
Must use cmake3 to run CMakeLists.txt.
When I use cmake-2.8.12.2, there is a error in line 205 of CMakeLists.txt
'if(NOT CMAKE_C_COMPILER_VERSION VERSION_GREATER_EQUAL 9.3)', because 'VERSION_GREATER_EQUAL' is not available in cmake < v3.7.

**Comment by steven-bellock** [comment]
If you change it to `VERSION_GREATER` does it resolve your issue?

**Comment by steven-bellock** [comment]
As an aside, it looks like we need to add an older version of CMake to CI/CD. I'll file a separate issue.

**Comment by tujc** [comment]
Thanks your reply, when I change it to `VERSION_GREATER`, cmake2 can build successfully.
