### ISSUE TITLE
ec_get_public_key_from_der should be in the same macro config

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1758]
`libspdm_ec_get_public_key_from_der` declaration and definition should be in the same macro config. 

https://github.com/DMTF/libspdm/blob/82fce0f4fba769a605429eb284ec3c471e9e21ff/include/hal/library/cryptlib/cryptlib_ec.h#L14-L44

https://github.com/DMTF/libspdm/blob/82fce0f4fba769a605429eb284ec3c471e9e21ff/os_stub/cryptlib_mbedtls/der/der.c#L80-L100

**Comment by xiangfeima** [comment]
Thanks @Wenxing-hou for reporting. I think I can fix it if you don't mind (since I remember I wrote this code at the very beginning).
