### ISSUE TITLE
key_update test fail after integrate #166

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#176]
@vinmaciel, would you please take a look and let us know if it is expected or not?

REF: https://github.com/DMTF/libspdm/pull/166

[  ERROR   ] --- 0x8000000000000007 != 0x8000000000000010
[   LINE   ] --- C:\home\DMTF\libspdm\unit_test\test_spdm_requester\key_update.c:4143: error: Failure!
[  ERROR   ] --- 0x8000000000000007 != 0x0
[   LINE   ] --- C:\home\DMTF\libspdm\unit_test\test_spdm_requester\key_update.c:4216: error: Failure!
[  ERROR   ] --- 0x3 != 0x0
[   LINE   ] --- C:\home\DMTF\libspdm\unit_test\test_spdm_requester\key_update.c:4279: error: Failure!
[  ERROR   ] --- 0x8000000000000007 != 0x0
[   LINE   ] --- C:\home\DMTF\libspdm\unit_test\test_spdm_requester\key_update.c:4405: error: Failure!
[  PASSED  ] 30 test(s).
[  FAILED  ] spdm_requester_key_update_tests: 4 test(s), listed below:
[  FAILED  ] test_spdm_requester_key_update_case29
[  FAILED  ] test_spdm_requester_key_update_case30
[  FAILED  ] test_spdm_requester_key_update_case31
[  FAILED  ] test_spdm_requester_key_update_case33

**Comment by vinmaciel** [comment]
Yes, these errors were expected (please, see comment in #166), and should be successful after fixing issue #165.

**Comment by jyao1** [comment]
Got it. Thanks for confirm.
Next time, I recommend we comment those cases at submission, and uncomment them after fix.

Having failure makes people confused.
