### ISSUE TITLE
Does LIBSPDM verifies all the certificates in the certificate chain?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1760]
For example, A certificate chain has three certificates, one is root, next is intermediate and last one is leaf certificate.
I see for root certificate, LIBSPDM just makes sure the subject name and issuer name should match. Is this enough to check for the root certificate? Will it be not compared against CA or some known good public key or public key hash?

I see for intermediate certificate, LIBSPDM verifies the intermediate certificate signature against the root public key which I see establish the trust between them. This is ok.

For the last certificate, which is leaf, it just makes sure all the x509 certificate attributes are present and all has valid values. It doesn't verifies the leaf certificate signature against the intermediate certificate. How the chain of trust is established between intermediate certificate and leaf certificate then?

**Comment by jyao1** [comment]
we can document that in https://github.com/DMTF/libspdm/blob/main/doc/api/requester_api.md.

**Comment by PrakashK94** [comment]
Just for clarification, can you confirm that LIBSPDM doesn't validate the signature of the leaf certificate in the case mentioned?

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/451002061874c3b606237b3ce3dc94066682ad6e/include/hal/library/cryptlib/cryptlib_cert.h#L248-L269 validates the integrity of signatures of the chain, including the leaf certificate.

**Comment by PrakashK94** [comment]
I saw the LIBSPDM code, it does verify all the certificates present in the certificate chain. For, root certificate, it makes sure the subject name and issuer name should match and for the certificate that is just after the root certificate, it makes sure it is trusted against root certificate. For the last certificate, which is leaf, it just makes sure all the x509 certificate attributes are present and all has valid values.
The above things are mandatory to verify the certificate chain other then verifying the signature?

**Comment by steven-bellock** [comment]
There's nothing in the specification that mandates what a Requester should do when validating the Responder's certificate chain, only recommendations. The specification mandates that the Responder needs to have certain fields present in the x.509 leaf certificate, so libspdm checks that they exist, even if doesn't do anything with a specific field.

<html>
<body>


Field | Description
-- | --
Version | Version of the encoded certificate shall be present and shall be 3 (encoded as value 2).
Serial Number | CA-assigned serial number shall be present with a positive integer value.
Signature Algorithm | Signature algorithm that CA uses shall be present.
Issuer | CA distinguished name shall be specified.
Subject Name | Subject name shall be present and shall represent the distinguished name associated with the leaf certificate.
Validity | See Certificate validity details, and RFC5280.
Subject Public Key Info | Device public key and the algorithm shall be present.
Key Usage | Shall be present and key usage bit for digital signature shall be set.

**Comment by PrakashK94** [comment]
The above table you took it from which spec? Is it SPDM spec or x509 spec?
