### ISSUE TITLE
SPDM 1.3.0 support development status

### ISSUE THREAD

**Issue by oferhz** [DMTF/libspdm#1769]
Hi,

I would like to know if there is a schedule for a libsdpm which will support SPDM v1.3.0 ?
Also, is there a way to get access prior to release to start testing it, like beta testers?

Thanks,

/Ofer

**Comment by steven-bellock** [comment]
We need to wait for 1.3 to be released, so we'll probably start on it in April / May. We do our development on the `main` branch, so you'll always have access to the latest code.

**Comment by oferhz** [comment]
Ok, so the coding will start right after the spec of 1.3 is released, are there any milestones expected for this ? (like initial support, libspdm-emu support and final release)

**Comment by steven-bellock** [comment]
We'll start a [discussion](https://github.com/DMTF/libspdm/discussions) on 1.3 after libspdm 3.0 is released in April, where we can plan those out.

**Comment by oferhz** [comment]
great, thanks for sharing

**Comment by jyao1** [comment]
From high level, it would be similar to the SPDM 1.2 dev process before.
1) Support the SPDM 1.3 parameter for the existing command.
2) Support the SPDM 1.3 new command.

You are welcome to contribute patch if you want to see some feature with priority.
