### ISSUE TITLE
Cert check should continue after libspdm_verify_peer_cert_chain_buffer_authority failed

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#1773]
The cert total check and handle should continue even the `libspdm_verify_peer_cert_chain_buffer_authority`  check failed.
Because `LIBSPDM_STATUS_VERIF_NO_AUTHORITY` should ensure the other cert format check is passed. 
And some device may treat the `LIBSPDM_STATUS_VERIF_NO_AUTHORITY` is feasible.

https://github.com/DMTF/libspdm/blob/fc18d62b5c9e627ea2f93b3fb26528cb79b2afae/library/spdm_requester_lib/libspdm_req_get_certificate.c#L322-L332

**Comment by steven-bellock** [comment]
If this isn't an error then there needs to be some other way to convey this information, either through another function parameter or through querying the `spdm_context`.

**Comment by Wenxing-hou** [comment]
I think some devices will treat the `LIBSPDM_STATUS_VERIF_NO_AUTHORITY` is wrong and some devices will treat the `LIBSPDM_STATUS_VERIF_NO_AUTHORITY` is acceptable. So it may be feasible to add a new return status.
