### ISSUE TITLE
Document libspdm's assertion vs run-time checking policy

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1775]
It can be added to https://github.com/DMTF/libspdm/blob/main/doc/programming_environment.md

**Comment by jyao1** [comment]
In general:
* assert == something should never happen. If it happens, then it means something is wrong in the development.
  * build time assert == It can be detected at build time, e.g. mis-configuration.
  * runtime assert == It can only be detected at runtime, e.g. complicated logic, state machine.
* runtime check == something might happen, e.g. adversary input via attack surface.
