### ISSUE TITLE
Is this logic correct?

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1776]
@jyao1 @Wenxing-hou 

In https://github.com/DMTF/libspdm/blob/fc18d62b5c9e627ea2f93b3fb26528cb79b2afae/os_stub/spdm_device_secret_lib_sample/lib.c#L1135-L1143

Is the use of `libspdm_const_compare_mem` correct? Note that if the buffers are the same then currently `libspdm_const_compare_mem` returns `0`, so according to the code the expectation is that the buffers are not the same.

If the use is not correct then I'll have a fix for it when I merge https://github.com/DMTF/libspdm/issues/1585#issuecomment-1460462778.

**Comment by Wenxing-hou** [comment]
Thanks. 
I have checked the code. This code need compare the `cached_req_info` and `requester_info` to ensure the `cached_req_info` is same as `requester_info`. 
I think the use of libspdm_const_compare_mem is not correct.

**Comment by jyao1** [comment]
We should also need add unit test to cover this code.

**Comment by steven-bellock** [comment]
Thanks for confirmation. This will be fixed by https://github.com/DMTF/libspdm/pull/1777.

**Comment by Wenxing-hou** [comment]
Thanks. I have submitted PR https://github.com/DMTF/libspdm/pull/1781 to add unit_test to cover this case.
