### ISSUE TITLE
Why there is no capability flag for `content_changed` in `MEASUREMENTS` response

### ISSUE THREAD

**Issue by mcsmonk** [DMTF/libspdm#1786]
I read https://github.com/DMTF/libspdm/issues/1735 and understood why the field is needed.

I just wondering why there is no capability flag for that.

Is it more valid that there is a capability flag representing support of `content_changed` function in responder?

**Comment by jyao1** [comment]
The MEASUREMENTS response message includes such capability report, see below:
```
00b : the Responder does not support detection of runtime measurement changes, or this message does not contain a signature
```

It is just not reported in CAPABILITY response.
