### ISSUE TITLE
Get measurements efficiency

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#179]
The Get Measurements code path seems inefficient. It looks like it the code path ends up in the spdm_measurement_collection routine. This routine collects all measurements on every single call, even though only single measurement may be requested at a higher level.  Some of the measurements, depending on their implementation, may involve some long/complex calculations, and may not be wise to repeat, or the responder may not want to cache the results. 

If my interpretation of the code path is correct, can we optimize this to only collect the measurements that were requested at a higher level? Perhaps by passing the "index" requested into the spdm_measurement_collection routine?

**Comment by steven-bellock** [comment]
Approved.
