### ISSUE TITLE
the Responder shall terminate the encapsulated request flow when the Requester delivers `ResponseNotReady` ERROR message

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1791]
the Responder shall **terminate** the encapsulated request flow when the Requester delivers `ResponseNotReady` ERROR message.
1. Refer to paragraph 645 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).

> In an encapsulated request flow, a Responder can issue an encapsulated request that can take up to CT time to
fulfill. When the Requester delivers an `ERROR` message with a `ResponseNotReady` error code, the Responder **shall
not encapsulate another request** by setting `Param2` in `ENCAPSULATED_RESPONSE_ACK` to a value of zero. This
**effectively and naturally terminates** the encapsulated request flow.
2. I think:
before running `libspdm_process_encapsulated_response` function at line 470~472,
first to check if `((spdm_message_header_t *)encap_response->header.request_response_code == SPDM_ERROR)`, then the Responder shall terminate the encapsulated request flow by setting Param2 in ENCAPSULATED_RESPONSE_ACK to a value of zero.
https://github.com/DMTF/libspdm/blob/2b4890b796a758e159f3b58860c99554724507e3/library/spdm_responder_lib/libspdm_rsp_encap_response.c#L470-L478

**Comment by steven-bellock** [comment]
It also says
>When the timeout is near expiration, the Responder should perform the following:
Trigger its transport-defined alert mechanism to initiate the Encapsulated request flow.

Do we have a way to trigger a transport-defined alert mechanism?

**Comment by steven-bellock** [comment]
I filed an issue against the specification, since it assumes there is a "transport-defined alert mechanism."

**Comment by Zhiqiang520** [comment]
> It also says
> 
> > When the timeout is near expiration, the Responder **should** perform the following:
> > Trigger its transport-defined alert mechanism to initiate the Encapsulated request flow.
> 
> Do we have a way to trigger a transport-defined alert mechanism?

I don't know how to trigger a transport-defined alert mechanism. 
By the way, you above mentioned part is **should**, recommended, not mandatory.
