### ISSUE TITLE
question related to test_spdm_requester_encap_request 

### ISSUE THREAD

**Issue by lironhimi** [DMTF/libspdm#1793]
the below is what is running when launching 'run_initial_seed.sh'
./test_spdm_requester_encap_request ./seeds/test_spdm_requester_encap_request/encap_request.raw ./seeds/test_spdm_requester_encap_request/encap_request12.raw 
and the output is as below:
libspdm_send_spdm_request[ffffffff] (0x4):
0000: 11 ea 00 00
libspdm_receive_spdm_response[ffffffff] (0x8):
0000: 11 6a 01 00 11 81 00 00
libspdm_send_spdm_request[ffffffff] (0x8):
0000: 11 eb 01 00 11 7f 07 81
libspdm_receive_spdm_response[ffffffff] (0x4):
0000: 11 6b 02 01
libspdm_send_spdm_request[ffffffff] (0x8):
0000: 11 eb 02 00 11 7f 07 eb
**libspdm_receive_spdm_response[ffffffff] (0x4):
0000: 01 00 00 00**
libspdm_send_spdm_request[ffffffff] (0x4):
0000: 12 ea 00 00
libspdm_receive_spdm_response[ffffffff] (0x8):
0000: 11 6a 01 00 11 81 00 00

is the above **bold** response is a valid response? if not and it is an error (as i think it should be) it should also be mark as error in 'libspdm_receive_response' flow, right?

BTW, if the command is ran with swapped files, there is no issue and the output is:
./test_spdm_requester_encap_request ./seeds/test_spdm_requester_encap_request/encap_request12.raw ./seeds/test_spdm_requester_encap_request/encap_request.raw
libspdm_send_spdm_request[ffffffff] (0x4):
0000: 11 ea 00 00
libspdm_receive_spdm_response[ffffffff] (0x8):
0000: 12 6a 00 00 12 81 00 ff
libspdm_send_spdm_request[ffffffff] (0x4):
0000: 12 ea 00 00
libspdm_receive_spdm_response[ffffffff] (0x8):
0000: 12 6a 00 00 12 81 00 ff
libspdm_send_spdm_request[ffffffff] (0x8):
0000: 12 eb 00 00 12 7f 07 81
libspdm_receive_spdm_response[ffffffff] (0x8):
0000: 12 6b 00 00 00 00 39 66

**Comment by Xiaohanjlll** [comment]
Please tell me your build steps. I hope I can recurrent it

**Comment by jyao1** [comment]
The bold does not have matching version, it should be treated as invalid response.

**Comment by Xiaohanjlll** [comment]
I am checking this lissues
