### ISSUE TITLE
Requester should check the size of the returned certificate chain

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1817]
https://github.com/DMTF/libspdm/blob/1e2350efd9c08b8be9d8624fdaf592a8176243bb/library/spdm_requester_lib/libspdm_req_get_certificate.c#L243-L244

`total_responder_cert_chain_buffer_length` is the size of the certificate reported through the `CERTIFICATE` response fields. Its value should be checked against the value returned in the certificate chain's `Length` field.

**Comment by jyao1** [comment]
This has been checked in https://github.com/DMTF/libspdm/blob/main/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1134
