### ISSUE TITLE
`app_message_size` without initialization maybe referenced

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1824]
Check on version: https://github.com/DMTF/libspdm/commit/03c9cb91495fc05d8353ee9413cdee775372f832
This issue is coming from the above commit.

1.`app_message_size` is declared without initialization at the following line 86.
https://github.com/DMTF/libspdm/blob/03c9cb91495fc05d8353ee9413cdee775372f832/library/spdm_transport_mctp_lib/libspdm_mctp_common.c#L86
2.if `is_app_message` equal to `false`, then `&app_message_size` will be the 4th parameter `size_t *transport_message_size` of `libspdm_mctp_encode_message()` function at the following line 116.
https://github.com/DMTF/libspdm/blob/03c9cb91495fc05d8353ee9413cdee775372f832/library/spdm_transport_mctp_lib/libspdm_mctp_common.c#L112-L124
3. Finally `app_message_size` **without initialization** will be referenced at the following line 79 and 81.
https://github.com/DMTF/libspdm/blob/03c9cb91495fc05d8353ee9413cdee775372f832/library/spdm_transport_mctp_lib/libspdm_mctp_mctp.c#L65-L86

**Comment by Zhiqiang520** [comment]
@xiangfeima, I found this issue is coming from: https://github.com/DMTF/libspdm/pull/1715 fixed https://github.com/DMTF/libspdm/issues/796.

**Comment by xiangfeima** [comment]
@Zhiqiang520 Much appreciated. I'm now looking into this.

**Comment by xiangfeima** [comment]
You can assign this ticket to me as well.
