### ISSUE TITLE
if response message size exceeds `MaxSPDMmsgSize` of requester then responder shall respond with `ErrorCode == ResponseTooLarge` or silently discard the request.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1825]
If the size of a response message exceeds the size of the `MaxSPDMmsgSize` of the requesting SPDM endpoint, the responding
SPDM endpoint shall respond with `ErrorCode == ResponseTooLarge` or silently discard the request.
1. Refer to paragraph 239  in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).

```
If the size of a response message exceeds the size of the `MaxSPDMmsgSize` of the requesting SPDM endpoint, the responding
SPDM endpoint shall respond with `ErrorCode == ResponseTooLarge` or silently discard the request.
```

2. Refer to paragraph 450 Table 48 — Error code and error data in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).

![image](https://user-images.githubusercontent.com/90754803/226577803-6fb2bc75-04dd-4359-b246-4979737d5583.png)

3. I think:

- a. the code at following line 622 :

`if (my_response_size < large_buffer_size) {` 
 may should be like:
`if (my_response_size <= large_buffer_size) {`.

- b. the code at following line 665~666: 

`status = libspdm_generate_error_response(context, `
`                                          SPDM_ERROR_CODE_LARGE_RESPONSE, `
may should be like:
`status = libspdm_generate_extended_error_response(context, `
`                                                  SPDM_ERROR_CODE_RESPONSE_TOO_LARGE,`
https://github.com/DMTF/libspdm/blob/0af7c1197cab8e99615fd9f062653aaf32552c03/library/spdm_responder_lib/libspdm_rsp_receive_send.c#L622-L669

**Comment by steven-bellock** [comment]
`large_buffer_size` is the size of the Responder's scratch buffer, no? In that case this is an internal error to the Responder and it should be `Unspecified`. 

I think `libspdm_build_response` needs a major refactoring. It's difficult to figure out what's going on in it.

**Comment by jyao1** [comment]
According to our definition:

```
#if LIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP
...
#define LIBSPDM_SCRATCH_BUFFER_LARGE_MESSAGE_CAPACITY (LIBSPDM_MAX_SPDM_MSG_SIZE)
```

large_buffer_size is LIBSPDM_MAX_SPDM_MSG_SIZE.
As such, I think we need to return ReponseTooLarge.

**Comment by steven-bellock** [comment]
>ResponseTooLarge
The response is greater than the MaxSPDMmsgSize of the requesting SPDM endpoint.

In this case the response message is too large for Responder's internal buffer, not the Requester's. There is no error for that other than `Unspecified`.

**Comment by jyao1** [comment]
> > ResponseTooLarge
> > The response is greater than the MaxSPDMmsgSize of the requesting SPDM endpoint.
> 
> In this case the response message is too large for Responder's internal buffer, not the Requester's. There is no error for that other than `Unspecified`.

This is internal buffer for LIBSPDM_MAX_SPDM_MSG_SIZE. Why we cannot return ReponseTooLarge  ?
Or if that is the case, then when we should return ReponseTooLarge ?

**Comment by jyao1** [comment]
agree

**Comment by jyao1** [comment]
other related issue: https://github.com/DMTF/libspdm/issues/1865

**Comment by Wenxing-hou** [comment]
> > Current code does not return `ReponseTooLarge` at all.
> 
> Well that's a problem!
> 
> The checking priority should be
> 
> 1. Responder checks if the response is larger than the Requester's `MaxSPDMmsgSize`. If so then send `ReponseTooLarge`. (It looks like this check is missing.)
> 2. Responder checks if the response is larger than the Responder's internal scratch buffer. If so then send `Unspecified`.

Yes. We need add check for Requester's `MaxSPDMmsgSize`. And I have submit PR.

For  Responder's internal scratch buffer, the check may don't need, because The responder will acquire sender_buffer size before build response.
https://github.com/DMTF/libspdm/blob/d7700798944f077bbd502710f222ce7580360c15/library/spdm_responder_lib/libspdm_rsp_communication.c#L65-L79

The `libspdm_acquire_sender_buffer` will return the max response size the when chunk is enabled.
`    *max_msg_size = libspdm_get_scratch_buffer_large_sender_receiver_capacity(spdm_context);`

So, the build response size will not be larger than the Responder's internal scratch buffer.
