### ISSUE TITLE
Add 2 more APIs libspdm_send_data and libspdm_receive_data

### ISSUE THREAD

**Issue by mxu9** [DMTF/libspdm#1831]
Currently the function of libspdm_send_receive_data send and receive an SPDM or APP message in one call.
There is no functions to send and receive data separately. In some scenarios sending and receiving may be separated.
Can we add 2 more APIs (libspdm_send_data / libspdm_receive_data) to do above tasks?

**Comment by mxu9** [comment]
> Like these?
> 
> https://github.com/DMTF/libspdm/blob/cbf9e65c6dfe086acc2909e5b1ca697ea5c2c648/include/library/spdm_requester_lib.h#L12-L56

libspdm_send_request need some preparation before it is called. 
For example, transport_header_size shall be retrieved by calling context->transport_get_header_size(context). libspdm_acquire_sender_buffer shall be called to acquire the sender_buffer and update some fields in spdm_context (which type is libspdm_context_t).
The problem is that libspdm_context_t is defined internally and it is not exported.
https://github.com/DMTF/libspdm/blob/cbf9e65c6dfe086acc2909e5b1ca697ea5c2c648/include/internal/libspdm_common_lib.h#L301-L405
I am not sure if libspdm_send_request can be called to send data outside.

Did I miss something?

**Comment by steven-bellock** [comment]
I see. So have
```
    transport_header_size = context->transport_get_header_size(context);
    status = libspdm_acquire_sender_buffer (context, &message_size, (void **)&message);
    if (LIBSPDM_STATUS_IS_ERROR(status)) {
        return status;
    }
    LIBSPDM_ASSERT (message_size >= transport_header_size);
    spdm_request = (void *)(message + transport_header_size);
    spdm_request_size = message_size - transport_header_size;
    libspdm_copy_mem (spdm_request, spdm_request_size, request, request_size);
    spdm_request_size = request_size;

    status = libspdm_send_request(context, session_id, is_app_message,
                                  spdm_request_size, spdm_request);
  ```
  inside the public `libspdm_send_data` and then we can move `libspdm_send_request` to the internal header. Yes, we can do that.

**Comment by mxu9** [comment]
That will be great! Thanks much.

**Comment by jyao1** [comment]
Can `libspdm_send_receive_data` be used directly ?
