### ISSUE TITLE
If request message size exceeds `MaxSPDMmsgSize` of responder then responder shall respond with `ErrorCode=RequestTooLarge` or silently discard the request.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#1832]
If the size of a request message exceeds the size of the `MaxSPDMmsgSize` of the responding SPDM endpoint, the
responding SPDM endpoint shall respond with `ErrorCode=RequestTooLarge` or silently discard the request.

1. Refer to paragraph 239 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
```
if the size of a request message exceeds the size of the MaxSPDMmsgSize of the responding SPDM endpoint, the
responding SPDM endpoint shall respond with ErrorCode=RequestTooLarge or silently discard the request.
```
2. Refer to paragraph 450 Table 48 — Error code and error data in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://user-images.githubusercontent.com/90754803/227152730-7de0f127-31cd-4ef7-8257-bbbd19bd0d30.png)
3. I think:
Maybe we should first to check `if (request_size <= spdm_context->connection_info.capability.max_spdm_msg_size)`, then call `libspdm_handle_large_request()` function at the following line 574 to handle the large SPDM message.
https://github.com/DMTF/libspdm/blob/cbf9e65c6dfe086acc2909e5b1ca697ea5c2c648/library/spdm_requester_lib/libspdm_req_send_receive.c#L553-L579

**Comment by steven-bellock** [comment]
This one makes my head hurt, but I believe `RequestTooLarge` is used when the Requester sends `GET_ENCAPSULATED_REQUEST` and the `ENCAPSULATED_REQUEST` is larger than the Requester's `MaxSPDMmsgSize`. In such a case the Responder would reply with error `RequestTooLarge`.

But it might be good to ask the SPDM working group if this is the correct use of it.

**Comment by steven-bellock** [comment]
After discussing this with the SPDM working group there's an even simpler case. The Requester attempts to send a request message that is larger than the Responder's `MaxSPDMmsgSize`. In such a case the Responder can reply with error `RequestTooLarge`. Note that a non-malicious Requester would never send the request in the first place.

**Comment by jyao1** [comment]
Current libspdm cannot return `RequestTooLarge`, because transport layer does not tell such info.

**Comment by steven-bellock** [comment]
We also clarified that for https://github.com/DMTF/libspdm/issues/1832#issuecomment-1481953402 the Responder should send `ResponseTooLarge`.

**Comment by jyao1** [comment]
I agree that the `ResponseTooLarge` should be sent, because the Response is known by the Responder.

However, the Responder might not know the Request. This issue only discusses `RequestTooLarge`.

`ResponseTooLarge` should be discussed in #1825.

**Comment by Zhiqiang520** [comment]
I think we can add the following check just in the requester side:
1. `if (request_size <= spdm_context->connection_info.capability.max_spdm_msg_size)`, then 
the SPDM request message is a **large** message, call `libspdm_handle_large_request()` to handle.
2. `if (request_size > spdm_context->connection_info.capability.max_spdm_msg_size)`, then 
the SPDM request message is **too large** message, we can silently discard the request in the requester side.
