### ISSUE TITLE
Incorrect `param1` value of `m_libspdm_negotiate_algorithm_request13`

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#1839]
Param1 value of `m_libspdm_negotiate_algorithm_request13` is incorrect.
It should be modified from 11 to 3 according to purpose of unittest17 and length field value.

https://github.com/DMTF/libspdm/blob/798ef4739ad5c1648f6d90a62774da2e7330795c/unit_test/test_spdm_responder/algorithms.c#L2525-L2526

https://github.com/DMTF/libspdm/blob/51c1cf4ecde9a9b2c7996217c86bebc97a212917/unit_test/test_spdm_responder/algorithms.c#L449-L485

**Comment by Xiaohanjlll** [comment]
I will check this
