### ISSUE TITLE
Type and `param1` value of `m_libspdm_negotiate_algorithm_request14`

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#1841]
For the purpose of unittest18, it seems that the value of param1 should be 5 and the number of Alg structs should be 4.
So I think the type of `m_libspdm_negotiate_algorithm_request14` is not `libspdm_negotiate_algorithms_request_spdm11_multiple_tables_t` but `libspdm_negotiate_algorithms_request_spdm11_t`.

https://github.com/DMTF/libspdm/blob/798ef4739ad5c1648f6d90a62774da2e7330795c/unit_test/test_spdm_responder/algorithms.c#L2527-L2528

https://github.com/DMTF/libspdm/blob/798ef4739ad5c1648f6d90a62774da2e7330795c/unit_test/test_spdm_responder/algorithms.c#L491-L567

**Comment by Xiaohanjlll** [comment]
I will check this
