### ISSUE TITLE
Requester should check `ResponderContext` before issuing `PSK_FINISH`

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1851]
After clarifying this with the SPDM Working Group (mostly @xiaoyuruan)...

It is legal for a Responder with `PSK_CAP=10b` to not return `ResponderContext`. In such a case the Requester should not issue `PSK_FINISH`. However libspdm only checks the Responder's `PSK_CAP`, not the `ResponderContext`, when determining if it should issue `PSK_FINISH`.
https://github.com/DMTF/libspdm/blob/9ad78c33235296c812e503e84ec7e5a89ba2e19d/library/spdm_requester_lib/libspdm_req_communication.c#L132-L140 Instead it should check if `ResponderContext` is present or not, and base its decision on that.

**Comment by steven-bellock** [comment]
In addition, the Requester should check that if the Responder's `PSK_CAP` is `01b` that the `ResponderContext` is not present.

**Comment by jyao1** [comment]
> It is legal for a Responder with PSK_CAP=10b to not return ResponderContext.

I am confused. 
SPDM spec says clearly "10b . Responder supports Pre-Shared Key and **provides ResponderContext for session key derivation.**"

Why it can not return ResponderContext ? I think we need clarify SPDM spec.

**Comment by xiaoyuruan** [comment]
The quote is in CAPABILITY.  Having a capability does not mean the Responder must exercise that capability all the time.  "Responder can return ResponderContext" does not mean it must return ResponderContext.  For example, the Responder may choose to not return ResponderContext (Q=0) for select "more trusted" Requesters to speed up the handshake by saving FINISH.

I think it's clear in the spec, but I also don't mind adding clarification.

**Comment by jyao1** [comment]
I think it is very misleading. Just like a device says:
I support to MEAS_CAP, but return 0 measurement block in MEASURMENT response.
I support to CERT_CAP, but return no digest for all slots.

Not sure if it is right approach.

**Comment by jyao1** [comment]
> Instead it should check if ResponderContext is present or not, and base its decision on that.


> For example, the Responder may choose to not return ResponderContext (Q=0) for select "more trusted" Requesters to speed up the handshake by saving FINISH.


If we need support that use case, what check is needed ?

**Comment by steven-bellock** [comment]
After talking to the wider SPDM Working Group, libspdm's current behavior is correct. If `PSK_CAP==01b` then Responder cannot provide `ResponderContext` and if `PSK_CAP==10b` then Responder must provide `ResponderContext`.
