### ISSUE TITLE
should it allow NULL cert_chain_size and cert_chain as input parameter for `libspdm_get_certificate()`?

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#1854]
From https://github.com/DMTF/libspdm/pull/1849#issuecomment-1490386084

Hi @jyao1 @steven-bellock ,
I tried spem-emu CI with this patch, the patch itself it works good though, another issue is detected as below.
You can find the detailed error log at https://github.com/xiangfeima/spdm-emu/actions/runs/4562345345

So far my debugging result shows #1835 changes the way of parameter check in `libspdm_try_get_certificate()` and it possibly breaks `spdm_device_validator_sample` in CI.

The detailed calling stack would be:
spdm_device_validator_sample -> spdm_responder_conformance_test (https://github.com/DMTF/spdm-emu/blob/172574ac46a5602e1692d19f6bb75d260cc4e49c/spdm_emu/spdm_device_validator_sample/spdm_device_validator_sample.c#L68) -> common_test_run_test_suite (https://github.com/DMTF/SPDM-Responder-Validator/blob/18e0fcc89216b5ac4c3c7e516fc7aab0cab31788/library/spdm_responder_conformance_test_lib/spdm_responder_test.c#L49) -> common_test_group_t m_spdm_test_groups[] (https://github.com/DMTF/SPDM-Responder-Validator/blob/18e0fcc89216b5ac4c3c7e516fc7aab0cab31788/library/spdm_responder_conformance_test_lib/spdm_responder_test.c#L9) -> m_spdm_test_group_challenge_auth (https://github.com/DMTF/SPDM-Responder-Validator/blob/18e0fcc89216b5ac4c3c7e516fc7aab0cab31788/library/spdm_responder_conformance_test_lib/spdm_responder_test.c#L21) -> spdm_test_case_challenge_auth_setup_version_10_11 (https://github.com/DMTF/SPDM-Responder-Validator/blob/18e0fcc89216b5ac4c3c7e516fc7aab0cab31788/library/spdm_responder_conformance_test_lib/spdm_responder_test_6_challenge_auth.c#L196) -> spdm_test_case_challenge_auth_setup_vca_digest (https://github.com/DMTF/SPDM-Responder-Validator/blob/18e0fcc89216b5ac4c3c7e516fc7aab0cab31788/library/spdm_responder_conformance_test_lib/spdm_responder_test_6_challenge_auth.c#L202) -> libspdm_get_certificate(spdm_context, NULL, slot_id, **NULL, NULL**) (https://github.com/DMTF/SPDM-Responder-Validator/blob/18e0fcc89216b5ac4c3c7e516fc7aab0cab31788/library/spdm_responder_conformance_test_lib/spdm_responder_test_6_challenge_auth.c#L174) -> finally segmentation fault occur at the line 93 in `libspdm_return_t libspdm_try_get_certificate()`
https://github.com/DMTF/libspdm/blob/9ad78c33235296c812e503e84ec7e5a89ba2e19d/library/spdm_requester_lib/libspdm_req_get_certificate.c#L92-L93

would you help to take a look?

**Comment by jyao1** [comment]
Steven is working on it.

**Comment by xiangfeima** [comment]
Thank you.
Let's close this one since I see https://github.com/DMTF/SPDM-Responder-Validator/pull/68 is merged.
I will update spdm-emu CI result in #1849 thread.
