### ISSUE TITLE
Does mutual authentication requires that the requester and responder both sign a challenge

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1858]
This would mean both sides must provision a private key.

**Comment by jyao1** [comment]
that is right.

**Comment by steven-bellock** [comment]
Note that 1.0/1.1 "mutual authentication" through `CHALLENGE` is not real mutual authentication, and so was deprecated in 1.2. The only way to do real mutual authentication in SPDM is either asymmetric or symmetric key exchange.

**Comment by PrakashK94** [comment]
I checked the SPDM spec 1.2, There are several ways of doing mutual authentication a. using certificate(Deprecated in SPDM spec 1.2, ch-10.8.1) b. using challenge(Deprecated in SPDM spec 1.2, ch-10.9.3) and c. using Key exchange(Real mutual authentication in SPDM 1.2, ch-10.16.1). Is my understanding correct on this?

**Comment by steven-bellock** [comment]
10.8.1 still applies for mutual authentication through asymmetric key exchange.

**Comment by PrakashK94** [comment]
One thing I don’t understand. I see LIBSPDM sets this flag BasicMutAuthReq in the challenge response. Then it does a mutual authentication after the requester challenge was done.  But the spec says this is deprecated.  The way I understand the spec is that the only time you do mutual authentication is before you do the key exchange, no other time.
My question is, if this is deprecated, then why LIBSPDM is doing it?
SpdmSendResponse[0]: msg SPDM_CHALLENGE_AUTH(0x3), size (0xe6): 
0000: 12 03 80 07 2c a8 5c 4e 78 52 26 6c f0 3e 8c 7f 0f c6 0a db 58 f3 14 04 71 b5 9b 04 92 51 ae 05 
0020: fc f7 99 88 85 16 03 fd 48 8c 9e 6e 74 95 36 7d a2 2a 4c c0 95 b7 7d 60 80 c6 8e 49 1e ba 9c c5 
0040: 12 63 05 7f c1 a4 e1 89 c7 63 29 d9 11 8d 26 9d 0a 23 14 ca 77 51 01 02 62 0f cd 16 18 48 32 48 
0060: 70 44 97 fc f9 04 90 fc ea 9b 53 81 a9 7a 0d b6 8b 7f ac 3d c2 59 e6 b3 e4 a7 78 f9 e7 6a 75 6c 
0080: 2f f2 7f 01 00 00 2b 52 59 b5 ef 9b 20 8b 62 c0 a5 90 ec 94 0d 8c 0f 61 a2 9c 4a df d6 54 95 c6 
00a0: 97 62 47 68 25 18 bc 86 b9 41 96 d2 74 16 00 2f 3f 35 a5 99 6b a4 b1 4a ce f0 a7 f1 3f 63 26 a1 
00c0: 12 97 8c 2f 61 a4 37 c8 6d 93 fd d7 87 46 8c 91 3f 95 82 31 d5 bb ed 81 06 13 89 f4 4e 0f 4f 88 
00e0: ca 96 7b 3c 15 57

**Comment by steven-bellock** [comment]
@PrakashK94 See https://github.com/DMTF/libspdm/issues/983.

**Comment by PrakashK94** [comment]
so this is WIP?

**Comment by steven-bellock** [comment]
We're not sure what to do and it's still open to discussion. Feel free to express your opinion in #983.
