### ISSUE TITLE
split LIBSPDM_MAX_SESSION_COUNT to DHE session and PSK session

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1860]
Current LIBSPDM_MAX_SESSION_COUNT means the sum of DHE session and PSK session.

We need consider the case that a device may want to allow n DHE session and m PSK session.

As such, we need define two macro LIBSPDM_MAX_DHE_SESSION_COUNT and LIBSPDM_MAX_PSK_SESSION_COUNT, 
where LIBSPDM_MAX_SESSION_COUNT = LIBSPDM_MAX_DHE_SESSION_COUNT + LIBSPDM_MAX_PSK_SESSION_COUNT.

**Comment by steven-bellock** [comment]
Since the size of a secured message context is the same for both PSK and DHE, they don't need to be macros, and can be set in the `spdm_context` at runtime.

**Comment by jyao1** [comment]
We can add LIBSPDM_DATA_MAX_DHE_SESSION_COUNT and LIBSPDM_DATA_MAX_PSK_SESSION_COUNT.
