### ISSUE TITLE
PSK means the public keys can be provisioned and allows for skipping any certificate management, Is that true?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1867]

**Comment by jyao1** [comment]
PSK == Pre-shared Key, it is a provisioned symmetric key.

**Comment by steven-bellock** [comment]
>PSK means the public keys can be provisioned and allows for skipping any certificate management, Is that true?

No, it is a provisioned symmetric key, and as such it should be kept secret.

>libspdm_encap_context_t - libspdm_large_managed_buffer_t certificate_chain_buffer, Is this needed/used for PSK support?

No, there is no encapsulated flow with PSK exchange.

**Comment by PrakashK94** [comment]
This is the flow for PSK_EXCHANGE right?
1. [GET_VERSION].*
2. [VERSION].*
3. [GET_CAPABILITIES].* (if issued)
4. [CAPABILITIES].* (if issued)
5. [NEGOTIATE_ALGORITHMS].* (if issued)
6. [ALGORITHMS].* (if issued)
7. [PSK_EXCHANGE].*
8. [PSK_EXCHANGE_RSP].*
9. [PSK_FINISH].* except the RequesterVerifyData field

**Comment by steven-bellock** [comment]
and
>10. [PSK_FINISH_RSP]

although that does not contribute to a transcript hash calculation.
