### ISSUE TITLE
why last_spdm_request and cache_spdm_request buffers are large in size in SPDM context structure?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1871]
uint8_t last_spdm_request[LIBSPDM_MAX_MESSAGE_BUFFER_SIZE];
uint8_t cache_spdm_request[LIBSPDM_MAX_MESSAGE_BUFFER_SIZE];

Can they not be small buffers or medium size buffers?

**Comment by jyao1** [comment]
No.
Because it is a full request message.
