### ISSUE TITLE
need clean up challenge_auth opaque data provisioning

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1889]
Current code requires provision challenge auth.
```
    size_t opaque_challenge_auth_rsp_size;
    uint8_t *opaque_challenge_auth_rsp;
```

We had better allow user to provide an input based upon need.

**Comment by steven-bellock** [comment]
Could return `opaque_data` as part of the measurement summary hash.

**Comment by jyao1** [comment]
we may consider similar fix as https://github.com/DMTF/libspdm/pull/1991
