### ISSUE TITLE
need clean up measurement opaque data provisioning

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#1890]
Current code requires provision measurement .
```
    size_t opaque_measurement_rsp_size;
    uint8_t *opaque_measurement_rsp;
```

We had better allow user to provide an input based upon need.

**Comment by steven-bellock** [comment]
Related issue : https://github.com/DMTF/libspdm/issues/1393

**Comment by jyao1** [comment]
fixed in https://github.com/DMTF/libspdm/pull/1991
