### ISSUE TITLE
Make LibSpdmConfig File Location Configurable

### ISSUE THREAD

**Issue by fdamato** [DMTF/libspdm#19]
The LibSpdmConfig.h file is currently located within the repository. A user, who doesn`t want to use the default configuration, need to modify the file within the repo.
It would be more flexible to pass the file at compilation time, externally from the repo.

**Comment by steven-bellock** [comment]
Approved at 6-July-2021: Use macro for the config file like mbed TLS. Need a volunteer to implement the change.
