### ISSUE TITLE
Can we not build latest LIBSPDM in Raspberry PI?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#1919]
I ran these commands to build,
1. cmake -DARCH=arm -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=openssl ..
2. make copy_sample_key
3. make

Build output,
root@raspberrypi:/home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/build# make
[  0%] Building C object os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/cipher/aead_aes_gcm.c.o
In file included from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/cryptlib_openssl/internal_crypt_lib.h:20,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:14:
/home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/include/crt_support.h:61:2: error: #error Unknown target architecture
 #error Unknown target architecture
  ^~~~~
In file included from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/aes.h:13,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:15:
/home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/include/openssl/opensslconf.h:46:2: error: #error Unknown target architecture
 #error Unknown target architecture
  ^~~~~
In file included from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/evp.h:13,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:16:
/home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/include/openssl/opensslconf.h:46:2: error: #error Unknown target architecture
 #error Unknown target architecture
  ^~~~~
In file included from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/e_os2.h:13,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/ossl_typ.h:19,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/evp.h:14,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:16:
/home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/include/openssl/opensslconf.h:46:2: error: #error Unknown target architecture
 #error Unknown target architecture
  ^~~~~
In file included from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/crypto.h:26,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/bio.h:20,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/evp.h:16,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:16:
/home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/include/openssl/opensslconf.h:46:2: error: #error Unknown target architecture
 #error Unknown target architecture
  ^~~~~
In file included from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/asn1.h:15,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/objects.h:15,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/openssl/include/openssl/evp.h:28,
                 from /home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/cryptlib_openssl/cipher/aead_aes_gcm.c:16:
/home/pi/Desktop/Hari/ResApp.bak20230403-1616/libspdm/os_stub/openssllib/include/openssl/opensslconf.h:46:2: error: #error Unknown target architecture
 #error Unknown target architecture
  ^~~~~
make[2]: *** [os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/build.make:63: os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/cipher/aead_aes_gcm.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1956: os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by steven-bellock** [comment]
This was fixed in https://github.com/DMTF/libspdm/pull/1722. 
@PrakashK94 you can either bring that pull request into your local space, or you can use the code at the `main` branch. Note that if you use the `main` branch we've had breaking changes since the 2.3.1 release.

**Comment by PrakashK94** [comment]
This is building now, but note added the following in this file https://github.com/DMTF/libspdm/blob/main/os_stub/cryptlib_openssl/CMakeLists.txt

if ((ARCH STREQUAL "arm") OR (ARCH STREQUAL "aarch64"))
    ADD_COMPILE_OPTIONS(-DLIBSPDM_CPU_ARM)
endif()

**Comment by steven-bellock** [comment]
> This is building now, but note we need to add the following in this file also, https://github.com/DMTF/libspdm/blob/main/os_stub/cryptlib_openssl/CMakeLists.txt
> 
> if ((ARCH STREQUAL "arm") OR (ARCH STREQUAL "aarch64")) ADD_COMPILE_OPTIONS(-DLIBSPDM_CPU_ARM) endif()
> 
> This change is not there in main branch.

@jyao1 @Wenxing-hou Have you tested the OpenSSL 3 changes with ARM?

**Comment by Wenxing-hou** [comment]
I will tested the OpenSSL 3 changes with ARM. Thanks.

**Comment by Wenxing-hou** [comment]
Hi, @PrakashK94 . I have submitted PR to fix the build error.  The arm build will pass when the PR is merged. You can follow the code change. Thanks.
