### ISSUE TITLE
Requesters and Alias Certificates

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1940]
Related issue with the SPDM specification : https://github.com/DMTF/SPDM-WG/issues/2585.

https://github.com/DMTF/libspdm/blob/6684f43117784b12e25e665df65d1d122540f11f/library/spdm_common_lib/libspdm_com_crypto_service.c#L589-L604 is common to both Requesters and Responders. Note that it uses the peer's `ALIAS_CERT_CAP`. However the Requester does not advertise its `ALIAS_CERT_CAP`, so the Responder does not have an easy way to determine if the Requester is using device certificates or alias certificates. This information is used to check whether the leaf certificate has a SPDM hardware identity OID.
https://github.com/DMTF/libspdm/blob/6684f43117784b12e25e665df65d1d122540f11f/library/spdm_crypt_lib/libspdm_crypt_cert.c#L824-L839

**Comment by jyao1** [comment]
It seems https://github.com/DMTF/libspdm/pull/1956 added some function to help to fix.

@xiangfeima , would you please take a look to see if you can take and fix this one?
