### ISSUE TITLE
Setting `LIBSPDM_DATA_PEER_USED_CERT_CHAIN_BUFFER` is incorrect

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1942]
When setting `LIBSPDM_DATA_PEER_USED_CERT_CHAIN_BUFFER` a full certificate chain, with SPDM header and root certificate hash, is provided. If `LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT==0` then the certificate chain is hashed and the leaf certificate of the public key is extracted via the `libspdm_*_get_public_key_from_x509` functions. However those functions do not process the SPDM header and hash. For example https://github.com/DMTF/libspdm/blob/771d4c826ff35f0a27c21d904330070a5f05504b/os_stub/cryptlib_mbedtls/pk/x509.c#L432-L443

**Comment by jyao1** [comment]
Or I think we can remove it, if it is only used by spdm-dump.

**Comment by jyao1** [comment]
related issue: https://github.com/DMTF/libspdm/issues/1952
