### ISSUE TITLE
Wrong memory comparison condition in `hardware_identity_oid` check process?

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#1949]
Looks the `!libspdm_consttime_is_mem_equal(xxx)` at line 827 should be `libspdm_consttime_is_mem_equal(xxx)`, right?
https://github.com/DMTF/libspdm/blob/8ada4786f07447fbf5f28c21f7a3114c2917fa1f/library/spdm_crypt_lib/libspdm_crypt_cert.c#L824-L832

**Comment by steven-bellock** [comment]
That's my bad. I introduced that in #1777. I guess we don't have any tests that would detect this?

**Comment by xiangfeima** [comment]
unit test requester_get_certificate_case24 should be the one cover this case.
https://github.com/DMTF/libspdm/blob/8ada4786f07447fbf5f28c21f7a3114c2917fa1f/unit_test/test_spdm_requester/get_certificate.c#L3488-L3492

It is commented out now, I will work on it.
https://github.com/DMTF/libspdm/blob/8ada4786f07447fbf5f28c21f7a3114c2917fa1f/unit_test/test_spdm_requester/get_certificate.c#L3858-L3862
