### ISSUE TITLE
Entropy exhaustion

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1950]
Consider the case where a Responder serves two Requesters, A and B. A may make many requests to the Responder, maliciously or not, that causes the Responder's entropy pool to dwindle, resulting in either insecure random numbers or increasing the time to generate a secure random number. This negatively affects B's interaction with the Responder. The Responder may partition its entropy pool so that half goes to A and half goes to B, and the two Requesters can't affect one another. libspdm requests random numbers through
https://github.com/DMTF/libspdm/blob/8ada4786f07447fbf5f28c21f7a3114c2917fa1f/include/hal/library/cryptlib/cryptlib_rng.h#L28
Consider adding another parameter to `libspdm_random_bytes` through which the Requester can be identified.

**Comment by xiaoyuruan** [comment]
The 800-90A DRBG requires reseed (getting new entropy) every 2^48 invocations to the generate random function.  
Entropy exhaustion does not seem a practical concern?

**Comment by steven-bellock** [comment]
That sounds reasonable. Closing for now.
