### ISSUE TITLE
Wrong dest buffer size for libspdm_copy_mem leads to assertion on ia32 platform

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#1957]
Hi @jyao1 @steven-bellock 

Few Windows platform CI tasks are running for long time, 
it seemed to be started from the current latest merge 
https://github.com/DMTF/libspdm/actions/runs/4738805656/

and based on that the new PR #1956 also gets the same issue.
https://github.com/DMTF/libspdm/pull/1956/checks

From the CI log can not find anything, do you have a clue what's going wrong?

Thanks.

**Comment by xiangfeima** [comment]
Here is the reason, introduced by #1866 
https://github.com/DMTF/libspdm/blob/258d489dc1f33433d8fcd7c03393e1fbc1d3d370/unit_test/test_spdm_responder/receive_send.c#L189-L191
it wrongly retrieves the dest buffer size for `libspdm_copy_mem` by using `sizeof(spdm_context->last_spdm_request)`, which is actually an uint8_t* pointer.
On x64 platform its size is 8 and on ia32 platform its size is 4.
In this case the src buffer for `libspdm_copy_mem` is `spdm_vendor_defined_request_msg_t` and its size is 7 thus the bug is not hit on x64 platform.

It should be changed to use `libspdm_get_scratch_buffer_last_spdm_request_capacity(spdm_context)`
```
    libspdm_copy_mem(spdm_context->last_spdm_request,
                     libspdm_get_scratch_buffer_last_spdm_request_capacity(spdm_context),
                     &spdm_request, sizeof(spdm_request));
```

**Comment by steven-bellock** [comment]
Thanks @xiangfeima. Also, in CI/CD if a `LIBSPDM_ASSERT` is hit then the process should terminate immediately and return failure to the operating system. But that is a separate issue.
