### ISSUE TITLE
`LIBSPDM_ASSERT` in CI/CD

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1961]
When running CI/CD, if a `LIBSPDM_ASSERT` is hit then it should
1. Print the assertion message.
2. Immediately exit and return failure to the test runner.

**Comment by jyao1** [comment]
The proposal is to define another MACRO

```
#define LIBSPDM_DEBUG_LIBSPDM_ASSERT_EXIT 3
```

And use that in CI/CD.

**Comment by Zhiqiang520** [comment]
I will check this.
