### ISSUE TITLE
`LIBSPDM_FIPS_TEST_AT_LOAD` is misleading

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1971]
@jyao1 @xiaoyuruan 

https://github.com/DMTF/libspdm/blob/364257164163b73bfbc664bff82cc448af379f8b/include/library/spdm_lib_config.h#L15-L22

However `libspdm_update_fips_selftest_context` is called at the start of connection establishment, which could be hours / days / weeks after libspdm is loaded. 

https://github.com/DMTF/libspdm/blob/364257164163b73bfbc664bff82cc448af379f8b/library/spdm_requester_lib/libspdm_req_communication.c#L9-L19

Also does this need to be a macro? It doesn't save much space when it's disabled.

**Comment by xiaoyuruan** [comment]
>However libspdm_update_fips_selftest_context is called at the start of connection establishment, which could be hours / days / weeks after libspdm is loaded.

Is there a problem?

**Comment by steven-bellock** [comment]
> If LIBSPDM_FIPS_TEST_AT_LOAD, then libspdm runs libspdm_fips_run_selftest() at load time.

That statement is not true, no?

**Comment by xiaoyuruan** [comment]
Right.  The comment section should be fixed.  Also some grammatical imperfections.  @Wenxing-hou

**Comment by steven-bellock** [comment]
Going even further why does https://github.com/DMTF/libspdm/blob/364257164163b73bfbc664bff82cc448af379f8b/library/spdm_common_lib/libspdm_com_context_data.c#L2432-L2509 exist? It seems to perform the same checks as https://github.com/DMTF/libspdm/blob/main/library/spdm_common_lib/libspdm_com_context_data.c#L2511-L2764

**Comment by Wenxing-hou** [comment]
I will check it to find a better ways. Thanks.

**Comment by jyao1** [comment]
Current flow is not right.

The expected behavior is:
1) If LIBSPDM_FIPS_TEST_AT_LOAD is defined, run all test once.
```
libspdm_update_fips_selftest_context()
{
#if LIBSPDM_FIPS_TEST_AT_LOAD
    libspdm_fips_run_selftest (fips_selftest_context);
    if (fips_selftest_context->tested_algo != fips_selftest_context->self_test_result) {
        return false;
    }
#endif
    return true;
}
```

2) If LIBSPDM_FIPS_TEST_AT_LOAD is not defined, run each libspdm_fips_selftest_xxx() in libspdm_crypt_xxx.c, when the API is called.

**Comment by steven-bellock** [comment]
Does `LIBSPDM_FIPS_TEST_AT_LOAD` need to be a macro? Ie, does its value need to be known at compile-time, or does it impart a significant reduction in code size?

**Comment by jyao1** [comment]
We can remove the FIPS_TEST_AT_LOAD macro. Then the flow will be:


1), the integrator can decide to call 
```
    libspdm_fips_run_selftest (fips_selftest_context);
    if (fips_selftest_context->tested_algo != fips_selftest_context->self_test_result) {
        return false; // need stop the process and reload the crypto or reset
    }
```

2) libspdm unconditionally call libspdm_fips_selftest_xxx() at each libspdm_crypto_xxx call.
See comment at https://github.com/DMTF/libspdm/pull/1974.

3) we need use LIBSPDM_STATUS_FIPS_FAIL to tell integrator that we have FIPS selftest failure.

**Comment by jyao1** [comment]
The latest proposal is at https://github.com/DMTF/libspdm/pull/1974#issuecomment-1521267574
