### ISSUE TITLE
Incorrect length of the NEGOTIATE_ALGORITHMS request message

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#198]
In clause '10.4 NEGOTIATE_ALGORITHMS request and ALGORITHMS response messages', paragraph 187 'NEGOTIATE_ALGORITHMS request message format', the Offset **4** Field **Length** means Length of the entire request message, in bytes.

But the following line 73 'spdm_request.**length** = sizeof(spdm_request); ' missed the size of Field **ExtAsym**, **ExtHash** and **ExtAlgCount** in **ReqAlgStruct**.

https://github.com/DMTF/libspdm/blob/f92be5023c1a3ff036b9e43cd8de0cd06b5eb711/library/spdm_requester_lib/negotiate_algorithms.c#L71-L80

**Comment by jyao1** [comment]
ext_algo is not supported.
If we open it here, then we have bigger problem in other places.

Suggest keep it as is.
