### ISSUE TITLE
`Negotiated State Preservation Indicator` should be accessible directly from the `spdm_context`

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1985]
`Negotiated State Preservation Indicator` is currently accessed through 
https://github.com/DMTF/libspdm/blob/d7700798944f077bbd502710f222ce7580360c15/library/spdm_common_lib/libspdm_com_context_data.c#L823-L826 and requires a session ID. However, even though it is only sent through a session it affects the connection between the Requester and Responder. It should be present directly in the `spdm_context` and have the property that, once set to `1`, it cannot be set to `0`.

**Comment by jyao1** [comment]
agree. It seems a bug.

If multiple sessions use different attributes, then the VCA cache will be discarded as long as one session attribute state it should be discarded.
