### ISSUE TITLE
Sending GET_VERSION inside a session (which is prohibited by the spec) resets the connection

### ISSUE THREAD

**Issue by PavelPu123** [DMTF/libspdm#1987]
From DSP0274_1.2.1 (page 37, table 6, last table line) it seems that GET_VERSION is not allowed inside the session. On my understanding there should be an error message issued in this case and connection reset should be prevented. In reality we see that the reset is happening in this case.

**Comment by steven-bellock** [comment]
Filed #1988 for version checks.
