### ISSUE TITLE
Check that SPDM messages and capabilities are consistent with the negotiated version

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1988]
libspdm is currently lax when it comes to checking that messages belong to the SPDM specification version they were introduced in. For example, if a libspdm Requester and Responder both support 1.0 and 1.1, and the Requester specifies 1.0 for the connection, I'm not sure there's much stopping 1.1 messages such as key exchange.

This enhancement would include checks of messages during runtime, and checks of the SPDM context (through `libspdm_check_context`) during development time.

**Comment by jyao1** [comment]
Yeah, I think we need add version check for each new command.
