### ISSUE TITLE
[SPDM 1.1.2] Handling multiple KEY_EXCHANGE messages

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#1989]
From the spec..
The Responder authentication multiple key exchange example provides an example of multiple sessions using two
independent sets of root session keys that coexist at the same time. The specification does not require a specific
temporal relationship between the second KEY_EXCHANGE request message and the first FINISH_RSP response
message. To simplify implementation, however, a Responder may generate an ErrorCode=Busy response to the
second KEY_EXCHANGE request message until the first FINISH_RSP response message is complete.

I'm planning to implement something like this on the responder side..
Before receiving the first KEY_EXCHANGE, the state was set to SPDM_RESPONSE_STATE_NOMAL.
Let's say I received the first KEY_EXCHANGE and by the end of the KEY_EXCHANGE  response will set the state to SPDM_RESPONSE_STATE_BUSY (to avoid the second KEY_EXCHANGE being received by the responder before the first FINISH is processed)

Whe the responder receives the first FINISH request, the response code will set the state back SPDM_RESPONSE_STATE_NOMAL, so I can receive the second KEY_EXCHANGE and process it....

Question:
Lets say I received the first KEY_EXCHANGE (set the state to SPDM_RESPONSE_STATE_BUSY on the responder code) and for some reason, requester never sent the corresponding FINISH - How to handle this?

**Comment by steven-bellock** [comment]
This is a generic issue. Ie, what can a Responder do if the Requester sends a request but never retrieves the response? It can
1.  Do nothing.
2. Terminate the session if there is one.
3. Terminate the connection.

For your scenario, where the Requester does not complete the handshake phase, it would probably terminate the session.

**Comment by goutham23** [comment]
Thanks for the quick response.
As a responder how to monitor this scenario and when to take the call to terminate or free the session?

**Comment by steven-bellock** [comment]
Set a timer interrupt before waiting for a request. If the interrupt fires then the Requester is taking too long and Responder can terminate connection / session.

**Comment by goutham23** [comment]
Thanks!!
