### ISSUE TITLE
FIPS `LIBSPDM_*_SUPPORT_TEST` should not exist

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#1997]
`LIBSPDM_SHA3_SUPPORT_TEST` and `LIBSPDM_EDDSA_SUPPORT_TEST` are defined in https://github.com/DMTF/libspdm/blob/88803c35e1b4ddf20a39866e6f74b3e105861b0c/library/spdm_crypt_lib/CMakeLists.txt#L28-L34
However, compilation of [spdm_crypt_lib](https://github.com/DMTF/libspdm/tree/main/library/spdm_crypt_lib) should not depend on the underlying cryptography library. If, at compile-time, an Integrator doesn't support a cryptography algorithm then they'll just set, for example, `LIBSPDM_SHA3_256_SUPPORT` to `0`. If `spdm_crypt_lib` supports a cryptography algorithm, but at runtime the Integrator wants to disable the self-test for that algorithm, then that should be a capability provided by a FIPS function before the self-test is run.

**Comment by jyao1** [comment]
The requirement is: We need make test pass for openssl and mbedtls.
The problem we need to resolve is that mbedtls does not support SHA3, EDDSA and SMx.
We need a way to skip those test.

If we need to remote `LIBSPDM_<algo>_SUPPORT_TEST`, then we need explicitly override `LIBSPDM_<algo>_SUPPORT`.

**Comment by steven-bellock** [comment]
The logic to disable algorithms at compile-time based on the cryptography library could go in https://github.com/DMTF/libspdm/blob/main/CMakeLists.txt. However, some Integrators may want to use a non-(MbedTLS / OpenSSL) cryptography library and just build the core libraries. For example `make spdm_responder_lib spdm_common_lib` etc. For such cases the CMake build should accommodate an empty `-DCRYPTO` value.

**Comment by jyao1** [comment]
We can override the crypto specific `LIBSPDM_<algo>_SUPPORT` definition in the top level CMakeLists.txt, and remove `LIBSPDM_<algo>_SUPPORT_TEST`.
We assume that a new project needs to create its own CMakeLists.txt, if other crypto library is used.
