### ISSUE TITLE
`encap_context.certificate_chain_buffer` should be provided by Integrator

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2001]
libspdm currently reserves a large amount of space in the `spdm_context` for a Responder to store the Requester's certificate chain during mutual authentication. Similar to #1454 let's have the Integrator provide a buffer to store the certificate chain.

https://github.com/DMTF/libspdm/blob/043f81877e435c7a84d3134128f566edfdddefbb/include/internal/libspdm_common_lib.h#L384

Note also that the comment
https://github.com/DMTF/libspdm/blob/043f81877e435c7a84d3134128f566edfdddefbb/include/internal/libspdm_common_lib.h#L480-L482 is incorrect. This is used by the Responder, not Requester.

**Comment by jyao1** [comment]
@steven-bellock will make a proposal.
