### ISSUE TITLE
`libspdm_gen_csr` interface changes

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2002]
`libspdm_gen_csr` currently takes the following parameters. https://github.com/DMTF/libspdm/blob/043f81877e435c7a84d3134128f566edfdddefbb/include/hal/library/responder_secretlib.h#L232-L234 To enhance this interface let's 
1. Include the Requester's opaque data. It may be used when generating the CSR and it is needed to support the `ResetRequired` flow.
2. Change `uint8_t **csr_pointer` to `uint8_t *csr_pointer` and have `libspdm_gen_csr` copy the CSR to the response buffer.

With 2, `LIBSPDM_MAX_CSR_SIZE` won't be needed anymore, and the large stack allocation will be removed.

**Comment by jyao1** [comment]
NOTE: we have mbedtls will write CSR to the end of the buffer. If we choose this approach, we need to move buffer to the beginning.

```
    /*data is written at the end of the buffer*/
    ret = mbedtls_x509write_csr_der(&req, *csr_pointer, csr_buffer_size, libspdm_myrand, NULL);
```
