### ISSUE TITLE
`GET_CSR` check enhancements

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2003]
1. https://github.com/DMTF/libspdm/blob/043f81877e435c7a84d3134128f566edfdddefbb/library/spdm_requester_lib/libspdm_req_get_csr.c#L154 `csr_length` is unsigned so it cannot be less than `0`. Change `<=` to `==`. 
2. Provide a check that if `ResetRequired` is returned by the Responder then its `CERT_INSTALL_RESET_CAP` is `1`.

**Comment by jyao1** [comment]
Using "UINT value <= 0" is a bug, because "< 0" is impossible.
