### ISSUE TITLE
[SPDM 1.1.2] END_SESSION request

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2008]
From the spec- This request shall terminate a session. Further communication between the Requester and Responder using the
same session ID shall be prohibited.

END_SESSION request format does not mention about session_id :(
How does the responder know which session to end without knowing the session_id from the requester?

From the lib_spdm - I see they kill the session based on the last  session_id from spdm_context->last_spdm_request_session_id. But, let's say you have 3 active sessions (Example: session_id 1,2,3) and the last sesion_id is 3 and requester wants to kill the first session (session_id) - How does the responder know in this case?

**Comment by steven-bellock** [comment]
See https://www.dmtf.org/dsp/DSP0277 which has the nice diagram. 
![image](https://user-images.githubusercontent.com/8474235/235508246-c2122108-6031-449b-9a89-9e9832755741.png)

**Comment by goutham23** [comment]
This is a secure message format, my question is for END_SESSION request.

For some reason if the requester wants to end an session- How does the responder know which session_id to end?

**Comment by steven-bellock** [comment]
See the circled box. 
![image](https://user-images.githubusercontent.com/8474235/235509914-3fde37d2-a526-4c0f-ab87-5861a1573386.png)

**Comment by goutham23** [comment]
I know, but this is the secure message format, right?

Will END_SESSION request be sent always as part of secure message, no, right?

**Comment by steven-bellock** [comment]
>I know, but this is the secure message format, right?

Correct.
>Will END_SESSION request be sent always as part of secure message

Yes.
![image](https://user-images.githubusercontent.com/8474235/235531292-d4cc18fc-1199-49cd-889f-cbd1abf003b3.png)
