### ISSUE TITLE
Unable to get ARM compiler in CI/CD

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2015]
Not sure if we need to do anything about this, as it looks like a certificate infrastructure issue. See https://github.com/DMTF/libspdm/actions/runs/4875761842/jobs/8698385271?pr=2014 which produces

> Run wget https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu.tar.xz
--2023-0[5](https://github.com/DMTF/libspdm/actions/runs/4875761842/jobs/8698385271?pr=2014#step:6:6)-03 19:26:57--  https://developer.arm.com/-/media/Files/downloads/gnu/11.2-2022.02/binrel/gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu.tar.xz
Resolving developer.arm.com (developer.arm.com)... 23.198.[7](https://github.com/DMTF/libspdm/actions/runs/4875761842/jobs/8698385271?pr=2014#step:6:8).175, 23.19[8](https://github.com/DMTF/libspdm/actions/runs/4875761842/jobs/8698385271?pr=2014#step:6:9).7.174
Connecting to developer.arm.com (developer.arm.com)|23.1[9](https://github.com/DMTF/libspdm/actions/runs/4875761842/jobs/8698385271?pr=2014#step:6:10)8.7.175|:443... connected.
ERROR: cannot verify developer.arm.com's certificate, issued by ‘CN=GlobalSign RSA OV SSL CA 2018,O=GlobalSign nv-sa,C=BE’:
  Unable to locally verify the issuer's authority.
To connect to developer.arm.com insecurely, use `--no-check-certificate'.

With `--no-check-certificate` the file is retrievable, but we probably want to wait for the certificate to be updated.

**Comment by jyao1** [comment]
Maybe we just remove this temporarily.

That caused all CI failure. :(

**Comment by steven-bellock** [comment]
Maybe the URL to download the compiler is stale? Not sure how stable that URL is.

**Comment by steven-bellock** [comment]
Looks like it has been resolved.
