### ISSUE TITLE
Question regarding libspdm_req_negotiate_algorithms.c file

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2021]
https://github.com/DMTF/libspdm/blob/8248e6245f89704f789b0e81eb95bbfe19f0394e/library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c#L224-L279 Only applicable to secure sessions?

**Comment by steven-bellock** [comment]
DHE, AEADCipherSuite, and KeySchedule are needed for secure sessions. ReqBaseAsymAlg is needed for mutual authentication.

**Comment by PrakashK94** [comment]
So the above piece of code needed for either SPDM v1.1 or SPDM v1.2 right?

**Comment by steven-bellock** [comment]
Yes, if the Requester wants to validate the Responder's 1.1/1.2 `ALGORITHMS` response.
