### ISSUE TITLE
Conflict with `libspdm_test_responder_certificate_case16`

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#2037]
According to `libspdm_test_responder_certificate_case16`, it is possible to request a 0 byte certificate chain and respond with a portion length of 0.
So it seems that `(spdm_response->portion_length == 0)` below should be removed.

https://github.com/DMTF/libspdm/blob/8299f668ba21b1def18436799168a2daa63b650e/library/spdm_requester_lib/libspdm_req_get_certificate.c#L225-L226

**Comment by jyao1** [comment]
The code is from requester lib, right?

The portion_length could be 0, only if the requestered portion_length is 0.
But that condition wont happen in requester lib. I dont see the conflict.

**Comment by steven-bellock** [comment]
> Are you saying the requester never requests a length of 0?

Currently a libspdm Requester retrieves the entire certificate chain.

**Comment by lazineer** [comment]
Ok. Then will `libspdm_test_responder_certificate_case16` be deleted later?
https://github.com/DMTF/libspdm/blob/8299f668ba21b1def18436799168a2daa63b650e/unit_test/test_spdm_responder/certificate.c#L1171-L1176

**Comment by steven-bellock** [comment]
No. A libspdm Responder may talk to a non-libspdm Requester, who is free to request a 0 byte length.

**Comment by lazineer** [comment]
Thanks for the answer. I'll close this.

**Comment by lazineer** [comment]
Thanks for the answer. I'll close this.
