### ISSUE TITLE
Question: Plans of integrating libspdm with OpenSSL 3.1

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#2038]
With OpenSSL 1.0 version getting end of life this September.
What is the plans to integrate OpenSSL 3.1 version with libspdm ?

**Comment by jyao1** [comment]
We already have OpenSSL 3.0.8, for OpenSSL 1.1 EOL

**Comment by PrithviAPai** [comment]
Can I please get a link of libspdm supporting 3.0.8 ?

**Comment by PrithviAPai** [comment]
If my understanding is right, when we clone libspdm, by default OpenSSL will be extracted with 3.0.x version. Is that assumption right ?

**Comment by steven-bellock** [comment]
>If my understanding is right, when we clone libspdm, by default OpenSSL will be extracted with 3.0.x version. Is that assumption right ?

Correct, so long as you used `--recurse-submodules` when cloning, or updated the `openssllib` submodule after the clone.
