### ISSUE TITLE
the Responder shall set MeasurementHashAlgo field to 0 when it not support GET_MEASUREMENTS

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#204]
In clause '10.4 NEGOTIATE_ALGORITHMS request and ALGORITHMS response messages', paragraph 195 'Successful ALGORITHMS response message format', the Offset **8** Field **MeasurementHashAlgo**.
If the Responder supports **GET_MEASUREMENTS**, exactly one bit in this bit field shall be set. **Otherwise, the Responder shall set this field to 0 .**

I think before setting spdm_response->measurement_hash_algo, the code should check whether the Responder supports GET_MEASUREMENTS. For example,
uint32 capabilities_flag = spdm_context->local_context.capability.flags;
uint8 meas_cap = (uint8)(capabilities_flag >> 3) & 0x03; 
if (meas_cap == 0) {
	spdm_response->measurement_hash_algo = 0;
}

https://github.com/DMTF/libspdm/blob/f0f39596dd4ea0689c6196f2d023bc98ba9663ba/library/spdm_responder_lib/algorithms.c#L364-L368

**Comment by Wenxing-hou** [comment]
I will check it.

**Comment by steven-bellock** [comment]
This issue inspired https://github.com/DMTF/Security-TF/issues/1676
