### ISSUE TITLE
The requester shall check whether the responder returned `CSR` match the `RequesterInfo` of requester.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2048]
The requester shall check whether the responder returned `CSR` match the `RequesterInfo` of requester.

But currently it looks like the requester just save the responder returned `CSR`,  not check whether match the `RequesterInfo` of requester.
https://github.com/DMTF/libspdm/blob/36e5a0e4c4c3570b522169eefdab9f8c8d9c815b/library/spdm_requester_lib/libspdm_req_get_csr.c#L169-L170

**Comment by steven-bellock** [comment]
>The requester shall check whether the responder returned CSR match the RequesterInfo of requester.

Where do you see that? The `RequesterInfo` contributes to the CSR response, but is it fully returned by the Responder?

**Comment by Zhiqiang520** [comment]
> > The requester shall check whether the responder returned CSR match the RequesterInfo of requester.
> 
> Where do you see that? The `RequesterInfo` contributes to the CSR response, but is it fully returned by the Responder?

Refer to the paragraph 665 in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
`The CSR shall be populated with a combination of attributes provided by the Requester via
the RequesterInfo field, and others contributed by the Responder itself.`
`The Responder shall return an ERROR message with
error code InvalidRequest if it cannot support all of the fields included in the RequesterInfo .`

So I think **the requester** shall check whether the responder returned `CSR` match the `RequesterInfo` of **requester**.

**Comment by steven-bellock** [comment]
That's a very vague normative statement. I [filed an issue](https://github.com/DMTF/SPDM-WG/issues/2884) against the specification to get it clarified.

**Comment by steven-bellock** [comment]
@jyao1 and I think we can leave parsing of the CSR and the `RequesterInfo` to the Integrator / Verifier. In that case libspdm only forms the `GET_CSR` messages.
