### ISSUE TITLE
`libspdm_test_responder_csr_case3` just check part of `RequesterInfo` is in the `CSRdata` responder generated.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2049]
`libspdm_test_responder_csr_case3` just check **part** of `RequesterInfo` is in the `CSRdata` responder generated.
1. At the end of `libspdm_test_responder_csr_case3(void **state)`, 
It looks like the following line 336~337 is to check whether the `CSRdata` responder generated match with the `RequesterInfo` of requester.
https://github.com/DMTF/libspdm/blob/36e5a0e4c4c3570b522169eefdab9f8c8d9c815b/unit_test/test_spdm_responder/csr.c#L335-L337
2. The above line 336~337 just check whether `right_req_info_string` is in `CSRdata` by calling `libspdm_find_buffer` function, but `right_req_info_string` at line 49 is just **part** of `right_req_info` at line 15.
https://github.com/DMTF/libspdm/blob/36e5a0e4c4c3570b522169eefdab9f8c8d9c815b/unit_test/test_spdm_responder/csr.c#L48-L49
https://github.com/DMTF/libspdm/blob/36e5a0e4c4c3570b522169eefdab9f8c8d9c815b/unit_test/test_spdm_responder/csr.c#L14-L29
3. I think may be here should first parse the **whole** `right_req_info` at the line 15 following the `CertificationRequestInfo` format in [PKCS #10 specification in RFC2986](https://datatracker.ietf.org/doc/html/rfc2986), then check whether the `CSRdata` responder generated match with the `CertificationRequestInfo` format `RequesterInfo` of requester.

**Comment by Wenxing-hou** [comment]
In spec 1.2.1  665 line :
```
The CSR shall be populated with a combination of attributes provided by the Requester via
the RequesterInfo field, and others contributed by the Responder itself.
```
In the PKCS#10 spec:
```
CertificationRequestInfo ::= SEQUENCE {
version INTEGER { v1(0) } (v1,...),
subject Name,
subjectPKInfo SubjectPublicKeyInfo{{ PKInfoAlgorithms }},
attributes [0] Attributes{{ CRIAttributes }}
}
```
In the unit_test, the code need check attributes from req_info.
The `right_req_info_string` is the attributes of  the` right_req_info`.

I think the unit_test check is right.

**Comment by steven-bellock** [comment]
Based on #2048 the RequesterInfo should be opaque to libspdm.

**Comment by jyao1** [comment]
please add some comment in the binary text. As such we can know which is which.

**Comment by Zhiqiang520** [comment]
> In spec 1.2.1 665 line :
> 
> ```
> The CSR shall be populated with a combination of attributes provided by the Requester via
> the RequesterInfo field, and others contributed by the Responder itself.
> ```
> 
> In the PKCS#10 spec:
> 
> ```
> CertificationRequestInfo ::= SEQUENCE {
> version INTEGER { v1(0) } (v1,...),
> subject Name,
> subjectPKInfo SubjectPublicKeyInfo{{ PKInfoAlgorithms }},
> attributes [0] Attributes{{ CRIAttributes }}
> }
> ```
> 
> In the unit_test, the code need check attributes from req_info. The `right_req_info_string` is the attributes of the` right_req_info`.
> 
> I think the unit_test check is right.

The `attributes` in spec 1.2.1 665 line is just the `attributes [0] Attributes{{ CRIAttributes }}` in the PKCS#10 spec?
Is the `attributes` in spec 1.2.1 665 line include the `subject Name` in the PKCS#10 spec?
I found one example in [openssl-req](https://www.openssl.org/docs/manmaster/man1/openssl-req.html):
![image](https://github.com/DMTF/libspdm/assets/90754803/114e5237-fe08-4ce5-aea0-179b02da9c7d)
