### ISSUE TITLE
Should not assert unsupported response capabbility in spdm_set_data()

### ISSUE THREAD

**Issue by liyi77** [DMTF/libspdm#205]
https://github.com/DMTF/libspdm/blob/f0f39596dd4ea0689c6196f2d023bc98ba9663ba/library/spdm_common_lib/context_data.c#L128-L152

1. spdm_set_data() is a spdm common lib function, it will falsely assert when the requester is correctly initialized.
2. It is confused that assert when have not used a libspdm supported capabbility,
    assert when user want to use a unsupported cap is good enough.

**Comment by steven-bellock** [comment]
Yeah the logic is backwards.

**Comment by liyi77** [comment]
> 1. spdm_set_data() is a spdm common lib function, it will falsely assert when the requester is correctly initialized.
> 2. It is confused that assert when have not used a libspdm supported capabbility,
>    assert when user want to use a unsupported cap is good enough.

Requester and responder use same bit to indicate supported capabilities, such:

#define SPDM_GET_CAPABILITIES_REQUEST_FLAGS_HANDSHAKE_IN_THE_CLEAR_CAP BIT15
#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_HANDSHAKE_IN_THE_CLEAR_CAP BIT15
it is my bad that treat it as different thing just according name, topic 1 is a wrong description :(  .

But requester should not check this CAP anyway:
```
#define SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_MEAS_CAP (BIT3 | BIT4)
```
because there is no corresponding REQUSET FLAGS.

**Comment by Wenxing-hou** [comment]
I will check it.
