### ISSUE TITLE
`requester_info` can't represent the whole `GET_CSR` request message.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2051]
`requester_info` is just **part** of the whole `GET_CSR` request message, it can't represent the whole `GET_CSR` request message.

1. After the Responder has processed the reset, current code decide a new `GET_CSR` request is same or different with the `GET_CSR` request that was sent before the reset, by calling `libspdm_consttime_is_mem_equal(cached_req_info, requester_info` at the following line 1142 to compare the `cached_req_info` and the new `requester_info`, but `requester_info` is just **part** of the whole `GET_CSR` request message, it can't represent the whole `GET_CSR` request message.
https://github.com/DMTF/libspdm/blob/36e5a0e4c4c3570b522169eefdab9f8c8d9c815b/os_stub/spdm_device_secret_lib_sample/lib.c#L1134-L1144

2. Refer to the paragraph 666 in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/6d0081a7-6f53-4a31-b48a-3994ae8ef564)

3. There are many other `Field` in `Table 79 — GET_CSR request message format`.
![image](https://github.com/DMTF/libspdm/assets/90754803/b934f8bf-7896-4ab1-9a7c-d7c9edf9badc)

**Comment by steven-bellock** [comment]
Yeah I was wondering how to handle that in https://github.com/DMTF/libspdm/issues/2002. Maybe libspdm should pass a pointer to the request message through `libspdm_gen_csr` and the Integrator can either store the message or a hash of it that persists between resets.

**Comment by Wenxing-hou** [comment]
> Yeah I was wondering how to handle that in #2002. Maybe libspdm should pass a pointer to the request message through `libspdm_gen_csr` and the Integrator can either store the message or a hash of it that persists between resets.

I will fix this issue after the PR: #2043 and #2045 are merged.

And the total request needs to be taken as `libspdm_gen_csr` input. The `requester_info` and `opaque_data` are obtained from the total request.

    result = libspdm_gen_csr(spdm_context->connection_info.algorithm.base_hash_algo,
