### ISSUE TITLE
The resulting CSR shall be different for the `DeviceCert` model and the `AliasCert` model

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2056]
The resulting CSR shall be different for the `DeviceCert` model and the `AliasCert` model.
I think:
for the `DeviceCert` model, set the `CA` constraint to `FALSE` in the CSR.
for the `AliasCert` model, set the `CA` constraint to `TRUE` in the CSR.

1. Refer to the paragraph 667 in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/4dff3f65-67dd-46c0-91d0-70318e1be5c2)

2. Refer to the paragraph 111 `Figure 1 — SPDM certificate chain models` in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/db06f026-7374-4c6d-ae91-317345889257)

**Comment by steven-bellock** [comment]
This is a functional code bug in `libspdm/library` or a test / os_stub bug?

**Comment by Wenxing-hou** [comment]
> This is a functional code bug in `libspdm/library` or a test / os_stub bug?

Both the `library` and `os_stub` code need change.
First, the `alias_cert` cap check is needed in library, like:
```
        if((spdm_context->connection_info.capability.flags &
            SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_ALIAS_CERT_CAP) == 0) {
            is_device_cert_model = true;
        }
```
Then, the `libspdm_gen_csr` will be changed based on the input `is_device_cert_model` in os_stub.
```
    result = libspdm_gen_csr(spdm_context->connection_info.algorithm.base_hash_algo,
                             spdm_context->connection_info.algorithm.base_asym_algo,
                             &need_reset, requester_info, requester_info_length,
                             &csr_len, &csr_p);
```
