### ISSUE TITLE
Currently `SET_CERTIFICATE_RSP` code miss checking the `AliasCert` model

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2066]
1. Currently `SET_CERTIFICATE_RSP` code miss checking the `AliasCert` model:
If the Responder uses the `AliasCert` model ( `ALIAS_CERT_CAP=1b` in `CAPABILITIES` response), the Responder should check the last certificate in the received `CertChain` from the Requester is Device Certificate CA.
https://github.com/DMTF/libspdm/blob/772338edcf727d46ebf56451c6927187d97b5d52/library/spdm_responder_lib/libspdm_rsp_set_certificate.c#L120-L126
https://github.com/DMTF/libspdm/blob/772338edcf727d46ebf56451c6927187d97b5d52/os_stub/spdm_device_secret_lib_sample/lib.c#L2009-L2018

3. Refer to the paragraph 678 `Table 81 — SET_CERTIFICATE request message format` in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/e01f7894-ee00-48d9-97ea-e3cb5aae4ce0)

4. Refer to the paragraph 111 `Figure 1 — SPDM certificate chain models` in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/bb3e5977-0cd7-4068-b4c5-35c3cfee68ac)

5. Refer to the paragraph 106 in [DSP0274_1.2.1.pdf]
![image](https://github.com/DMTF/libspdm/assets/90754803/93199f2c-5ea1-4cf1-8d0c-b32fa8d425ef)

**Comment by steven-bellock** [comment]
Yeah there can be something similar to https://github.com/DMTF/libspdm/blob/772338edcf727d46ebf56451c6927187d97b5d52/include/library/spdm_common_lib.h#L790 for the Responder to validate the `SET_CERTIFICATE` certificate chain.

**Comment by jyao1** [comment]
we need add test to set device cert in alias cert mode. It may cause failure. The reason is that libspdm_x509_verify_cert_chain() will check the full cert chain including the leaf cert.
