### ISSUE TITLE
Unit tests that use `LIBSPDM_DATA_TRANSFER_SIZE` and `LIBSPDM_MAX_SPDM_MSG_SIZE` are incorrect

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2071]
For example https://github.com/DMTF/libspdm/blob/60e1a4ab19e5f1060f0caf2e55d98c2311ab8e77/unit_test/test_spdm_requester/error_test/get_capabilities_err.c#L1923-L1927 However https://github.com/DMTF/libspdm/blob/60e1a4ab19e5f1060f0caf2e55d98c2311ab8e77/unit_test/test_spdm_requester/error_test/get_capabilities_err.c#L1047-L1048 In this case it should be
```
spdm_response->data_transfer_size = LIBSPDM_DATA_TRANSFER_SIZE; 
spdm_response->max_spdm_msg_size = LIBSPDM_DATA_TRANSFER_SIZE - 1; 
```
The test passes because currently `LIBSPDM_DATA_TRANSFER_SIZE == LIBSPDM_MAX_SPDM_MSG_SIZE`. There are multiple instances of this issue.

**Comment by Zhiqiang520** [comment]
I will check this issue.
