### ISSUE TITLE
the Requester should allow issue `SET_CERTIFICATE` outside of a secure session for slots 1-7

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2077]
the Requester should allow issue SET_CERTIFICATE outside of a secure session for slots 1-7.
1. The current code behavior is The Requester **shall** issue SET_CERTIFICATE **inside** a secure session for slot 1-7 provisioning.
https://github.com/DMTF/libspdm/blob/aa51e293809194e601af7db7c96f5e855d4d78cb/library/spdm_requester_lib/libspdm_req_set_certificate.c#L58-L62
2. Refer to the paragraph 675 in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/5119751d-1c52-4f1b-ad29-02953fd5dbfe)
![image](https://github.com/DMTF/libspdm/assets/90754803/6270b96c-2a31-4d2a-b7fb-b4eec45c97ca)
3. Base on the above specification, `"should" ("recommended")`, I think:
For slots 1-7, if the provisioning happens in a trusted environment, the Requester should **allow** issue `SET_CERTIFICATE` **outside** of a secure session.

**Comment by steven-bellock** [comment]
From 5-Jun-2023 meeting: we could add a bit to the `spdm_context` or require a function (in secretlib) that says whether the Responder is in a trusted environment or not.
