### ISSUE TITLE
should we keep sequence number (not increase) in case of decryption error

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#2082]
In current code, we do
* increase sequence number in local storage
* decrypt message
* if fail, return error

It means that the sequence number is still increased, in case of failure. That follows the DSP0277.
```
For each record, both SPDM endpoints shall follow these steps as prescribed:
1. Zero extend the sequence number to iv_length according to the selected AEAD cipher suite in
ALGORITHMS messages.
2. Perform a bitwise XOR of the zero-extended sequence number with the appropriate IV derived in the
SPDM key schedule. The sequence number shall be padded with zeros to the left (most significant) to the
size of the IV.
◦ The output of this step is called the per-message nonce.
3. Increment the sequence number by a value of one for the next Secured Message
```

Is that expected way?
Or should we keep sequence number as original in case of failure ?

**Comment by steven-bellock** [comment]
From 5-Jun-2023 meeting: should probably terminate the session. If someone needs more flexibility to retry DSP0277 messages then we can revisit it.
