### ISSUE TITLE
Not able to build LIBSPDM in Windows using CLANG

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2089]
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=CLANG -DTARGET=Release -DCRYPTO=mbedtls ..
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
The CMAKE_C_COMPILER:

cl
is not a full path and was not found in the PATH.

To use the NMake generator with Visual C++, cmake must be run from a shell
that can use the compiler cl from the command line. This environment is
unable to invoke the cl compiler. To fix this problem, run cmake from the
Visual Studio Command Prompt (vcvarsall.bat).

Tell CMake where to find the compiler by setting either the environment
variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
the compiler, or to the compiler name if it is in the PATH.

My concern is Can we not build LIBSPDM by just using CLANG? Does it requires Visual Studio to build?

**Comment by steven-bellock** [comment]
We currently don't test it in CI/CD but we do support it. See https://github.com/DMTF/libspdm/blob/ea98cd192f2c1bda42d99aa13355f26698dc4c91/CMakeLists.txt#L623-L624
>My concern is Can we not build LIBSPDM by just using CLANG? Does it requires Visual Studio to build?

I believe it does need VS, specifically clang-cl and nmake. We'll use this issue to enable CLANG / Windows in CI/CD.

**Comment by jyao1** [comment]
We have described the step in readme.

Are you following that?

```
b) [LLVM](https://llvm.org/) (LLVM13)

Install [LLVM-13.0.0-win64.exe](https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.0). Change the LLVM install path to C:\LLVM, and add LLVM in PATH environment.
LLVM13 works good for clang and [libfuzzer](https://llvm.org/docs/LibFuzzer.html) build. Other versions are not validated for clang build.
Because the libfuzzer lib path is hard coded in CMakeLists, other versions may fail for libfuzzer build.
```

**Comment by PrakashK94** [comment]
> We currently don't test it in CI/CD but we do support it. See
> 
> https://github.com/DMTF/libspdm/blob/ea98cd192f2c1bda42d99aa13355f26698dc4c91/CMakeLists.txt#L623-L624
> 
> > My concern is Can we not build LIBSPDM by just using CLANG? Does it requires Visual Studio to build?
> 
> I believe it does need VS, specifically clang-cl and nmake. We'll use this issue to enable CLANG / Windows in CI/CD.

So, VS is compulsory needed for building LIBSPDM in windows right?

**Comment by PrakashK94** [comment]
> We have described the step in readme.
> 
> Are you following that?
> 
> b) [LLVM](https://llvm.org/) (LLVM13)
> 
> Install [LLVM-13.0.0-win64.exe](https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.0). Change the LLVM install path to C:\LLVM, and add LLVM in PATH environment. LLVM13 works good for clang and [libfuzzer](https://llvm.org/docs/LibFuzzer.html) build. Other versions are not validated for clang build. Because the libfuzzer lib path is hard coded in CMakeLists, other versions may fail for libfuzzer build.

Yes, followed that after that only not able to build.

**Comment by PrakashK94** [comment]
Without nmake also we can build in windows using CLANG?

**Comment by Wenxing-hou** [comment]
> Without nmake also we can build in windows using CLANG?

Hi, @PrakashK94. 
Please add the LLVM path such as `C:\LLVM\bin` in the environment for CLANG build on Windows.
The build will pass. Thanks.

**Comment by PrakashK94** [comment]
You mean without visual studio also we can build the LIBSPDM source using CLANG?

**Comment by Wenxing-hou** [comment]
> You mean without visual studio also we can build the LIBSPDM source using CLANG?

No. The Libspdm clang build for Windows needs Visual Studio. I am enabling CLANG CI build for Windows.

**Comment by PrakashK94** [comment]
CLANG CI build of windows is complete or is it work in progress?
