### ISSUE TITLE
version mismatch in `libspdm_test_responder_measurements_case22`

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#2097]
There is version mismatch.

`m_libspdm_get_measurements_request6` is version 1.0.

https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/measurements.c#L40-L42

`libspdm_test_responder_measurements_case22` expects version 1.1.
https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/measurements.c#L1273-L1274

I think `m_libspdm_get_measurements_request6` should be changed to `m_libspdm_get_measurements_request9` in `libspdm_test_responder_measurements_case22`.

https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/measurements.c#L59-L61

**Comment by Zhiqiang520** [comment]
I will check it.
