### ISSUE TITLE
wrong variable names

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#2099]
the variable name generating the nonce is wrong like below.
Need to change `m_libspdm_challenge_request1` to `m_libspdm_challenge_request3`.

https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/challenge_auth.c#L478-L481

There are same cases in `libspdm_test_responder_measurements_case9, 10, 12, 13 and 14`.

**Comment by Zhiqiang520** [comment]
I will check it.

**Comment by lazineer** [comment]
I mean there are wrong variable in libspdm_test_responder_challenge_auth_case9, 10, 12, 13 and 14 like libspdm_test_responder_challenge_auth_case8.
