### ISSUE TITLE
wrong request variable name

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#2100]
`libspdm_test_responder_challenge_auth_case10` description says slot number 1.

https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/challenge_auth.c#L556-L562

And `libspdm_test_responder_challenge_auth_case10` uses `m_libspdm_challenge_request3`.
https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/challenge_auth.c#L605-L607

But `m_libspdm_challenge_request3` have not slot number 1.

https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/challenge_auth.c#L18-L21

I think `m_libspdm_challenge_request3` should be changed to `m_libspdm_challenge_request4`.

https://github.com/DMTF/libspdm/blob/1897d6580214cdc242e0acf72b9519bdc9de076b/unit_test/test_spdm_responder/challenge_auth.c#L24-L27

**Comment by Zhiqiang520** [comment]
I will check it.
