### ISSUE TITLE
should not hardcode the test key in spdm_device_secret_lib_sample

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#2106]
Currently, we support RAW private key mode and hardcode key in https://github.com/DMTF/libspdm/blob/main/os_stub/spdm_device_secret_lib_sample/lib.c.

It is not a good design, because if the test key at https://github.com/DMTF/libspdm/tree/main/unit_test/sample_key is updated, it will cause mismatch.

See issue https://github.com/DMTF/spdm-emu/issues/257

I think we need a better way to keep them in sync.

**Comment by DavidPu** [comment]
to keep RAW keys in sync with sample_key/*, maybe we can auto-generate those raw keys from sample_key/ and include in lib.c
