### ISSUE TITLE
An error response with any error code other than `ResponseNotReady` shall re-initialize L1/L2 to null.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2114]
An error response with **any** error code **other than** `ResponseNotReady` shall re-initialize L1/L2 to null.

1. Refer to the paragraph 432 in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/e432e178-abb7-41c9-9f6c-67b20d9790f9)
2. So I think in `libspdm_get_response_measurements` function, should call `libspdm_reset_message_m(spdm_context, session_info);` before return **any** `libspdm_generate_error_response` **other than** `ResponseNotReady` error.
3. the Requester issues **a number of requests** without requiring signatures followed by a final request requiring a signature over the entire set of request-response messages exchanged.
> GET_MEASUREMENTS_REQUEST1
MEASUREMENTS_RESPONSE1
GET_MEASUREMENTS_REQUEST2
MEASUREMENTS_RESPONSE2
... ...
GET_MEASUREMENTS_REQUESTn
MEASUREMENTS_RESPONSEn

4. In the above scenario, if `MEASUREMENTS_RESPONSE1` successful, but `MEASUREMENTS_RESPONSE2` **error** at the following line 364 or 372, then should call `libspdm_reset_message_m(spdm_context, session_info);`  before return  `libspdm_generate_error_response`.
https://github.com/DMTF/libspdm/blob/83cbb2fd450e67a60e7e549069b595905099e637/library/spdm_responder_lib/libspdm_rsp_measurements.c#L362-L375
5. there are many same issues is in `libspdm_rsp_measurements.c`, for example,
https://github.com/DMTF/libspdm/blob/83cbb2fd450e67a60e7e549069b595905099e637/library/spdm_responder_lib/libspdm_rsp_measurements.c#L95-L107
6. there are also many similar issues in `libspdm_req_get_measurements.c`, for example, the line 414~415,
https://github.com/DMTF/libspdm/blob/83cbb2fd450e67a60e7e549069b595905099e637/library/spdm_requester_lib/libspdm_req_get_measurements.c#L411-L424

**Comment by jyao1** [comment]
Please help check if M1/M2 has similar issue.

**Comment by Zhiqiang520** [comment]
> Please help check if M1/M2 has similar issue.

a. After checking I found one new issue about set `M1/M2` to `null` : #2118
b. Unlike `L1/L2`, for `M1/M2`:
Refer to the paragraph 362 ~ 363 in [DSP0274_1.2.1.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
> If a response contains an ErrorCode other than ResponseNotReady :
No concatenation function is performed on the contents of both the original request and response.

**Comment by steven-bellock** [comment]
`Busy` should not affect the transcript as well, but that's an issue with the specification. I will file an issue against the specification.

**Comment by steven-bellock** [comment]
After talking with the SPDM Working Group, `Busy` is still being discussed, but `LargeResponse` should definitely not reset L1/L2.

**Comment by jyao1** [comment]
I dropped BUSY in this PR.

If SPDM decides to add BUSY later, we can add a new issue.
