### ISSUE TITLE
`return false;` in `libspdm_rsp_measurements.c` should be changed to `return libspdm_generate_error_response(`.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2115]
1. the following line 352 `return false;` in `libspdm_rsp_measurements.c` should be changed to `return libspdm_generate_error_response(`.
https://github.com/DMTF/libspdm/blob/83cbb2fd450e67a60e7e549069b595905099e637/library/spdm_responder_lib/libspdm_rsp_measurements.c#L351-L353
2. just like in `libspdm_rsp_challenge_auth.c`
https://github.com/DMTF/libspdm/blob/83cbb2fd450e67a60e7e549069b595905099e637/library/spdm_responder_lib/libspdm_rsp_challenge_auth.c#L188-L193

**Comment by steven-bellock** [comment]
Related discussion : https://github.com/DMTF/libspdm/discussions/1391.
