### ISSUE TITLE
The timer for the Heartbeat period shall start at transmission of `PSK_EXCHANGE_RSP` when `ResponderContext` is absent 

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2135]
The timer for the Heartbeat period shall start at the transmission of `PSK_EXCHANGE_RSP` response messages, when `ResponderContext` is **absent** in `PSK_EXCHANGE_RSP` response message.

1. Refer to paragraph 564 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/3f122a2c-a3d0-4ed1-8237-67cc23b9c2ba)
2. But for the special **case** `ResponderContext` is **absent** in `PSK_EXCHANGE_RSP` response message, the Requester **shall not** send `PSK_FINISH`.
I think: 
The timer for the Heartbeat period shall start at the transmission of `PSK_EXCHANGE_RSP` response messages.
Refer to paragraph 549 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/7518bc9e-4310-4999-87b9-4d4c915a108a)
3. I think `libspdm_start_watchdog` function should be called in the code block between the following line 409 ~ 432 in `libspdm_rsp_psk_exchange.c`, just like the line 230 ~ 243 in `libspdm_rsp_psk_finish.c`.
https://github.com/DMTF/libspdm/blob/2b8bfc06c775308a7c0fe06bc552496191d167da/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L407-L432
https://github.com/DMTF/libspdm/blob/2b8bfc06c775308a7c0fe06bc552496191d167da/library/spdm_responder_lib/libspdm_rsp_psk_finish.c#L230-L243
4. It is better to add the description for this special case in the paragraph 564 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).

**Comment by steven-bellock** [comment]
Oh good catch. I'll file an issue against the specification.
