### ISSUE TITLE
The Requester and Responder shared the same one timer?

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2137]
The Requester and Responder shared the **same one** timer?
Or the Requester and Responder have their **own respective** timer?

1. For **Responder**, The timer for the Heartbeat period shall start at the **transmission** of either the `FINISH_RSP` or `PSK_FINISH_RSP` response messages.
For **Requester**, The timer for the Heartbeat period shall start at the **reception** of either the `FINISH_RSP` or `PSK_FINISH_RSP` response messages.
Refer to paragraph 564 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/2c971ee0-31e7-4140-99c4-c272410d2093)
2. **Both** of the **Requester** and **Responder** shall terminate the session if session traffic is **not received** in twice `HeartbeatPeriod`.
Refer to paragraph 563 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/c8b6edf8-6e56-443c-96db-651bf5716d5f)
3. Currently **only** the Responder side code start the timer `libspdm_start_watchdog`. Does the the Requester side code also should start the timer?
https://github.com/DMTF/libspdm/blob/e5b93af2cd44cc52e5be18a23f9c39e1b3991a6d/library/spdm_responder_lib/libspdm_rsp_finish.c#L638-L651
https://github.com/DMTF/libspdm/blob/e5b93af2cd44cc52e5be18a23f9c39e1b3991a6d/library/spdm_responder_lib/libspdm_rsp_psk_finish.c#L230-L243

**Comment by jyao1** [comment]
for requester, we rely on integrator, not libspdm.

**Comment by steven-bellock** [comment]
I've always thought the specification is a bit heavy-handed with 
>The Responder shall terminate the session if session traffic is not received for two successive HeartbeatPeriods. Likewise, the Requester shall terminate the session if session traffic, including ERROR responses, is not received for two successive HeartbeatPeriods.

I think it's up to the endpoint doing the monitoring whether they want to terminate the session or not. If a Responder can support multiple Requesters then it may use Heartbeat to ensure quality-of-service and availability. However if there's only one Requester connected then the Responder doesn't have to be so stringent about the Heartbeat.

**Comment by steven-bellock** [comment]
@steven-bellock to file an issue against the specification.
