### ISSUE TITLE
spdm_send_receive_data() error handling is unable to distingish between a DecryptError from responder and device error

### ISSUE THREAD

**Issue by jcahill0** [DMTF/libspdm#214]
The spdm_send_receive_data() error handling uses limited return statuses that cause an application to be unable to distinguish between a DecryptError ERROR response from SPDM Responder and a generic error of the device.  The two are important to distinguish because a DecryptError signifies a sufficient error occurred in the session to warrant terminating the session and possibly starting a new session.  A generic device error signifies the application may not want to even talk to the device/SPDM responder, or start just start again at attestation.

Starting at spdm_receive_spdm_response() call, this calls spdm_receive_response() directly without any changing of the error status.
```
    return spdm_receive_response(spdm_context, session_id, FALSE,
                     response_size, response);
```

Next, the spdm_receive_response() call always checks first if the passed in session and received response's session match.  Then it throws RETURN_DEVICE_ERROR regardless of the actual response from the device/SPDM responder:
```
    message_session_id = NULL;
    is_message_app_message = FALSE;
    status = spdm_context->transport_decode_message(
        spdm_context, &message_session_id, &is_message_app_message,
        FALSE, message_size, message, response_size, response);

    if (session_id != NULL) {
        if (message_session_id == NULL) {
            DEBUG((DEBUG_INFO,
                   "spdm_receive_spdm_response[%x] GetSessionId - NULL\n",
                   (session_id != NULL) ? *session_id : 0x0));
            return RETURN_DEVICE_ERROR;
        }
```

One way to obtain the desired result, is to nuance this inner if-statement with checks against the actual message.
```
    message_session_id = NULL;
    is_message_app_message = FALSE;
    status = spdm_context->transport_decode_message(
        spdm_context, &message_session_id, &is_message_app_message,
        FALSE, message_size, message, response_size, response);

    if (session_id != NULL) {
        if (message_session_id == NULL) {
            spdm_message_header_t *spdm_response;
            spdm_response = response;
            DEBUG((DEBUG_INFO,
                   "spdm_receive_spdm_response[%x] GetSessionId - NULL\n",
                   (session_id != NULL) ? *session_id : 0x0));
            if (    spdm_response.header.request_response_code == SPDM_ERROR
                &&  spdm_response.header.param1 == SPDM_ERROR_CODE_DECRYPT_ERROR ) {
               return RETURN_SECURITY_VIOLATION;
            }
            else
            {
                return RETURN_DEVICE_ERROR;
            }
        }
```

Two other comments about this code:
1) It might be worth while adding checks against is_message_app_message == FALSE in the above code as well, so then we know it is not a Secure Message response being mis-parsed for an ErrorCode.
2) One additional check in spdm_receive_response() after spdm_context->transport_decode_message()'s status == RETURN_SUCCESS would guarantee other errors within the decode couldn't be blindly overwritten by other error checks, e.g. the responder use the wrong MsgType in the response.  While unlikely, it would provide extra protection and provide clear error handling.

**Comment by jyao1** [comment]
11/8/21 - Agree. Need propagate the DECRYPT_ERROR to the caller with SECURITY_VIOLATION. 
Maybe we need return the error from my side + error in SPDM_ERROR message from peer.
Type 1: RERUTN_SPDM_REPONDER_ERROR + GetLastSpdmResponderError().
Type 2: First 16 bit (my side) + Second 16 bit (peer side).

**Comment by jcahill0** [comment]
Type 1 looks very clean and re-usable of a design.  If we find other cases where addition debug would be helpful, we can return a new high level error and define a slightly different API to get the more specific errors.
Type 2 definitely would work and would need additional macros to clean up the concatenation and separation of the fields.  It does complicate basic return error testing, as there are many unique combinations to pull together.  So I think it will complicate the client's error handling too much.

**Comment by jyao1** [comment]
OK, let's take Type 1.

**Comment by qizhangz** [comment]
I try to undertsand how to do this implementation.
To SPDM message, the header of the response is formated as spdm_message_header_t. Then we can get request_response_code from it.
When is_app_message is TRUE, the message is APP message. What the format of it's response? Can we get request_response_code from it? I didn't find its definition in spec or code.
Thank you!

**Comment by qizhangz** [comment]
I have a PR as trail fix for this issue.  Could you please review and comment on it? Thanks!

https://github.com/DMTF/libspdm/pull/296
