### ISSUE TITLE
`DataTransferSize` must equal to `MaxSPDMmsgSize` when `CHUNK_CAP` not set?

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2149]
`DataTransferSize` **must equal** to `MaxSPDMmsgSize` when `CHUNK_CAP` **not set**?
 if yes, I think the specification should explicitly declare.

1. If `CHUNK_CAP` set, **Requester**/**Responder** supports Large SPDM message transfer mechanism **messages**.

Refer to paragraph 242 `Table 13 — Flag fields definitions for the Requester` in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
<img width="545" alt="image" src="https://github.com/DMTF/libspdm/assets/90754803/6ea6b53b-dc84-4590-a98c-cd51687701c0">

Refer to paragraph 245 `Table 14 — Flag fields definitions for the Responder` in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).
<img width="544" alt="image" src="https://github.com/DMTF/libspdm/assets/90754803/65bfbe98-54d1-4f5c-8cca-d57ef6d127e6">

2. `DataTransferSize` and `MaxSPDMmsgSize`

Refer to paragraph 233 in [DSP0274_1.2.1]
<img width="599" alt="image" src="https://github.com/DMTF/libspdm/assets/90754803/c08dee82-4163-4cdb-ada0-8b0424a025fb">

Refer to paragraph 237 `GET_CAPABILITIES request message format` in [DSP0274_1.2.1]
<img width="545" alt="image" src="https://github.com/DMTF/libspdm/assets/90754803/9f9a4d49-22d6-471f-bafd-aa0b4fcb3ba5">

Refer to paragraph 238 `Successful CAPABILITIES response message format` in [DSP0274_1.2.1]
<img width="547" alt="image" src="https://github.com/DMTF/libspdm/assets/90754803/b4a5e9b6-1182-462f-83b3-02e34aa8a7f5">

3. If `CHUNK_CAP` not set, `DataTransferSize` and `MaxSPDMmsgSize` are still useful and meaningful? 
a. if yes, 
`DataTransferSize` still shall be **equal to or greater than** `MinDataTransferSize`?
`MaxSPDMmsgSize` still shall be **greater than or equal to** `DataTransferSize`?
b. if no,
just ignore `DataTransferSize` and `MaxSPDMmsgSize`? 

4. But the current code check `DataTransferSize` **must equal** to `MaxSPDMmsgSize` when `CHUNK_CAP` not set.
Does it make sense? if yes, I think the specification should explicitly declare.
https://github.com/DMTF/libspdm/blob/6674aa87c5a3b6991e25e22fcd1bf44e2a111331/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L186-L191

**Comment by steven-bellock** [comment]
That was clarified in 1.3 / 1.2.2. 
![image](https://github.com/DMTF/libspdm/assets/8474235/98d07ed2-b792-4e9e-8320-3711ed5b088a)

**Comment by steven-bellock** [comment]
But yes, even if endpoints do not support chunking the Responder can issue `ResponseTooLarge` if the message is too large for the Requester.
