### ISSUE TITLE
Does LIBSPDM supports Key schedule process?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2162]
I see it supports KEY_EXCHANGE, KEY_UPDATE etc. What about Key schedule?

**Comment by steven-bellock** [comment]
It does support the DMTF key schedule, which is modeled on TLS 1.3.

**Comment by PrakashK94** [comment]
Does Key exchange process covers the key schedule?

**Comment by steven-bellock** [comment]
Yes that is how all the symmetric keys are derived from the shared secret.
