### ISSUE TITLE
libspdm_get_hash_size returns wrong value for sha384 if LIBSPDM_SHA256_SUPPORT is not defined

### ISSUE THREAD

**Issue by DavidPu** [DMTF/libspdm#2164]
There is a typo for 'LIBSPDM_SHA384_SUPPORT':

diff --git a/library/spdm_crypt_lib/libspdm_crypt_hash.c b/library/spdm_crypt_lib/libspdm_crypt_hash.c
index 527783f4c..44f3a2573 100644
--- a/library/spdm_crypt_lib/libspdm_crypt_hash.c
+++ b/library/spdm_crypt_lib/libspdm_crypt_hash.c
@@ -22,7 +22,7 @@ uint32_t libspdm_get_hash_size(uint32_t base_hash_algo)
         return 0;
 #endif
     case SPDM_ALGORITHMS_BASE_HASH_ALGO_TPM_ALG_SHA_384:
-#if LIBSPDM_SHA256_SUPPORT
+#if LIBSPDM_SHA384_SUPPORT
         return 48;
 #else
         return 0;

**Comment by steven-bellock** [comment]
I guess you were the first person to enable SHA384 without SHA256?

**Comment by jyao1** [comment]
@DavidPu , would you please create a PR ? Then we can merge it.

**Comment by DavidPu** [comment]
> @DavidPu , would you please create a PR ? Then we can merge it.

sure. filed PR https://github.com/DMTF/libspdm/pull/2168
