### ISSUE TITLE
Build fails in absence of algorithms

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2165]
For example https://github.com/DMTF/libspdm/blob/c70fc237601628c271e576bca823aec481a35b8a/include/library/spdm_crypt_lib.h#L54-L58
If Integrator does not support AEAD then build will fail. 

Cryptography algorithms should be added to CI/CD.

**Comment by DavidPu** [comment]
There is another build failure in this header file if some asymmetric algorithms are not enabled and the C preprocessor reaches to: https://github.com/DMTF/libspdm/blob/c70fc237601628c271e576bca823aec481a35b8a/include/library/spdm_crypt_lib.h#L41..L43

> spdm/lib/spdm//libspdm/include/library/spdm_crypt_lib.h:41:73: error: operator '||' has no right operand
 #elif ((LIBSPDM_ECDSA_P256_SUPPORT) || (LIBSPDM_SM2_DSA_P256_SUPPORT) ||
                                                                         ^

**Comment by jyao1** [comment]
@DavidPu , that is also fixed in #2179.
