### ISSUE TITLE
TLS1.3 compliance issue w.r.t sequence number handling (AEAD encryption and decryption)

### ISSUE THREAD

**Issue by manishc88** [DMTF/libspdm#2166]
Hi,

Libspdm does not handle sequence number in correct byte order, as per the spec it's encoded in network byte order so it should be handled in the network byte order.

As per TLS1.3 spec section 5.3 (below)

https://datatracker.ietf.org/doc/html/rfc8446#section-5.3

"
The per-record nonce for the AEAD
   construction is formed as follows:

   1.  The 64-bit record sequence number is encoded in network byte
       order and padded to the left with zeros to iv_length.

   2.  The padded sequence number is XORed with either the static
       client_write_iv or server_write_iv (depending on the role).

   The resulting quantity (of length iv_length) is used as the
   per-record nonce.
"

Libspdm reference code -  (file: libspdm_secmes_encode_decode.c)
=============================================

```
libspdm_return_t libspdm_decode_secured_message(
--
--
--
--
    if (sequence_number > 0) {
        data64 = libspdm_read_uint64((const uint8_t *)salt) ^
                 (sequence_number - 1) ^ sequence_number;
        libspdm_write_uint64(salt, data64);
    }
--
--
}
```

As a result the salt/IV produced results to incorrect values which causes failures from device (being as responder)

Thanks,
Manish

**Comment by steven-bellock** [comment]
Interesting. According to [DSP0277](https://www.dmtf.org/sites/default/files/standards/documents/DSP0277_1.1.0.pdf) when the sequence number is transmitted over the wire it's little endian. Regarding the sequence number and the cryptography algorithm
1. Zero extend the sequence number to iv_length according to the selected AEAD cipher suite in
ALGORITHMS messages.
2. Perform a bitwise XOR of the zero-extended sequence number with the appropriate IV derived in the
SPDM key schedule. The sequence number shall be padded with zeros to the left (most significant) to the
size of the IV.

So in SPDM the endianness is implied through
>to the left (most significant)

which looks like big-endian. However the SPDM specification needs to be way more explicit, and not use parentheses `()` to specify endianness. I'll file an issue against the specification.

@jyao1 @xiaoyuruan do you agree?

**Comment by steven-bellock** [comment]
In particular ChaCha is way more explicit:
>AEAD_CHACHA20_POLY1305 requires a 96-bit nonce, which is formed as follows:
>1.  The 64-bit record sequence number is serialized as an 8-byte, big-endian value and padded on the left with four 0x00 bytes.
>2.  The padded sequence number is XORed with the client_write_IV (when the client is sending) or server_write_IV (when the server is sending).

**Comment by jyao1** [comment]
Agree that we need to make it clear. Sigh...

We may use PCI-IDE style with bit definition, it is clear to me

> For each Sub-Stream, per [AES-GCM], there must be a 96b initialization vector IV of deterministic construction, consisting of:
> * a fixed field in **bits 95:64** of the IV, where bits 95:64 are all 0’s
> * an invocation field in **bits 63:0** of the IV, containing the value of a counter, initially set to the value 0000_0001h for each Sub-Stream upon establishment of the Stream and each time the Sub-Stream key is refreshed, and incremented every time an IV is consumed.

**Comment by steven-bellock** [comment]
@manishc88 Thanks for finding this before the 3.0 release. Looks like you are one of the few building a non-libspdm Responder that does key exchange.

**Comment by steven-bellock** [comment]
Relevant OpenSSL code (I think) : https://github.com/openssl/openssl/blob/810f7dc1c7cc5441097b398f753e33652848a4cc/ssl/record/methods/tls_common.c#L2047-L2063

**Comment by jyao1** [comment]
Also openssl-3.0: https://github.com/openssl/openssl/blob/openssl-3.0/ssl/record/ssl3_record_tls13.c#L131-L140.

```
TLS 1.3:
         Seq[0]  (big endian)  Seq[7]
+--------+--------------------------+
| static |                          |
+--------+--------------------------+
Buf[0]   Buf[4]               Buf[11]

IDE:
Seq[0]  (little endian)  Seq[7]
+-----------------------------+--------+
|                             | static |
+-----------------------------+--------+
Buf[0]                   Buf[7]  Buf[11]

Current SPDM: (align with IDE)
Seq[0]  (little endian)  Seq[7]
+-----------------------------+--------+
|                             | static |
+-----------------------------+--------+
Buf[0]                   Buf[7]  Buf[11]

```

**Comment by steven-bellock** [comment]
After discussing this in the SPDM Working Group I think, similar to #2151, we'll support both and allow the Integrator to specify the endianness, with a default to big-endian since that's what's in the specification.

**Comment by jyao1** [comment]
The default one should be current implementation. I dont think we should change.

**Comment by steven-bellock** [comment]
libspdm should faithfully represent the specification and, according to 0277, the sequence number is big-endian and libspdm has a bug.

@bhenning10 and @xiaoyuruan can voice their opinion on what the default endianness should be.

**Comment by steven-bellock** [comment]
Looking at 0277 1.0, the specification does not specify endianness at all. The `padded with zeros to the left (most significant)` was added in 1.1. So as far as 1.0 is concerned the implementers get to choose the endianness.

**Comment by jyao1** [comment]
SPDM WG decides to recommend little endian by default now and enforce little endian later.

**Comment by steven-bellock** [comment]
@manish-chopra-mvl wait for the specifications to be published but... some folks think that the wording in 277 1.1 is still too vague to determine the endianness of the sequence number. So, similar to 1.0, the endianness is whatever you want it to be. For 277 1.2 the plan is to explicitly specify in unambiguous terms, with tables and stuff, the exact layout of the sequence number and how it is incremented, and the encoding will be little endian. But 1.2 hasn't been published yet.

**Comment by jyao1** [comment]
For current version, I think we can do similar thing in https://github.com/DMTF/libspdm/issues/2151. E.g.
```
LIBSPDM_SECURED_SPDM_10_AEAD_BIG_ENDIAN
LIBSPDM_SECURED_SPDM_10_AEAD_DUAL_DECRYPTION
LIBSPDM_SECURED_SPDM_11_AEAD_BIG_ENDIAN
LIBSPDM_SECURED_SPDM_11_AEAD_DUAL_DECRYPTION
```

**Comment by steven-bellock** [comment]
@manish-chopra-mvl @lr-mrvl if you want, feel free to re-discuss this at the next SPDM Working Group meeting, as nothing official has been published yet. The issue is https://github.com/DMTF/SPDM-WG/issues/2945.

**Comment by lr-mrvl** [comment]
Thanks @steven-bellock - we have raised our concerns at https://github.com/DMTF/SPDM-WG/issues/2945

**Comment by steven-bellock** [comment]
I will leave the sequence number at the lower bytes of the IV, even though that's not specified in 1.0.

**Comment by jyao1** [comment]
@manishc88, @lr-mrvl would you please double check https://github.com/DMTF/libspdm/pull/2357 ?

**Comment by lr-mrvl** [comment]
@jyao1  and @steven-bellock - sorry, I did not get a response to this

@steven-bellock - is there a problem in having "both LE BE" as the default ? thanks

**Comment by steven-bellock** [comment]
>is there a problem in having "both LE BE" as the default ?

Probably not. I don't think many Responders care what endianness the Requester is using, so automatically checking shouldn't be too burdensome. @jyao1 are you ok if the default is `encrypt LE / decrypt both`?

**Comment by lr-mrvl** [comment]
Thanks @steven-bellock

**Comment by jyao1** [comment]
I think we had better align the default behavior with 1.2 in the future, that only supports LE.

**Comment by lr-mrvl** [comment]
@jyao1 - sorry, I did not understand. Are u saying we should align and make "both LE BE" as default for requestor ?

**Comment by steven-bellock** [comment]
`LIBSPDM_DATA_SESSION_SEQUENCE_NUMBER_ENDIAN` will be ignored once 277 1.2 is published. Maybe we should add `10_11` like with the signature endianness. But for 1.0/1.1 I think it's fine to automatically support both.

**Comment by jyao1** [comment]
I disagree. I think we should align what we plan to do in 277 1.2 - only support LE as default value.

**Comment by steven-bellock** [comment]
How to resolve this? A public vote in https://github.com/DMTF/libspdm/discussions or a private vote from member companies in the SPDM Working Group? Should probably also bring signature verification to a vote as well, since that's a similar issue.

**Comment by lr-mrvl** [comment]
@steven-bellock I missed out on resolution or discussion to go with LE for 1.2 ? considering 274 refers TLS RFC - I think having requestor try default is preferred for backward compatibility. If one choose to update it for their implementation it is fine. I have logged https://github.com/DMTF/SPDM-WG/issues/3118 to convey preference starting with v1.4

**Comment by steven-bellock** [comment]
According to https://github.com/DMTF/SPDM-WG/issues/2945 277 1.2 will unify everything to LE-only and every SPDM implementation will be on the same page. For 1.0 and 1.1, the question is, for a libspdm endpoint what should its default behavior be when handling endianness. Right now it can be one of
1. Encrypt / decrypt LE only.
    - This is what 1.2 will be.
2. Encrypt with LE. Try to decrypt with LE; if that fails try to decrypt with BE.
3. Encrypt / decrypt BE only.
4. Encrypt with BE. Try to decrypt with BE; If that fails try to decrypt with LE.

The case for 1 being the default is that that is aligned with the future 1.2 specification. The case for 2 or 4 being the default is that this is consistent with 1.0 and its vagueness; 1.0 (and to a certain extent 1.1) doesn't explicitly specify the IV layout so it's up to endpoints to figure it out.

But either way any of those four options are supported in libspdm.
