### ISSUE TITLE
An `ERROR` message with an `ErrorCode == LargeResponse` shall not be allowed in `ResponseToLargeRequest`.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2181]
An `ERROR` message with an `ErrorCode == LargeResponse` **shall not** be allowed in `ResponseToLargeRequest`.

1. Refer to paragraph 696 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).

>  An ERROR message with an ErrorCode == LargeResponse shall not be allowed in ResponseToLargeRequest. 

2. I have submitted one [pull request](https://github.com/DMTF/libspdm/pull/2180) to add unit test for An `ERROR` message with an `ErrorCode == LargeResponse` shall not be allowed in `ResponseToLargeRequest`.

3. Test result is **fail**: Put an `ERROR` message with an `ErrorCode == LargeResponse` in `ResponseToLargeRequest`, currently the requester take this `LargeResponse` ERROR message as a **valid** message and then send `CHUNK_GET` request message.
I think it is not a right behavior, the requester should take it as a **invalid** message.
<img width="668" alt="image" src="https://github.com/DMTF/libspdm/assets/90754803/6a4d3f8b-3d4a-447c-8700-f48582cea77e">

**Comment by steven-bellock** [comment]
This is somewhat related to #1207.

**Comment by Zhiqiang520** [comment]
I think maybe we can add the check whether `ErrorCode == LargeResponse` is in `ResponseToLargeRequest` field, before `libspdm_copy_mem` at the following line 489 and 517.
https://github.com/DMTF/libspdm/blob/675ba03723116a6cc3e4f9eb99c78a4450b9e623/library/spdm_requester_lib/libspdm_req_send_receive.c#L483-L500

https://github.com/DMTF/libspdm/blob/675ba03723116a6cc3e4f9eb99c78a4450b9e623/library/spdm_requester_lib/libspdm_req_send_receive.c#L513-L523
