### ISSUE TITLE
A Responder shall not respond to the `GET_VERSION` request message with `ErrorCode=ResponseNotReady`.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2187]
A Responder **shall not** respond to the `GET_VERSION` request message with `ErrorCode=ResponseNotReady`.

1. Refer to paragraph 213 in [DSP0274_1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf).

> A Responder shall not respond to the GET_VERSION request message with ErrorCode=ResponseNotReady. 

2. So I think:
if the Responder respond to the `GET_VERSION` request message with `ErrorCode=ResponseNotReady`, maybe it is **more accurate** that the requester return `LIBSPDM_STATUS_ERROR_PEER`.  ---`/* Received an unexpected error message. */`
https://github.com/DMTF/libspdm/blob/138af46bffc55c0420ad32288848e8eeeae1e908/include/library/spdm_return_status.h#L108-L110

3. But currently the code behavior is return `LIBSPDM_STATUS_NOT_READY_PEER`. 
https://github.com/DMTF/libspdm/blob/138af46bffc55c0420ad32288848e8eeeae1e908/include/library/spdm_return_status.h#L104-L106

4. The line 648 `LIBSPDM_STATUS_ERROR_PEER `and 661 `LIBSPDM_STATUS_NOT_READY_PEER` are inconsistent in test case `libspdm_test_requester_get_version_err_case8`.
https://github.com/DMTF/libspdm/blob/138af46bffc55c0420ad32288848e8eeeae1e908/unit_test/test_spdm_requester/error_test/get_version_err.c#L647-L662

**Comment by steven-bellock** [comment]
I agree that's a better error code.
