### ISSUE TITLE
`spdm_responder_emu.exe` will `LIBSPDM_ASSERT` when `-DLIBSPDM_SENDER_BUFFER_SIZE=170 -DLIBSPDM_RECEIVER_BUFFER_SIZE=170 -DLIBSPDM_MAX_SPDM_MSG_SIZE=170`.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2207]
`spdm_responder_emu.exe` will `LIBSPDM_ASSERT` when `-DLIBSPDM_SENDER_BUFFER_SIZE=170 -DLIBSPDM_RECEIVER_BUFFER_SIZE=170 -DLIBSPDM_MAX_SPDM_MSG_SIZE=170`.

Verified on the current latest commit https://github.com/DMTF/spdm-emu/commit/5dd34068a580e96e3dc64d10ab35289ad4e35828.
The detail step is as following:

**Step-1**:

> mkdir build_x64_Debug_mbedtls_size_170
cd build_x64_Debug_mbedtls_size_170
cmake -E env CFLAGS="-DLIBSPDM_SENDER_BUFFER_SIZE=170 -DLIBSPDM_RECEIVER_BUFFER_SIZE=170 -DLIBSPDM_MAX_SPDM_MSG_SIZE=170" cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Debug -DCRYPTO=mbedtls ..
nmake copy_sample_key
nmake

**Step-2**:

> cd build_x64_Debug_mbedtls_size_170\bin
spdm_responder_emu.exe

**Step-3**:

> cd build_x64_Debug_mbedtls_size_170\bin
spdm_requester_emu.exe

**Step-4**:
at the end,  `spdm_responder_emu.exe` `LIBSPDM_ASSERT`.
![image](https://github.com/DMTF/spdm-emu/assets/90754803/22f27c21-8820-4855-a8fc-9dfee3dbc570)

**Comment by jyao1** [comment]
Discussed in SPDM WG. It seems we dont want to support the case that cert chain size larger than MaxSPDMmsgSize.
As such, we need to return ResponseTooLarge in this case.

**Comment by steven-bellock** [comment]
@Zhiqiang520 You have misconfigured the Responder. Presumably the certificates are larger than `170 B` and so the Responder is unable to form a response. An assertion is a correct action to a misconfigured endpoint.

**Comment by Zhiqiang520** [comment]
@steven-bellock agree.
