### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#221]
It seems that many file names between the requester/responder are the same. Generally we avoid h/c file collisions because they are in different directories. I’m not so sure this applies to object files though as they may be built into the same directory and have the same name if some client wants to use both the requester and responder.  

When I ported the libspdm to a Windows static library to be finally built as a Windows dll, I ran into problems and had to rename some of the files so their object files would not collide. The VC++ standard project/solution build system normally dumps all object files to a single output dir. I did not see an easy way to change this, so I resolved it by changing the files with the name collision to have “requester” in front of them. 

I think other potential clients may fun into this problem, and was wondering if we should name the files differently, by prepending requester or responder to then.  Example. Instead of “communication.c”, name it “requester_communication.c” and “responder_communication.c”.

**Comment by jyao1** [comment]
Resolve together with https://github.com/DMTF/libspdm/issues/155

**Comment by steven-bellock** [comment]
Resolved by https://github.com/DMTF/libspdm/pull/278
