### ISSUE TITLE
Extended key usage question

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2212]
Based on SPDM spec, Extended key usage field has either id-DMTF-spdm 3/id-DMTF-spdm 4 or both. But I see there are device/leaf certificate present in unit test folder which has these attributes added in for extended key usage like TLS Web Server Authentication, TLS Web Client Authentication, OCSP Signing. May I know why these attributes are added?

**Comment by steven-bellock** [comment]
The SPDM specification defines those OIDs but does not restrict a certificate to only have those OIDs; it's free to have other OIDs. It's possible that some of libspdm's example certificate OIDs don't make sense and we can remove them to make things more clear.
