### ISSUE TITLE
`spdm_responder_emu.exe --ver 1.0` and `spdm_requester_emu.exe --ver 1.1` negotiated fail.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2216]
`spdm_responder_emu.exe --ver 1.0` and `spdm_requester_emu.exe --ver 1.1` negotiated fail.

I think maybe they should select **ver 1.0** as the **common supported version** to continue the capability discovery and negotiation.
Refer to paragraph 241 in [DSP0274_1.3.0](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).

> The Requester shall consult the VERSION response to select a common supported version, which should be the
latest supported common version.

Refer to paragraph 253 `Table 10 — VersionNumberEntry definition` in [DSP0274_1.3.0](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/d005836d-d16c-4252-a189-76a46e5c0abc)

Verified on the current latest commit https://github.com/DMTF/spdm-emu/commit/5dd34068a580e96e3dc64d10ab35289ad4e35828.
The detail step is as following:

**Step-1**:

> mkdir build_x64_Debug_mbedtls
cd build_x64_Debug_mbedtls
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Debug -DCRYPTO=mbedtls ..
nmake copy_sample_key
nmake

**Step-2**:

> cd build_x64_Debug_mbedtls\bin
spdm_responder_emu.exe --ver 1.0

**Step-3**:

> cd build_x64_Debug_mbedtls\bin
spdm_requester_emu.exe --ver 1.1

Then `libspdm_init_connection - 0x80010007`, means `LIBSPDM_STATUS_NEGOTIATION_FAIL`.
![image](https://github.com/DMTF/libspdm/assets/90754803/cce22943-8ef6-45f4-9337-a3471d617ce3)

**Step-4**:
After debugging, I found it return `LIBSPDM_STATUS_NEGOTIATION_FAIL` at the following line 167.
https://github.com/DMTF/libspdm/blob/1c34043d8142ed285ead67eb07d4aa09c8d0a8d8/library/spdm_requester_lib/libspdm_req_get_version.c#L159-L169

**Comment by jyao1** [comment]
That is right behavior. Expected.

What is the issue?

**Comment by Zhiqiang520** [comment]
ok, so both of the requester and the responder should **explicitly** state their supported version, just like the following:

> spdm_responder_emu.exe --ver 1.0
 spdm_requester_emu.exe --ver 1.0
