### ISSUE TITLE
DEBUG macros

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#222]
I noticed the use of DEBUG macro which compiles to _DEBUG then _DEBUG_PRINT. 

debuglib.h
#define _DEBUG_PRINT(PrintLevel, ...)                                          \
               do {                                                                   \
                              debug_print(PrintLevel, ##__VA_ARGS__);                        \
               } while (FALSE)
#define _DEBUG(expression) _DEBUG_PRINT expression

#if !defined(MDEPKG_NDEBUG)
#define DEBUG(expression)                                                      \
               do {                                                                   \
                              _DEBUG(expression);                                            \
               } while (FALSE)
#else
#define DEBUG(expression)
#endif

I think we should use a different name than DEBUG and _DEBUG for debug prints as these seem common enough names that clients may already define this for their platforms. For example, standard Windows builds in VC++ define _DEBUG and NDEBUG to distinguish debug/release builds. 

Since _DEBUG only defines to _DEBUG_PRINT, perhaps we can reduce the 3 macros down to 2 and get rid of _DEBUG. The DEBUG and _DEBUG_PRINT will be good enough and change the name so it is DEBUG_PRINT and DEBUG_PRINT_EX to reduce chance of potential build environment conflict?

Example:

#define DEBUG_PRINT_EX(PrintLevel, ...)                                          \
               do {                                                                   \
                              debug_print(PrintLevel, ##__VA_ARGS__);                        \
               } while (FALSE)

#if !defined(MDEPKG_NDEBUG)
#define DEBUG_PRINT(expression)                                                      \
               do {                                                                   \
                              DEBUG_PRINT_EX(expression);                                            \
               } while (FALSE)
#else
#define DEBUG_PRINT(expression)
#endif

**Comment by steven-bellock** [comment]
Voted to close at 6-Dec-2021 meeting.
