### ISSUE TITLE
LIBSPDM builds in linux generates static library

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2224]
Is it possible to tweak the make file and generates the dynamic library instead of static library in libspdm/build/lib folder?

**Comment by jyao1** [comment]
feel free to create a PR.

**Comment by PrakashK94** [comment]
I was able to do this by replacing STATIC keyword with SHARED keyword in make file.

**Comment by steven-bellock** [comment]
@PrakashK94 Do you want to make a pull request, or are you ok with your local changes?

**Comment by PrakashK94** [comment]
Local changes is fine.
