### ISSUE TITLE
GET_CSR/SET_CERTIFICATE process against SPDM certificate chain models

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#2227]
Hi team,
If device is in **AliasCert Model**, what type would the public key in CSR response be for CA signing (device public key or alias public key)?

1. If it is the device public key, dose it suggest CA on requester side will generate the certificate chain ends with the device certificate, and it then falls on device's responsibility to generate the alias certificate and append to the chain after SET_CERTIFICATE?
2. If it is the alias public key, how the CA on reqeuster side to know the device certificate and its private key? The device private kay is to issue the alias certificate and the device certificate should be the preceding of alias certificate in the complete certificate chain.

I tend to believe it should be 1, but the specification has no clear description about this.
I also looked through libspdm and spdm-emu code, there seems no GET_CSR then SET_CERTIFICATE joint use case, the certificate chain data for SET_CERTIFICATE all come from `libspdm_read_responder_public_certificate_chain` which reads ready-made bundle of chain from sample_key for testing.

Would you help to confirm this?
Thanks.

**Comment by steven-bellock** [comment]
As far as the specification is concerned it could be 1 or 2. In reality though it will be 1. 

For spdm-emu / libspdm, if the device is in AliasCert mode then they could generate the leaf certificate on-the-fly to emulate something like DICE. Feel free to file a separate issue if you think that's valuable.

**Comment by xiangfeima** [comment]
Thanks @steven-bellock for shareing the opnion. It is enough to me for now.
