### ISSUE TITLE
Secure message support for application data (SPDM 1.1.2)

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2230]
![image](https://github.com/DMTF/libspdm/assets/36578776/dd7d940c-6c85-4306-bf6a-f45f16d26c22)

**Comment by goutham23** [comment]
I'm in the middle of adding support for the secured messages (encryption and MAC), calculated all the secret keys, completing implementing KEY_EXCHANGE, and FINISH RSP (SPDM Responder).

To start with, I'm only adding support to decode the message received and encode, and send the response back to the requester.

Here the message is just application data (not supporting SPDM CMD in a secure session for now)
Can you please help me understand 
1)what application data (message blob) can REQUESTER send? 
2)what the responder can decode, and save the plain text and what does the responder needs to encode and send the response

Or an practical usage where the requester sends application data and what does the responder do after decoding the meesage.

Thanks in advance

**Comment by goutham23** [comment]
![image](https://github.com/DMTF/libspdm/assets/36578776/b2316000-f23c-4921-aab0-dd6b18b45618)


Does that mean the only application data (message) that REQUESTER can encode and send the responder in the SESSION will be the one highlighted in yellow?

Requester cannot just send a random data (Let say "abcdgsjkghurbvonroeiveo" as plain text) use this as a message, encode and send it RESPONDER??

**Comment by jyao1** [comment]
You can send SPDM vendor defined message (e.g. IDE_KM or TDISP defined in PCI-SIG), or PMCI message (e.g. PLDM).

**Comment by goutham23** [comment]
Thanks for the quick response, @jyao1 - Can you answer this - "Does that mean the only application data (message) that REQUESTER can encode and send the responder in the SESSION will be the one highlighted in yellow"

Refer the above figure for the context

**Comment by jyao1** [comment]
> Does that mean the only application data (message) that REQUESTER can encode and send the responder in the SESSION will be the one highlighted in yellow

No.
In this table, you can find lots of other SPDM command, such as "GET_MEASUREMENT", "HEARTBEAT", etc. They can be sent.
In this table, "All other" == "All other SPDM command defined in this spec".

NOTE: "All other" != "All other application data", because the definition of "application data" is out of scope.

**Comment by goutham23** [comment]
Thanks
