### ISSUE TITLE
Follow comment and disable time checks for OpenSSL PK checking

### ISSUE THREAD

**Issue by alistair23** [DMTF/libspdm#2237]
https://github.com/DMTF/libspdm/pull/2235

**Comment by steven-bellock** [comment]
I would say either disable the check or allow enabling/disabling by the Integrator. In most cases there will be a Verifier which will do a thorough job of examining the certificate chain.

**Comment by jyao1** [comment]
7/17/2023: This check is in cryptolib, not libspdm.
1) we need make it consistent between openssl and mbedtls.
2) we can make it configurable, such as a MACRO. It will be crypto lib specific (`mbedtls/config.h`), not in `spdm_lib_config.h`.

It could be documentation to inform people how to change MACRO.

**Comment by alistair23** [comment]
> 1. we need make it consistent between openssl and mbedtls.

There isn't the same easy way to disable the check in mbedtls. The only way I can figure out how to do this is by modifying mbedtls directly which we don't want to do

> 2\. we can make it configurable, such as a MACRO. It will be crypto lib specific (`mbedtls/config.h`), not in `spdm_lib_config.h`.

I'm happy to make it configurable, is it ok if it's configurable just for OpenSSL though?

**Comment by jyao1** [comment]
> There isn't the same easy way to disable the check in mbedtls. The only way I can figure out how to do this is by modifying mbedtls directly which we don't want to do

You can modify the `MBEDTLS_HAVE_TIME_DATE` in [`mbedtls/config.h`](https://github.com/DMTF/libspdm/blob/main/os_stub/mbedtlslib/include/mbedtls/config.h#L164)

**Comment by alistair23** [comment]
Thanks! Sorry I missed that in your first comment
