### ISSUE TITLE
[SPDM 1.1.2 version] - Requester/Responder-direction data secret

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2253]
From the Spec..
Requester-direction data secret
This secret shall be used for any data transmitted during the application phase of the session. This secret shall only
be applied for all data traveling from the Requester to the Responder.

I'm implementing the responder code and calculated all the keys (Handhsake, data, Encryption, IV , Master..keys)..
Encryption and IV will be used by AEAD for encryption/decryption which is clear to me...

Questions:
1)When do we actually use the calculated Requester-direction data secret and  Responder-direction data secret?

2)After Finish_RSP is sent to the requester, now the requester send the first message (GET_MEasuremnt cmd) encrypted in secure session, per my understanding requester will use the Encryption_key and IV to encrypt and Responder uses the same Emcryption_key and IV to decrypt... and respnder will send the GET_MEASUREMT response encrypted using the same Emcryption_key and IV to encrypt and send to requester in secure session - Is my understanding correct?

**Comment by steven-bellock** [comment]
>When do we actually use the calculated Requester-direction data secret and Responder-direction data secret?

You use the keys / IVs derived from the data secrets when sending data and SPDM messages in a secure session.

>Is my understanding correct?
No. When sending from Requester to Responder the Requester will encrypt with the key derived from the request-direction data secret. When sending from Responder to Requester the Responder will encrypt with the key derived from the response-direction data secret.

**Comment by goutham23** [comment]
@steven-bellock 

For each key schedule major secret, the following function shall be applied to obtain the encryption key and IV value.
EncryptionKey = HDKF-Expand(major-secret, bin_str5, key_length);
IV = HKDF-Expand(major-secret, bin_str6, iv_length);

When do we use the EncryptionKey?


If "When sending from Requester to Responder the Requester will encrypt with the key derived from the request-direction data secret. - Then in this case encryption_key is the request-direction data secret key for AEAD_encrypt when we send from requester??
encryption_key = request-direction data secret_key - I'm confused, sorry

AEAD_Encrypt(encryption_key, nonce, associated_data, plaintext);

**Comment by steven-bellock** [comment]
> Is my understanding correct?

Yes, it is.

**Comment by goutham23** [comment]
Thanks
