### ISSUE TITLE
LIBSPDM build issue in windows

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2267]
I used VS2019 to build LIBSPDM code. But gets this build issue? Could anyone suggest what be the cause for this build issue?

MT: command "C:\PROGRA~2\WINDOW~4\10\bin\100190~1.0\x64\mt.exe /nologo /manifest ..\..\..\..\bin\test_spdm_requester_negotiate_algorithms.exe.manifest /outputresource:..\..\..\..\bin\test_spdm_requester_negotiate_algorithms.exe;#1" failed (exit code 0x1f) with the following output:

mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "..\..\..\..\bin\test_spdm_requester_negotiate_algorithms.exe". The process cannot access the file because it is being used by another process.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by jyao1** [comment]
It seems your env issue.

Can you try to rebuild, or reinstall it?

**Comment by PrakashK94** [comment]
It build. Thanks.
