### ISSUE TITLE
`Param2` of `PSK_EXCHANGE request message` was mistaken as `Param1` in code.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2268]
`Param2` of `PSK_EXCHANGE request message` was mistaken as `Param1` in code.

1. `Param1` of `PSK_EXCHANGE request message` is `Type of measurement summary hash requested`.
Refer to paragraph 542 `Table 63 — PSK_EXCHANGE request message format` in [DSP0274_1.3.0](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/fd5f86b0-187a-4f11-a356-2f598d62811d)

2. But `Param2` of `PSK_EXCHANGE request message` was mistaken as `Param1` at the following line 323.
https://github.com/DMTF/libspdm/blob/bb04e135880a005ffeba6c3f9df8bd458c8b6eee/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L322-L328

**Comment by Zhiqiang520** [comment]
I will take this.

**Comment by steven-bellock** [comment]
That entire check can be removed. Not sure why it's there.
If `param1` is `0` then `measurement_summary_hash_size` is `0`.
https://github.com/DMTF/libspdm/blob/bb04e135880a005ffeba6c3f9df8bd458c8b6eee/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L197-L198 https://github.com/DMTF/libspdm/blob/bb04e135880a005ffeba6c3f9df8bd458c8b6eee/library/spdm_common_lib/libspdm_com_crypto_service.c#L1150-L1173

In addition libspdm should not be calling `libspdm_generate_measurement_summary_hash` if the Requester doesn't want it.

**Comment by Zhiqiang520** [comment]
> That entire check can be removed.

I don't think so, I think the entire check is useful.
If `param1` is equal to **one illegal value**, for example  `param1`= `0x50`, then `measurement_summary_hash_size` is 0, then  libspdm should return error `SPDM_ERROR_CODE_INVALID_REQUEST`.

**Comment by steven-bellock** [comment]
That's a roundabout way to do it, but that error should be returned much sooner. In particular libspdm is calling `libspdm_generate_measurement_summary_hash` with a potentially illegal `param1` value. That should be validated by libspdm before handing it over to the Integrator.

**Comment by Zhiqiang520** [comment]
> That's a roundabout way to do it, but that error should be returned much sooner. In particular libspdm is calling `libspdm_generate_measurement_summary_hash` with a potentially illegal `param1` value. That should be validated by libspdm before handing it over to the Integrator.

The solution is:
first,  correct `(spdm_request->header.param2 != SPDM_CHALLENGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH)) {` to `(spdm_request->header.param1 != SPDM_CHALLENGE_REQUEST_NO_MEASUREMENT_SUMMARY_HASH)) {` at line 323.
second,  move the entire check at line 322~327 to the front, between line 198 and 199, then that error will be returned much sooner.
https://github.com/DMTF/libspdm/blob/bb04e135880a005ffeba6c3f9df8bd458c8b6eee/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L309-L327
https://github.com/DMTF/libspdm/blob/bb04e135880a005ffeba6c3f9df8bd458c8b6eee/library/spdm_responder_lib/libspdm_rsp_psk_exchange.c#L197-L199
