### ISSUE TITLE
Question about RespAlgStruct in response of NEGOTIATE_ALGORITHMS (libspdm\library\spdm_responder_lib\libspdm_rsp_algorithms.c)

### ISSUE THREAD

**Issue by YangYunLong1988** [DMTF/libspdm#2274]
Hi,

I check the respond message of NEGOTIATE_ALGORITHMS, I capture the code here for reference:

line 495:
    _spdm_response->struct_table[0].alg_type = SPDM_NEGOTIATE_ALGORITHMS_STRUCT_TABLE_ALG_TYPE_DHE;
    spdm_response->struct_table[0].alg_count = 0x20;
    spdm_response->struct_table[0].alg_supported = (uint16_t)libspdm_prioritize_algorithm(
        dhe_priority_table, LIBSPDM_ARRAY_SIZE(dhe_priority_table),
        spdm_context->local_context.algorithm.dhe_named_group,
        spdm_context->connection_info.algorithm.dhe_named_group);

    spdm_response->struct_table[1].alg_type = SPDM_NEGOTIATE_ALGORITHMS_STRUCT_TABLE_ALG_TYPE_AEAD;
    spdm_response->struct_table[1].alg_count = 0x20;
    spdm_response->struct_table[1].alg_supported = (uint16_t)libspdm_prioritize_algorithm(
        aead_priority_table, LIBSPDM_ARRAY_SIZE(aead_priority_table),
        spdm_context->local_context.algorithm.aead_cipher_suite,
        spdm_context->connection_info.algorithm.aead_cipher_suite);

    spdm_response->struct_table[2].alg_type =
        SPDM_NEGOTIATE_ALGORITHMS_STRUCT_TABLE_ALG_TYPE_REQ_BASE_ASYM_ALG;
    spdm_response->struct_table[2].alg_count = 0x20;
    spdm_response->struct_table[2].alg_supported = (uint16_t)libspdm_prioritize_algorithm(
        req_asym_priority_table,
        LIBSPDM_ARRAY_SIZE(req_asym_priority_table),
        spdm_context->local_context.algorithm.req_base_asym_alg,
        spdm_context->connection_info.algorithm.req_base_asym_alg);

    spdm_response->struct_table[3].alg_type =
        SPDM_NEGOTIATE_ALGORITHMS_STRUCT_TABLE_ALG_TYPE_KEY_SCHEDULE;
    spdm_response->struct_table[3].alg_count = 0x20;
    spdm_response->struct_table[3].alg_supported = (uint16_t)libspdm_prioritize_algorithm(
        key_schedule_priority_table,
        LIBSPDM_ARRAY_SIZE(key_schedule_priority_table),
        spdm_context->local_context.algorithm.key_schedule,
        spdm_context->connection_info.algorithm.key_schedule);_

May i know why we need **struct_table** since already have BaseAsymAlgo/BaseHashAlgo ? and Does responder must support algorithms in this RespAlgStruct ? I couldn't find how to disable them except delete code.

Background: The MCU in my project only support Hash function.

**Comment by jyao1** [comment]
> May i know why we need struct_table since already have BaseAsymAlgo/BaseHashAlgo 

Please check SPDM spec. It defines more algorithms such as DHE, AEAD, etc.

> Does responder must support algorithms in this RespAlgStruct ?

No. If responder does not support all the algos defined in struct_table, it can be absent.

**Comment by YangYunLong1988** [comment]
Thank you for your quick response, Bellock,Jiewen.

Yes, That's is what i try to enable（unsigened measurement）.

**Comment by steven-bellock** [comment]
@YangYunLong1988 If this answered your question please close the issue.

**Comment by YangYunLong1988** [comment]
Question answered.
