### ISSUE TITLE
sequence number in secured message format

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2278]
Hello,

I'm implementing Responder SPDM 1.1.2 secure session, planning to support only application data which is in-0session SPDM message like GET_MEASUREMENT, HEARTNEAT and END_SESSION

From the spec DSP277, sequence number field is marked as "NO" in the recommendation column of Secured Message fields definition. Does that mean I can completely avoid this field (as I don't see any usage) or better to allocate 2 bytes and assign value "ZERO"... 

session_id = 4 bytes
sequence_num = 0 bytes (or should I allocate 2 bytes and assign"ZERO")
length = 2 bytes

From the code: spdm_secured_message.h
/* The length of sequence_number between HEADER_1 and HEADER_2 is transport specific.*/

I see in the code you have allocated UINT64_t and assigned zero, never used anywhere to increment the value..

**Comment by steven-bellock** [comment]
What transport are you using underneath 277? That will tell you what the size of the partial sequence number is. For example MCTP says that it's two bytes.

**Comment by goutham23** [comment]
MCTP = transport
1) Can you point me to where in the code/doc it says 2 bytes for MCTP transport
2)In the above case, where application data is in-session SPDM messages like GET_MEASUREMENT, HEARTBEAT and END_SESSION - How does the sequence number fit in this case?

**Comment by steven-bellock** [comment]
https://www.dmtf.org/sites/default/files/standards/documents/DSP0276_1.1.0.pdf says 
>The Partial Sequence Number field is the Sequence Number field described in DSP0277. The Partial Sequence
Number field shall be two bytes in length and shall contain the lower 16 bits of the Sequence Number. The field
presence requirement for Partial Sequence Number shall always be present for Encryption and Message
Authentication or Message Authentication Only sessions.

>In the above case, where application data is in-session SPDM messages like GET_MEASUREMENT, HEARTBEAT and END_SESSION - How does the sequence number fit in this case?

Sequence number is used to construct the IV used by the AEAD algorithm. Note that 274 shows how to derive an "IV" but that's really an IV mask or salt.

**Comment by goutham23** [comment]
Sequence number is used to construct the IV used by the AEAD algorithm. Note that 274 shows how to derive an "IV" but that's really an IV mask or salt.

I'm still trying to digest this :)
I have the IV calculated per 274, and will be using AES 256-bit GCM as AEAD cipher, could not see anywhere mentioning about "Sequence number is used to construct the IV used by the AEAD algorithm"

I'm missing anyhting? or it there any other doc that I need to refer to other than 274, 277, 276...

**Comment by steven-bellock** [comment]
From 277:
![image](https://github.com/DMTF/libspdm/assets/8474235/61c3d2fe-a19b-4937-b3ae-9357debb4b2d)

**Comment by goutham23** [comment]
Thanks

**Comment by goutham23** [comment]
I got the answer for this, will close the issue
