### ISSUE TITLE
Error response structure for case : SPDM_ERROR_CODE_DECRYPT_ERROR

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2300]
Implementing responder side... "Secured Messages using SPDM over MCTP"

Let's assume libspdm_decode_secured_message() API returned libspdm_decode_secured_message as spdm_error.error_code

And in the libspdm_build_response you are generating error response
witch (context->last_spdm_error.error_code) {
        case SPDM_ERROR_CODE_DECRYPT_ERROR:
            /* session ID is valid. Use it to encrypt the error message.*/
            if((context->handle_error_return_policy &
                LIBSPDM_DATA_HANDLE_ERROR_RETURN_POLICY_DROP_ON_DECRYPT_ERROR) == 0) {
                status = libspdm_generate_error_response(
                    context, SPDM_ERROR_CODE_DECRYPT_ERROR, 0,
                    &my_response_size, my_response);
                   

In libspdm_generate_error_response() API , you are setting as 
spdm_response->header.request_response_code = SPDM_ERROR;  /0x7f

And in mctp_encode_message, add msg_type as MCTP_MESSAGE_TYPE_SECURED_MCTP

Is this the correct order to follow if I'm sending error code SPDM_ERROR_CODE_DECRYPT_ERROR to requester.

**Comment by jyao1** [comment]
right

**Comment by goutham23** [comment]
Let's assume the handshake phase is established (FINISH_RSP successful), the requester sent GET_MEASUREMT as application data in a secure session( my understanding is this is a valid use case of a secure session)

Now for some reason reponder while decoding this app data we hit the error "SPDM_ERROR_CODE_DECRYPT_ERROR", not responder will send this error code back to requester...

So this will be |MCTP_1byte: 0x6| and then followed by spdm error structure which libspdm_generate_error_response will populate ---- Is this correct?

or does requester expects error message also to be encrypted and sent in the secure session?

**Comment by jyao1** [comment]
If the session ID is valid, then the error message will be encrypted.

**Comment by goutham23** [comment]
Can you point me to the code/test_case where the responder sends an error message as encrypted

**Comment by goutham23** [comment]
@jyao1 

In the API - libspdm_transport_mctp_decode_message, I feel its confusing to understand the meaning of below comments
/* Secured message to APP message*/ -->?
/* APP message to SPDM message.*/-->?


/* get non-secured message*/ --> This is clear, we received a non-secured SPDM message to decode

**Comment by goutham23** [comment]
@jyao1 - Its not very clear for me, cna you point me to the code where this "If the session ID is valid, then the error message will be encrypted" is handled .

THanks in advance
