### ISSUE TITLE
SPDM vs secured SPDM vs secured APP message

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2301]
From the comments...libspdm_transport_mctp_encode_message API definition

For normal SPDM message, it adds the transport layer wrapper.
 For secured SPDM message, it encrypts a secured message then adds the transport layer wrapper.
For secured APP message, it encrypts a secured message then adds the transport layer wrapper.

I understand normal SPDM is like GET_VERSION, GET_DIGEST... secured SPDM message is like GET_MEASUREMNT, HEARTBEAT in an secure session, but could not understand secured APP message..
Can you give me an example of a secured APP message? What is an APP message here int his context?

**Comment by jyao1** [comment]
Secure/Encrypted PLDM message

**Comment by goutham23** [comment]
If I don't plan to support PLDM, then I can ignore secured APP code in libspdm?

**Comment by jyao1** [comment]
PLDM is just one example.
In general, you can ignore it, if it is not applicable in your use case.

**Comment by steven-bellock** [comment]
App message is effectively anything that is a non-SPDM message.

**Comment by goutham23** [comment]
Thank you both!!
