### ISSUE TITLE
Message Transcript appending when request message error is encountered

### ISSUE THREAD

**Issue by tmarkey64** [DMTF/libspdm#2303]
The libSPDM responder library does not append to the message transcript when an error is encountered in the request.  I can't find anywhere where this is the specified behavior in the SPDM specification.

**Comment by steven-bellock** [comment]
L1/L2 says
>An error response with ErrorCode=ResponseNotReady shall not re-initialize L1/L2 - Requester and
Responder shall continue to construct L1/L2 with GET_MEASUREMENTS and MEASUREMENTS . An error
response with any error code other than ResponseNotReady shall re-initialize L1/L2 to null.

so for that most errors just reset the transcript. Note that this is a bug in the 1.2 specification. `LargeResponse` should not reset L1/L2. It will be clarified in 1.2.2 and 1.3.1.

M1/M2 says
>If a response contains an ErrorCode other than ResponseNotReady :
No concatenation function is performed on the contents of both the original request and response.

so the errors are ignored in the transcript. It looks like `CHALLENGE_AUTH` could be chunked, and so `LargeResponse` applies there as well. I'll file an issue against the specification for that.

For key exchange transcripts they are all explicitly laid out. For example
>Transcript for FINISH signature, mutual authentication
1. VCA
2. Hash of the specified certificate chain in DER format (that is, Param2 of KEY_EXCHANGE ) or hash of the
public key in its provisioned format, if a certificate is not used.
3. [KEY_EXCHANGE] . *
4. [KEY_EXCHANGE_RSP] . *
5. Hash of the specified certificate chain in DER format (that is, Param2 of FINISH ) or hash of the public key
in its provisioned format, if a certificate is not used.
6. [FINISH] . SPDM Header Fields

Maybe there should be additional normative text that says that errors don't contribute to those transcripts.

**Comment by steven-bellock** [comment]
> It looks like CHALLENGE_AUTH could be chunked, and so LargeResponse applies there as well. I'll file an issue against the specification for that.

Upon re-reading that the specification is fine; no need to clarify things. However it sounds like it would help to have a blanket
>Unless otherwise specified, if a request results in an `ERROR` response neither the request nor the response shall be included in the transcript.

in the "Transcript and transcript hash calculation rules" section.

**Comment by tmarkey64** [comment]
Thanks Steven, this is all very helpful.

**Comment by steven-bellock** [comment]
@tmarkey64 If this answered your question please close this issue.

**Comment by tmarkey64** [comment]
@steven-bellock, yes it did.  Thanks.
