### ISSUE TITLE
Per-message nonce derivation - Secure session

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2305]
From 277..
4.2.3 Per-message nonce derivation
The nonce shall never be transmitted in Secured Messages. This means that both the Responder and Requester must
internally track the nonce. To ensure proper tracking, the Requester and Responder shall follow the nonce derivation
schedule laid henceforth.
Before the creation of the first Secured Message in the session for a given major secret and its derived encryption
and IV keys, both the Responder and Requester shall start with a 64-bit sequence number with a value of zero. For
each record, both SPDM endpoints shall follow these steps as prescribed:
    1. Zero extend the sequence number to iv_length according to the selected AEAD cipher suite in
           ALGORITHMS messages.
   2. Perform a bitwise XOR of the zero-extended sequence number with the appropriate IV derived in the
      SPDM key schedule.
         ◦ The output of this step is called the per-message nonce.
   3. Increment the sequence number by a value of one for the next Secured Message.

Because different secrets are used for different directions of data transmission, each endpoint would have to track
two sequence numbers: one for the reception and the other for the transmission.

QUESTION:
1) For MCTP transport, sequence number size is 2 bytes and from the above context "both the Responder and Requester shall start with a 64-bit sequence number with a value of zero" - should this be 16-bit sequence number with a value of zero in my case?

2) From the above context,  each endpoint would have to track two sequence numbers: one for the reception and the other for the transmission- I on;y see one instant of "response_data_sequence_number" for both transmission and reception in the libspdm code

3) Also in my case, will be initializing max_spdm_session_sequence_number =- 0xFFFF , instead of 0xFFFFFFFF per libspdm, is this correct?

**Comment by steven-bellock** [comment]
> For MCTP transport, sequence number size is 2 bytes and from the above context "both the Responder and Requester shall start with a 64-bit sequence number with a value of zero" - should this be 16-bit sequence number with a value of zero in my case?

For MCTP, the partial sequence number that is sent between endpoints in `Secured Message fields definition` is 16 bits. The sequence number that is used for AEAD operations is 64 bits.

>From the above context, each endpoint would have to track two sequence numbers: one for the reception and the other for the transmission- I only see one instant of "response_data_sequence_number" for both transmission and reception in the libspdm code

libspdm uses `request_data_sequence_number` and `response_data_sequence_number`.

>Also in my case, will be initializing max_spdm_session_sequence_number =- 0xFFFF , instead of 0xFFFFFFFF per libspdm, is this correct?

MCTP does not define the maximum number of messages that can be encrypted with a key. That is a security policy of either the device or the platform. Note that the amount of data, in bytes, is a better measure of when to update the key or end the session, but libspdm currently does not support that.

**Comment by goutham23** [comment]
In the code, libspdm_decode_secured_message()
request_data_sequence_number this will get incremented only if "is_requester" flag is set, which means if you are calling this API as a responder it will never get used, right?

Also in the code, for per-message nonce calculation
data64 = libspdm_read_uint64((const uint8_t *)salt) ^ (sequence_number - 1) ^ sequence_number;
I could not follow why this logic is needed "(sequence_number - 1) ^ sequence_number"
Can you help break the logic here?


older version of libspdm has this calculation which is simple to understand..
*(uint64_t *)salt = *(uint64_t *)salt ^ sequence_number;

**Comment by steven-bellock** [comment]
>request_data_sequence_number this will get incremented only if "is_requester" flag is set, which means if you are calling this API as a responder it will never get used, right?

That does look weird. 

Encode : https://github.com/DMTF/libspdm/blob/c7c7f7fbc3d16cccd6eaaeda8ec196bbf0998b48/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c#L150-L156 
Decode :
https://github.com/DMTF/libspdm/blob/c7c7f7fbc3d16cccd6eaaeda8ec196bbf0998b48/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c#L422-L428

@jyao1 @Wenxing-hou Why, when the Requester decodes a response does it use the `request_data_sequence_number` instead of the `response_data_sequence_number`? Is this a bug?

**Comment by jyao1** [comment]
Currently the requester use `false` for context->transport_decode_message().

https://github.com/DMTF/libspdm/blob/main/library/spdm_requester_lib/libspdm_req_send_receive.c#L188-L190

So, it works.

**Comment by steven-bellock** [comment]
> Currently the requester use false for context->transport_decode_message().

That is a bug in either the name of the parameter or the functions themselves. 

`* @param  is_requester            Indicates if it is a requester message.`

`is_requester` should specify whether an endpoint is a Requester or Responder, not the message type. If we don't want to change the functions then the parameter should be renamed to `is_request_message`.

**Comment by jyao1** [comment]
Agree it is a bug. Good suggestion for renaming.

**Comment by jyao1** [comment]
> data64 = libspdm_read_uint64((const uint8_t *)salt) ^ (sequence_number - 1) ^ sequence_number;

`Salt` means the previous AEAD nonce.
`Salt ^ (sequence_number - 1)` means the original AEAD IV - derived in SPDM key scheduling process.
`Salt ^ (sequence_number - 1) ^ sequence_number` means the current AEAD nonce.

I think we may add comment in the code to clarify.

**Comment by steven-bellock** [comment]
>I think we may add comment in the code to clarify.

#1980 is the issue.

**Comment by goutham23** [comment]
@jyao1 

Salt means the previous AEAD nonce.
Salt ^ (sequence_number - 1) means the original AEAD IV - derived in SPDM key scheduling process.
Salt ^ (sequence_number - 1) ^ sequence_number means the current AEAD nonce.

Lets assume we are using AEAD AES 256-bit GCM.. 
IV (salt) calculated per KEY-schedule will be 12bytes data (IV length for AES 256-bit GCM is 12 bytes)

In the above code,
sequence number is UINT64 which is 8 bytes..
assume the sequence number is 8... and salt = {1,2,3,4,5,6,7,8,9,10,11,12}

then, libspdm_read_uint64((const uint8_t *)salt) ^  (sequence_number - 1) = How does this becomes original AEAD IV, derived in key scheduling process ?? (Dint the value changed after XOR)

**Comment by jyao1** [comment]
> then, libspdm_read_uint64((const uint8_t *)salt) ^ (sequence_number - 1) = How does this becomes original AEAD IV, derived in key scheduling process ?? (Dint the value changed after XOR)

The following line is `libspdm_write_uint64(salt, data64);`. It patches the salt.
