### ISSUE TITLE
About Certificate Verifying

### ISSUE THREAD

**Issue by xityp** [DMTF/libspdm#2316]
In function 
```
bool libspdm_verify_certificate_chain_buffer(uint32_t base_hash_algo, uint32_t base_asym_algo,
                                             const void *cert_chain_buffer,
                                             size_t cert_chain_buffer_size,
                                             bool is_requester_cert,
                                             bool is_device_cert_model)
```

There is a offset modification:

```
cert_chain_data = (const uint8_t *)cert_chain_buffer + sizeof(spdm_cert_chain_t) + hash_size;
cert_chain_data_size = cert_chain_buffer_size - sizeof(spdm_cert_chain_t) - hash_size;
```

    if (!libspdm_x509_get_cert_from_cert_chain(
            cert_chain_data, cert_chain_data_size, 0, &first_cert_buffer,
            &first_cert_buffer_size)) {
        LIBSPDM_DEBUG((LIBSPDM_DEBUG_INFO,
                       "!!! VerifyCertificateChainBuffer - FAIL (get root certificate failed)!!!\n"));
        return false;
    }
 

When I test a device SPDM function using SPDM-EMU, there is a error because certificate verification failed. 
If remove the offset modification operation, certificate verifying is OK.
    Is this offset  for test? because SPDM specification has no this structure. 

thanks for your help

**Comment by jyao1** [comment]
> When I test a device SPDM function using SPDM-EMU, there is a error because certificate verification failed.

Could you please describe how you trigger the error?
The https://github.com/DMTF/spdm-emu CI shows it can pass the communication.

**Comment by steven-bellock** [comment]
>because SPDM specification has no this structure.

Sure it does. That has been there since the 1.0 specification.
![image](https://github.com/DMTF/libspdm/assets/8474235/6a5efe4a-40b3-4133-9896-ab33375daf01)

**Comment by xityp** [comment]
@steven-bellock ，SPDM spec version 1.0.0 describe Table 19 — Successful CERTIFICATE response message
![image](https://github.com/DMTF/libspdm/assets/30803543/71b8b4b6-7fb9-4455-9813-dba7fb2c20d6)

that is to say,  spdm responder should construct {length; Reserved;RootHash;Certificates} struct as certificate response message CertChain field, not just putting .der format certificates file in certChain field?

**Comment by steven-bellock** [comment]
>not just putting .der format certificates file in certChain field?

Correct. The newer specifications, including 1.0.1, are more clear. Please don't read 1.0.0. 😄 
![image](https://github.com/DMTF/libspdm/assets/8474235/793d7e7d-d64f-44e7-bf76-93cefcd94b1b)
