### ISSUE TITLE
SPDM secure session error response

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2317]
Let's say the SPDM requester sent an SPDM message  (app message) in a secure session.

On the responder, we hit an error while decoding the message and set the error as DECRYPT_ERROR
Now, since the session id is valid we will be sending this error response encoded

Now while encoding this error response, if let's say spdm_encode _message hit an error then what will be the format of the error response sent to the requester (since the encoding failed)

**Comment by goutham23** [comment]
@steven-bellock @jyao1 - Thanks in advance for the help!!

**Comment by jyao1** [comment]
> Now while encoding this error response, if let's say spdm_encode _message hit an error then what will be the format of the error response sent to the requester (since the encoding failed)

No message will be sent to the requester in this case.

**Comment by goutham23** [comment]
Thanks
