### ISSUE TITLE
SEQUENCE OF and SEQUENCE for "id-DMTF-hardware-identity"

### ISSUE THREAD

**Issue by rioone2023** [DMTF/libspdm#2325]
In the sample certificates for unit_test, such as end_responder1.cert.der, where "id-DMTF-hardware-identity" is implemented as follows
[https://github.com/DMTF/libspdm/blob/main/unit_test/sample_key/ecp384/end_responder1.cert.der](url)

<pre>
$ openssl asn1parse -in ./end_responder1.cert.der -dump -inform DER -strparse 436
    0:d=0  hl=2 l=  26 cons: SEQUENCE
    2:d=1  hl=2 l=  10 prim: OBJECT            :1.3.6.1.4.1.412.274.6
   14:d=1  hl=2 l=  12 prim: OCTET STRING
      0000 - 06 0a 2b 06 01 04 01 83-1c 82 12 02               ..+.........
$ openssl asn1parse -in ./end_responder1.cert.der -dump -inform DER -strparse 450
    0:d=0  hl=2 l=  10 prim: OBJECT            :1.3.6.1.4.1.412.274.2
</pre>

Doesn't it require SEQUENCE OF and SEQUENCE as defined in SPDM v1.2?

<pre>
id-DMTF-spdm-extension Extension ::=
{
	extnID { id-DMTF-spdm 6 }
	critical FALSE
	extnValue id-spdm-cert-oids
}
id-spdm-cert-oids ::= SEQUENCE SIZE (1..MAX) OF id-spdm-cert-oid
id-spdm-cert-oid ::= SEQUENCE
{
	spdmOID OBJECT IDENTIFIER
	spdmOIDdefinition OCTET STRING OPTIONAL
}

id-DMTF-hardware-identity id-spdm-cert-oid :: = {
	spdmOID { id-DMTF-spdm 2 }
	spdmOIDdefinition ABSENT
}
</pre>

**Comment by Wenxing-hou** [comment]
The generated cert does have the format error.  I will fix it. Thanks!

**Comment by Wenxing-hou** [comment]
Hi, @rioone2023, I have regenerated the cert.

**The before id-DMTF-hardware-identity is:**
Parse from https://lapo.it/asn1js/:
![image](https://github.com/DMTF/libspdm/assets/87060980/93081407-3f5f-4250-8347-e8267afa1bbf)
Parse from Openssl command:
![image](https://github.com/DMTF/libspdm/assets/87060980/228a63e6-81fc-4eb0-97cd-c181b76c868e)



**The new id-DMTF-hardware-identity is:**
Parse from https://lapo.it/asn1js/:
![image](https://github.com/DMTF/libspdm/assets/87060980/0a2d7ff7-d15d-41fe-a183-74a8a11ffe22)
Parse from Openssl command:
![image](https://github.com/DMTF/libspdm/assets/87060980/8aff2a86-959c-4224-b2f6-f714b7a69546)


Do you think my regenerated cert meets the formatting requirements?

**Comment by rioone2023** [comment]
Hi [Wenxing-hou](https://github.com/Wenxing-hou),

In the SPDM-defined Format, "1.3.6.1.4.1.412.274.2" belongs to two SEQUENCEs (SEQUENCE OF and SEQUENCE).
It means, In addition to your modification, a SEQUENCE  is required.

<pre>
  347:d=5  hl=2 l=  10 prim: OBJECT            :1.3.6.1.4.1.412.274.6
  359:d=5  hl=2 l=  16 prim: OCTET STRING
      0000 - 30 0e 30 0c 06 0a 2b 06-01 04 01 83 1c 82 12 02   0.0...+.........
</pre>

Here the OCTET STRING is as follows

<pre>
    0:d=0  hl=2 l=  14 cons: SEQUENCE          
    2:d=1  hl=2 l=  12 cons: SEQUENCE          
    4:d=2  hl=2 l=  10 prim: OBJECT            :1.3.6.1.4.1.412.274.2

</pre>

**Comment by Wenxing-hou** [comment]
Thanks for your feedback. The last new cert format is:
![image](https://github.com/DMTF/libspdm/assets/87060980/1303b2b1-51c4-4900-9460-d23b70d31918)
And I have submitted the PR.
