### ISSUE TITLE
I wonder which SPDMVersion responder have to send in each case

### ISSUE THREAD

**Issue by lazineer** [DMTF/libspdm#2334]
Could you answer the questions below?

Case 1.
After `GET_VERSION`/`VERSION`, requester has sent `GET_CAPABILITIES` which has `SPDMVersion` = 0x12 and some other invalid fields.
If the responder supports SPDM v1.2, which `SPDMVersion` should the responder send the InvalidRequest `ERROR` response with? 0x10? or 0x12?

Case 2.
If the requester and responder have correctly handshaked `GET_CAPABILITIES`/`CAPABILITIES` (`SPDMVersion` = 0x12, in this case), should the responder send all `ERROR` responses with `SPDMVersion` = 0x12 except `GET_VERSION`? Even if the response exceeds `maxSpdmMsgSize`?

**Comment by steven-bellock** [comment]
The specification says 
>The selected version shall be the version in the SPDMVersion field of the Request (other than GET_VERSION) immediately following the GET_VERSION request.

and doesn't say it has to be a successful request, so I would imagine, in your example, it would be 0x12.

>If the requester and responder have correctly handshaked GET_CAPABILITIES/CAPABILITIES (SPDMVersion = 0x12, in this case), should the responder send all ERROR responses with SPDMVersion = 0x12 except GET_VERSION? Even if the response exceeds maxSpdmMsgSize?

Yes. But the size of an `ERROR` response cannot exceed a legal `MaxSPDMmsgSize`.

**Comment by lazineer** [comment]
Sorry, there is a typo. Even if the response exceeds maxSpdmMsgSize? => Even if the request exceeds maxSpdmMsgSize?
I mean a request, not response.

**Comment by steven-bellock** [comment]
>I mean a request, not response.

Yes, it would use 1.2 if it responds with an error at all.

**Comment by lazineer** [comment]
Than you for your answer.
