### ISSUE TITLE
Suggestion on buffer sizes

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#2335]
Hi Team,

I have a use case where certificate size go more than 4K. 
I see we have macros defined in https://github.com/DMTF/libspdm/blob/main/include/library/spdm_lib_config.h
and some other macros like LIBSPDM_MAX_SPDM_MSG_SIZE, LIBSPDM_SCRATCH_BUFFER_SENDER_RECEIVER_CAPACITY, LIBSPDM_SCRATCH_BUFFER_LARGE_SENDER_RECEIVER_CAPACITY 

What should be the sizes of each which I need to customize for optimal performance. 

Thanks,
Prithvi  A Pai

**Comment by jyao1** [comment]
Currently, it should be `LIBSPDM_MAX_CERT_CHAIN_SIZE`.


But we dont have "LIBSPDM_MAX_SPDM_MSG_SIZE, LIBSPDM_SCRATCH_BUFFER_SENDER_RECEIVER_CAPACITY, LIBSPDM_SCRATCH_BUFFER_LARGE_SENDER_RECEIVER_CAPACITY" any more. Those need to be set at runtime. Please refer to https://github.com/DMTF/libspdm/blob/main/doc/user_guide.md

**Comment by PrithviAPai** [comment]
@jyao1 Thank you for your suggestion.
We are using libspdm 2.3.2 (https://github.com/DMTF/libspdm/releases/tag/2.3.2) so that doesn't allow us to set sizes at runtime. So is there any suggestion on other buffer sizes so that performance is not compromised

**Comment by PrithviAPai** [comment]
Thanks a lot for suggestion.
