### ISSUE TITLE
libspdm_rsa_generate_key should not always assume the E is default

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#2336]
The `libspdm_rsa_generate_key` API implemented by **mbedtls** should not always assume that E is the default value.
https://github.com/DMTF/libspdm/blob/b8b48ae4d909840346dca244634975e9c08a6613/os_stub/cryptlib_mbedtls/pk/rsa_ext.c#L180-L187

**Comment by jyao1** [comment]
We can fix it at first. Then file an issue to move this `libspdm_rsa_generate_key` to https://github.com/DMTF/libspdm/blob/main/os_stub/spdm_crypt_ext_lib/cryptlib_ext.h, because only test needs it.
