### ISSUE TITLE
Behavior of responder according to `CACHE_CAP` and `MEAS_FRESH_CAP`

### ISSUE THREAD

**Issue by IamSukwonKim** [DMTF/libspdm#2342]
I'm little bit confused about behavior of responder according to `CACHE_CAP` and `MEAS_FRESH_CAP`.
This statements which from `DSP0274_1.2.1` makes me more confused.
> 402 If `MEAS_FRESH_CAP` bit in the `CAPABILITIES` response message returns 0, and the Requester requires fresh measurements, the Responder shall be **_Reset_** before `GET_MEASUREMENTS` is resent.

Please confirm that the following behavior is correct or not.

If responder receives `GET_MEASUREMENTS` while

1. `CACHE_CAP` = `0` and `MEAS_FRESH_CAP` = `0`. Then,
responder should be reset and `VCA` should be cleared.
So, `VCA` should follow `GET_MEASUREMENTS` and `n` in `L1/L2` is always `1`.

2. `CACHE_CAP` = `1` and `MEAS_FRESH_CAP` = `0`. Then,
responder should be reset and `VCA` doesn't be cleared.
So, `n` in `L1/L2` is always `1`.

3. `CACHE_CAP` = `0` and `MEAS_FRESH_CAP` = `1`. Then,
responder doesn't be reset and `VCA` doesn't be cleared.

4. `CACHE_CAP` = `1` and `MEAS_FRESH_CAP` = `1`. Then,
responder doesn't be reset and `VCA` doesn't be cleared.

If I understand correctly, following codes need to be modified.
https://github.com/DMTF/libspdm/blob/b8b48ae4d909840346dca244634975e9c08a6613/library/spdm_responder_lib/libspdm_rsp_measurements.c#L431-L432

**Comment by steven-bellock** [comment]
>So, VCA should follow GET_MEASUREMENTS and n in L1/L2 is always 1.

`VCA` comes before `GET_MEASUREMENTS`.

>If I understand correctly, following codes need to be modified.

Why do you think it needs to be modified? A **Reset** event is outside of libspdm. 

Also note that `MEAS_FRESH_CAP` is effectively a useless capability, since all the measurement blocks need to be fresh and if one of the measurement blocks isn't fresh, then `MEAS_FRESH_CAP` must be `0`. It would be surprising to see a Responder support `MEAS_FRESH_CAP == 1`.

**Comment by IamSukwonKim** [comment]
I apologize for bothering you with weird questions every time. But it's my job to interpret the spec. correctly and apply it to products. Even if a Reset event is outside of libspdm, but the specification states the behavior related to reset. (DSP0274_1.2.1 is referenced)

> 245 If set, the Responder supports the ability to cache the Negotiated State across a Reset.

This describes the behavior when `CACHE_CAP` = `1`.
> 402 the Responder shall be Reset before GET_MEASUREMENTS is resent.

This describes the behavior when `MEAS_CAP` = `0`.

>Why do you think it needs to be modified? A Reset event is outside of libspdm.

IMO, this is a matter of scope of reset and it is obvious that reset `VCA` is included in the reset. I think just adding `libspdm_reset_message_a()` is [necessity but not sufficiency](https://en.wikipedia.org/wiki/Necessity_and_sufficiency). 

> Also note that `MEAS_FRESH_CAP` is effectively a useless capability, since all the measurement blocks need to be fresh and if one of the measurement blocks isn't fresh, then `MEAS_FRESH_CAP` must be `0`. 

Did you mean `L1/L2`, not measurement blocks? Anyway, I think it is useless as you think. But it still remains on the spec. ;(
>It would be surprising to see a Responder support `MEAS_FRESH_CAP == 1`.

I think the behavior of libspdm is closer to `MEAS_FRESH_CAP`=`1`, since Responder isn't be reset.

**Comment by steven-bellock** [comment]
>Did you mean L1/L2, not measurement blocks? Anyway, I think it is useless as you think. But it still remains on the spec. ;(

No, they're measurements blocks. The typical example is that BootROM measures and loads the BootLoader that measures and loads the Application. Oftentimes once the Application is up and running the BootLoader cannot be measured again. In such a case, since the BootLoader can't be measured in response to a `GET_MEASUREMENT` then `MEAS_FRESH_CAP` must be `0`.

**Comment by IamSukwonKim** [comment]
I totally misunderstood the mechanism of `GET_MEASUREMENT` and `MEASUREMENT`. Thank you for kind explanation.
