### ISSUE TITLE
SET_CERTIFICATE AliasCert Device Certificate Private Key

### ISSUE THREAD

**Issue by alistair23** [DMTF/libspdm#2352]
Looking at the 1.3 spec, section 113-120 I see this

```
The certificates from the root certificate to the Device Certificate are
considered immutable because the Responder cannot change them, as they can
only be changed through the SET_CERTIFICATE command or an equivalent
capability.
...
Through the certificate chain, the root CA indirectly endorses the device
public key in the Device Certificate. When the AliasCert model is in use,
the Alias Certificates are endorsed by the device private key, meaning
that the Alias Certificates are also indirectly endorsed by the root CA.
...
In the AliasCert model, the device private key signs the next level Alias
Certificate, and then the private key associated with the public key in
each Alias Intermediate CA signs the Alias Certificate below it
...
When the AliasCert model is in use, the Device Certificate is referred
to as a Device Certificate CA, indicating that the certificate both
contains device hardware identity information and functions as a certificate
authority to sign an additional certificate.
```

In simple terms the device has a Device Certificate (or Device Certificate CA) that is immutable. The Device Certificate is used to sign other certificates, which are mutable certificates. These mutable certificates change when the state changes (such as a reset).

So basically every responder using `AliasCert` must have a Device Certificate public certificate and private key. The key is used for signing and the certificate is used for the certificate chain.

The `SET_CERTIFICATE` command can set the immutable certificates, effectively changing `The certificates from the root certificate to the Device Certificate`.

It's not clear, but I'm assuming that as `SET_CERTIFICATE` changes the certificates it should also change the key used to sign the mutable certificates. That is it results in a change to the public and private key of the Device Certificate.

Looking at `libspdm_set_cert_verify_certchain()` in libspdm though, I don't see how that is possible. libspdm_set_cert_verify_certchain() will fail on a private key. How can a requester pass the Device Certificate private key to a responder? Or is it instead expected that the Device Certificate private key is constant and `SET_CERTIFICATE` just changes the chain, but not the actual keys used to sign the alias cert?

**Comment by steven-bellock** [comment]
>Or is it instead expected that the Device Certificate private key is constant and SET_CERTIFICATE just changes the chain, but not the actual keys used to sign the alias cert?

Yes, that is the most common use case. Some folks use the device certificate key as an "identity key" since it uniquely identifies the device. The more ephemeral alias cert key can represent how the device is configured. 

https://www.youtube.com/watch?v=NO3l9QhpbzQ shows how we do it at NVIDIA.

**Comment by alistair23** [comment]
The alias cert key isn't changed by `SET_CERTIFICATE` though, so it just represents the device state.

I'm not clear on a use case of `SET_CERTIFICATE` then. It seems like a requester can overwrite part of the certificate chain with `SET_CERTIFICATE`. But then the device doesn't actually use that new chain to sign the alias key.

Doesn't that lead to a odd state where the device will provide an incomplete chain?

**Comment by steven-bellock** [comment]
>The alias cert key isn't changed by SET_CERTIFICATE though,

It can be. The alias certificate key can be derived from a mix of a lot of different things.
- Certificate chain.
- Firmware image.
- Fuse values.
- Random numbers.

>I'm not clear on a use case of SET_CERTIFICATE then.

Once a device is in a data center the data center owner may want to provision their own certificate chains (and root certificate) in addition to the device vendor's certificate chain in slot 0.

**Comment by alistair23** [comment]
> It can be. The alias certificate key can be derived from a mix of a lot of different things.

I should have been more clear. The alias cert isn't directly changed from `SET_CERTIFICATE`. It's entirely possible that the certificate chain is involved in deriving the alias cert, but it isn't directly controllable.

> Once a device is in a data center the data center owner may want to provision their own certificate chains (and root certificate) in addition to the device vendor's certificate chain in slot 0.

That's true, but the final leaf certificate won't be generated from those chains.

The spec does allow `SET_CERTIFICATE` for slot 0 though. So in a secure environment it's not impossible that a manufacture would use `SET_CERTIFICATE` to set the slot 0 certificate. But with libspdm that's not going to work as we can't set private keys.

**Comment by jyao1** [comment]
>  but the final leaf certificate won't be signed from those chains. Instead the final leaf certificate will be signed from the original certificates 

Here is my understanding:
In common provision case, the data center owner should use their CA to **endorse** the device cert chain in slot 1~7. (Not change device cert chain)
The leaf cert should still be signed by the device cert.

If owner wants to change a device private key, that is big update, because the identity is changed.
SET_CERT only handle public part. There should be a device specific way to handle private key.
All existing cert chains must be updated, and reboot is required.
During next boot, the new device cert will sign the new alias cert to create a brand new cert chain (Root CA -> Device cert -> Alias cert).

**Comment by alistair23** [comment]
> In common provision case, the data center owner should use their CA to **endorse** the device cert chain in slot 1~7. (Not change device cert chain)

If a data centre owner uses `SET_CERTIFICATE` to set slot 1 (which was empty before hand) on a device they can set the root CA up to the device CA.

Then when a requester runs `GET_CERTIFICATE` on slot 1, they get the new root CA to device CA. Then everything after that is the original alias CA and certs, exactly the same as slot 0. Nothing in slot 1 is signed by any of the new certificates as we have no private keys. Won't that be an invalid chain? I'm pretty sure libspdm today would throw an error

> SET_CERT only handle public part

Is that in the spec? Section 766 specially says:

```
For Slot 0 provisioning, the Requester should issue SET_CERTIFICATE only in a
trusted environment (such as a secure manufacturing environment)
```

Which to me implies `SET_CERTIFICATE` can specify the entire chain (including private keys).

Even this line implies to me that the `SET_CERTIFICATE` command will result in difference signatures

```
The device might require a reset to complete the SET_CERTIFICATE request, potentially
so that the device can generate AliasCert certificates using lower firmware layers
```

**Comment by jyao1** [comment]
@alistair23 , I am not sure if I understand your concern.
Since it is about SPDM spec interpretation, would you please file an SPDM spec issue in SPDM WG? Then we can discuss more spec issue there.

**Comment by steven-bellock** [comment]
Yes, this is a specification question. @alistair23 let us know if you need access to https://github.com/DMTF/SPDM-WG.

**Comment by alistair23** [comment]
I'm not sure it's a specification issue. I think the spec implies that `SET_CERTIFICATE` works with private keys which libspdm doesn't correctly handle.

Otherwise I don't see any use case for `SET_CERTIFICATE`. I have raised an issue here though to discuss it: https://github.com/DMTF/SPDM-WG/issues/3121
