### ISSUE TITLE
Need to better handle version negotiation

### ISSUE THREAD

**Issue by liyi77** [DMTF/libspdm#237]
@rw8896
I was wondering the error handling of "After GET_CAPABILITY, the responder will know this is the version selected by the requester and always stick it it."

After the version is negotiated (either from cache or set by GET_CAPABILITIES), If requester sends a command with a version other than the negotiated one, current responder seems to ignore the error and continue to process it with the previously negotiated version.

Shouldn't the responder validate the version against the negotiated one and return error if it doesn't match?

**Comment by rw8896** [comment]
@liyi77 Thanks for copying my question here.

Current code is a little bit confusing about **supported versions** vs **negotiated version**:
- `spdm_version_number_t version;` in `spdm_connection_info_t` is the negotiated version and would be more convenient to use the same type as `uint8 spdm_version;` in `spdm_message_header_t` 
- `spdm_is_version_supported()` actually means `spdm_is_version_negotiated()`

Here are the proposed changes:

1) For any received command (except GET_VERSION), the responder should check if the command uses the negotiated version
- GET_VERSION is always 1.0. No need to check it against negotiated version.
- Negotiated version is determined ((either from successful GET_CAPABILITIES or cached negotiation) if connection state >= SPDM_CONNECTION_STATE_AFTER_CAPABILITIES  

A pseudo code like this might work in spdm_build_response so we don't need to add the check in each handler function
```
spdm_message_header_t *spdm_request = (spdm_message_header_t *)spdm_context->last_spdm_request;
if ((spdm_request->request_response_code != SPDM_GET_VERSION) && (connection state >= SPDM_CONNECTION_STATE_AFTER_CAPABILITIES)) {
    if (!spdm_is_version_negotiated(spdm_request->spdm_version))
        return Error; /* 0x41? */
}
```

2) requester and responder should fill header.spdm_version using selected/negotiated version except GET_VERSION to replace the hardcoded spdm_version in current code, e.g. 
`spdm_response->header.spdm_version = SPDM_MESSAGE_VERSION_11;`
- not very sure about Error response with Error code 0x41 though

**Comment by liyi77** [comment]
It doesn't seem important since only versions 1.1 and 1.0 are currently supported.
If libspdm supports more versions in the future, it will be a bit confusing.

**Comment by jyao1** [comment]
This code is not scalable, if we need support 1.2, 1.3, etc.

I think we need write code like:
```
spdm_request.header.spdm_version = get_negotiated_version(spdm_context);
```

**Comment by rw8896** [comment]
@jyao1 yes, that's what I mean.
@liyi77 Thanks for copying my question here.

Current code is a little bit confusing about **supported versions** vs **negotiated version**:
- `spdm_version_number_t version;` in `spdm_connection_info_t` is the negotiated version and would be more convenient to use the same type as `uint8 spdm_version;` in `spdm_message_header_t` 
- `spdm_is_version_supported()` actually means `spdm_is_version_negotiated()`

Here are the proposed changes:

1) For any received command (except GET_VERSION), the responder should check if the command uses the negotiated version
- GET_VERSION is always 1.0. No need to check it against negotiated version.
- Negotiated version is determined ((either from successful GET_CAPABILITIES or cached negotiation) if connection state >= SPDM_CONNECTION_STATE_AFTER_CAPABILITIES  

A pseudo code like this might work in spdm_build_response so we don't need to add the check in each handler function
```
spdm_message_header_t *spdm_request = (spdm_message_header_t *)spdm_context->last_spdm_request;
if ((spdm_request->request_response_code != SPDM_GET_VERSION) && (connection state >= SPDM_CONNECTION_STATE_AFTER_CAPABILITIES)) {
    if (!spdm_is_version_negotiated(spdm_request->spdm_version))
        return Error; /* 0x41? */
}
```

2) requester and responder should fill header.spdm_version using selected/negotiated version to replace the hardcoded spdm_version in current code, e.g. 
`spdm_response->header.spdm_version = SPDM_MESSAGE_VERSION_11;`

**Comment by jyao1** [comment]
11/8/21 - no need for stable. But agree we should do for 1.2.

**Comment by qizhangz** [comment]
I will check it.

**Comment by Wenxing-hou** [comment]
I will check it.

**Comment by jyao1** [comment]
The responder should use spdm_get_connection_version() to check if the version from requester is expected.
```
    if (spdm_request->header.spdm_version != spdm_get_connection_version(spdm_context)) {
        return libspdm_generate_error_response(spdm_context,
                         SPDM_ERROR_CODE_INVALID_REQUEST, 0,
                         response_size, response);
    }
```

Special cases:
1) spdm_get_response_version: 1.0 should be used.
2) spdm_get_response_capabilities(): the spdm_version should be set to spdm_context->connection_info.version.

**Comment by rw8896** [comment]
@jyao1 This [commit](https://github.com/DMTF/libspdm/commit/7a908b4400074bd6cbc50647ddaed5e7bdf77a0d) used error cause SPDM_ERROR_CODE_INVALID_REQUEST.

Will it be better to use 0x41?

1.2 Specs mentioned:
If the Requester uses a
different version than the selected version in other Requests, the Responder should return an ERROR message with
ErrorCode = VersionMismatch or the Responder can silently discard the Request.

**Comment by jyao1** [comment]
@rw8896, Can you file a new issue?

Commenting in a closed issue may be easily ignored.

**Comment by rw8896** [comment]
Done. Created #509 .
