### ISSUE TITLE
Lack of backward compatibility for version 1.2.0

### ISSUE THREAD

**Issue by JakubLedworowski** [DMTF/libspdm#2375]
According to [SPDM specification 1.2.1](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf) new capabilities where added between 1.2.0 and 1.2.1:
`Added SET_CERT_CAP , CSR_CAP and CERT_INSTALL_RESET_CAP capabilities bits.`
This means, that any SPDM Responder implemented to 1.2.0 specification (there are already such implementors in the field) does not know about these capabilities and send `0` n CAPABILITIES response.

However, libspdm library always performs a check if this flag is set e.g. during [requester set certificate](https://github.com/DMTF/libspdm/blob/137b6f7056be9df0295165bf1a30517814dfc5ad/library/spdm_requester_lib/libspdm_req_set_certificate.c#L46):
```
if (!libspdm_is_capabilities_flag_supported(
        spdm_context, true, 0,
        SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_SET_CERT_CAP)) {
    return LIBSPDM_STATUS_UNSUPPORTED_CAP;
}
```

Thus, SPDM command SET_CERTIFICATE will always be blocked by libspdm when communicating with SPDM Responder with version 1.2.0 even if the responder supports SET_CERTIFICATE.

My proposal is to add additional check for 0x121 version and check the flag only if SPDM Responder version >= 0x121.
Proposal for SET_CERTIFICATE is [on the Pull Request from fork](https://github.com/DMTF/libspdm/pull/2374) - it will be probably necessary to also implement this for CSR_CAP and CERT_INSTALL_RESET_CAP where applicable.

**Comment by steven-bellock** [comment]
I had forgotten about this. There is an issue with the specification that I am clarifying with the SPDM Working Group. In particular the inclusion of these capabilities should not have gone into 1.2.1. @JakubLedworowski To resolve this issue the Requester can just skip the capability check. But yes, we should review the other capabilities as well.

As an aside, do you really have a 1.2.0 Responder that supports `SET_CERTIFICATE`?

**Comment by steven-bellock** [comment]
The checks in https://github.com/DMTF/libspdm/blob/137b6f7056be9df0295165bf1a30517814dfc5ad/library/spdm_requester_lib/libspdm_req_get_capabilities.c#L127-L138 should be fine as-is.

The capability checks in https://github.com/DMTF/libspdm/blob/137b6f7056be9df0295165bf1a30517814dfc5ad/library/spdm_requester_lib/libspdm_req_handle_error_response.c#L118-L126 and https://github.com/DMTF/libspdm/blob/137b6f7056be9df0295165bf1a30517814dfc5ad/library/spdm_requester_lib/libspdm_req_get_csr.c#L55-L59 should be removed.
