### ISSUE TITLE
[SPDM 1.1.2] - tag mismatch with AEAD secure session

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2387]
I see the tag mismatch error, any idea?
1)key calculation went wrong
2) On the requester side I'm using requester_direction_data_Secret key as major-secret and on the responder side I'm using reponder-direction-data-key as major-secret for the below EncryptionKey  calculation - Is this correct?

EncryptionKey = HDKF-Expand(major-secret, bin_str5, key_length);
IV = HKDF-Expand(major-secret, bin_str6, iv_length);

**Comment by steven-bellock** [comment]
> Is this correct?

No. The symmetric key used for decryption must be the same as the key used for encryption.

**Comment by goutham23** [comment]
What is symmetric here, can you help me understand 

EncryptionKey = HDKF-Expand(major-secret, bin_str5, key_length);

On the requester implementation major-secret = requester_direction_data_secret key
On the responder implementation major-secret = responder_directon_data_secret_key

**Comment by steven-bellock** [comment]
Both the Requester and Responder derive keys from both the request-direction secret and the response-direction secret. The Requester encrypts data with the key derived from the request-direction secret, and the Responder decrypts it with the same key. The Responder encrypts data with the key derived from the response-direction secret, and the Requester decrypts it with the same key.

**Comment by goutham23** [comment]
To elaborate your below statement..
"The Requester encrypts data with the key derived from the request-direction secret, and the Responder decrypts it with the same key"

Lets say..
EncryptionKey = HDKF-Expand(major-secret, bin_str5, key_length);
Requester encrypts data with encryption_key derived from major-secret = requester_direction_data_secret key
you are telling responder decrypts the data with the same key.. meaning
Responder decrypts data with encryption_key derived from **major-secret = requester_direction_data_secret key**

In the above encryption and decryption path major-secret is same to calculate the encryption key?

**Comment by steven-bellock** [comment]
> In the above encryption and decryption path major-secret is same to calculate the encryption key?

Correct. That is the essence of symmetric-key cryptography.

**Comment by goutham23** [comment]
@steven-bellock thanks for confirming - I stand corrected

There is follow-up question to this in https://github.com/DMTF/libspdm/issues/2388
