### ISSUE TITLE
[SPDM 1.1.2] - Secure session data secret keys

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2388]
Both the requester and responder calculate data secret keys on their end..

**responder_direction_data_secret_key** calculated by RESPONDER should match with **responder_direction_data_secret_key** calculated on REQUESTER side

Like wise..

**requester_direction_data_secret_key** calculated by RESPONDER should match with **requester_direction_data_secret_key** calculated on REQUESTER side

Is my understanding correct? (I'm seeing it different)

**Comment by goutham23** [comment]
DHE secret, handshake-secret and master secret keys matched both on RESPONDER and REQUESTER side.

**Comment by jyao1** [comment]
> Is my understanding correct? (I'm seeing it different)

I think your understanding is right. What is different?

**Comment by goutham23** [comment]
My TH2 calculation was not matching on the requester and responder side, fixed it.
Now I see symmetric keys, all good.

Thanks @steven-bellock  ad @jyao1 again for the timely response!!
