### ISSUE TITLE
AEAD sequence number endianness detection does not work

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2393]
If the endianness of the sequence number has not been determined, then on decryption libspdm will attempt to determine the endianness through https://github.com/DMTF/libspdm/blob/28571c8653f657ff26cdd6dfcd36414eff7dab86/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c#L534-L568 This does not work in practice as the first sequence number is `0` which has the same byte layout in both big and little endian. Endianness can only be determined on the subsequent decryption, when the sequence number is `1`.

**Comment by jyao1** [comment]
It seems we need skip the assignment only if sequence number is non 0.
