### ISSUE TITLE
Secure session - Data sequence number tracking

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2398]
REQUESTER:
When the Requester encodes a request msg, we should store/track the sequence in request_data_sequence_number
When the Requester decodes a response, we should store/track the sequence in response_data_sequence_number

RESPONDER:
When the Responder encodes a response we should store/track the sequence in response_data_sequence_numbe
When the Responder decodes a request message received, we should store/track the sequence in request_data_sequence_number

Is this correct?

**Comment by steven-bellock** [comment]
> Is this correct?

Yes.
