### ISSUE TITLE
How to calculate measurement summary hash according to spdm version

### ISSUE THREAD

**Issue by mcsmonk** [DMTF/libspdm#2404]
Although there was an issue #899 and pr below code

https://github.com/DMTF/libspdm/blob/28571c8653f657ff26cdd6dfcd36414eff7dab86/os_stub/spdm_device_secret_lib_sample/lib.c#L1284-L1311

Current implementation calculate measurement summary hash using only concatenation of real measurement in version 1.0, 1.1, otherwise, measurement blocks.
However, how to calculate of measurement summary hash, which described in each version of spec, make me confused.

| version | measurement summary hash | spec link |
| --- | --- | --- |
| 1.0.0 | hash(Concatenation(Measurement 1, Measurement 2, ...., Measurement N)) | https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.0.0.pdf |
| 1.0.1 | hash(Concatenation(Measurement 1, Measurement 2, ...., Measurement N)) | https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.0.1.pdf |
| 1.1.0 | hash(Concatenation(MeasurementBlock[0].Measurement, MeasurementBlock[1].Measurement, ..., MeasurementBlock[n].Measurement)) | https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.1.0.pdf |
| 1.1.1 | hash(Concatenation(MeasurementBlock[0].Measurement, MeasurementBlock[1].Measurement, ..., MeasurementBlock[n].Measurement)) | https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.1.1.pdf |
| 1.1.2 | hash(Concatenation(MeasurementBlock[0], MeasurementBlock[1], ..., MeasurementBlock[n])) | https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.1.2.pdf |
| `>=`1.2 | hash(Concatenation of measurement blocks) | https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.0.pdf |

Which method is a correct I must comply?

**Comment by mcsmonk** [comment]
Do you suggest that we should comply current way?
despite of version 1.1.2, which describe that "When requested Param2=0xFF , this field is computed as the hash(Concatenation(MeasurementBlock[0], MeasurementBlock[1], ..., MeasurementBlock[n])) of all supported **measurement blocks** available in the measurement index range 0x01 - 0xFE , concatenated in ascending index order."

**Comment by jyao1** [comment]
I did not notice `1.1.2` already changed that. I think we can ask SPDM WG's clarification on 1.0.

**Comment by mcsmonk** [comment]
I discovered this when I tested our device using spdm-emu and spdm-responder-validator (test 7.1)

@steven-bellock , @jyao1 
Would you let me know how should I have approach? Would I'm able to expect that there will be change in libspdm such that it use whole measurement block in all version?

**Comment by jyao1** [comment]
I am not against to change. But that change is in **sample** library - **spdm_device_secret_lib_sample**

Question is: What is broken today?
I don't think libspdm or spdm-responder-validator has any check on that. Do we?

**Comment by mcsmonk** [comment]
Test 7.1 is an example

The below code is a comparison between `measurement_summary_hash` from `CHALLENGE` and fresh `measurement_summary_hash` from `GET_MEASUREMENTS`
https://github.com/DMTF/SPDM-Responder-Validator/blob/9d1aa8856b0c4314d74a31155de39306357ada98/library/spdm_responder_conformance_test_lib/spdm_responder_test_7_measurements.c#L975-L976

**Comment by jyao1** [comment]
Got it. I agree we should fix that.

**Comment by steven-bellock** [comment]
> The below code is a comparison between `measurement_summary_hash` from `CHALLENGE` and fresh `measurement_summary_hash` from `GET_MEASUREMENTS` using the sample function code https://github.com/DMTF/SPDM-Responder-Validator/blob/9d1aa8856b0c4314d74a31155de39306357ada98/library/spdm_responder_conformance_test_lib/spdm_responder_test_7_measurements.c#L975-L976

Without additional information the test should not assume that measurement values cannot change between `CHALLENGE` and `GET_MEASUREMENTS`.

**Comment by mcsmonk** [comment]
I think that we should change only the below two codes for the successful test because the test of measurement_summary_hash would be nececessary for original goal of spdm

https://github.com/DMTF/SPDM-Responder-Validator/blob/9d1aa8856b0c4314d74a31155de39306357ada98/library/spdm_responder_conformance_test_lib/spdm_responder_test_7_measurements.c#L453-L466

https://github.com/DMTF/libspdm/blob/28571c8653f657ff26cdd6dfcd36414eff7dab86/os_stub/spdm_device_secret_lib_sample/lib.c#L1284-L1311

**Comment by steven-bellock** [comment]
> > The below code is a comparison between `measurement_summary_hash` from `CHALLENGE` and fresh `measurement_summary_hash` from `GET_MEASUREMENTS` using the sample function code https://github.com/DMTF/SPDM-Responder-Validator/blob/9d1aa8856b0c4314d74a31155de39306357ada98/library/spdm_responder_conformance_test_lib/spdm_responder_test_7_measurements.c#L975-L976
> 
> Without additional information the test should not assume that measurement values cannot change between `CHALLENGE` and `GET_MEASUREMENTS`.

@steven-bellock to file an issue with SPDM WG.

**Comment by steven-bellock** [comment]
The change from 1.1.1 to 1.1.2 (`MeasurementBlock[0].Measurement` -> `MeasurementBlock[0]`) should not have happened. I've filed https://github.com/DMTF/SPDM-WG/issues/3218 to bring awareness of the issue to the SPDM Working Group.
