### ISSUE TITLE
Improving for making GET_CAPABILITIES request message

### ISSUE THREAD

**Issue by mcsmonk** [DMTF/libspdm#2412]
I identified this issue from https://github.com/DMTF/libspdm/pull/2406#discussion_r1360169066

Current code fills the all fields of GET_CAPABILITIES request message unconditionally
https://github.com/DMTF/libspdm/blob/5fb8f10b907b6d8bc755f751d2bbd45e476be78b/library/spdm_requester_lib/libspdm_req_get_capabilities.c#L208-L211

But, such fields are filled according to spdm version.
When `>=v1.1`, `ct_exponent` and `flags` are filled.
When `>=v1.2`, `data_transfer_size` and `max_spdm_msg_size` are filled.

**Comment by steven-bellock** [comment]
To be clear, there isn't a bug in the code, as the size of the request message is sized appropriately based on the negotiated SPDM version. But this is important for documentation purposes so that folks aren't misled into thinking those fields are unconditional.

**Comment by mcsmonk** [comment]
I will fix this
