### ISSUE TITLE
Getting error message while running tests

### ISSUE THREAD

**Issue by premalathak12** [DMTF/libspdm#2413]
getting error while running test_spdm_responder
[       OK ] test_spdm_responder_encap_get_certificate_case2
[ RUN      ] test_spdm_responder_encap_get_certificate_case3
Unable to open file ecp256/bundle_responder.certchain.der
0000: 5b 20 52 55 4e 20 20 20 20 20 20 5d 20 74 65 73 74 5f 73 70 64 6d 5f 72 65 73 70 6f 6e 64 65 72 
0020: 5f 65 6e 63 61 70 5f 67 65 74 5f 63 65 72 74 69 66 69 63 61 74 65 5f 63 61 73 65 33 0a 00 73 29 
0040: 2e 0a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0

and while running test_crypt
Unable to open file ecp256/inter.cert.der

**Comment by xiangfeima** [comment]
Looks the step of `make copy_sample_key` was missing. Would you try it and see if the issue is still there?
Note for Windows builds, try `nmake copy_sample_key`.
Good luck.
