### ISSUE TITLE
[SPDM 1.1.2] - END_SESSION request

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2417]
Let's say I've 4 active sessions.. 
session_id = 1,2,3,4 (for our convenience )

Requester wants to end the session (session_id = 2)
How does the requester pass this session_id info to the responder?

![image](https://github.com/DMTF/libspdm/assets/36578776/b02d6c9b-37d2-4184-8f04-34974951bd69)

END_SESSION request header format does not allow to specify session_id ?

**Comment by steven-bellock** [comment]
See #2008.

**Comment by goutham23** [comment]
thanks
