### ISSUE TITLE
Question on AEAD based Encryption and Decryption

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2418]
AEAD is encryption + MAC. 

Encryption requirements is AES 128 and 256 right?
But the MAC method I did not find the requirements. 

Could you provide the MAC method requirements?

**Comment by steven-bellock** [comment]
It's provided by either 274 itself or a transport binding specification. 

274 defines it for [CHACHA20_POLY1305](https://github.com/DMTF/SPDM-WG/blob/master/docs/DSP0274/SPDMSpecification.md#chachapoly).
![image](https://github.com/DMTF/libspdm/assets/8474235/44edce8d-aa08-4204-97fa-0f2c56215710)

277 defines it for everyone
![image](https://github.com/DMTF/libspdm/assets/8474235/aa688ef8-af07-425e-92d5-73c38b89b3a4)

So it looks like it's 16 bytes for everyone.

**Comment by PrakashK94** [comment]
Did you find this information in SPDM spec? If yes, which version spec it is? Can you share the link of the spec?

**Comment by steven-bellock** [comment]
@PrakashK94 please close this issue if it has been resolved.
