### ISSUE TITLE
There seems to be a conflict in the DSP0274_1.2.1 regarding the Session and `KEY_EXCHANGE`.

### ISSUE THREAD

**Issue by IamSukwonKim** [DMTF/libspdm#2430]
There seems to be a conflict in the DSP0274_1.2.1 regarding the Session and `KEY_EXCHANGE`.

1. According to following statements, It seems that either `KEY_EXCHANGE` or `PSK_EXCHANGE` are conducted in the session but not in secure session.
`KEY_EXCHANGE` is not included in Secure Session in Figure 2 .
> 719 A session has three phases, as Figure 26 - Session phases shows: The _handshake_, The _application_, _termination_ phases.
(...)
> 723 The session handshake phase begins with either `KEY_EXCHANGE` or `PSK_EXCHANGE`.

2. According to Table 6 - SPDM request and response messages validity, both `KEY_EXCHANGE` and `PSK_EXCHANGE` are prohibited in a session, because they are included in a row of `All others` which is `Prohibited` in a Session.

Due to the conflct, Error code of `FINISH_RSP` is ambiguous. 
In case, `FINISH` before `KEY_EXCHANGE`, there are two cases.

1. response `UnexpectredRequest`
If `KEY_EXCHANGE` is not included in a session, `UnexpectedRequest` is the only Error code for `FINISH_RSP`

2. response `SessionRequired` or `UnexpectedRequest`
If `KEY_EXCHANGE` is inluded in a session, both of `SessionRequired` and `UnexpectedRequest` make sense.
Which is the appropriate error code? Latest libspdm response `SessionRequired`. Following is related code.

https://github.com/DMTF/libspdm/blob/052bc7b1f02e3d0538d07525359b9e29e4f7738a/library/spdm_responder_lib/libspdm_rsp_finish.c#L436-L453

**Comment by steven-bellock** [comment]
I don't think the specification will go into detail on priority of error messages when multiple ones make sense. It will be left up to the implementer.

**Comment by jyao1** [comment]
@IamSukwonKim , I recommend you take a look at the https://github.com/DMTF/SPDM-Responder-Validator/blob/main/doc/9.FinishRsp.md, if there is some assumption, then you can file an issue.

I agree that if the spec is ambiguous about tit, then we should allow implementation either way.

**Comment by steven-bellock** [comment]
@IamSukwonKim please close this issue / question if there are no additional comments.
