### ISSUE TITLE
Certificate verification fails with sample alias cert

### ISSUE THREAD

**Issue by xiangfeima** [DMTF/libspdm#2442]
@Wenxing-hou
My recent test using spdm-emu was failed due to libspdm sample certificate validation failure.
According to the checking logic in `libspdm_verify_leaf_cert_basic_constraints()`, the CA flag in leaf certificate when using alias cert model is supposed to be either non-existing or FALSE.
https://github.com/DMTF/libspdm/blob/ca2fde8ae4a129f994d3e645cc9bcaf1caeed94a/library/spdm_crypt_lib/libspdm_crypt_cert.c#L747
Would you please take a look at the alias certs we have right now?
Looks they were introduced by https://github.com/DMTF/libspdm/pull/2094.
We need to set `basicConstraints = critical,CA:false` in the [ v3_end_alias ] section in openssl.cnf if I understand it correctly.

**Comment by Wenxing-hou** [comment]
I am checking this issue.

**Comment by Wenxing-hou** [comment]
Hi, @xiangfeima.  I found the reason for this issue.
In the PR #2094, I generated the alias_cert model cert for set_cert command. 
But these cert is the part of entire alias cert, you can find the spec in the issue: #2066. 
So the generated alias_cert is only used for set_cert command.
![image](https://github.com/DMTF/libspdm/assets/87060980/1e5417ea-a466-4304-85d7-5618b118dc07)


In the code, it is clear:
https://github.com/DMTF/libspdm/blob/84989bf8ed9a108665873c8a7eaa514846422aec/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1142-L1145

https://github.com/DMTF/libspdm/blob/84989bf8ed9a108665873c8a7eaa514846422aec/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1174-L1178

I am fixing this issue.  Thanks!

**Comment by jyao1** [comment]
I filed https://github.com/DMTF/libspdm/issues/2454 for real alias cert for GET_CERTIFICATE.

**Comment by xiangfeima** [comment]
Thank you very much for the updating. It's clear to me now.
#2094/#2454 alias certs are for SET_CERTIFICATE.
#2454 alias certs would be for GET_CERTIFICATE
