### ISSUE TITLE
ENCAP_CAP should not be checked for SPDM Version 1.2.1

### ISSUE THREAD

**Issue by JakubLedworowski** [DMTF/libspdm#2447]
In DSP0274_1.2.0 and DSP0274_1.2.1 the ENCAP_CAP was deprecated but in DSP0274_1.2.2 this deprecation was removed.

libspdm correctly checks the capability for 1.2.2 (https://github.com/DMTF/libspdm/blob/3.1.1/library/spdm_requester_lib/libspdm_req_encap_request.c#L147) however it should NOT be validated for 1.2.1.

**Comment by steven-bellock** [comment]
Yes, for 1.2 the check should be for `ENCAP_CAP` or `MUT_AUTH_CAP`. 1.1 and 1.3 are well-defined.

**Comment by JakubLedworowski** [comment]
Thanks Steven, but the SPDM 1.2.2 spec states that these capabilities are separate:
1. if Requester/Responder supports any form of mutual authentication - it shall set `MUT_AUTH_CAP`
2. if Requester/Responder supports sending encapsulated flow (for any purpose) - it shall set `ENCAP_CAP`

From those above statements I can infer, that if Requester/Responder supports mutual authentication using encapsulated flow it shall set both `MUT_AUTH_CAP` and `ENCAP_CAP`.

It is confirmed in the description of `KEY_EXCHANGE_RSP`, which has a parameter `MutAuthRequested`:
        _Bit 0 - If set, the Responder is requesting to authenticate the Requester (Session-based mutual authentication) **without using the encapsulated request flow**.
        Bit 1 - If set, Responder is requesting Session-based mutual authentication **with the encapsulated request flow**._

Thus, I think that libspdm shall:
1. for version 1.2.0 and 1.2.1 - do not check `ENCAP_CAP` before sending `GET_ENCAPSULATED_REQUEST` - because
2. for version 1.2.2 - check for `ENCAP_CAP` before sending `GET_ENCAPSULATED_REQUEST`

**Comment by steven-bellock** [comment]
>Thus, I think that libspdm shall:

The `UpdateVersionNumber` is not to be used when checking versions for interoperability.

![image](https://github.com/DMTF/libspdm/assets/8474235/a729ec7e-98cc-473f-87c8-a8a0845dc54d)

Also, since it's informational, I'm not sure how strict folks are about setting the `UpdateVersionNumber`.

**Comment by steven-bellock** [comment]
> Yes, for 1.2 the check should be for `ENCAP_CAP` or `MUT_AUTH_CAP`. 1.1 and 1.3 are well-defined.

**Comment by steven-bellock** [comment]
So with this change the recommendation to Integrators would be, if their 1.2 endpoint supports encapsulated messages, to set both `ENCAP_CAP` and `MUT_AUTH_CAP`. In particular, deprecating a field does not make it reserved.
