### ISSUE TITLE
Provide the use case of SPDM 1.2 commands

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2448]
Could you please share the use case so that we can test SPDM 1.2 commands like CHUNK_GET, CHUNK_SEND, GET_CSR and SET_CERTIFICATE?

**Comment by steven-bellock** [comment]
`CHUNK_GET` and `CHUNK_SEND` are used when both endpoints support chunking and the message to be sent is larger than the transmission buffer size of the sender and/or receiver. `GET_CSR` is used to retrieve a certification signing request from the Responder, typically in anticipation of `SET_CERTIFICATE` command where the new certificate and its chain are deposited in a Responder's certificate slot.

**Comment by PrakashK94** [comment]
Any tool test these commands? Whether these commands needs to be tested in session or it can be tested outside session also?

I saw there is SPDM emulation tool that does test GET CSR command but I see no other SPDM 1.2 command it does test other than GET CSR.

**Comment by jyao1** [comment]
No tool so far.
@PrakashK94 , please contribute if you have interest.

**Comment by PrakashK94** [comment]
For example, While sending set certificate request to the responder, request length is large which in my case is 1434 bytes long since it contains the certificate chain of the requestor which is 1429 bytes long, but the transport layer like MCTP which divides the request to multiple MCTP packets each of size 72 bytes long and sends it over I2C, if that is the case we can't test CHUNK_SEND & CHUNK_GET command right?

**Comment by steven-bellock** [comment]
SPDM supports chunking so that if an endpoint uses a transport that does not support chunking then SPDM can take on that burden. However if the transport does support chunking then it's best to use that.

**Comment by PrakashK94** [comment]
ok, scratch buffer in libspdm code is only used for chunking purpose right?

**Comment by steven-bellock** [comment]
>ok, scratch buffer in libspdm code is only used for chunking purpose right?

No. It's used as an actual scratch pad for data that's too large for the stack, as well as for encrypted messages. Right now its size is not optimal based on the capabilities. For example if an endpoint does not support chunking or encryption, then the scratch buffer should be small, but it's not.

**Comment by PrakashK94** [comment]
Please correct my understanding here,
GET CSR command is for getting the certificate signing request from the responder and then certificate signing request needs to be signed by CA and then we will get the certificate chain and then requestor can issue SET certificate command to set this certificate chain in different slots of the responder.

But as per libspdm code, I see Requestor does gets CSR from the responder but CA doesn't sign it and for set certificate I see it just writes the certificates in a file which requestor provides to responder.

**Comment by steven-bellock** [comment]
>But as per libspdm code, I see Requestor does gets CSR from the responder but CA doesn't sign it and for set certificate I see it just writes the certificates in a file which requestor provides to responder.

libspdm / OpenSSL simulates a CA by producing certificate chains. For "real" CA services one oftentimes has to pay money, which the DMTF does not want to do.

**Comment by PrakashK94** [comment]
Does libspdm validates the response that comes in this field, _ResponseToLargeRequest_ field in **CHUNK_SEND_ACK response message format**? For example if it contains Negotiate Algorithm response, does it validates that response?

**Comment by steven-bellock** [comment]
> Does libspdm validates the response that comes in this field, _ResponseToLargeRequest_ field in **CHUNK_SEND_ACK response message format**? For example if it contains Negotiate Algorithm response, does it validates that response?

Yes, it is validated in the same way a response to a non-chunked request is.

**Comment by PrakashK94** [comment]
How to validate CHUNK_GET command for requestor?
Need to decrease LIBSPDM_DATA_TRANSFER_SIZE in the requestor side?

**Comment by steven-bellock** [comment]
> Need to decrease LIBSPDM_DATA_TRANSFER_SIZE in the requestor side?

Yes, if both endpoints support chunking and if the response is larger than the Requester's `DataTransferSize` then the Requester will need to use `CHUNK_GET` to retrieve the response.

**Comment by PrakashK94** [comment]
You mean both the endpoints should have LIBSPDM_ENABLE_CAPABILITY_CHUNK_CAP set to 1 and the response which responder is going to frame for a particular request is greater than the requestor data transfer size then requestor will need to use CHUNK_GET to retrieve the response?

**Comment by steven-bellock** [comment]
Yes. In addition the response needs to be less than the Requester's `MaxSPDMmsgSize`.
