### ISSUE TITLE
check_tbs_certificate check order matches RFC5280 but it is not aligned with libspdm and DMTF SPDM certificate requirements

### ISSUE THREAD

**Issue by OuyangHang33** [DMTF/libspdm#2451]
**In rust-spdm check_tbs_certificate (check issuer name -> validity -> subject name):**
https://github.com/intel/rust-spdm/blob/e7123b9af874f573ab27ea5a35a0f590dd226541/spdmlib/src/crypto/x509v3.rs#L129C1-L139C32
```
    // issuer               Name,
    let bytes_consumed = check_name(&data[t_walker..])?;
    t_walker += bytes_consumed;


    // validity             Validity,
    let bytes_consumed = check_validity(&data[t_walker..])?;
    t_walker += bytes_consumed;


    // subject              Name,
    let bytes_consumed = check_name(&data[t_walker..])?;
    t_walker += bytes_consumed;
```
**In RFC5280 page16 (check issuer name -> validity -> subject name):**
https://datatracker.ietf.org/doc/html/rfc5280#section-4.1
<img width="514" alt="image" src="https://github.com/intel/rust-spdm/assets/109128373/adbc0338-caab-405c-bfab-3ccc0212d93a">

**In DMTF/libspdm code (check issuer name -> subject name -> validity ):**
https://github.com/DMTF/libspdm/blob/84989bf8ed9a108665873c8a7eaa514846422aec/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1046C1-L1075C1
```
    /* 4. issuer_name*/
    asn1_buffer_len = 0;
    status = libspdm_x509_get_issuer_name(cert, cert_size, NULL, &asn1_buffer_len);
    if (asn1_buffer_len == 0) {
        status = false;
        goto cleanup;
    }


    /* 5. subject_name*/
    asn1_buffer_len = 0;
    status = libspdm_x509_get_subject_name(cert, cert_size, NULL, &asn1_buffer_len);
    if (asn1_buffer_len == 0) {
        status = false;
        goto cleanup;
    }


    /* 6. validaity*/
    status = libspdm_x509_get_validity(cert, cert_size, end_cert_from,
                                       &end_cert_from_len, end_cert_to,
                                       &end_cert_to_len);
    if (!status) {
        goto cleanup;
    }


    status = libspdm_internal_x509_date_time_check(
        end_cert_from, end_cert_from_len, end_cert_to, end_cert_to_len);
    if (!status) {
        goto cleanup;
    }
```
**In DMTF spdm version 1.2.1 spec SPDM certificate requirements page75 Table33-Required fields (check issuer name -> subject name -> validity ):**
<img width="647" alt="image" src="https://github.com/intel/rust-spdm/assets/109128373/d4f82fb0-a345-4f0b-8232-45eeeed5996a">

**Comment by Wenxing-hou** [comment]
For your issue, I think the `check_tbs_certificate` check order code  is acceptable for libspdm.  Because the validity check can exist before  or after the Subject Name check.  It is all OK.

**Comment by OuyangHang33** [comment]
Thank you for the anwer :) I can understand reason of the check order.
