### ISSUE TITLE
The priority table of BaseAsymAlgo and ReqBaseAsymAlg should be same

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#246]
Both of BaseAsymAlgo and ReqBaseAsymAlg are asymmetric key signature algorithms, I think their priority tables for asymmetric key signature algorithms selection should be same. But currently they are different(Line44 and Line62).

https://github.com/DMTF/libspdm/blob/68169b89611ee04ec7a8de3a12ae80e97b881dfa/library/spdm_responder_lib/algorithms.c#L44-L78

**Comment by jyao1** [comment]
Most likely, the requester is host. The responder is device. I think it is OK to use different policy.  

Also we are discussing priority at https://github.com/DMTF/libspdm/discussions/121.

**Comment by Zhiqiang520** [comment]
OK, got it. Agree.

**Comment by jyao1** [comment]
11/8/21 - prefer to be same by default. but allow it be overridden to be different.

**Comment by Wenxing-hou** [comment]
I will check it.
