### ISSUE TITLE
PCIe VDM Transport

### ISSUE THREAD

**Issue by Kendidi** [DMTF/libspdm#2461]
Hi,

Does _libspdm_ support **PCIe VDM Transport**?
I currently have a server that contains a BMC.  I wonder can host (running Ubuntu) send **SPDM over PCIe VDM** messages to PCIe device (plugged to a PCIe slot on motherboard) through BMC with this _libspdm_. Thanks.

**Comment by Kendidi** [comment]
@steven-bellock Thanks. Any recommendation on how to send SPDM over PCIe VDM messages to PCIe device (plugged to a PCIe slot on motherboard) through BMC?

**Comment by steven-bellock** [comment]
https://github.com/openbmc/openbmc would be a good place to ask.

**Comment by Kendidi** [comment]
Thanks @steven-bellock !
