### ISSUE TITLE
Potential out-of-bounds write with MbedTLS

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2467]
The value of `LIBSPDM_MAX_HASH_SIZE` is adjusted based on the largest supported SHA algorithm : https://github.com/DMTF/libspdm/blob/955350eff19ff9cf2af29663b5407bb7e9cede57/include/library/spdm_crypt_lib.h#L60-L66

This value is used to allocate memory, for example https://github.com/DMTF/libspdm/blob/955350eff19ff9cf2af29663b5407bb7e9cede57/library/spdm_common_lib/libspdm_com_crypto_service.c#L759

This memory gets passed to MbedTLS and its `mbedtls_sha512_finish_ret` function which states 
```
 * \param output   The SHA-384 or SHA-512 checksum result.
 *                 This must be a writable buffer of length \c 64 Bytes.
 ```

In the case of `LIBSPDM_SHA384_SUPPORT` the value of `LIBSPDM_MAX_HASH_SIZE` is `48` which is in violation of the function's precondition. Note that this issue is "fixed" in more recent [versions of Mbed TLS ](https://github.com/Mbed-TLS/mbedtls/blob/90d07118ad0108b9d1f61524173d801c6e8ce781/include/mbedtls/sha512.h#L121-L123) where the size of the buffer is conditional based on whether the context is 384 or 512.

Note that, at least for the [version of Mbed TLS that libspdm currently uses as a sub-module](https://github.com/Mbed-TLS/mbedtls/blob/dd79db10014d85b26d11fe57218431f2e5ede6f2/library/sha512.c#L431-L440) this out-of-bounds write does not occur if the context is 384.

**Comment by jyao1** [comment]
I think we need to fix mbedtls stub - https://github.com/DMTF/libspdm/blob/main/os_stub/cryptlib_mbedtls/hash/sha.c#L365

**Comment by jyao1** [comment]
Another way is to upgrade to mbedtls 3.x.

**Comment by steven-bellock** [comment]
This issue has been resolved by transitioning to Mbed TLS 3.
