### ISSUE TITLE
null cryptlib

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#247]
Should we provide a null version of cryptlib under os_stub? This would be a copy of cryptlib_mbedtls\cryptlib_openssl, but have just empty top level functions that only assert and return failure. This would perhaps save a step for clients that wish to use their own internal crypto libraries?

**Comment by jyao1** [comment]
Good idea.
It can be a template for cryptolib_pkcs11 in the future (https://github.com/DMTF/libspdm/issues/1)

**Comment by steven-bellock** [comment]
This is also a solution for a Responder that does not support cryptography.
