### ISSUE TITLE
Convert // comments to /* */ comments

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#249]

**Comment by jyao1** [comment]
Hey
I know other project does not like /* */ and convert to //.

Any special reason for this issue?

**Comment by steven-bellock** [comment]
// was introduced with C99. C89 only supports /* */, and it's something that the integrator can't override.

**Comment by jyao1** [comment]
I see your point. Agree.

**Comment by Wenxing-hou** [comment]
I will check it.
