### ISSUE TITLE
[SPDM 1.3] The code should check the `CertModel` and `KeyUsageMask` for slot 0 in the received DIGESTS response message.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2490]
The code should check the `CertModel` and `KeyUsageMask` for slot 0 in the received DIGESTS response message.

1. Refer to the paragraph `354` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/5c82fd9b-ec15-4009-9531-d202564b2ac2)

2. Refer to the paragraph `374` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/05952797-ef5c-477e-b3b9-b5f19b53e118)

3. But the code will not check the `CertModel` and `KeyUsageMask` for slot 0 in the received DIGESTS response message.
I think may we should add check the `CertModel` and `KeyUsageMask` for slot 0 (when `index` == 0) at the following block line 283~292.
https://github.com/DMTF/libspdm/blob/159ecd11d70f09c16fe0278821c80513dc99b4bd/library/spdm_requester_lib/libspdm_req_get_digests.c#L278-L295

4. We have created test case to catch this issue: `libspdm_test_requester_get_digests_case28`.
https://github.com/DMTF/libspdm/pull/2489

**Comment by jyao1** [comment]
1) Agree. No-Cert, Cert, Alias Cert is allowed. Generic Cert is NOT allowed.
2) Agree. 

4) test case has bug: Non cert should be allowed.
See spec:
356: Slot 0 shall contain a valid
certificate chain unless the device has not yet had a certificate chain provisioned and is in a trusted environment.

**Comment by Zhiqiang520** [comment]
@jyao1 
> 4.1) test case has bug 0x1A: key_usage_bit_mask is 0.

Agree. Sorry for missing the config of `key_pair_id`, `cert_info` and `key_usage_mask`. 
I saw your PR https://github.com/DMTF/libspdm/pull/2502 has fixed this test case bug. Thanks a lot.


> 4.2) test case has bug 0x1C: Non cert should be allowed.

Agree. We have update our PR https://github.com/DMTF/libspdm/pull/2489
