### ISSUE TITLE
[SPDM 1.3] If a certificate chain is not present in this slot, the value of Digest field shall be all zeros.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2492]
If a certificate chain is not present in this slot, the value of Digest field shall be all zeros.

1. Refer to the paragraph 369 `Table 35 — Successful DIGESTS response message format` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/dcf23c02-94a5-4b20-a976-dc1103a00573)

2. I think the above highlight case is matching with the following state `3.  Exists with key `.
Refer to the paragraph 366 In [DSP0274_1.3.0.pdf].
![image](https://github.com/DMTF/libspdm/assets/90754803/4360c4b7-f7ac-4051-959b-0c7e520bf48e)
Refer to the paragraph 371 `Table 36 — Certificate info` In [DSP0274_1.3.0.pdf].
![image](https://github.com/DMTF/libspdm/assets/90754803/ebccddcd-0c66-4ee1-ac9b-38842e60441a)

3. But the requester will not check whether the received digest value is zero or not for state `3.  Exists with key `, just directly `libspdm_copy_mem` and save. at the following line 258-259, and line 268-271.
https://github.com/DMTF/libspdm/blob/159ecd11d70f09c16fe0278821c80513dc99b4bd/library/spdm_requester_lib/libspdm_req_get_digests.c#L257-L271

4. We have created test case to catch this issue: `libspdm_test_requester_get_digests_case29`.
https://github.com/DMTF/libspdm/pull/2489

**Comment by jyao1** [comment]
@Zhiqiang520 , libspdm_test_requester_get_digests_case29() can pass now.

How does it catch the issue?

**Comment by Zhiqiang520** [comment]
@jyao1 
Base on your PR https://github.com/DMTF/libspdm/pull/2502, we tried `libspdm_test_requester_get_digests_case29()`, then fixed the test case bug and updated our PR https://github.com/DMTF/libspdm/pull/2489, please check the latest.
