### ISSUE TITLE
[SPDM 1.3] The `SlotID` fields shall not specify this certificate slot when the corresponding `Key Usage` is not set.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2495]
The `SlotID` fields **shall not** specify this certificate slot when the corresponding `MULTI_KEY_CONN_REQ` or `MULTI_KEY_CONN_RSP` is true and the corresponding `Key Usage` is not set, for CHALLENGE, MEASUREMENTS, KEY_EXCHANGE and so on.

1. Refer to the paragraph 373 `Table 37 — Key usage bit mask` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/84b606d4-d368-4887-a474-7da61c7a0d49)

2. For example, `slot_id` received from CHALLENGE request message at line 94 was directly set to `auth_attribute` without checking its corresponding `Key Usage` at line 141.
https://github.com/DMTF/libspdm/blob/159ecd11d70f09c16fe0278821c80513dc99b4bd/library/spdm_responder_lib/libspdm_rsp_challenge_auth.c#L94
https://github.com/DMTF/libspdm/blob/159ecd11d70f09c16fe0278821c80513dc99b4bd/library/spdm_responder_lib/libspdm_rsp_challenge_auth.c#L139-L141

**Comment by jyao1** [comment]
@Zhiqiang520 please create a test for that.

**Comment by Zhiqiang520** [comment]
@jyao1 We have created test cases to catch this issue.
https://github.com/DMTF/libspdm/pull/2518
