### ISSUE TITLE
[SPDM 1.3] What is their expect `cert_model` in `CERTIFICATE` response attributes for `DeviceCert` model and `AliasCert` model if `MULTI_KEY_CAP` is not set?

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2497]
What is their expect `cert_model` in `CERTIFICATE` response attributes for `DeviceCert` model and `AliasCert` model if `MULTI_KEY_CAP` is not set?

1.  Currently if `MULTI_KEY_CONN_RSP` is false and `cert_model != 0` in `CERTIFICATE` response attributes, then report error `status = LIBSPDM_STATUS_INVALID_MSG_FIELD` at the following line 246-249.
https://github.com/DMTF/libspdm/blob/159ecd11d70f09c16fe0278821c80513dc99b4bd/library/spdm_requester_lib/libspdm_req_get_certificate.c#L233-L251

2. It looks like the above mentioned code behavior is following the highlight in 371 `Table 36 — Certificate info` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/251644e7-8e13-4026-9020-c73eefe9f847)

3. But for `DeviceCert` model and `AliasCert` model, if `MULTI_KEY_CAP` is not set, what is their expect `cert_model` in `CERTIFICATE` response attributes? still zero?
![image](https://github.com/DMTF/libspdm/assets/90754803/5232ae76-182d-4fb8-9120-3fb31a5ab7f6)

**Comment by steven-bellock** [comment]
I think the specification is clear that it is `0`. However libspdm has an issue that I'll file a separate issue for. For the specification it sounds like if `MULTI_KEY_CAP` is set then `ALIAS_CERT_CAP` is effectively ignored. I wonder if `MULTI_KEY_CAP` is set then `ALIAS_CERT_CAP` must be `0`.

**Comment by jyao1** [comment]
> I wonder if MULTI_KEY_CAP is set then ALIAS_CERT_CAP must be 0.

I filed https://github.com/DMTF/SPDM-WG/issues/3311 to clarify.

**Comment by jyao1** [comment]
@Zhiqiang520 , the answer to your question is clear.

Please design test case for the check.

**Comment by Zhiqiang520** [comment]
> I think the specification is clear that it is 0.

@steven-bellock Sorry, I disagree. the specification is **NOT** clear.

1. for scenario `MULTI_KEY_CAP` is not set, the paragraph `371 Table 36 — Certificate info` is **inconsistent with** the paragraph `352` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf). 
Why we follow the paragraph 371 and ignore the paragraph 352?

2. for the paragraph `371 Table 36 — Certificate info` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf). 
Its `Field` name is `CertModel`.
I think it make sense that Value of 0 **just** indicates that the certificate slot does not contain any certificates.
But I don't understand why Value of 0 also can indicates that the corresponding `MULTI_KEY_CONN_REQ` or `MULTI_KEY_CONN_RSP` is false.
> Value of 0 indicates either that the certificate slot does not contain any certificates or that the corresponding
MULTI_KEY_CONN_REQ or MULTI_KEY_CONN_RSP is false.

**Comment by jyao1** [comment]
I filed https://github.com/DMTF/SPDM-WG/issues/3313

**Comment by steven-bellock** [comment]
In 352 / 353 all instances of `MULTI_KEY_CAP` should be changed to at least `MULTI_KEY_CONN_RSP`; maybe also include `MULTI_KEY_CONN_REQ`, but Requesters don't have `ALIAS_CERT_CAP`.

**Comment by Zhiqiang520** [comment]
Based on https://github.com/DMTF/SPDM-WG/issues/3313
Clarify in paragraph 352 that when multi-key is not in use, the `CertModel` field is set to 0.

So close this issue.
