### ISSUE TITLE
Are all the configuration flags are enabled to use mbedtls library for generating CSR?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2506]
If yes, where are the flags defined so that those flags are included in the build?

**Comment by steven-bellock** [comment]
The only flag needed to generate CSRs in MbedTLS is `LIBSPDM_CERT_PARSE_SUPPORT` which is enabled in the [default configuration file](https://github.com/DMTF/libspdm/blob/4ccf4c75ce0aeac6929f9e489c83705d1d059901/include/library/spdm_lib_config.h#L198-L200).

**Comment by PrakashK94** [comment]
I am asking about mbedtls configuration that needs to be enabled in order to generate the CSR.

**Comment by PrakashK94** [comment]
So libspdm considers whatever defined as 1 to be included in the build which is present in this file right?
https://github.com/DMTF/libspdm/blob/main/os_stub/mbedtlslib/include/mbedtls/config.h

**Comment by steven-bellock** [comment]
@PrakashK94 if this question is answered then please close it.
