### ISSUE TITLE
[SPDM 1.3] If `MULTI_KEY_CONN_RSP` is true, then Value of 0 `CertModel` indicates that the certificate slot does not contain any certificates.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2512]
If `MULTI_KEY_CONN_RSP` is **true**, then Value of 0 `CertModel` indicates that the certificate slot does not contain any certificates.

1. Refer to the paragraph `371 Table 36 — Certificate info` In [DSP0274_1.3.0.pdf].
![image](https://github.com/DMTF/libspdm/assets/90754803/ef028443-0231-4846-983f-33e51e0f35ad)
2. We have created test case `/* Sub Case 5: CertModel Value of 0 , MULTI_KEY_CONN_RSP is true*/` in `libspdm_test_requester_get_certificate_case30`.
**Input**: 
`MULTI_KEY_CONN_RSP` is true;
received response: `CertModel` Value is **0** but certificate chain is **present**.
**Expect output**:
 `LIBSPDM_STATUS_INVALID_MSG_FIELD`
**Actual output**: 
`LIBSPDM_STATUS_SUCCESS`
https://github.com/DMTF/libspdm/pull/2511

**Comment by steven-bellock** [comment]
If `SlotSizeRequested == 0` and the slot exists but is not populated with a certificate chain then I'd imagine the Responder would return an `ERROR` response, but I guess it can also send a `CERTIFICATE` response as well.
