### ISSUE TITLE
Questions on certificate chains

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2516]
The signing algorithm that requestor and responder agreeing to is the signing algorithm that has been used in leaf certifictates to sign or is it a signing algorithm that has been used for all the cerificates to sign?

I understand from the negotiate algorithm is, From requestor, Requestor says I am supporting ECDSA256 & ECDSA384 and Responder says that I am supporting ECDSA256 signing algorithm, so both agrees to ECDSA256 signing algorithm for further SPDM flow. But I see in there are so many vendors that produces certificates using different signing algorthm across different certificates like for Root certificates they have been using ECDSA512 and for other intermediate certificates they have been using ECDSA384 and then for the last certificate they are using ECDSA256 and says I am only supporting ECDSA256 signing algorithm in Negotiate algorithm response. Is that a valid case?

**Comment by steven-bellock** [comment]
>Is that a valid case?

Yes, the root certificate will not know what algorithms downstream certificates will support, in particular the algorithm of the Responder's leaf certificate(s). The OCP Attestation specification has a recommendation that folks try and keep the algorithms somewhat consistent throughout the certificate chain, but that may not be possible. A general purpose Requester / Verifier will need to support many algorithms if it wants to validate a certificate chain from root to leaf.

**Comment by PrakashK94** [comment]
ok thanks.
