### ISSUE TITLE
Which error code should a responder return in v1.1 when response message is larger than buffer

### ISSUE THREAD

**Issue by mcsmonk** [DMTF/libspdm#2522]
Due to my ambiguous question(https://github.com/DMTF/SPDM-WG/issues/3304), I issue this question again in here

Which error code should a responder return in v1.1 when response message is larger than buffer?

Because there is no large SPDM message mechanism in version 1.1, there is no appropriate error code such as `ResponseTooLarge`, which is a error code in version 1.2

**Comment by steven-bellock** [comment]
> is larger than buffer?

Whose buffer? Requester's, Responder's, or both?

**Comment by mcsmonk** [comment]
I mean, in case the responder's buffer is smaller than MEASUREMENTS response message on all measurements

**Comment by steven-bellock** [comment]
>I mean, in case the responder's buffer is smaller than MEASUREMENTS response message on all measurements

If a Responder cannot send a message that it has advertised support for in its capabilities, then that is a design / configuration bug and the Responder should not be let into (general purpose) production. Absent that, `Unspecified` would be the only error message that makes sense.
