### ISSUE TITLE
The current actual result in libspdm(spdm_requester_lib) about `MEL_CAP` and `MELspecification` is right or wrong?

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2531]
1. The current actual result in libspdm(spdm_requester_lib) of the following 8 scenarios about `MEL_CAP` and `MELspecification` is right or wrong?

No. | MEL_CAP   in Responder | MELspecification   in NEGOTIATE_ALGORITHMS | MELspecificationSel   in received ALGORITHMS | Actual   result in libspdm(spdm_requester_lib) | Related description in DSP0274_1.3.0.pdf
-- | -- | -- | -- | -- | --
1 | set | DMTFmelSpec | DMTFmelSpec | LIBSPDM_STATUS_SUCCESS | The Responder shall select one of the MEL specifications supported by the Requester and Responder. The selected MEL specification ( MELspecificationSel ) is used in construction of the MEL. 
2 | set | DMTFmelSpec | 0 | LIBSPDM_STATUS_INVALID_MSG_FIELD | Same as above 
3 | set | 0 | DMTFmelSpec | LIBSPDM_STATUS_SUCCESS | Same as above 
4 | set | 0 | 0 | LIBSPDM_STATUS_SUCCESS | Same as above 
5 | Not set | DMTFmelSpec | DMTFmelSpec | LIBSPDM_STATUS_SUCCESS | Same as above 
6 | Not set | DMTFmelSpec | 0 | LIBSPDM_STATUS_SUCCESS | Same as above 
7 | Not set | 0 | DMTFmelSpec | LIBSPDM_STATUS_SUCCESS | Same as above 
8 | Not set | 0 | 0 | LIBSPDM_STATUS_SUCCESS | Same as above 

2. Checked on:
https://github.com/DMTF/libspdm/blob/01a8c0c46e4cfb277076322b821c3a241a2d0010/library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c#L573-L584

**Comment by jyao1** [comment]
Reviewed in meeting: (Same for MEAS_CAP)


No. | MEL_CAP   in Responder | MELspecification   in NEGOTIATE_ALGORITHMS | MELspecificationSel   in received ALGORITHMS | Actual   result in libspdm(spdm_requester_lib) | Related description in DSP0274_1.3.0.pdf
-- | -- | -- | -- | -- | --
1 | set | DMTFmelSpec | DMTFmelSpec | LIBSPDM_STATUS_SUCCESS | The Responder shall select one of the MEL specifications supported by the Requester and Responder. The selected MEL specification ( MELspecificationSel ) is used in construction of the MEL. 
2 | set | DMTFmelSpec | 0 | LIBSPDM_STATUS_INVALID_MSG_FIELD | Same as above 
3 | set | 0 | DMTFmelSpec | LIBSPDM_STATUS_INVALID_MSG_FIELD | Same as above 
4 | set | 0 | 0 | LIBSPDM_STATUS_SUCCESS | Same as above 
5 | Not set | DMTFmelSpec | DMTFmelSpec | LIBSPDM_STATUS_INVALID_MSG_FIELD | Same as above 
6 | Not set | DMTFmelSpec | 0 | LIBSPDM_STATUS_SUCCESS | Same as above 
7 | Not set | 0 | DMTFmelSpec | LIBSPDM_STATUS_INVALID_MSG_FIELD | Same as above 
8 | Not set | 0 | 0 | LIBSPDM_STATUS_SUCCESS | Same as above

**Comment by jyao1** [comment]
@Zhiqiang520 , could you please design some cases to see if there is anything wrong?

**Comment by Zhiqiang520** [comment]
@jyao1 We have added test cases and caught something wrong.
https://github.com/DMTF/libspdm/pull/2534

**Comment by Xiaohanjlll** [comment]
I have submitted a PR to fix this issue @jyao1
