### ISSUE TITLE
Need to disable LIBSPDM_ENABLE_VENDOR_DEFINED_MESSAGES by default

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#2532]
After https://github.com/DMTF/libspdm/pull/2429 is merged, LIBSPDM_ENABLE_VENDOR_DEFINED_MESSAGES  is enabled by default.

It will cause IDE_KM or TDISP message fail without the change, which breaks compatibility.

See https://github.com/DMTF/spdm-emu/issues/328

**Comment by jyao1** [comment]
@uvinrg , could you please provide a patch for https://github.com/DMTF/spdm-emu/issues/328

**Comment by uvinrg** [comment]
Hi @jyao1 I created a pull request that should fix backwards-compatibility with Vendor Commands.

**Comment by jyao1** [comment]
@uvinrg , thank you very much. We will look into it.
