### ISSUE TITLE
requester lib doesn't fill OtherParamsSupport field right when version is 0x12.

### ISSUE THREAD

**Issue by longlongyang** [DMTF/libspdm#2539]
building spdm-emu from here: https://github.com/DMTF/spdm-emu  
then run commands
```
./spdm_responder_emu
./spdm_requester_emu --ver 1.2
```

by inspecting the log, it shows, in negotiate algorithm request data, the value of OtherParamsSupport field is 0x12, while the Bits [7:4] is marked as Reserved by spdm spec 1.2.1: https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.1.pdf

libspdm_send_spdm_request[0] msg SPDM_NEGOTIATE_ALGORITHMS(0xe3), size (0x30): 
0000: 12 e3 04 00 30 00 01 12 90 00 00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0020: 02 20 1b 00 03 20 06 00 04 20 0f 00 05 20 01 00

**Comment by jyao1** [comment]
@Zhiqiang520 , please consider adding a test case.

**Comment by Zhiqiang520** [comment]
@jyao1 
We have add test cases for this issue.
https://github.com/DMTF/libspdm/pull/2559
