### ISSUE TITLE
Incorrect measurements buffer size hashed in spdm_generate_measurement_summary_hash

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#254]
It looks like the **spdm_generate_measurement_summary_hash** may be calculating wrong the size of the measurements data to be hashed. If you look in the for loop below, the measurements are coped from the **device_measurement** buffer to the **measurement_data** buffer.  The **measurement_data** buffer is uninitialized and filled with random data.  In each iteration of the for loop, the **measurment_data_size** (location in **measurement_data** buffer to copy next) is advanced, even if there was no copy, as the copy is in the previous if statement.  This results in the **measurement_data** up to **measurement_data_size** used in the **spdm_hash_all** function call to contain random garbage data.

To fix this, I believe the incrementing of the **measurment_data_size** value should also be moved into the "if" statement right after the copy.  Can someone else confirm this is a bug?

```
 **spdm_generate_measurement_summary_hash** 
...
		cached_measurment_block = (void *)device_measurement;
		measurment_data_size = 0;
		for (index = 0; index < device_measurement_count; index++) {
			measurment_block_size =
				sizeof(spdm_measurement_block_common_header_t) +
				cached_measurment_block
					->Measurement_block_common_header
					.measurement_size;
			// filter unneeded data
			if (((measurement_summary_hash_type ==
			      SPDM_CHALLENGE_REQUEST_ALL_MEASUREMENTS_HASH) &&
			     ((cached_measurment_block
				       ->Measurement_block_dmtf_header
				       .dmtf_spec_measurement_value_type &
			       SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_MASK) <
			      SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_MEASUREMENT_MANIFEST)) ||
			    ((cached_measurment_block
				      ->Measurement_block_dmtf_header
				      .dmtf_spec_measurement_value_type &
			      SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_MASK) ==
			     SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_IMMUTABLE_ROM)) {
				copy_mem(
					&measurement_data[measurment_data_size],
					&cached_measurment_block
						 ->Measurement_block_dmtf_header,
					cached_measurment_block
						->Measurement_block_common_header
						.measurement_size);**
			}
			measurment_data_size += // This should be moved into the "if" statement above right after the copy_mem??
				cached_measurment_block
					->Measurement_block_common_header
					.measurement_size;
			cached_measurment_block =
				(void *)((uintn)cached_measurment_block +
					 measurment_block_size);
		}
		**spdm_hash_all(
			spdm_context->connection_info.algorithm.base_hash_algo,
			measurement_data, measurment_data_size,
			measurement_summary_hash);**
```

**Comment by jyao1** [comment]
Confirmed. It is a bug.

Since you are working on measurement related stuff, would you please help to fix it?

**Comment by rkongintel** [comment]
Yes. I can fix it.

**Comment by rw8896** [comment]
@rkongintel @jyao1 Thanks for the finding.
It's a little bit difficult to trace the code.
Maybe we could also simplify it when Richard fix this issue, e.g.

```
			// filter unneeded data
			uint8_t measurement_type = cached_measurment_block
				       ->Measurement_block_dmtf_header
				       .dmtf_spec_measurement_value_type &
			       SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_MASK;

			if (((measurement_summary_hash_type == SPDM_CHALLENGE_REQUEST_ALL_MEASUREMENTS_HASH) &&
			     (measurement_type < SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_MEASUREMENT_MANIFEST)) ||
			    (measureement_type == SPDM_MEASUREMENT_BLOCK_MEASUREMENT_TYPE_IMMUTABLE_ROM)) 
```

Tracing the code I think this issue could happen when CHALLENGE command requests "TCB measurement hash" and the responder has not only the "Immutable ROM" but also other measurements, is that correct?
Assume all measurements are valid (by valid I mean measurement_type is valid), do you think of other scenarios hitting this error?

I also have two follow-up questions about this code.
1) why MEASUREMENT_TYPE_MEASUREMENT_MANIFEST is excluded from ALL_MEASUREMENTS_HASH?
2) could we allow users to customize the TCB measurements (currently only IMMUTABLE_ROM is counted as TCB measurement)?

Thanks,
Ray

**Comment by rw8896** [comment]
@jyao1 @rkongintel 

I looked into the code a little more.

Maybe we could add a parameter in spdm_measurement_collection_func to specify the measurement type(TCB or ALL for now)?
- So user could decide which components should be included in TCB hash.
- spdm_generate_measurement_summary_hash doesn't need to filter not needed measurement blocks. (it could still check if the DMTFSpecMeasurementValueType is valid though)

**Comment by rkongintel** [comment]
@rw8896 
I can fix the bug first then simplify the code as a part of another refactoring in a separate pull request.  

I had the same questions about the "if" statement you referenced above. I think @jyao1  can answer them.

Regarding the parameter to spdm_measurement_collection, I've added a "measurement_index" parameter in a different pull request [https://github.com/DMTF/libspdm/pull/251](https://github.com/DMTF/libspdm/pull/251) for optimizing the get measurements code path. 

We could revisit for this code path after that pull request is in and we understand what the branches in the "if" statement you were asking about.  

Even if the code needs to filter the measurements by type, I was going to put in a change to use a single buffer rather than copying between two.

**Comment by jyao1** [comment]
I think we need move spdm_generate_measurement_summary_hash() to the https://github.com/DMTF/libspdm/blob/main/include/library/spdm_device_secret_lib.h.

It should be determined by the device vendor.
