### ISSUE TITLE
`libspdm_gen_csr_ex` is missing parameter for `KeyPairID`.

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2550]
https://github.com/DMTF/libspdm/blob/9d562f4ba0cdf234fb654d34c12a457ee585be0d/include/hal/library/responder/csrlib.h#L103-L110

I think this should be fixed in 3.2.1 and highlighted as a necessary API-breaking change.

@jyao1 @twilfredo

**Comment by jyao1** [comment]
> I think this should be fixed in 3.2.1 and highlighted as a necessary API-breaking change.

Agree.
