### ISSUE TITLE
Certificate chain verification fails

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2552]
Please find the attached certificate chain and could you please check and let us know why certificate verification fails?

[CertificateChain.zip](https://github.com/DMTF/libspdm/files/14135963/CertificateChain.zip)

**Comment by steven-bellock** [comment]
This is part of the `CERTIFICATES` response? If so
- Is the entire SPDM certificate chain formatted as defined in the specification? With `Length`, `RootHash`, and `Certificates` fields?
- Is the `Certificates` field ASN.1 DER-encoded?

**Comment by PrakashK94** [comment]
Yes

**Comment by Wenxing-hou** [comment]
Refer to the `libspdm_x509_common_certificate_check` API, please check where the failure occurred. Then we can tell you the possible reasons.
In addition, how do you enroll the cert? Is the Cert form the unit_test/sample_key? Or is the Cert generated by yourself?

**Comment by steven-bellock** [comment]
In the root certificate I see
>Validity
Not Before: Bad time value
Not After : Bad time value

So that would be flagged as a validation error. Also the `Issuer` and `Subject` are `NULL`.

**Comment by steven-bellock** [comment]
Also the serial number of any of the certificates cannot be `0`.
>The serial number MUST be a positive integer assigned by the CA to each certificate.

**Comment by PrakashK94** [comment]
But it fails while validating intermediate certificate. I see no problem in intermediate certificate. Do you see any problem in that?

**Comment by PrakashK94** [comment]
> Refer to the `libspdm_x509_common_certificate_check` API, please check where the failure occurred. Then we can tell you the possible reasons. In addition, how do you enroll the cert? Is the Cert form the unit_test/sample_key? Or is the Cert generated by yourself?

Yes, we generated the certificate using mbedtls library.

**Comment by steven-bellock** [comment]
@PrakashK94 you can verify a certificate chain using OpenSSL's `openssl verify` command. Once that is clean, if there are still failures, then we can look at them more closely.

**Comment by PrakashK94** [comment]
Yes, we are able to verify it using openssl command.

**Comment by PrakashK94** [comment]
I have attached the script which verifies all three certificates present in the attached certificate chain using openssl command.

Please find the logs below,

ranjithkumara@BFGIND-9848 MINGW64 /e/DICE/Certificate_chain/RootCert/Certificates/SPDM_received_certificate/6-2-24
$ ./cverify.sh
v--------------------------------------------------------v
certificate: root.pem
 
verify using openssl:
note: if this fails it could be due to an incompatibility
between openssl and the device certificates
root.pem: OK
 
verify using pubkey, signature, and unsigned data:
Verified OK
^--------------------------------------------------------^
 
 
v--------------------------------------------------------v
certificate: inter.pem
 
verify using openssl:
note: if this fails it could be due to an incompatibility
between openssl and the device certificates
error inter.pem: verification failed
C = TW, O = AST, CN = Aspeed Tech
error 18 at 0 depth lookup: self signed certificate
 
verify using pubkey, signature, and unsigned data:
Verified OK
^--------------------------------------------------------^
 
 
v--------------------------------------------------------v
certificate: leaf.pem
 
verify using openssl:
note: if this fails it could be due to an incompatibility
between openssl and the device certificates
error leaf.pem: verification failed
C = IN, O = AMI, CN = American Megatrends
error 18 at 0 depth lookup: self signed certificate
 
verify using pubkey, signature, and unsigned data:
Verified OK
^--------------------------------------------------------^
[Verify.zip](https://github.com/DMTF/libspdm/files/14175660/Verify.zip)

**Comment by steven-bellock** [comment]
>which verifies all three certificates

It's obviously not successful.

>error 18 at 0 depth lookup: self signed certificate

**Comment by PrakashK94** [comment]
Does intermediate certificate should have,
1. CA equals to FALSE?
2. Subject Name and Issuer Name should not match?

**Comment by steven-bellock** [comment]
1. No.
2. Yes. And it is even stronger than that. The Issuer Name should match the Subject Name of the root certificate.

**Comment by PrakashK94** [comment]
1. Are you saying that CA can be true/false as well as for intermediate certificate?

**Comment by steven-bellock** [comment]
> Are you saying that CA can be true or false for intermediate certificate?

CA should be `TRUE`. From [5280](https://datatracker.ietf.org/doc/html/rfc5280):
>If certificate i is a version 3 certificate, verify that the basicConstraints extension is present and that cA is set to TRUE.
