### ISSUE TITLE
The wrong debug message

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#2553]
https://github.com/DMTF/libspdm/blob/eded450e4f2e569aecb41b378572bd7ce8b25549/library/spdm_requester_lib/libspdm_req_key_update.c#L186-L189

There is a wrong debug message output.
It was found when the other project use libspdm.

**Comment by steven-bellock** [comment]
@Wenxing-hou do you know how the other project prints these messages? If it's one of the C `*printf` functions then it should only print the `session_id`. From C99
>If the format is exhausted while arguments remain, the excess arguments are evaluated (as always) but are otherwise ignored.

However it would be good to be able to catch this during testing. I'll file a separate issue.

**Comment by Wenxing-hou** [comment]
The detail error message is:
![image](https://github.com/DMTF/libspdm/assets/87060980/fd2bc840-891f-456d-8955-6e41b9ababbf)

Thanks.

**Comment by steven-bellock** [comment]
Ah so they are checking the number of specifiers to the number of arguments. Yes, we should try and do the same.
