### ISSUE TITLE
How to test chunking features if transport layer supports maximum 32 bytes transmission between requestor and responder

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2569]
What value we should set to LIBSPDM_DATA_TRANSFER_SIZE?

Previously we use to set this value as 42 to test chunking support when transport layer supports more than 42 bytes of transmission between requestor and responder.

**Comment by steven-bellock** [comment]
The SPDM layer requires at least 42 bytes from the transport layer below it. If the transport layer cannot support that then you'll need to do "chunking" in the transport layer, ie send two 32 byte transport messages per SPDM chunk.

**Comment by PrakashK94** [comment]
ok thanks, closing this issue.
