### ISSUE TITLE
Question on SPDM 1.2 Chunking features

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#2585]
To test chunking features, we need to set, 
LIBSPDM_DATA_TRANSFER_SIZE to 42 in either the requestor/responder side or in both the sides.

But if we set only the above then I see, that we have another build option that was set to 64.
LIBSPDM_TRANSPORT_ADDITIONAL_SIZE to 64.

To do SPDM communication over I2C over MCTP, we need to set LIBSPDM_TRANSPORT_ADDITIONAL_SIZE to 8 right, since the MCTP header is 8 bytes.

Please correct my understanding if I am wrong.

**Comment by steven-bellock** [comment]
See https://github.com/DMTF/libspdm/blob/22a9055bf545ed225ad7648ded1decddc47b29a9/doc/user_guide.md?plain=1#L85-L91 For both 275 and 276 only one byte is needed for MCTP to specify the message type, either `0x05` for an unencrypted message or `0x06` for an encrypted message. If the message is encrypted then additional bytes are needed before the SPDM message for the 277 fields, such as Session ID.

**Comment by PrakashK94** [comment]
Let's assume we set the LIBSPDM_DATA_TRANSFER_SIZE to 42, in that case if the length of the SPDM request/response message is greater than 42, then it has to either send in chunks/get in chunks, but with this if the transport layer also has the limitation to send maximum 32 bytes at a time, then it will do again chunking and send it to the requestor/responder.

Please correct my understanding if it is wrong.

**Comment by steven-bellock** [comment]
That is correct.
