### ISSUE TITLE
Provisioned raw public key format is vendor defined

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#26]
From https://github.com/jyao1/openspdm/issues/173

SPDM 1.1 says
"The format of the provisioned public key is out of scope of this specification. Vendors can use proprietary formats or public key formats that other standards define, such as RFC7250 and RFC4716."

Suggest:
OpenSPDM implements a "raw_public_key_extract" API prototype and leaves to the integrator to implement.
input: raw public key of format defined by vendor
output: raw public key of the following format
256-bit ECC: 32-byte x || 32-byte y.
384-bit ECC: 48-byte x || 48-byte y.
2048-bit RSA: 256-byte n || 8-byte e.
3072-bit RSA: 384-byte n || 8-byte e.
4096-bit RSA: 512-byte n || 8-byte e.

The input is saved in "context" for transcript hash construction.
The output is saved in "context" for session establishment, mutual authentication, and other requests requiring signature.

This issue is depending on approval of SPDM issue
DMTF/Security-TF#1110

NOTE:
Current OpenSPDM uses X509 certificate based public key. The whole public key certificate is included in transcript hash calculation.
I think we can use ASN.1_subjectPublicKeyInfo defined in https://tools.ietf.org/html/rfc7250.
Maybe we take a look at the openssl/mbedtls implementation on how to handle the raw keys.

**Comment by steven-bellock** [comment]
Closing as this is implementation-defined.
