### ISSUE TITLE
The definite form of length encoding shall be used, encoded in the minimum number of octets.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2600]
The definite form of length encoding shall be used, encoded in the **minimum** number of octets.

1. SPDM certificates also adhere to the requirements as [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280) defines.
Refer to the paragraph 394 In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/4694e945-b8a2-4625-b512-41fc8189fec1)

2. The data that is to be signed is encoded using the ASN.1 distinguished encoding rules (DER).
Refer to the [4.1](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1).  Basic Certificate Fields In [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280)
![image](https://github.com/DMTF/libspdm/assets/90754803/e296fe28-911f-44f1-ab74-c6f956c7f90d)

3. The definite form of length encoding shall be used, encoded in the **minimum** number of octets.
Refer to the 10.1 Length forms In [ITU-T Recommendation X.690](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.690-202102-I!!PDF-E&type=items)
![image](https://github.com/DMTF/libspdm/assets/90754803/3f6ee332-7ab5-4d3a-9266-232dc7730ea2)
![image](https://github.com/DMTF/libspdm/assets/90754803/a3e72a50-349f-4cea-8ad7-f51cb22c6a7f)

4. We have created a test case, the length octets using the long form instead of the short form.
https://github.com/DMTF/libspdm/pull/2595
We change the length of version element from `0x03`(short form) to `0x81 0x03`(long form) in the test case.
 due to the definite form of length encoding shall be used, encoded in the **minimum** number of octets, so the expected return of the 2nd call `libspdm_x509_certificate_check( )` is `false`, but the actual return is `true` now.
![image](https://github.com/DMTF/libspdm/assets/90754803/96d81f76-e132-4126-9b18-823992d39cd7)

**Comment by jyao1** [comment]
Discussed in SPDM Code TF, 2024/03/04 - It seems not a real issue, because even using long form encoding does not bring any negative impact. The openssl/mbedtls can parse it correctly. Prefer to keep it as is.
