### ISSUE TITLE
Question on checking KeyUsage in certificate

### ISSUE THREAD

**Issue by mcsmonk** [DMTF/libspdm#2638]
I read a test scenario in https://github.com/DMTF/SPDM-Responder-Validator/blob/main/doc/5.Certificate.md#case-55, which is not yet implemented, and the next code https://github.com/DMTF/libspdm/blob/d6a800391260d31f973a12e59fa9575066aee6d3/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1125-L1136

I'm wondering that this DMTF code implies that digital signature should be included in KeyUsage field in leaf certificate. Why is there no other bit such as nonRepudiation, keyEncipherment, and keyAgreement?

**Comment by steven-bellock** [comment]
![image](https://github.com/DMTF/libspdm/assets/8474235/653b9cc0-fff7-4b5d-8478-083ad4b32be8)
has been in the specification since 1.0, and it only specifies digital signatures. As for why other bits aren't required by the specification, you would need to ask the SPDM Working Group.
