### ISSUE TITLE
Remove function pointer typedefs in spdm_device_secret_lib.h

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#264]
There are a few function pointer typedefs in spdm_device_secret_lib.h. 

spdm_measurement_collection_func, spdm_requester_data_sign_func, spdm_responder_data_sign_func, spdm_psk_hkdf_expand_func

We don't use the typedefs. There may have been some discussion around removing some function pointers for better security? Adding this to track.

**Comment by jyao1** [comment]
That is old code. it should be deleted.
