### ISSUE TITLE
`if (spdm_response_size < sizeof(spdm_supported_event_types_response_t))`, then `spdm_response->supported_event_groups_list_len` will overflow

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2642]
The checking `spdm_response_size` for `SUPPORTED_EVENT_TYPES` **response message** is not accurate.

1. I think we should change the code at the line 97
from
`if (spdm_response_size < sizeof(spdm_message_header_t)) {`
to
`if (spdm_response_size < sizeof(spdm_supported_event_types_response_t)) {`
https://github.com/DMTF/libspdm/blob/d6a800391260d31f973a12e59fa9575066aee6d3/library/spdm_requester_lib/libspdm_req_get_event_types.c#L96-L100

2. if `(spdm_response_size < sizeof(spdm_supported_event_types_response_t))`, then `spdm_response->supported_event_groups_list_len` will overflow at the line 121.
https://github.com/DMTF/libspdm/blob/d6a800391260d31f973a12e59fa9575066aee6d3/library/spdm_requester_lib/libspdm_req_get_event_types.c#L121-L123

**Comment by steven-bellock** [comment]
Since this must be sent in a secure session the response size must be exactly equal. The Responder portion already has this logic.

**Comment by steven-bellock** [comment]
The fix in the production code is easy. However there is an issue in `libspdm_test_encode_message` where padding is added to the SPDM message that causes the unit test to fail. I filed #2645 for that.
