### ISSUE TITLE
[SPDM 1.3] For `GenericCert` certificate models, `Signature Algorithm`, `Issuer`, `Subject Name`, `Validity` and `Key Usage` Fields is Optional, not Mandatory.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2656]
1. For `GenericCert` certificate models,
`Signature Algorithm`, `Issuer`, `Subject Name`, `Validity` and `Key Usage` Fields is **Optional**, **not Mandatory**.

Refer to the paragraph 397 `Table 42 — Field requirements` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/b6aeef01-025c-45ce-8172-5fd4dc754b0b)

2. But `libspdm_x509_common_certificate_check( )` function take `Issuer`, `Subject Name`, `Validity` and `Key Usage` Fields as **Mandatory** even for `GenericCert` certificate models.
https://github.com/DMTF/libspdm/blob/828ef62524bcaeca4e90d0c021221e714872e2b5/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1198-L1224
https://github.com/DMTF/libspdm/blob/828ef62524bcaeca4e90d0c021221e714872e2b5/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1041-L1111

**Comment by steven-bellock** [comment]
If a generic certificate only implemented the mandatory fields and did not implement the optional fields, would it pass the OpenSSL / Mbed TLS certificate chain validation functions?

**Comment by Wenxing-hou** [comment]
Hi all. 
 I have investigated the OpenSSL command cert generation.
For Signature Algorithm, Issuer, Subject Name, Validity and Key Usage Fields, I make a table.

| Optional field for GenericCert   | can be absent in when use OpenSSL command generate cert |
| :--------: | :-------: |
| Signature Algorithm | false    |
|  Issuer | false    |
| Subject Name    | false    |
|  Validity | false    |
| Key Usage    | true    |
