### ISSUE TITLE
SPDM 1.0 & SPDM 1.1 & SPDM 1.2 take `Basic Constraints` Field as Optional, but SPDM 1.3 take `Basic Constraints` Field as Mandatory.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2657]
1. SPDM 1.0 & SPDM 1.1 & SPDM 1.2 take `Basic Constraints` Field as **Optional**, but SPDM 1.3 take `Basic Constraints` Field as **Mandatory**.

- Refer to the paragraph 200 `4.9.2.4.2 Optional fields` in [DSP0274_1.0.2.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.0.2.pdf)

![image](https://github.com/DMTF/libspdm/assets/90754803/919eac62-e3d8-41d8-b762-fcfdbe2cc6f4)

- Refer to the paragraph 250 `Optional fields` in [DSP0274_1.1.3.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.1.3.pdf)

![image](https://github.com/DMTF/libspdm/assets/90754803/5c4c908e-1ef9-4949-945e-828734511228)

- Refer to the paragraph 330 `Table 32 — Optional fields` in [DSP0274_1.2.2.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.2.pdf)

![image](https://github.com/DMTF/libspdm/assets/90754803/76749aeb-8c4b-471e-ba3a-c57f01dba185)

- Refer to the paragraph 397 `Table 42 — Field requirements` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).

![image](https://github.com/DMTF/libspdm/assets/90754803/b37d8519-c00b-47b1-92a1-83a95af6a9d1)

2. But the code still take `Basic Constraints` Field as **Optional** in `libspdm_verify_leaf_cert_basic_constraints( )` function for SPDM1.3.
`return true` at the following line 764~765 when basic constraints is **not present** in cert.
https://github.com/DMTF/libspdm/blob/828ef62524bcaeca4e90d0c021221e714872e2b5/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1198-L1229
https://github.com/DMTF/libspdm/blob/828ef62524bcaeca4e90d0c021221e714872e2b5/library/spdm_crypt_lib/libspdm_crypt_cert.c#L737-L766

**Comment by steven-bellock** [comment]
This is also needed for `SET_CERTIFICATE`.
