### ISSUE TITLE
The checking for `Signature Algorithm` Fields is missed for `DeviceCert / AliasCert` certificate models.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2658]
The checking for `Signature Algorithm` Fields is missed for `DeviceCert / AliasCert` certificate models.

1. For `DeviceCert / AliasCert` certificate models, `Signature Algorithm` Fields is **Mandatory**.
Refer to the paragraph 397 `Table 42 — Field requirements` In [DSP0274_1.3.0.pdf](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.3.0.pdf).
![image](https://github.com/DMTF/libspdm/assets/90754803/5679e35b-6892-429d-9993-0ade2fc5ec0c)

2. But there is no checking for `Signature Algorithm` Fields in function `libspdm_x509_common_certificate_check( )` when certificate model is `DeviceCert` or `AliasCert`. 
I think `/* 3. Verify public key algorithm. */` at the following line 1083 is not the checking for `Signature Algorithm` Fields.
https://github.com/DMTF/libspdm/blob/828ef62524bcaeca4e90d0c021221e714872e2b5/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1041-L1095

3. I think maybe `libspdm_x509_common_certificate_check()` should call `libspdm_x509_get_signature_algorithm()` to get `Signature Algorithm`.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/ebb408ee596d8104269f82f6141a63fe7ec15482/library/spdm_crypt_lib/libspdm_crypt_cert.c#L532-L533 seems to return `false` if the `Signature Algorithm` field isn't present. So I would say that `libspdm_verify_cert_subject_public_key_info` does check it when the negotiated algorithm is not SM2.
