### ISSUE TITLE
Should the payload of spdm message for MCTP transport layer include MSG TYPE field?

### ISSUE THREAD

**Issue by sunzc** [DMTF/libspdm#2664]
## Should the payload of spdm message for MCTP transport layer include MSG TYPE field?

 
In `include/library/spdm_transport_mctp_lib.h`, 
```
/* Required sender/receive buffer in device io.
 * +-------+--------+---------------------------+------+--+------+---+--------+-----+
 * | TYPE  |TransHdr|      EncryptionHeader     |AppHdr|  |Random|MAC|AlignPad|FINAL|
 * |       |        |SessionId|SeqNum|Len|AppLen|      |  |      |   |        |     |
 * +-------+--------+---------------------------+------+  +------+---+--------+-----+
 * | MCTP  |    1   |    4    |   2  | 2 |   2  |   1  |  |  32  | 16|   0    |  60 |
 * +-------+--------+---------------------------+------+--+------+---+--------+-----+
 */
```

TYPE is part of the payload that is passed to MCTP transport layer, however, the MCTP transport layer(kernel mctp driver) will also add TYPE field before the payload, which will cause a problem on the responder side when **the Responder is not implemented using libspdm**, they would not expect an extra TYPE field. Note below is demo code of how transport layer send payload over mctp send msg API.

```
libspdm_return_t spdm_device_send_message_mctp(void *spdm_context,
                                               size_t request_size,
                                               const void *req,
                                               uint64_t UNUSED(timeout)) {
...
  struct sockaddr_mctp addr = {0};
  ssize_t rc;

  addr.smctp_family = AF_MCTP;
  addr.smctp_addr.s_addr = mctp_eid;
  addr.smctp_network = mctp_nid;
  addr.smctp_type = MCTP_MSG_TYPE_SPDM;
  addr.smctp_tag = MCTP_TAG_OWNER;

  rc = sendto(mctp_socket, req, request_size, 0,
              (struct sockaddr *)&addr, sizeof(addr));
  if (rc == -1) {
    debug_log("%s ERROR! socket sendto failed!\n", __func__);
    return LIBSPDM_STATUS_INVALID_PARAMETER;
  }
...
}
```

### ref1: DMTF MCTP Spec on MCTP Packet format
![image](https://github.com/DMTF/libspdm/assets/3291450/f4dbaaeb-4340-4b78-9f5d-8fe55e8fb2b9)

### ref2: DMTF MCTP SPDM BINDING
![image](https://github.com/DMTF/libspdm/assets/3291450/b170d68f-66bd-4120-b184-6fe4b1f777d6)

**Comment by steven-bellock** [comment]
@jyao1

**Comment by jyao1** [comment]
> when the Responder is not implemented using libspdm, they would not expect an extra TYPE field. 

I am confused on this statement. Why you think any responder other than libspdm `would NOT expect an extra TYPE field`? How you conclude that?

**Comment by sunzc** [comment]
We found this issue while testing a spdm requester using libspdm with a Responder that is not using libspdm.  During debugging, we found that both the MCTP transport layer and libspdm added MSG TYPE field. The responder complain about the redundant MSG TYPE field and treat it as ill-formatted SPDM message.

The point is, according to the spec, if I understand correctly,  MSG TYPE field should be added by the MCTP transport layer https://www.dmtf.org/sites/default/files/standards/documents/DSP0275_1.0.1.pdf. The SPDM payload should not include this field.

**Comment by rw8896** [comment]
According to the function descriptions, "The message is an SPDM message with transport layer wrapper", it's not simply a SPDM payload.

[/**
 * Send an SPDM transport layer message to a device.
 *
 * The message is an SPDM message with transport layer wrapper,
 * or a secured SPDM message with transport layer wrapper.
 *
](https://github.com/DMTF/libspdm/blob/45902d26104bb9eb8a7a54f41ddd2e0dceb566ea/include/library/spdm_common_lib.h#L466-L471)

**Comment by sunzc** [comment]
I understand that `spdm_device_send_message()` is trying to do some work for the transport layer, but currently it is doing partial but not all for MCTP transport layer. The question here is, in `include/library/spdm_transport_mctp_lib.h`, should the `TYPE` belongs to the `required sender/receive buffer in device io`?

```
/* Required sender/receive buffer in device io.
 * +-------+--------+---------------------------+------+--+------+---+--------+-----+
 * | TYPE  |TransHdr|      EncryptionHeader     |AppHdr|  |Random|MAC|AlignPad|FINAL|
 * |       |        |SessionId|SeqNum|Len|AppLen|      |  |      |   |        |     |
 * +-------+--------+---------------------------+------+  +------+---+--------+-----+
 * | MCTP  |    1   |    4    |   2  | 2 |   2  |   1  |  |  32  | 16|   0    |  60 |
 * +-------+--------+---------------------------+------+--+------+---+--------+-----+
 */
```

As the MCTP transport layer will add the `MCTP Header + MSG TYPE`, if libspdm also mark the `MSG TYPE` as required field, it will create some overlapping fields with MCTP transport layer and incompatibility with other SPDM Responder/Requester that is not implemented with libspdm.

The suggestion would be remove the `TYPE` field from  `include/library/spdm_transport_mctp_lib.h` and let the MCTP transport layer handle the 'TYPE' field that it is already handling for all different upper layer protocols (e.g., PLDM).

**Comment by sunzc** [comment]
It is doable to work around this in the device send/receive function. 

For example, on the sender side, 
- right shift the buffer pointer to skip the TYPE byte; 
-  decrease the message size by 1; 

On the receiver side, 
-  right shift the receive buffer to reserve one byte for TYPE field, set it to MCTP_TYPE; 
-  increase message size by 1;

Assumption: MAC field in the SPDM message is not calculated with TYPE field counted in `include/library/spdm_transport_mctp_lib.h`.

However, I have to pointed out that it is error prone and might create hidden bugs and potential incompatibility when not handled properly for the following reasons:
1) If a firmware developer is using libspdm on both requester and responder side, and use standard mctp kernel stack for handling message send/receive, she or he might not be able to detect the issue that there is an extra TYPE field introduced to the MCTP message, as both the sender and receiver added this TYPE field. The developer will believe the device send/recv function is implemented correctly without realizing the issue.
2) However, when the actual device shipped with the fw is used with some spdm requester/responder that is not implemented using libspdm, the extra TYPE field will cause issue as it is not expected.

I understand that it is the developer's fault to misunderstand the usage of libspdm's device send/recv function. But what I described could be a very common misuse of the library as it is hard to detect this one byte issue given that the developer is also using the standard mctp send/recv + standard libspdm device send/recv function.

**Comment by jyao1** [comment]
Without TYPE field, how the transport layer code knows it is normal SPDM or secure SPDM?

**Comment by sunzc** [comment]
I see, that make senses. Unless we can infer the TYPE from from spdm_context, we need to keep the TYPE field.

Hoping there will be some comment or reminder in the code to warn against feeding the payload directly to transport layer as the transport layer will add the msg TYPE field.

Thank you!
