### ISSUE TITLE
need move spdm_generate_measurement_summary_hash() to spdm_device_secret_lib

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#267]
It should be device policy to determine what is TCB hash and what is all Hash.

**Comment by rkongintel** [comment]
@rkongintel

**Comment by rkongintel** [comment]
I'm interpreting the request to move the function to also mean change the interface so we don't need to pass the entire context across.

**Comment by jyao1** [comment]
Right. Moving also means to make necessary change.
