### ISSUE TITLE
Use case to invalidate SPDM slot 0 certificate? 

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#2671]
Hello,

Slot_0 is programmed by the manufacturer in the secured environment and slot[1:7] can be programmed by customers.

For slot_0, invalidating the slot_0 is a used case? If Yes, when do we invalidate it?

Since the device cannot reprovisioned again, should we allow the invalidating option for slot_0?

Thanks,
Goutham

**Comment by steven-bellock** [comment]
Slot 0 contains the manufacturer's certificate and gives the device its identity that is tied to the manufacturer. For the most part it should not be invalidated. Maybe if the device gets RMAed back to the manufacturer they might update the slot 0 certificate. Also, if the device's private key gets leaked then, in addition to revoking the certificate, you could invalidate the slot.

**Comment by goutham23** [comment]
Thanks

**Comment by goutham23** [comment]
@steven-bellock 

I have a follow-up question.. Let us assume the device's private key gets leaked then, in addition to revoking the certificate, we invalidate the slot_0.
How do we handle CHALLENGE_AUTH request for this part after invalidating slot_0 ? private key will also be invalid, only way is to get the part back to manufacturer to re-program slot_0 certificate?

**Comment by steven-bellock** [comment]
>How do we handle CHALLENGE_AUTH request for this part after invalidating slot_0 ?

Device could
1. No longer function as an SPDM endpoint. Ie, it ignores SPDM requests.
2. Return some error to the Requester.

Note that in SPDM 1.0/1.1 the specifications assume Slot 0 is populated by default. Ie, if an endpoint does not have a Slot 0 certificate chain then it doesn't conform to the specification. That is relaxed in 1.2/1.3 due to `SET_CERTIFICATE`.

**Comment by goutham23** [comment]
Thanks.
We give the option for users to invalidate slot[0:7] from the host tool.
Should we disable the option of invalidating slot[0]? 
Maybe give the option only to invalidate slot[1:7]?

**Comment by steven-bellock** [comment]
That's a question for a group like [OCP Security](https://ocp-all.groups.io/g/OCP-Security).
