### ISSUE TITLE
Currently CI will not run the unit test `test_spdm_vendor_cmds` for `VENDOR_DEFINED_REQUEST` and `VENDOR_DEFINED_RESPONSE`.

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2677]
Currently CI will not run the unit test `test_spdm_vendor_cmds` for `VENDOR_DEFINED_REQUEST` and `VENDOR_DEFINED_RESPONSE`.
https://github.com/DMTF/libspdm/blob/main/unit_test/test_spdm_vendor_cmds/test_spdm_vendor_cmds.c

https://github.com/DMTF/libspdm/blob/266c3ca50b10df5f8aea3e90429e7b23b2e3cfd2/.github/workflows/build.yml#L180-L214
https://github.com/DMTF/libspdm/blob/266c3ca50b10df5f8aea3e90429e7b23b2e3cfd2/.github/workflows/code_coverage.yml#L28-L47

**Comment by jyao1** [comment]
Can we just merge it into `test_spdm_requester` or `test_spdm_responder`?

**Comment by steven-bellock** [comment]
Yes, they really don't need to be their own executable.
