### ISSUE TITLE
The authority and integrity verify should be in the same logic

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#2689]
Because the `verify_peer_spdm_cert_chain`  callback function will have both authority and integrity verify operation, the 
`libspdm_verify_peer_cert_chain_buffer_integrity` and `libspdm_verify_peer_cert_chain_buffer_authority` should in the same logic.

https://github.com/DMTF/libspdm/blob/908994f780bfc487b06ef534c09b4f97fa83b3ff/library/spdm_requester_lib/libspdm_req_get_certificate.c#L356-L379

**Comment by steven-bellock** [comment]
To rephrase
>`libspdm_verify_peer_cert_chain_buffer_authority` is called unconditionally, even if the Integrator has registered their own `verify_peer_spdm_cert_chain` function via `libspdm_register_verify_spdm_cert_chain_func`.

**Comment by steven-bellock** [comment]
Re-opening this issue, as this bug is also present in https://github.com/DMTF/libspdm/blob/05f59eb7d04cb67b139a949dbfc5338037cc790b/library/spdm_responder_lib/libspdm_rsp_encap_get_certificate.c#L191-L211
