### ISSUE TITLE
Question on libspdm_append_message_b.

### ISSUE THREAD

**Issue by IamSukwonKim** [DMTF/libspdm#2692]
When processing `DIGESTS` and `CERTIFICATE`, libspdm is appending to message b only when `session_info == NULL`, would someone explain the rationale for this?

https://github.com/DMTF/libspdm/blob/ceb880200dcb6d7e3f5ed88cb2f25445dda7e388/library/spdm_responder_lib/libspdm_rsp_certificate.c#L153-L170

https://github.com/DMTF/libspdm/blob/ceb880200dcb6d7e3f5ed88cb2f25445dda7e388/library/spdm_responder_lib/libspdm_rsp_digests.c#L163-L189

**Comment by jyao1** [comment]
message_b is only for transcript for CHALLENGE.

However, CHALLENGE is not supported inside of session.

**Comment by IamSukwonKim** [comment]
> message_b is only for transcript for CHALLENGE.
> 
> However, CHALLENGE is not supported inside of session.

Thank you. I understand the reason, but it seems like it would cause incorrect behavior in some situations.

Even if `CHALLENGE` is prohibited inside of seesion, `GET_DIGESTS/DIGESTS` and `GET_CERTIFICATE/CERTIFICATE` are allowed inside of session, the following sequence seems possible.

1. VCA
2. Runtime authentication
3. Session handshake
4. `GET_CERTIFICATE` inside of session.
5. `CHALLENGE` outside of session.

In this case, the current implementation leaves message_b empty. Shouldn't GET_CERTIFICATE be included in M1/M2?

**Comment by steven-bellock** [comment]
What happens in `Runtime authentication`?

**Comment by IamSukwonKim** [comment]
> > Shouldn't GET_CERTIFICATE be included in M1/M2?
> 
> No

Why? Is it based on the spec.?

> What happens in `Runtime authentication`?

`GET_CERTIFICATE/CERTIFICATE` and `CHALLENGE/CHALLENGE_AUTH` is processed.

**Comment by IamSukwonKim** [comment]
I've noticed that `L1/L2` is managed for each context inside the session and outside the session. For consistency, it makes sense to exclude `GET_DIGESTS/DIGESTS` and `GET_CERTIFICATE/CERTIFICATE` inside the session for `M1/M2`.

It would be nice if the specification was a bit clearer.
