### ISSUE TITLE
Add session ID parameter to `libspdm_vendor_response_callback_func`

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2694]
From #2681. 

The vendor response callback function may need to know whether the message was sent within a secure session, and if so, which secure session. Pass the session ID as new parameter that is not present by default.

**Comment by m-milinkovic** [comment]
Hi @steven-bellock,
Do you mind assigning this one to me?

**Comment by steven-bellock** [comment]
This was fixed by #2702.
