### ISSUE TITLE
Need reset MessageM for any interruption

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#27]
From https://github.com/jyao1/openspdm/issues/172

SPDM spec: Any communication between Requester and Responder other than a GET_MEASUREMENTS request or response resets L1/L2 computation to null.

Also reset MessageB/C for any interrupt:

If the Requester issued GET_MEASUREMENTS or KEY_EXCHANGE or FINISH or PSK_EXCHANGE or PSK_FINISH or KEY_UPDATE or HEARTBEAT or GET_ENCAPSULATED_REQUEST or DELIVER_ENCAPSULATED_RESPONSE or END_SESSSION request(s) and skipped CHALLENGE completion, M1 and M2 are reset to null .

Same criteria for MessageMutB/MutC

**Comment by rw8896** [comment]
Spec also mentioned "Completion of CHALLENGE resets M1 and M2." in the table of Request ordering and message transcript computation rules for M1/M2.

I don't seem to find this in the current implementation. Would you point me if it's implemented?

**Comment by liyi77** [comment]
@rw8896 
I dont find this feature too, It seems as a bug.
But it has nothing to do with interrupt, I submit another issue to solve it. #93
