### ISSUE TITLE
Defect in libspdm_x509_common_certificate_check cleanup action

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2700]
https://github.com/DMTF/libspdm/blob/ddfd7a1080cdbeffbe02267e6a164a0a3149be1a/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1151-L1152

The context to be freed is actually only used in get public key.
https://github.com/DMTF/libspdm/blob/ddfd7a1080cdbeffbe02267e6a164a0a3149be1a/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1119-L1123

It doesn't really need the goto cleanup in each verification step. context can simply be freed after get public key.

Otherwise, if any verification failed before get public key and it goes to cleanup,
the libspdm_asym_free may eventually call free_pool(context) to free a NULL/unallocated pointer.
Which will cause ASSERT according to free_pool() descriptions below.
https://github.com/DMTF/libspdm/blob/ddfd7a1080cdbeffbe02267e6a164a0a3149be1a/os_stub/include/library/malloclib.h#L56-L57

**Comment by steven-bellock** [comment]
Consistent with the C standard library's `free` function, if the pointer is `NULL` then `libspdm_asym_free` returns early.

https://github.com/DMTF/libspdm/blob/ddfd7a1080cdbeffbe02267e6a164a0a3149be1a/library/spdm_crypt_lib/libspdm_crypt_asym.c#L356-L360

**Comment by rw8896** [comment]
Thanks for clarification, my code base is old and libspdm_asym_free didn't have this check.
Yes, then it's not a defect, but maybe could be a enhancement to get rid of the unnecessary goto.

**Comment by steven-bellock** [comment]
The `goto` makes things consistent so I would say things are fine the way they are.
