### ISSUE TITLE
Add length check when traverse certchain in libspdm_x509_verify_cert_chain

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2701]
libspdm_x509_verify_cert_chain() assumes the input certchain is "One or more ASN.1 DER-encoded X.509 certificates" but it didn't traverse the whole certchain with the code below.
https://github.com/DMTF/libspdm/blob/ddfd7a1080cdbeffbe02267e6a164a0a3149be1a/os_stub/cryptlib_mbedtls/pk/x509.c#L711-L716

Should it add more check to make sure there is no more data left unchecked? E.g. 

if (ret != 0) { 
     if (current_cert < cert_chain + cert_chain_length)
           verify_flag = false;
     break; 
 }

**Comment by steven-bellock** [comment]
This is a case where the `length` field in the SPDM Certificate Chain Struct says the size of the certificate chain is `X`, but when the certificate chain is actually parsed the value is `Y`, where `Y < X`? And if that happens then that is considered an error? If we can't come up with any good reason why that should be allowed, then yeah, seems like an OK check.

**Comment by rw8896** [comment]
> This is a case where the `length` field in the SPDM Certificate Chain Struct says the size of the certificate chain is `X`, but when the certificate chain is actually parsed the value is `Y`, where `Y < X`?

Yes, or maybe there are gaps between certificates in the certificate chain, this function will stop before the gap and could also return true without traversing all the certificates down.

> And if that happens then that is considered an error?

Yes, I think it should be an error.

**Comment by jyao1** [comment]
Agree. If cert chain length is X, but only size Y (where Y < X) is parsed, then it should be treated as an error.

**Comment by rw8896** [comment]
And before calling libspdm_x509_verify_cert(), it should also check if current cert exceeds the end of certchain
`if (current_cert + libspdm_x509_verify_cert > cert_chain + cert_chain_length)`

https://github.com/DMTF/libspdm/blob/ddfd7a1080cdbeffbe02267e6a164a0a3149be1a/os_stub/cryptlib_mbedtls/pk/x509.c#L718-L727

**Comment by steven-bellock** [comment]
@rw8896 are you interested in adding this check?

**Comment by rw8896** [comment]
Sure, will do.
