### ISSUE TITLE
cmocka submodule is unreliable

### ISSUE THREAD

**Issue by makubacki** [DMTF/libspdm#2707]
The `unit_test/cmockalib/cmocka` submodule used in this repo is hosted at https://git.cryptomilk.org/projects/cmocka.git.

This has failed to clone today, and other projects (TianoCore) frequently saw issues in the past leading to https://github.com/tianocore/edk2-cmocka.

This request is to consider similarly hosting a mirror at an acceptable location for libspdm so downstream consumers of this repo can reliably clone the submodule.

**Comment by steven-bellock** [comment]
I'm not opposed to switching to a mirror hosted at a more reliable site. However it seems like most of the mirrors are not up-to-date.
- https://github.com/clibs/cmocka is at 1.1.5.
- https://gitlab.com/cmocka/cmocka is at 1.1.5.

@makubacki Is https://github.com/tianocore/edk2-cmocka no longer maintained?

**Comment by makubacki** [comment]
> I'm not opposed to switching to a mirror hosted at a more reliable site. However it seems like most of the mirrors are not up-to-date.
> 
> * https://github.com/clibs/cmocka is at 1.1.5.
> * https://gitlab.com/cmocka/cmocka is at 1.1.5.
> 
> @makubacki Is https://github.com/tianocore/edk2-cmocka no longer maintained?

My understanding is that it is a manual and mostly unmaintained repo. I doubt the tianocore organization would be opposed to updating it.

Though, it looks like https://gitlab.com/cmocka/cmocka is a good option. It has corresponding branches (`master` and `stable-1.1`), all tags accounted for, and the `master` branch is synced with the cryptomilk.org branch:

![image](https://github.com/DMTF/libspdm/assets/21320094/6a1a40e0-2a27-444d-a6b9-5bf7d755fd98)
*[cryptomilk.org/projects/cmocka](https://git.cryptomilk.org/projects/cmocka.git)*

| Release Tags   | `master` Branch    |
|:--------------:|:------------------:|
| ![image](https://github.com/DMTF/libspdm/assets/21320094/3756f915-dc5b-4013-a341-1b5559c94702) | ![image](https://github.com/DMTF/libspdm/assets/21320094/ff7af1f6-4a4a-434c-81f6-dac5ac73e776) |
| https://gitlab.com/cmocka/cmocka/-/tags | https://gitlab.com/cmocka/cmocka/-/tree/master?ref_type=heads |

It also appears to have the added benefit of CI checks.

**Comment by steven-bellock** [comment]
Ah looks like the `master` branch changelog only goes to 1.1.5, but the 1.1.7 release is there. Yes, we can switch to Gitlab, provided it is more reliable.
