### ISSUE TITLE
What is the endianness of IV expected by libspdm ?

### ISSUE THREAD

**Issue by svajghal** [DMTF/libspdm#2723]
I see that Final IV is calculated by XORing Initial IV with Sequence Number based on sequence_number endianness only.

Url: https://github.com/DMTF/libspdm/blob/main/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c#L18

Why is endianness of IV not considered here ? Is it always expected to be LE ?
Does Mbedtls always outputs LE IV value from HKDF_EXPAND ?
What should be the scenario if any of the responder implementation operates on BE IV ?

**Comment by jyao1** [comment]
Please see https://github.com/DMTF/libspdm/blob/main/doc/crypto_endianness.md

**Comment by steven-bellock** [comment]
When the "final IV" is input to the AEAD encryption/decryption algorithm, it is technically considered big-endian, at least by CTR/GCM. When the block counter is appended to the "final IV" it is incremented in a big-endian manner. But that is handled by the cryptography library. So libspdm does not need to worry about endianness in that scenario. Where it does need to worry about endianness is the sequence number, which was ill-defined in 277 1.0 and 1.1, and is why libspdm supports different endianness schemes for it.

**Comment by steven-bellock** [comment]
@svajghal if this answered your question then please close the issue.
