### ISSUE TITLE
the name SPDM_DATA_OPAQUE_CONTEXT_DATA is confusing

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#274]
Because it includes "OPAQUE", people may think it is used to set the "Opaque data" for measurement/challenge/keyExchange etc.

I think we need replace "opaque" with some other name.

**Comment by steven-bellock** [comment]
Issue that drove this https://github.com/DMTF/libspdm/issues/66

**Comment by jyao1** [comment]
11/15/2021 - agree the problem statement. But we don't want to use TRANSPORT_CONTEXT_DATA, because it can be used for any purposed.
