### ISSUE TITLE
Fix code scanning alert - Comparison of narrow type with wide type in loop condition

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#2740]
Tracking issue for:
- [ ] https://github.com/DMTF/libspdm/security/code-scanning/96

**Comment by steven-bellock** [comment]
Good to know code scanning is actually working. It's been a while since we had one of these.

**Comment by Wenxing-hou** [comment]
Sorry. I don't have the access of the link: https://github.com/DMTF/libspdm/security/code-scanning/96 
How can I access this link?

**Comment by steven-bellock** [comment]
@Wenxing-hou you should have access now.
