### ISSUE TITLE
need a way to measure the stack size consumption

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#275]
REF: https://github.com/DMTF/libspdm/issues/58

As such, we can know the stack size difference before and after the fix.

**Comment by jyao1** [comment]
11/15/2021 - approved.

**Comment by qizhangz** [comment]
I will check it.

**Comment by qizhangz** [comment]
We may use gcc build flag -fstack-usage flag which is useful for analyzing the stack usage of individual functions.

**Comment by jyao1** [comment]
Can you try to enable it on libspdm and get some data?

**Comment by qizhangz** [comment]
enabled the flag -fstack-usage for gcc build to generate extra files like libspdm_req_send_receive.c.su.

Will check the file one by one and provide the data.

https://github.com/DMTF/libspdm/pull/311

**Comment by rw8896** [comment]
@qizhangz 
FYI that I have used avstack.pl to generate the initial stack usage on openspdm.
It still needs some manual works to analyze the result though.

https://dlbeer.co.nz/oss/avstack.html

**Comment by qizhangz** [comment]
@rw8896 Thank you! I used avstack.pl to get the below data (listed part of them) on the build with -fstack-usage enabled.

But the the value of column of Height are always 1 which seems not expected. Do you know why or need to do any change in the script avstack.pl?

The columns are:
Cost: peak stack usage during a call to the function.
Frame: stack frame size, obtained from the .su file, plus the call-cost constant.
Height: height in call graph – calculated as maximum height of any callee, plus one.

qizhang1@qizhang1-fir:~/src/libspdm/build/library$ ~/avstack.pl */*/*/*.o
  Func                               Cost    Frame   Height
------------------------------------------------------------------------
> spdm_transport_mctp_decode_message     9428     9428        1
> spdm_transport_mctp_encode_message     9412     9412        1
> spdm_encapsulated_request          9396     9396        1
> libspdm_responder_dispatch_message     9316     9316        1
> spdm_generate_measurement_summary_hash     8340     8340        1
> try_spdm_get_certificate           5828     5828        1
> spdm_decode_secured_message        4980     4980        1
> spdm_transport_pci_doe_decode_message     4804     4804        1
> spdm_transport_pci_doe_encode_message     4788     4788        1
> libspdm_build_response             4772     4772        1
> libspdm_receive_response           4756     4756        1
> libspdm_send_request               4740     4740        1
> try_spdm_send_receive_key_exchange     4116     4116        1
> try_spdm_send_receive_psk_exchange     2708     2708        1
> try_spdm_get_measurement           2436     2436        1
> try_spdm_challenge                 1956     1956        1
> try_spdm_send_receive_finish        868      868        1
> spdm_generate_session_data_key      708      708        1
> try_spdm_get_digest                 660      660        1
> spdm_secured_message_dhe_compute_key      628      628        1
> spdm_is_root_certificate            580      580        1
> spdm_generate_session_handshake_key      516      516        1
> spdm_generate_aead_key_and_iv       404      404        1
> spdm_encode_secured_message         388      388        1
> spdm_get_response_psk_exchange      308      308        1
> try_spdm_send_receive_psk_finish      276      276        1

**Comment by rw8896** [comment]
@qizhangz 
It works for me.
In my usage,
- objdump: arm-linux-gnueabihf-objdump
- explicitly list all obj files (instead of *.o in your usage)
