### ISSUE TITLE
Removal of disclaimer that libspdm is not fit for production

### ISSUE THREAD

**Issue by raghuncstate** [DMTF/libspdm#2765]
libspdm readme known limitation states “This package is only the sample code to show the concept of SPDM and should not be considered fit for production.”
This invites question on what changes would be required for it to be production worthy. Can we revisit removing this or modifying it to say something along the lines of "what quality bar it passes" and let users make decision on production worthiness? Or if we have a stronger stance t say the intent is to use it in production but without any liability, that might work too.

**Comment by steven-bellock** [comment]
@jyao1 did DMTF require the disclaimer or was that entirely your words?

**Comment by jyao1** [comment]
It is for initial version. I think we can remove it now.
