### ISSUE TITLE
test_spdm_requester crashes with OpenSSL

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#277]
> [ RUN      ] test_spdm_requester_get_certificate_case1
/home/runner/work/_temp/a6d3e837-cbab-4f86-83fe-737952fe3251.sh: line 2:  7070 Aborted                 (core dumped) ./test_spdm_requester
Error: Process completed with exit code 134.

**Comment by jyao1** [comment]
Have you run "nmake copy_sample_key" ?

**Comment by steven-bellock** [comment]
Yes.

> -- Build files have been written to: /home/runner/work/libspdm/libspdm/build
Built target copy_sample_key
[  0%] Building C object os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/cipher/aead_aes_gcm.c.o
[  0%] Building C object os_stub/openssllib/CMakeFiles/openssllib.dir/openssl/crypto/aes/aes_cbc.c.o

**Comment by steven-bellock** [comment]
Probably related to https://github.com/DMTF/libspdm/pull/270

**Comment by jyao1** [comment]
#270 is fix.

I do not see any problem on my side. Weird.

**Comment by jyao1** [comment]
BTW: Do you do "git submodule update --recursive" ? We just upgrade openssl version.

**Comment by steven-bellock** [comment]
Yes.
Did you check "cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=openssl .." ?

**Comment by jyao1** [comment]
You are right. I only test Debug. but not release.

Yes, I can reproduce the error with Release build now.

**Comment by jyao1** [comment]
Just curious, why CI did not fail before? I do merge only after CI passes.
But anyway, I will investigate it.

**Comment by Wenxing-hou** [comment]
I find the first bad patch to cause the error :_enable time checks for openssl._  [https://github.com/DMTF/libspdm/commit/c8becfca3163f98937a43e0215c9a256f7f9acd8](url)
Before the patch, build with  cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=<Release|Debug> -DCRYPTO=openssl .. pass ,and pass in the unit_test.

**Comment by steven-bellock** [comment]
That's https://github.com/DMTF/libspdm/pull/270

**Comment by liyi77** [comment]
I found that time() will cause a segfault in there:
https://github.com/openssl/openssl/blob/fb047ebc87b18bdc4cf9ddee9ee1f5ed93e56aff/crypto/x509/x509_vfy.c#L1929-L1938

And we defined time_t as int32 in openssllib:
https://github.com/DMTF/libspdm/blob/9d1e74ae49cce9e1fd78f9966a36da7fe7e79816/os_stub/openssllib/include/crt_support.h#L105-L107

I think this may cause time() to use 64-bit memory pointers to access 32-bit memory , 
And If I change it to "typedef int64 time_t;", all the unittests can pass again.

It may be the root cause, because RELEASE version will do stricter memory protection (-fstack-protector),
But I have no idea to debug time(), so not completely sure that this is the correct solution, just FYI.

**Comment by jyao1** [comment]
I think you are right @liyi77, see https://www.ibm.com/docs/en/ibm-mq/9.0?topic=platforms-standard-data-types-unix-linux-windows. It is 64bit in 64bit system.

At least we need make it uintn_t

**Comment by steven-bellock** [comment]
Similar to base.h and processor_bind.h we can discuss why crt_support.h is even needed.

**Comment by jyao1** [comment]
It is historic reason. We want minimal std/compiler dependency. So we almost define everything in firmware.

But it might be OK here because we are using openssl as OS binding.

**Comment by steven-bellock** [comment]
Is edk2 seeing this issue?

**Comment by jyao1** [comment]
Right. They did not, I guess, because the time() function is implemented in EDKII.

But it is still a potential risk, I filed issue for EDKII - https://bugzilla.tianocore.org/show_bug.cgi?id=3733

**Comment by steven-bellock** [comment]
When I compiled spdm-emu I got
```/home/scratch.sbellock_sw/temp/spdm-emu/libspdm/os_stub/openssllib/include/crt_support.h:183:8: warning: type of ‘time’ does not match original declaration [-Wlto-type-mismatch]
  183 | time_t time(time_t *);
      |        ^
/usr/include/time.h:75:15: note: return value type mismatch
   75 | extern time_t time (time_t *__timer) __THROW;
      |               ^
/usr/include/time.h:75:15: note: ‘time’ was previously declared here
/usr/include/time.h:75:15: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
[100%] Built target spdm_responder_emu
/home/scratch.sbellock_sw/temp/spdm-emu/libspdm/os_stub/openssllib/include/crt_support.h:183:8: warning: type of ‘time’ does not match original declaration [-Wlto-type-mismatch]
  183 | time_t time(time_t *);
      |        ^
/usr/include/time.h:75:15: note: return value type mismatch
   75 | extern time_t time (time_t *__timer) __THROW;
      |               ^
/usr/include/time.h:75:15: note: ‘time’ was previously declared here
/usr/include/time.h:75:15: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
```
I don't think this warning showed up when I compiled standalone libspdm.

**Comment by Wenxing-hou** [comment]
The spdm_emu build issue is fixed, when I change the type of time_t to intn.

**Comment by jyao1** [comment]
11/15/2021 - approved. Need consider removing crt support.
