### ISSUE TITLE
Handle Responder sending `END_SESSION` in application phase

### ISSUE THREAD

**Issue by PrithviAPai** [DMTF/libspdm#2776]
Once Application Phase is over, as per SPDM spec SPDM Responders have the capability to trigger END_SESSION. 
<img width="614" alt="image" src="https://github.com/user-attachments/assets/93feda4c-2d78-4780-84bf-c91b7d80cf6d">

Currently libspdm does NOT provide way to handle application messages getting triggered from SPDM responder. 
Is there any plans to add this ? 

Thanks,
Prithvi A Pai

**Comment by steven-bellock** [comment]
> as per SPDM spec SPDM Responders have the capability to trigger END_SESSION.

No. Currently `END_SESSION` cannot be encapsulated : 

>Only certain requests can be encapsulated in any encapsulated request flow. Their corresponding responses, including ERROR, can also be encapsulated. Additionally, these requests are only allowed in certain flows as described in various parts of this specification. This consolidated list shall be the requests that are allowed to be encapsulated:
>- CHALLENGE
>- GET_CERTIFICATE
>- GET_DIGESTS
>- KEY_UPDATE
>- SUBSCRIBE_EVENT_TYPES
>- SEND_EVENT
>- GET_SUPPORTED_EVENT_TYPES
>- GET_ENDPOINT_INFO

A Responder can internally terminate its session, and then reply with `DecryptError` to request messages. This will signal to the Requester that the session is over. That is being tracked in #2309.

**Comment by PrithviAPai** [comment]
Yes I agree `END_SESSION` cannot be encapsulated. 
But spec allows SPDM Responders to send END_SESSION right ? So in case spdm requester gets `END_SESSION` command from SPDM Responder we dont have mechanism to handle in libspdm

**Comment by steven-bellock** [comment]
>But spec allows SPDM Responders to send END_SESSION right ?

An asynchronous (non-encapsulated) transmission from Responder to Requester? No. Only a subset of the encapsulated requests can be sent asynchronously by the Responder:
- KEY_UPDATE
- SUBSCRIBE_EVENT_TYPES
- SEND_EVENT
- GET_SUPPORTED_EVENT_TYPES
- GET_ENDPOINT_INFO

For those SPDM (and application) messages that are supported #498 tracks that issue.
