### ISSUE TITLE
`libspdm_set_mem(requester_context, SPDM_REQ_CONTEXT_SIZE, 0xAA)` will overflow write in `libspdm_test_responder_measurements_case36`

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#2784]
`libspdm_set_mem(requester_context, SPDM_REQ_CONTEXT_SIZE, 0xAA)` at the following line 2717 will overflow write in `libspdm_test_responder_measurements_case36`, due to `m_libspdm_get_measurements_request17` has no `requester_context` field.

https://github.com/DMTF/libspdm/blob/21d720c93a70c54b7c081e500b3ae6a5104d44a0/unit_test/test_spdm_responder/measurements.c#L2715-L2717

https://github.com/DMTF/libspdm/blob/21d720c93a70c54b7c081e500b3ae6a5104d44a0/unit_test/test_spdm_responder/measurements.c#L112-L115

https://github.com/DMTF/libspdm/blob/21d720c93a70c54b7c081e500b3ae6a5104d44a0/include/industry_standard/spdm.h#L615-L624

**Comment by Xiaohanjlll** [comment]
I come to check it
