### ISSUE TITLE
github_pages branch vastly inflates size of repository

### ISSUE THREAD

**Issue by leiflindholm** [DMTF/libspdm#2787]
https://github.com/tianocore/edk2 integrates lidspdm (since April 2024), pulling it in as a submodule. Since that was done, the time it takes to clone the repo and submodules has increased many times over.

When looking into why, I realised that cloning the libspdm repository means pulling down 1.1GB of compressed data, taking 5m44s on its own. This seemed unreasonable to me, so I investigated what was going on.

Turns out the code coverage logs being stored in the `github_pages` branch make up prett much all this data. If I run
```
$ git branch -r -d origin/github_pages
$ git gc --prune=now
```
the size of the cloned repository shrinks from 1.1GB to 27MB.

Is there any way this branch could be moved out into its own repository?

**Comment by steven-bellock** [comment]
`github_pages` should only include the most recent commit.

**Comment by leiflindholm** [comment]
It has 636 of them...

**Comment by steven-bellock** [comment]
Yes, when this issue is resolved it will always have exactly one commit.

**Comment by leiflindholm** [comment]
Thank you! Clone now takes 7.4s and results in 36MB :)
