### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#279]
Just throwing this out. Does anyone else have issue with tabs being used throughout the code? Wondering if spaces would be better.

**Comment by steven-bellock** [comment]
Yeah I prefer 4 spaces to tabs.

This is specified in https://github.com/DMTF/libspdm/blob/main/.clang-format and I think we should update it. Especially to allow at least 100 characters per line.

**Comment by rkongintel** [comment]
I prefer spaces as well. I could live with 100 characters per line, but prefer we not go further as I like being able to fit 2 code pages, side by side, on the screen.

**Comment by steven-bellock** [comment]
@raghuncstate set up the initial clang-format so he might have an opinion... or not.

**Comment by jyao1** [comment]
I prefer 4 spaces, too.

I also agree to increase the max char per line.

@rkongintel, how about you just update the clang-format and submit a P-R ?

**Comment by jyao1** [comment]
If we want to change, I prefer we change it in the STABLE release.

**Comment by jyao1** [comment]
11/15/2021 - set up discussion for vote which one is preferred? space or tab?
If we want to change, then change clang-format at first.
Another thing is to max char in a line, current it is 80. Propose to change to 100 or 120.
@steven-bellock will setup those voting.

**Comment by jyao1** [comment]
11/22/21 - final decision - https://github.com/DMTF/libspdm/discussions/294
4 space + 100 chars per line.

**Comment by Wenxing-hou** [comment]
I will check it.
