### ISSUE TITLE
Certificate chain parsing fails

### ISSUE THREAD

**Issue by mazen-mahmoud16** [DMTF/libspdm#2791]
I used these commands to generate certificate_chain.der

`nano new_openssl.cnf
[ req ]
default_bits        = 2048
default_md          = sha256
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
prompt              = no

[ req_distinguished_name ]
CN                  = YourRootCA

[ v3_ca ]
basicConstraints    = critical, CA:TRUE
keyUsage            = critical, cRLSign, keyCertSign

[ v3_intermediate_ca ]
basicConstraints    = critical, CA:TRUE, pathlen:0
keyUsage            = critical, cRLSign, keyCertSign
subjectKeyIdentifier= hash

[ v3_leaf ]
basicConstraints    = CA:FALSE
keyUsage            = critical, digitalSignature
extendedKeyUsage    = serverAuth, clientAuth
subjectKeyIdentifier= hash

----------------------------------------

# Generate Root CA Key and Certificate
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem -subj "/CN=YourRootCA" -config new_openssl.cnf -extensions v3_ca

# Generate Intermediate CA Key and CSR
openssl genrsa -out intermediateCA.key 2048
openssl req -new -key intermediateCA.key -out intermediateCA.csr -subj "/CN=YourIntermediateCA" -config new_openssl.cnf -reqexts v3_intermediate_ca

# Sign the Intermediate CA CSR with the Root CA to get the Intermediate CA certificate
openssl x509 -req -in intermediateCA.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out intermediateCA.pem -days 500 -sha256 -extfile new_openssl.cnf -extensions v3_intermediate_ca

# Generate Leaf Key and CSR
openssl genrsa -out leaf.key 2048
openssl req -new -key leaf.key -out leaf.csr -subj "/CN=YourCommonName" -config new_openssl.cnf -reqexts v3_leaf

# Sign the Leaf CSR with the Intermediate CA to get the Leaf Certificate
openssl x509 -req -in leaf.csr -CA intermediateCA.pem -CAkey intermediateCA.key -CAcreateserial -out leaf.crt -days 365 -sha256 -extfile new_openssl.cnf -extensions v3_leaf

# Verify the chain of trust
openssl verify -CAfile rootCA.pem -untrusted intermediateCA.pem leaf.crt

# Convert PEM to DER format
openssl x509 -in rootCA.pem -outform DER -out rootCA.der
openssl x509 -in intermediateCA.pem -outform DER -out intermediateCA.der
openssl x509 -in leaf.crt -outform DER -out leaf.der

cat rootCA.der intermediateCA.der leaf.der > certificate_chain.der`

And when I set_data of the LIBSPDM_DATA_LOCAL_PUBLIC_CERT_CHAIN with the certificate_chain.der, when I send get_certificate from the requester it passes all the checking even libspdm_x509_get_cert_from_cert_chain (of leaf certificate) and fails in libspdm_x509_certificate_check with this message '!!! VerifyCertificateChainBuffer - FAIL (leaf certificate check failed)!!!'.

After some debugging I found that this API

`if (!libspdm_x509_get_cert_from_cert_chain(
            cert_chain_data, cert_chain_data_size, -1,
            &leaf_cert_buffer, &leaf_cert_buffer_size)) {
        LIBSPDM_DEBUG((LIBSPDM_DEBUG_INFO,
                       "!!! VerifyCertificateChainBuffer - FAIL (get leaf certificate failed)!!!\n"));
        return false;
    }`

Returns the inetrmediate certificate instead of leaf certificate, that is why it fails in the key_usage because it checks for the intermediate certificate. Is this a problem in my certificate chain? When I used bundle_responder.certchain.der of rsa2048 it also fails.

**Comment by steven-bellock** [comment]
With `LIBSPDM_DATA_LOCAL_PUBLIC_CERT_CHAIN` are you forming the entire SPDM certificate chain structure?

Byte offset | Field | Size (bytes) | Description
-- | -- | -- | --
0 | Length | 2 | Shall be the total length of the certificate chain, in bytes, including all fields in this table. This field is little endian.
2 | Reserved | 2 | Reserved.
4 | RootHash | H | Shall be the digest of the Root Certificate. Note that the Root Certificate is ASN.1 DER-encoded for this digest. This field shall be in hash byte order. H is the output size, in bytes, of the hash algorithm selected by the most recent ALGORITHMS response.
4 + H | Certificates | Length - (4 + H) | Shall be a complete certificate chain consisting of one or more ASN.1 DER-encoded X.509 v3 certificates. This field shall be in Encoded ASN.1 byte order.

I noticed the documentation does not explicitly specify this. https://github.com/DMTF/libspdm/blob/96a7a3962285d2a7b1e2d2fcd3ad5f2895fc9a09/doc/api/common_api.md?plain=1#L235-L238 I'll file a separate issue for this.

**Comment by mazen-mahmoud16** [comment]
It works but the issue was in 
`cat rootCA.der intermediateCA.der leaf.der > certificate_chain.der`

When I concat the files manually into certificate_chain.der it works.
