### ISSUE TITLE
Capability flags should be masked with version mask

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2796]
https://github.com/DMTF/libspdm/blob/3a69c7bb0faccb2c5ac75c52d2d905fcf92d5510/library/spdm_responder_lib/libspdm_rsp_capabilities.c#L250C5-L250C73

Capability flags actually need to be masked with version mask(e.g. SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_12_MASK).
For example, if the responder supports multiple versions and different/new capabilities, the integrator would expect to set all the supported flags and rely on libspdm to report the flags according to version negotiation results.

**Comment by steven-bellock** [comment]
This is also needed for algorithms. Ie, EdDSA ed25519 was added in SPDM 1.2.
