### ISSUE TITLE
Get_capabilities fuzzing test folder name typo

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#281]
https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/test_spdm_responder_get_capabilities/get_capabilities.c

I think the above folder name `test_spdm_responder_get_capabilities` should be  `test_spdm_requester_get_capabilities`, because `get_capabilities` is requester side message.

**Comment by jyao1** [comment]
11/15/2021 - approved

**Comment by Xiaohanjlll** [comment]
I will check this issue.
