### ISSUE TITLE
Add GCOV as an option can be selected for fuzzing in Linux with AFL

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#282]
For fuzzing in Linux with AFL, I think we should add `GCOV` as an option can be selected,  and default is OFF just like GCC TOOLCHAIN.
Fuzzing can enable this option `GCOV` to collect code coverage.

GCC TOOLCHAIN:
https://github.com/DMTF/libspdm/blob/20277fb102f38fd33c0e74b471bfd48cef4c532f/CMakeLists.txt#L145-L166

AFL TOOLCHAIN
https://github.com/DMTF/libspdm/blob/20277fb102f38fd33c0e74b471bfd48cef4c532f/CMakeLists.txt#L294-L306

**Comment by jyao1** [comment]
11/15/2021 - approved.
