### ISSUE TITLE
Need to consider DataTransferSize to determine the length of certchain to return

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2824]
https://github.com/DMTF/libspdm/blob/b327ead227f14998789bca7d045af17b99dd6d50/library/spdm_responder_lib/libspdm_rsp_certificate.c#L113-L119

In case that the requester is sending the GET_CERTIFICATE with offset=0 and Length=0xFFFF but LIBSPDM_MAX_CERT_CHAIN_BLOCK_LEN is defined larger than the requester's DataTransferSize, the responder won't be able to send a CERTIFICATE response according to the current code.

Probably it should also consider DataTransferSize to determine the length of certchain to return?

Relevant issues: #1655 #2472

**Comment by steven-bellock** [comment]
This is when at least the Requester and/or Responder does not support chunking?

**Comment by rw8896** [comment]
> This is when at least the Requester and/or Responder does not support chunking?

Yes, this is when chunk is not supported.

**Comment by steven-bellock** [comment]
The Requester should not set `Length` greater than its `DataTransferSize`. If it does, the specification does not specify what the Responder should do in that case. Ie, return an error or attempt to send the response.

**Comment by rw8896** [comment]
Got it, thanks for the clarification. It looks like the current code will return ResponseTooLarge or LargeResponse which makes sense to me.
