### ISSUE TITLE
Set Cert: should not check BasicConstraint CA: True with hardcoded value

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2831]
https://github.com/DMTF/libspdm/blob/b327ead227f14998789bca7d045af17b99dd6d50/library/spdm_crypt_lib/libspdm_crypt_cert.c#L840-L846

Device Cert could specify pathLenConstraint in BasicConstraints and hence the hardcoded BASIC_CONSTRAINTS_STRING_TRUE_CASE can't cover all the true cases.
https://github.com/DMTF/libspdm/blob/b327ead227f14998789bca7d045af17b99dd6d50/library/spdm_crypt_lib/libspdm_crypt_cert.c#L98

**Comment by steven-bellock** [comment]
Presumably the call to `libspdm_x509_get_extended_basic_constraints` would fail as `cert_basic_constraints` is not large enough to hold the whole field.
