### ISSUE TITLE
Set Cert: incorrect key usage check for AliasCert Model

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2833]
https://github.com/DMTF/libspdm/blob/b327ead227f14998789bca7d045af17b99dd6d50/library/spdm_crypt_lib/libspdm_crypt_cert.c#L1193-L1197

When set_cert is true and cert model is SPDM_CERTIFICATE_INFO_CERT_MODEL_ALIAS_CERT, the leaf cert is device CA cert which doesn't need to have the digitalSignature usage. Probably could check keyCertSign instead.

**Comment by steven-bellock** [comment]
>Probably could check keyCertSign instead.

In the SPDM specification `Key Usage` is only mandatory for leaf certificates. For now libspdm can just skip the check.
