### ISSUE TITLE
Why responder return an incomplete certificate chain if Get_Certificate with offset = 0 and length = 0xFFFF is issued?

### ISSUE THREAD

**Issue by owen126315** [DMTF/libspdm#2855]
I modified some responder configs

> `LIBSPDM_MAX_CERT_CHAIN_BLOCK_LEN` = `0x78`,
> `Capability` = `SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CERT_CAP | SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHAL_CAP`
> `DataTransferSize` = `MaxMsgSize` = `0xFC`

And then I issue Get_Certificate with offset = 0 and length = 0xFFFF. I expect the responder would return an error with `SPDM_ERROR_CODE_RESPONSE_TOO_LARGE`. Yet, an incomplete cert chain was returned. The respond is as follows:

> libspdm_send_spdm_request[0] msg SPDM_GET_CERTIFICATE(0x82), size (0x8): 
> 0000: 12 82 00 00 00 00 ff ff 
> libspdm_receive_spdm_response[0] msg SPDM_CERTIFICATE(0x2), size (0x80): 
> 0000: 12 02 00 00 78 00 5a 07 d2 07 00 00 43 e0 b1 d6 32 d9 f9 51 1b b3 56 6e 16 e1 0a 7f a1 ac 47 ba 
> 0020: 10 95 be ec 98 b6 6d cf 1c 8c 9d dd ef 6a cf 14 43 17 4a 86 50 e7 bf a5 5c cb 0f 76 30 82 02 0e 
> 0040: 30 82 01 95 a0 03 02 01 02 02 14 24 44 87 75 96 d5 cc 8d d3 ff 86 d6 75 02 4e 7b dd a6 b5 45 30 
> 0060: 0a 06 08 2a 86 48 ce 3d 04 03 03 30 4f 31 24 30 22 06 03 55 04 03 0c 1b 41 45 49 20 4d 43 52 50 
> Certificate (offset 0x0, size 0x78):

After that, I reviewed the libspdm_rsp_certificate.c and found something strange. The responder override the incoming request length if  either requester or responder do not support `Get Chunk`. I think that is violating the SPDM spec. Can anyone tells if this is correct or not?
https://github.com/DMTF/libspdm/blob/525ba87b2f167350a622d9c997f5ea48ced65b52/library/spdm_responder_lib/libspdm_rsp_certificate.c#L113-L119
![image](https://github.com/user-attachments/assets/f0df6301-ed94-4d8b-99e3-2f7fe16f8d08)

**Comment by steven-bellock** [comment]
If chunking is not enabled on both endpoints then the Responder is free to truncate the size of the response. `CERTIFICATE.PortionLength` says
>This should be less than or equal to Length received as part of the request. For example, the Responder might set this field to a value less than Length received as part of the request due to limitations on the transmit buffer of the Responder. 

Note that `LIBSPDM_MAX_CERT_CHAIN_BLOCK_LEN` should not exist. See #1655.

**Comment by owen126315** [comment]
@steven-bellock Thank you for your reply. But I am still wondering, is this handling mentioned in the SPDM spec DSP0274?

**Comment by steven-bellock** [comment]
You will have to explain why you expect `SPDM_ERROR_CODE_RESPONSE_TOO_LARGE`.

**Comment by owen126315** [comment]
@steven-bellock My understanding to the highlighted paragraph is, when `GET_CERTIFICATE(offset = 0x0, length = 0xFFFF)` comes in, responder attempt to prepare a respond message including the complete cert chain data. And then try to send the message out in single transection (remainder length should always be 0).

If the incoming request length got overridden, the remainder length is not 0 anymore and contradict with the highlighted paragraph.

I think responder should success to return complete cert chain data with `libspdm_get_response_certificate()`, do not override the incoming request length. And let the `libspdm_build_respond()` to judge whether the respond message hit the error `SPDM_ERROR_CODE_RESPONSE_TOO_LARGE`.
![image](https://github.com/user-attachments/assets/4b1b0d64-99b7-4a04-9b4e-95afe5b85a2e)

**Comment by steven-bellock** [comment]
@owen126315 in your case the Requester and/or Responder does not support chunking, correct? In that case the paragraph 394 does not apply, as that is only for the large SPDM message transfer mechanism (chunking). In that case
>This should be less than or equal to Length received as part of the request. For example, the Responder might set this field to a value less than Length received as part of the request due to limitations on the transmit buffer of the Responder.

applies.

**Comment by owen126315** [comment]
@steven-bellock Understanded the handling of `GET_CERTIFICATE`. But there is another scenario which will encounter oversize problem, which is `GET_MEASUREMENT(SignatureRequested = 1, Index = 0xFF)`. 

Following are the configs of both requester and responder:
**requester config**
> - Capability = SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CERT_CAP | 
                          SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHAL_CAP
> - DataTransferSize = 0x1200
> - MaxMsgSize = 0x1200

**responder config**
> - Capability = SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CERT_CAP | SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHAL_CAP | SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_MEAS_CAP_SIG | SPDM_GET_CAPABILITIES_RESPONSE_FLAGS_CHUNK_CAP
> - DataTransferSize = 0xFC (Because of PMBUS transport layer limitation)
> - MaxMsgSize = 0x1200

I assume measurement respond message size would be more than 0xFC (for my case, it is 0x205), and how would the responder behave under this situation?

**Comment by steven-bellock** [comment]
![image](https://github.com/user-attachments/assets/4df86410-5fab-4e40-8047-ded2af9f596a)

**Comment by steven-bellock** [comment]
@owen126315 if this answered your question(s) please close the issue.

**Comment by rayling** [comment]
> ![image](https://private-user-images.githubusercontent.com/8474235/374971111-4df86410-5fab-4e40-8047-ded2af9f596a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODQ3NzIsIm5iZiI6MTcyODg4NDQ3MiwicGF0aCI6Ii84NDc0MjM1LzM3NDk3MTExMS00ZGY4NjQxMC01ZmFiLTRlNDAtODA0Ny1kZWQyYWY5ZjU5NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMDU0MTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZlYTBmZWYwOWY4ZGQxOWI3MGM3YWY2ZDc2OTYxZjllOGZjZGM4MjQ1YzQxZTUxMzgxNzUxMjk4MzE0Y2M2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CAJ7K5csIzPj350OSEodRshZpaseZjqyIf_I_pmFhDc)

Hi @steven-bellock,

From your latest replied, I just wonder, was this conflict with "In that case the paragraph 394 does not apply, as that is only for the large SPDM message transfer mechanism (chunking). In that case

> This should be less than or equal to Length received as part of the request. For example, the Responder might set this field to a value less than Length received as part of the request due to limitations on the transmit buffer of the Responder.

applies."

**Comment by steven-bellock** [comment]
That applies to the `CERTIFICATE` response but not `MEASUREMENTS`.

**Comment by steven-bellock** [comment]
Closing this issue. Please file another issue if you have further questions.

**Comment by rayling** [comment]
@steven-bellock 
I have consulted with offical SPDM working group. https://spdmforum.com/
I raised same question, they provide the answer
https://spdmforum.com/thread/8/question-on-response-large-error

The answer is the response need to reply "0xD0" error code to the requester.
Please check

**Comment by steven-bellock** [comment]
Assuming we're talking about
1. Negotiated SPDM version >= 1.2.
2. The size of the certificate chain is greater than than the `MaxSPDMmsgSize` of the Requester then

>The answer is the response need to reply "0xD0" error code to the requester.

is one possible response from the Responder. However, a truncated `CERTIFICATE` response is also legal. It depends on when the Responder does its checks and the size of the Responder's transmit buffer and the size of the certificate chain.

**Flow 1**
1. Responder receives `GET_CERTIFICATE` with `Length == 0xffff`.
2. Responder prepares `CERTIFICATE` response with its size truncated to fit inside the Responder's transmit buffer.
3. Responder checks if the size of the response is greater than the `MaxSPDMmsgSize` of the Requester.
    - If it is greater then send `ResponseTooLarge` to Requester.
    - If it is less than or equal then send the `CERTFICIATE` response.

**Flow 2**
1. Responder receives `GET_CERTIFICATE` with `Length == 0xffff`.
2. Responder prepares `CERTIFICATE` response with its size truncated to the size of the certificate chain.
3. Responder checks if the size of the response is greater than the `MaxSPDMmsgSize` of the Requester.
   - If it is greater then send `ResponseTooLarge` to Requester.
4. Responder checks if the size of the response is greater than its transmit buffer.
   - If it is greater then truncate size of the response some more and send response to Requester.

In theory the Responder could also truncate the `CERTIFICATE` response so that it fits inside the Requester's `MaxSPDMmsgSize`. That's up the Responder.

On the Requester side though, it shouldn't assume any of this, especially since it does not know the size of the Responder's transmit buffer. The Requester should size the `CERTIFICATE` request appropriately so that the response fits in its receive buffer.
