### ISSUE TITLE
Libspdm build error on Linux - "add_executable called with incorrect number of arguments"

### ISSUE THREAD

**Issue by DillonHeinenIntel** [DMTF/libspdm#2861]
My CMake version is greater than the minimum required version of 3.5:
**dheinen@remote:/dir> cmake --version
cmake version 3.5.2**

I'm using the following commands, as described in the documentation:

**git clone https://github.com/DMTF/libspdm.git libspdm
cd libspdm
git submodule update --init
git submodule update
mkdir build
cd build
cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=openssl ..**

dheinen@remote:/dir> git clone https://github.com/DMTF/libspdm.git libspdm
Cloning into 'libspdm'...
remote: Enumerating objects: 33649, done.
remote: Counting objects: 100% (3022/3022), done.
remote: Compressing objects: 100% (1239/1239), done.
remote: Total 33649 (delta 2232), reused 2271 (delta 1748), pack-reused 30627 (from 1)
Receiving objects: 100% (33649/33649), 17.81 MiB | 32.81 MiB/s, done.
Resolving deltas: 100% (23729/23729), done.
dheinen@remote:/dir> cd libspdm
dheinen@remote:/dir/libspdm> git submodule update --init
Submodule 'os_stub/mbedtlslib/mbedtls' (https://github.com/ARMmbed/mbedtls) registered for path 'os_stub/mbedtlslib/mbedtls'
Submodule 'os_stub/openssllib/openssl' (https://github.com/openssl/openssl) registered for path 'os_stub/openssllib/openssl'
Submodule 'unit_test/cmockalib/cmocka' (https://gitlab.com/cmocka/cmocka.git) registered for path 'unit_test/cmockalib/cmocka'
Cloning into '/dir/libspdm/os_stub/mbedtlslib/mbedtls'...
Cloning into '/dir/libspdm/os_stub/openssllib/openssl'...
Cloning into '/dir/libspdm/unit_test/cmockalib/cmocka'...
Submodule path 'os_stub/mbedtlslib/mbedtls': checked out '2ca6c285a0dd3f33982dd57299012dacab1ff206'
Submodule path 'os_stub/openssllib/openssl': checked out 'de90e54bbe82e5be4fb9608b6f5c308bb837d355'
Submodule path 'unit_test/cmockalib/cmocka': checked out 'a01cc69ee9536f90e57c61a198f2d1944d3d4313'
dheinen@remote:/dir/libspdm> git submodule update
dheinen@remote:/dir/libspdm> mkdir build
dheinen@remote:/dir/libspdm> cd build
dheinen@remote:/dir/libspdm/build> cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=openssl ..
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
#########################
#########################
CMAKE_GENERATOR = Unix Makefiles
ARCH = x64
TOOLCHAIN = GCC
GCOV = OFF
TARGET = Release
CRYPTO = openssl
ENABLE_BINARY_BUILD=0; Building openssl library from source.
CMake Error at unit_test/test_spdm_requester/CMakeLists.txt:3 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at unit_test/test_spdm_requester/CMakeLists.txt:5 (target_include_directories):
  Cannot specify include directories for target "test_spdm_requester" which
  is not built by this project.

CMake Error at unit_test/test_spdm_requester/CMakeLists.txt:17 (target_sources):
  Cannot specify sources for target "test_spdm_requester" which is not built
  by this project.

CMake Error at unit_test/test_spdm_requester/CMakeLists.txt:96 (target_link_libraries):
  Cannot specify link libraries for target "test_spdm_requester" which is not
  built by this project.

-- Configuring incomplete, errors occurred!
See also "/dir/libspdm/build/CMakeFiles/CMakeOutput.log".

Do you know what might be causing this?

**Comment by steven-bellock** [comment]
I believe that was a bug in that version of CMake. In particular the default (apt) CMake version in Ubuntu 16.04 or18.04 doesn't work. Maybe we should bump the minimum version to 3.6.

**Comment by DillonHeinenIntel** [comment]
> I believe that was a bug in that version of CMake. In particular the default (apt) CMake version in Ubuntu 16.04 or18.04 doesn't work. Maybe we should bump the minimum version to 3.6.

Thank you for the information on this issue; I just switched to 3.26.4 and everything appears to build correctly now.
