### ISSUE TITLE
Design for ResponseNotReady

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2863]
Hi,

Does libspdm support returning an ERROR(ResponseNotReady) for a specific command during processing the command like the example scenario below?
![image](https://github.com/user-attachments/assets/bf4cabce-e3ac-4b88-8daf-2e7d25cf5bdf)

The current code returns ResponseNotReady when the ResponseState is LIBSPDM_RESPONSE_STATE_NOT_READY, but that's only when ResponseState is set to LIBSPDM_RESPONSE_STATE_NOT_READY before the command is received. It seems that the responder is not able to send ERROR(ResponseNotReady) during processing the command even when the responder finds itself is going to exceed CT.

**Comment by steven-bellock** [comment]
>Does libspdm support returning an ERROR(ResponseNotReady) for a specific command during processing the command like the example scenario below?

No. Currently, this would need to be handled somewhere above the transport layer but below the libspdm / SPDM layer. It's a simple message to form, although it would need to get the currently negotiated version.

In most cases the Responder can / will just block at the transport layer until the response is ready and there's no need to support `ResponseNotReady`.

**Comment by rw8896** [comment]
Thanks, so I am evaluating to return ResetRequired instead but it seems some behaviors haven't been implemented yet. Create another issue #2864 for further discussion.

**Comment by steven-bellock** [comment]
@rw8896 please close this issue if it is answered / resolved.
