### ISSUE TITLE
Context: slot_id is not in use for setting LIBSPDM_DATA_LOCAL_SUPPORTED_SLOT_MASK

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#2865]
It shouldn't need to read slot_id from additional_data[0].

https://github.com/DMTF/libspdm/blob/5149b567a6dc2eecc5dc9c48978a1782edc031ed/library/spdm_common_lib/libspdm_com_context_data.c#L484-L494

**Comment by jyao1** [comment]
agree.
