### ISSUE TITLE
Debug library passing x86 asm mnemonic to ARM compiler

### ISSUE THREAD

**Issue by wmaroneAMD** [DMTF/libspdm#2890]
https://github.com/DMTF/libspdm/blob/d6f4b0b6b0a37f53031b7707cafa349b1512dc0d/os_stub/debuglib/debuglib.c#L42

If LIBSPDM_DEBUG_LIBSPDM_ASSERT_CONFIG is set to LIBSPDM_DEBUG_LIBSPDM_ASSERT_BREAKPOINT and the architecture is ARM, the compiler will be fed an x86 assembly instruction.

```
[ 44%] Building C object lib/spdm/libspdm/external/libspdm/os_stub/debuglib/CMakeFiles/debuglib.dir/debuglib.c.o
/tmp/ccCXgt0Y.s: Assembler messages:
/tmp/ccCXgt0Y.s:37: Error: unknown mnemonic `int' -- `int $3'
```

**Comment by steven-bellock** [comment]
@wmaroneAMD do you need this functionality or would just like a cleaner error message? Ie
>Debug breakpoints for the target architecture are not supported.

**Comment by wmaroneAMD** [comment]
A cleaner error message. I can put together a patch that restricts the mnemonic to x86/x86-64 and throws an error if the arch is anything else.
