### ISSUE TITLE
The return value of spdm_secured_message_dhe_generate_key function should be checked

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#291]
**boolean** `spdm_secured_message_dhe_generate_key`(IN uint16 dhe_named_group,
					      IN OUT void *dhe_context,
					      OUT uint8 *public_key,
					      IN OUT uintn *public_key_size)

The return type of `spdm_secured_message_dhe_generate_key` function in the following line 135 is **boolean**.
It should be checked whether its return value is FALSE before calling subsequent function.
https://github.com/DMTF/libspdm/blob/063a6e7c26432d5adfa6a273a232fbdfa519532d/library/spdm_requester_lib/libspdm_req_key_exchange.c#L135-L138

**Comment by steven-bellock** [comment]
This is already covered in https://github.com/DMTF/libspdm/issues/75

**Comment by jyao1** [comment]
agree. we can close this one.
