### ISSUE TITLE
Do we really need `LIBSPDM_DATA_TOTAL_KEY_PAIRS`?

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#2913]
Currently, all key pair info is inside of spdm_device_secret_lib_sample.
The library hardcoded first 9 algorithms, and assert the total key pairs no greater than 16.

Also, it hardcoded the last (10, total_key_pairs) to same EDDSA 448. I am not sure why to do that.
And I am not sure why we need to expose `LIBSPDM_DATA_TOTAL_KEY_PAIRS`?

Why not just return `total_key_pairs` from spdm_device_secret_lib_sample?

**Comment by steven-bellock** [comment]
See https://github.com/DMTF/libspdm/pull/2771#discussion_r1706099910.

**Comment by jyao1** [comment]
Ok. If the purpose is to just **return** total pairs, I am fine with that.

But now the problem is the **set** total pairs. Do we really want to let integrator **set** key pairs number?
I think it is problematic, since it is already defined in spdm_device_secret_lib_sample().

I propose to remove the **set** feature https://github.com/DMTF/libspdm/blob/main/library/spdm_common_lib/libspdm_com_context_data.c#L792-L800.

**Comment by steven-bellock** [comment]
>Do we really want to let integrator set key pairs number?

Yes, they need to be able to set it, else it will be `0`.

**Comment by jyao1** [comment]
keep it in this version. Update device_secret_lib_sample to make it easy to use.
