### ISSUE TITLE
try_spdm_challenge() restricts SPDM responder to having one slot populated

### ISSUE THREAD

**Issue by jcahill0** [DMTF/libspdm#292]
try_spdm_challenge() unnecessarily restricts an SPDM responder to having one slot populated.  The last check against param2 only allows 1 bit to be set in the below code snippet.
```
    if (spdm_response.header.spdm_version == SPDM_MESSAGE_VERSION_11 && slot_id == 0xFF) {
        if (auth_attribute.slot_id != 0xF) {
            return RETURN_DEVICE_ERROR;
        }
        if (spdm_response.header.param2 != 0) {
            return RETURN_DEVICE_ERROR;
        }
    } else {
        if ((spdm_response.header.spdm_version == SPDM_MESSAGE_VERSION_11 && auth_attribute.slot_id != slot_id) ||
            (spdm_response.header.spdm_version == SPDM_MESSAGE_VERSION_10 && *(uint8 *)&auth_attribute != slot_id)) {
            return RETURN_DEVICE_ERROR;
        }
        if (spdm_response.header.param2 != (1 << slot_id)) {
            return RETURN_DEVICE_ERROR;
        }
    }
```

@bhenning10 and I talked, the SPDM spec doesn't restrict param2 to having only one bit set; otherwise it shouldn't be a mask.  In reality, param2/slot_mask needs to be passed back to the libspdm client as a new parameter to spdm_challenge() to implement the proper policy, unless the expected slot ID bit is not properly set. which is a device error.  A client needs to decide what to do if new slots show up, and if slots disappear.
> Slot mask. The bit in position K of this byte shall be set to 1b if and only if slot
> number K contains a certificate chain for the protocol version in the SPDMVersion
> field. Bit 0 is the least significant bit of the byte. This field is reserved if the public
> key of the Responder was provisioned to the Requester in a trusted environment.

**Comment by jyao1** [comment]
11/15/2021 - approved.

**Comment by jyao1** [comment]
11/22/2021 - approved.
