### ISSUE TITLE
Query about GET_CSR

### ISSUE THREAD

**Issue by manishc88** [DMTF/libspdm#2925]
Hello,

In SPDM specification, under certificate provisioning flow, this is mentioned under GET_CSR section

"a Responder shall generate and sign a CSR for the corresponding public key. The CSR shall be populated with a combination of attributes provided by the Requester via the RequesterInfo field, and others contributed by the Responder itself. RequesterInfo format
shall comply to the PKCS #10 specification in RFC2986, specifically the CertificationRequestInfo format. OEM extensions (that is, OEM OIDs) shall be encoded using the Attributes type."

Does it mean CSR can be changed at runtime provided that it has to be formed with some runtime RequesterInfo fields/attributes in request coming from the requester ? Asking this because some crypto devices (on responder side) might have hardcoded CSR, in that case would it be okay to return the hardcoded/fixed CSR to the requester ? 

Thanks You
Manish Chopra

**Comment by steven-bellock** [comment]
>Does it mean CSR can be changed at runtime provided that it has to be formed with some runtime RequesterInfo fields/attributes in request coming from the requester ?

Yes, if the Responder supports that.

>Asking this because some crypto devices (on responder side) might have hardcoded CSR, in that case would it be okay to return the hardcoded/fixed CSR to the requester ?

If a Responder has a completely hardcoded CSR and it will not evaluate `RequesterInfo` then presumably the Requester should not populate the `RequesterInfo` field. For such a Responder if the field is populated then the Responder should reply with `InvalidRequest`. Note that SPDM itself does not specify how a Requester knows what `RequesterInfo` fields are legal for a Responder. That information could be in a data sheet.

**Comment by steven-bellock** [comment]
@manishc88 if this answers your question please close the issue.
