### ISSUE TITLE
Link error in the user_guide doc

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#2928]
Now, there are two wrong links in user_guide doc. 

https://github.com/DMTF/libspdm/blob/52466508464c1932867c1f89b768740e9c9b546f/doc/user_guide.md?plain=1#L18

https://github.com/DMTF/libspdm/blob/52466508464c1932867c1f89b768740e9c9b546f/doc/user_guide.md?plain=1#L281

It should be `https://github.com/DMTF/libspdm/tree/main/include/hal/library/xxx`.

**Comment by steven-bellock** [comment]
@Wenxing-hou do you want to take this issue?

**Comment by Wenxing-hou** [comment]
Sorry, it is not convenient for me to submit patch now.
