### ISSUE TITLE
Question on an condition in `validate_responder_capability`

### ISSUE THREAD

**Issue by mcsmonk** [DMTF/libspdm#2937]
https://github.com/DMTF/libspdm/blob/02aaa4904343a1f8d80aaeb855a08e8302ed2073/library/spdm_requester_lib/libspdm_req_get_capabilities.c#L122-L126

I'm wonder why this condition is in `validate_responder_capability`

I already reviewed the DSP0274 v1.0.2, v1.1.3, v1.2.2, and v1.3.1, but I cannot find its reason.

Where in the specification can I find the reason for adding this conditional statement?

**Comment by steven-bellock** [comment]
>Where in the specification can I find the reason for adding this conditional statement?

It is a derived check. Mutual authentication with the Responder using asymmetric keys can only occur if the Responder supports `CHALLENGE` (now deprecated) or `KEY_EXCHANGE`. If the Responder does not support at least one of those then mutual authentication is not happening.

**Comment by steven-bellock** [comment]
I can add a comment to the code / documentation which states that.

**Comment by mcsmonk** [comment]
Thank you for your response. I understand this clearly.
