### ISSUE TITLE
SpdmProcessEncapsulatedRequest function always return RETURN_SUCCESS

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#297]
The following line 304 will check the status returned by `SpdmProcessEncapsulatedRequest` function in line 300.
https://github.com/DMTF/libspdm/blob/3ff968553368dd5517ca8143cc620f48c66e65f3/library/spdm_requester_lib/libspdm_req_encap_request.c#L300-L306

But `SpdmProcessEncapsulatedRequest` function always return RETURN_SUCCESS in fact, it will never return error.
https://github.com/DMTF/libspdm/blob/3ff968553368dd5517ca8143cc620f48c66e65f3/library/spdm_requester_lib/libspdm_req_encap_request.c#L87-L127

**Comment by jyao1** [comment]
I think we should return Status from libspdm_generate_encap_error_response().

**Comment by jyao1** [comment]
11/22/21 - we think it might return error in the future. So we prefer to keep the error status.
