### ISSUE TITLE
build with openssl then test_crypt.exe test fail

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#298]
Verified on https://github.com/DMTF/libspdm/commit/3ff968553368dd5517ca8143cc620f48c66e65f3
For x64 builds, use a x64 Native Tools Command Prompt for Visual Studio... command prompt.
cd libspdm
mkdir build_x64_Release_openssl
cd build_x64_Release_openssl
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=openssl ..
nmake copy_sample_key
nmake
cd bin
test_crypt.exe > test_crypt.log

There is the following fail information in "test_crypt.log".
Line 29: - SM4-GCM Encryption: [Fail]
Line 158: - Context1 ... [Fail]

**Comment by jyao1** [comment]
SM4-GCM is not supported. It is known issue.
