### ISSUE TITLE
build with mbedtls then test_crypt.exe test fail

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#299]
Verified on 3ff9685
For x64 builds, use a x64 Native Tools Command Prompt for Visual Studio... command prompt.
cd libspdm
mkdir build_x64_Release_mbedtls
cd build_x64_Release_mbedtls
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=mbedtls ..
nmake copy_sample_key
nmake
cd bin
test_crypt.exe > test_crypt.log

There is the following fail information in "test_crypt.log".
	Line 8: - SHA3_256: Update... [Failed]
	Line 9: - SHA3_384: [Failed]
	Line 10: - SHA3_512: [Failed]
	Line 11: - SHAKE256: [Failed]
	Line 12: - SM3_256: HashAll... [Failed]
	Line 16: - HMAC-SHA3_256: [Fail]
	Line 20: - HKDF-SHA3_256: extract... [Fail]
	Line 27: - SM4-GCM Encryption: [Fail]
	Line 140: - Context1 ... [Fail]
	Line 142: - Retrieve Ed Private key for PEM ...[Fail]
	Line 144: - Context1 ... [Fail]
	Line 146: - Context1 ... [Fail]
	Line 148: - Retrieve sm2 Private key for PEM ...[Fail]

**Comment by jyao1** [comment]
mbedtls does not support SHA3, SM4, EdDSA.
