### ISSUE TITLE
test_size_of_spdm_requester.exe and test_size_of_spdm_responder.exe pop up dialog box

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#300]
Verified on 3ff9685
For x64 builds, use a x64 Native Tools Command Prompt for Visual Studio... command prompt.
cd libspdm
mkdir build_x64_Release_mbedtls
cd build_x64_Release_mbedtls
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=mbedtls ..
nmake copy_sample_key
nmake
cd bin
test_size_of_spdm_requester.exe
test_size_of_spdm_responder.exe

1. Then pop up dialog box "This app can't run on your PC". Please refer to the attached screen shot.
2. build with other cofiguration,  test_size_of_spdm_requester.exe also have the same issue.
    cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=openssl ..
    cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Debug -DCRYPTO=openssl ..
    cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Debug -DCRYPTO=mbedtls ..

![image](https://user-images.githubusercontent.com/90754803/142345937-cf6e9f36-09da-4afa-a897-d59679622028.png)

**Comment by jyao1** [comment]
It is only for test evaluation. You cannot run it.
