### ISSUE TITLE
Managing certificates on resource-constrained Responders

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#313]
The SPDM specification requires that the Responder must transmit to the Requester either the complete certificate chain or the complete certificate chain minus the root certificate. Resource-constrained Responders may experience difficulty in fulfilling this requirement, especially for large certificate chains. Portions of the certificate chain may need to reside in non-contiguous areas of memory. Going even further, portions of the certificate chain may be generated on-the-fly in response to a GET_CERTIFICATE request, which are then discarded to reclaim memory. This issue is to highlight the concern and go through possible solutions for SPDM 1.x responders.

For SPDM 2.x I think we should advocate that it should be allowable for a Responder to return only its leaf certificate to the Requester, and have the Requester / Verifier fill in the rest of the chain.

**Comment by jyao1** [comment]
Is this a spec issue or code issue ?
Any code change is required ?

**Comment by steven-bellock** [comment]
Code issue. Right now libspdm expects the Responder's certificates to reside in contiguous memory in the SPDM context, which might not be achievable for some resource-constrained Responders.

**Comment by jyao1** [comment]
Got it. Any proposal ?

**Comment by jyao1** [comment]
We can provide a callback - such as libspdm_get_device_certificate_chain(). it is not a big problem.
But the question is how to handle *partial* cert_chain request?

**Comment by jyao1** [comment]
11/29/2021 - problem is clear. @taprinz may provide a proposal.

**Comment by steven-bellock** [comment]
Closing this issue for now. In particular if the endpoint is so resource-constrained that it needs this then libspdm probably isn't the right choice.
