### ISSUE TITLE
Need add readme on "how to evaluate the libspdm image size + how to evaluate libspdm context size"

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#314]
The image size can be evaluated by `test_size_of_spdm_requester` and `test_size_of_spdm_responder` from https://github.com/DMTF/libspdm/tree/main/unit_test/test_size.

The context size can be shown by https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_requester_emu/spdm_requester.c#L110, or https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_responder_emu/spdm_responder.c#L112

**Comment by jyao1** [comment]
11/29/2021 - approved

**Comment by Wenxing-hou** [comment]
I will check it.
