### ISSUE TITLE
openssl build failed with VS2019

### ISSUE THREAD

**Issue by qizhangz** [DMTF/libspdm#324]
libspdm build failed with VS2019.

Build command:
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Debug -DCRYPTO=openssl ..
nmake copy_sample_key
nmake

Build error:
C:\Workspace\project\rebase_spdm\libspdm\build>nmake

Microsoft (R) Program Maintenance Utility Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[  0%] Building C object os_stub/cryptlib_openssl/CMakeFiles/cryptlib_openssl.dir/cipher/aead_aes_gcm.c.obj
aead_aes_gcm.c
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include\vcruntime.h(197): error C2371: 'size_t': redefinition; different basic types
C:\Workspace\project\rebase_spdm\libspdm\os_stub\cryptlib_openssl\cipher\aead_aes_gcm.c: note: see declaration of 'size_t'
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\BUILDT~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by qizhangz** [comment]
I will check it.

**Comment by jyao1** [comment]
It is known issue. Assign to @steven-bellock

**Comment by rkongintel** [comment]
I may have a fix for this. Does CI run all build configurations?

**Comment by steven-bellock** [comment]
Right now it's Linux (Mbed TLS, OpenSSL) and Windows / VS2019 (Mbed TLS). Once this issue gets fixed we'll add VS2019 / OpenSSL to CI.

**Comment by rkongintel** [comment]
Does it do the 32/64 bit flavors of each?

**Comment by steven-bellock** [comment]
Right now Linux is only 32-bit. I think we can do 32-bit Windows. @Wenxing-hou can comment on that.

**Comment by Wenxing-hou** [comment]
The current CI test include: 
- Linux x64 openssl build;
- Linux x64 mbedtls build;
- windows x64 mbedtls build;

When @rkongintel fix the windows openssl x64 build issue, I will add the windows x64 openssl build CI test asap.
The all ia32 build CI test is not added.

**Comment by steven-bellock** [comment]
Should be fixed by https://github.com/DMTF/libspdm/pull/407
