### ISSUE TITLE
need add transport layer fuzzing.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#326]
include both PCI-DOE and MCTP

**Comment by Xiaohanjlll** [comment]
I will check this issue.

**Comment by steven-bellock** [comment]
@jyao1 is this really a bug?

**Comment by Xiaohanjlll** [comment]
MCTP
spdm_transport_mctp_encode_message
mctp_encode_message
spdm_transport_mctp_decode_message
mctp_decode_message
PCI_DOE
spdm_transport_pci_doe_encode_message pci_doe_encode_message
spdm_transport_pci_doe_decode_message pci_message

**Comment by Xiaohanjlll** [comment]
MCTP
spdm_transport_mctp_encode_message
mctp_encode_message
spdm_transport_mctp_decode_message
mctp_decode_message

**Comment by Xiaohanjlll** [comment]
PCI_DOE
spdm_transport_pci_doe_encode_message 
pci_doe_encode_message
spdm_transport_pci_doe_decode_message 
pci_message
