### ISSUE TITLE
need add secured message fuzzing.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#327]

**Comment by Xiaohanjlll** [comment]
I will check this issue.

**Comment by Xiaohanjlll** [comment]
MCTP
spdm_transport_mctp_encode_message 
mctp_encode_message
spdm_transport_mctp_decode_message 
mctp_decode_message
PCI_DOE
spdm_transport_pci_doe_encode_message pci_doe_encode_message
spdm_transport_pci_doe_decode_message pci_doe_decode_message

**Comment by Xiaohanjlll** [comment]
spdm_decode_secured_message
spdm_decode_secured_message
