### ISSUE TITLE
MANAGED_BUFFER, LARGE_MANAGED_BUFFER, SMALL_MANAGED_BUFFER

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#33]
from https://github.com/jyao1/openspdm/issues/6

The code requires that MANAGED_BUFFER be the same as the first two components of LARGE/SMALL_MANAGED_BUFFER.
To facilitate such, suggest below:

typedef struct {
UINTN MaxBufferSize;
UINTN BufferSize;
//UINT8 Buffer[MaxBufferSize];
} MANAGED_BUFFER;

typedef struct {
MANAGED_BUFFER ManagedBufferSizes;
UINT8 Buffer[MAX_SPDM_MESSAGE_BUFFER_SIZE];
} LARGE_MANAGED_BUFFER;

typedef struct {
MANAGED_BUFFER ManagedBufferSizes;
UINT8 Buffer[MAX_SPDM_MESSAGE_SMALL_BUFFER_SIZE];
} SMALL_MANAGED_BUFFER;

**Comment by jyao1** [comment]
low priority.

**Comment by steven-bellock** [comment]
Closing on 13-Dec-2021.
