### ISSUE TITLE
Some executable programs were not successfully generated when building with VS2019 in windows

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#333]
Verified on https://github.com/DMTF/libspdm/commit/3e0e1b9c20ed568704a393bc02686236d773a3c4
```
cd libspdm
mkdir build
cd build
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=mbedtls ..
nmake copy_sample_key
nmake
```
The following executable programs were not successfully generated:
test_size_of_spdm_requester.exe
test_size_of_spdm_responder.exe
test_spdm_common.exe
test_spdm_requester_get_version.exe
test_spdm_responder_version.exe
test_spdm_requester_get_capabilities.exe
test_spdm_responder_capabilities.exe
test_spdm_requester_negotiate_algorithms.exe
test_spdm_responder_algorithms.exe
test_spdm_requester_get_digests.exe
test_spdm_responder_digests.exe
test_spdm_requester_get_certificate.exe
test_spdm_responder_certificate.exe
test_spdm_requester_get_measurements.exe
test_spdm_responder_measurements.exe
test_spdm_responder_key_exchange.exe
test_spdm_requester_key_exchange.exe
test_spdm_requester_finish.exe
test_spdm_responder_finish_rsp.exe
test_spdm_requester_psk_exchange.exe
test_spdm_responder_psk_exchange_rsp.exe
test_spdm_requester_heartbeat.exe
test_spdm_responder_heartbeat_ack.exe
test_spdm_requester_key_update.exe
test_spdm_responder_key_update.exe
test_spdm_requester_end_session.exe
test_spdm_responder_end_session.exe
test_spdm_responder_psk_finish_rsp.exe
test_spdm_requester_psk_finish.exe
test_spdm_requester_challenge.exe
test_spdm_responder_challenge_auth.exe
test_spdm_requester_encap_challenge_auth.exe
test_spdm_responder_encap_challenge.exe
test_spdm_requester_encap_certificate.exe
test_spdm_responder_encap_get_certificate.exe
test_spdm_requester_encap_digests.exe
test_spdm_responder_encap_get_digests.exe
test_spdm_requester_encap_key_update.exe
test_spdm_responder_encap_key_update.exe
test_spdm_responder_if_ready.exe

**Comment by qizhangz** [comment]
I will check this
