### ISSUE TITLE
build failed due to build error in toolchain_harness.c

### ISSUE THREAD

**Issue by qizhangz** [DMTF/libspdm#334]
Build command:
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Debug -DCRYPTO=mbedtls  ..

Build error:
toolchain_harness.c
C:\Workspace\project\mine\libspdm\unit_test\fuzzing\spdm_unit_fuzzing_common\toolchain_harness.c(67): error C2036: 'void *': unknown size
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\BUILDT~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\nmake.exe"' : return code '0x2'

**Comment by Xiaohanjlll** [comment]
I will check this issue.

**Comment by qizhangz** [comment]
Please also check this build error.

C:\Workspace\project\mine\libspdm\unit_test\fuzzing\test_spdm_responder_algorithms\algorithms.c(428): error C2220: the following warning is treated as an error
C:\Workspace\project\mine\libspdm\unit_test\fuzzing\test_spdm_responder_algorithms\algorithms.c(428): warning C4244: '=': conversion from 'uint32_t' to 'uint8_t', possible loss of data
NMAKE : fatal error U1077: 'C:\PROGRA~2\MIB055~1\2019\BUILDT~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe' : return code '0x2'

**Comment by steven-bellock** [comment]
GCC permits pointer arithmetic on void pointers https://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Pointer-Arith.html However this is illegal according to the C standard.
