### ISSUE TITLE
test_spdm_requester_get_certificate Fuzzing test occur ‘Infinite loop’

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#337]
Verified on 3e0e1b9
```
cd libspdm
mkdir build
cd build
cmake -DARCH=x64 -DTOOLCHAIN=AFL -DTARGET=Release -DCRYPTO=mbedtls -DGCOV=ON ..
make copy_sample_key
make
cd bin
./test_spdm_requester_get_certificate ./test_spdm_requester_get_certificate_hang
request (offset 0x0, size 0x400):
spdm_send_spdm_request[0] (0x8):
0000: 10 82 00 00 00 00 00 04
spdm_receive_spdm_response[0] (0x368):
0000: 11 02 00 00 00 00 01 00 31 2c 30 2a 06 03 55 04 03 0c 23 69 6e 74 65 6c 20 74 65 73 74 20 45 43
0020: 50 32 35 36 20 69 6e 74 65 72 6d 65 64 69 61 74 65 20 63 65 72 74 30 1e 17 0d 32 31 31 30 31 32
...
Certificate (offset 0x0, size 0x0):
request (offset 0x0, size 0x400):
spdm_send_spdm_request[0] (0x8):
0000: 10 82 00 00 00 00 00 04
spdm_receive_spdm_response[0] (0x368):
0000: 11 02 00 00 00 00 01 00 31 2c 30 2a 06 03 55 04 03 0c 23 69 6e 74 65 6c 20 74 65 73 74 20 45 43
0020: 50 32 35 36 20 69 6e 74 65 72 6d 65 64 69 61 74 65 20 63 65 72 74 30 1e 17 0d 32 31 31 30 31 32
...
Certificate (offset 0x0, size 0x0):
request (offset 0x0, size 0x400):
spdm_send_spdm_request[0] (0x8):
0000: 10 82 00 00 00 00 00 04
spdm_receive_spdm_response[0] (0x368):
0000: 11 02 00 00 00 00 01 00 31 2c 30 2a 06 03 55 04 03 0c 23 69 6e 74 65 6c 20 74 65 73 74 20 45 43
0020: 50 32 35 36 20 69 6e 74 65 72 6d 65 64 69 61 74 65 20 63 65 72 74 30 1e 17 0d 32 31 31 30 31 32
```
**The above log will Infinite Ioop print, need press ctrl + C to stop.**
Please extract the attached zip file to get the binary file "test_spdm_requester_get_certificate_hang".
[test_spdm_requester_get_certificate_hang.zip](https://github.com/DMTF/libspdm/files/7640427/test_spdm_requester_get_certificate_hang.zip)

I think the root cause is the following Line87~Line197:
do { spdm_send_spdm_request; 
**spdm_receive_spdm_response**; } while (**spdm_response.remainder_length != 0**).

The scenario is when Responder response cannot return the **entire data** requested by the Requester in the first response, this means do { spdm_send_spdm_request; **spdm_receive_spdm_response**; }  more than one time, but our fuzzing test_harness will keep the same buffer response every time, spdm_response.remainder_length will never decrease.

https://github.com/DMTF/libspdm/blob/3e0e1b9c20ed568704a393bc02686236d773a3c4/library/spdm_requester_lib/libspdm_req_get_certificate.c#L87-L197

**Comment by qizhangz** [comment]
I will check this

**Comment by qizhangz** [comment]
spdm_response.remainder_length is not reduced in the below function. So the infinite loop is caused by fuzzing code itself. 

unit_test/fuzzing/test_spdm_requester_get_certificate/get_certificate.c:
return_status spdm_device_receive_message(IN void *spdm_context,
					  IN OUT uintn *response_size,
					  IN OUT void *response,
					  IN uint64_t timeout)
{
	spdm_test_context_t *spdm_test_context;

	spdm_test_context = get_spdm_test_context();
	*response_size = spdm_test_context->test_buffer_size;
	copy_mem(response, spdm_test_context->test_buffer,
		 spdm_test_context->test_buffer_size);

	return RETURN_SUCCESS;
}

**Comment by Xiaohanjlll** [comment]
I will check this
