### ISSUE TITLE
SPDM_DEVICE_CONTEXT for Requester and Responder 

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#34]
From https://github.com/jyao1/openspdm/issues/3

SPDM_DEVICE_CONTEXT is overloaded with both Requester and Responder context.

Suggest define SPDM_REQUESTER_CONTEXT and SPDM_RESPONDER_CONTEXT instead.

**Comment by jyao1** [comment]
currently it seems no much overhead for 1.1. Not sure for 1.2 and future. Will revisit if we see big difference.

**Comment by rkongintel** [comment]
I'm seeing the size of spdm_context_t close to 70KB. Code/rodata is also 50KB+. This is going to be tough for embedded environments. Would like to revisit this issue again, perhaps after adding conditional compilation based on caps support.

**Comment by jyao1** [comment]
I think size issue may be addressed in https://github.com/DMTF/libspdm/issues/22.

**Comment by jyao1** [comment]
@rkongintel if you have any proposal, feel free to submit PR as well.

**Comment by jyao1** [comment]
With https://github.com/DMTF/libspdm/pull/158, the context size can be reduced to 29KB.

**Comment by jyao1** [comment]
With https://github.com/DMTF/libspdm/pull/159, we can start investigating code optimization.
Current responder is ~50K, requester is ~40K.

I think we can define more feature flags, such as encapsulated message for mutual auth.

**Comment by rkongintel** [comment]
Collected some data on the sizes of various members of the spdm_context_t:

Struct::Member                                Bytes   Overall %
spdm_context_t                                70176       100.00
last_spdm_request                              4608         6.57
last_spdm_error                                   8         0.01
encap_context                                  4648         6.62
spdm_session_state_callback                      32         0.05
spdm_connection_state_callback                   32         0.05
local_context                                   232         0.33
connection_info                                4176         5.95
transcript                                    14688        20.93
session_info                                  37056        52.80
response_state                                    4         0.01
error_data                                        4         0.01
cache_spdm_request                             4608         6.57

**Comment by rkongintel** [comment]
You're right. I was working on an older version.  I'll port my tool to the latest and run there.

  commit df3db1ba161f4164d5aca21dd394a940411b156b (HEAD -> main, origin/main, origin/HEAD)
      Author: yi1 li <yi1.li@intel.com>
      Date:   Thu Sep 2 14:31:41 2021 +0800
        Add test case about first returned cert is not root.
        Signed-off-by: yi1 li <yi1.li@intel.com>

**Comment by steven-bellock** [comment]
Closing as we don't feel to space savings is worth the effort, for now. May re-open in the future.
