### ISSUE TITLE
Stack space in spdm_responder_dispatch_message

### ISSUE THREAD

**Issue by richkong88** [DMTF/libspdm#351]
Seems like we use significant stack space in the responder dispatch code path. In just reviewing the code (not measuring programmatically), I estimate we can use 22K+ of stack space. This is due to multiple large buffers of size MAX_SPDM_MESSAGE_BUFFER_SIZE (0x1200).

This is the flow I see and the stack space used at each level of the stack:

spdm_responder_dispatch_message 9K
-----ctxt->receive_message
---------spdm_process_message
-------------spdm_process_request
-----------------ctxt->transport_decode_message (spdm_transport_mctp_decode_message) 9K
-------------spdm_build_response 4.5K
-----------------ctxt->transport_encode_message (spdm_transport_mctp_encode_message) 9K
-----ctxt->send_message

Total stack usage from spdm_responder_dispatch_message -> spdm_build_response->transport_encode_message
is (9K + 4.5K + 9K). It would be good if someone else can confirm this flow is using that much.

This is just for tracking now.

**Comment by jyao1** [comment]
I think you are probably right.
We need do some optimization work to make it smaller. The basic idea is to preserve the header.

**Comment by qizhangz** [comment]
I will check this

**Comment by steven-bellock** [comment]
Right now will defer to STABLE 0.2. It might make it into 0.1.

**Comment by qizhangz** [comment]
With PR #409, the stack is reduced by 20K in the responder dispatch code path. Context size is increased by 12K.
Can this be accepted?

**Comment by jyao1** [comment]
@rkongintel , would you please review it?

**Comment by rkongintel** [comment]
@jyao1 Yes. I will review.

**Comment by jyao1** [comment]
continue working on it after #409.

**Comment by jyao1** [comment]
Some idea for the buffer management.

We need provide option to allow external (libspdm integrator) to provides the buffer to libspdm - to achieve zero copy.
1) libspdm integrator provides `send_buffer` to libspdm - libspdm can manage the pointer inside of `send_buffer`.
2) libspdm integrator provides `receive_buffer` to libspdm - libspdm can manage the pointer inside of `receive_buffer`.
3) libspdm integrator provides `scratch_buffer` to libspdm - libspdm can manage the pointer inside of `scratch_buffer`. Sizeof `scratch_buffer` can be calculated based upon transport capability.

The usage of scratch buffer to hold a copy of messages, such as decrypted send_buffer, decrypted receive_buffer, last_message.

**Comment by ekohandel** [comment]
> 1. libspdm integrator provides `send_buffer` to libspdm - libspdm can manage the pointer inside of `send_buffer`.
> 2. libspdm integrator provides `receive_buffer` to libspdm - libspdm can manage the pointer inside of `receive_buffer`.

I spent some time looking at this today and I would like to propose the following direction:

## Receive
#### Change Receive Function
Change the `libspdm_device_receive_message_func` type from:
```c
typedef return_status (*libspdm_device_receive_message_func)(
    IN void *spdm_context, IN OUT uintn *message_size, IN OUT void *message,
    IN uint64_t timeout);
```
to
```c
typedef return_status (*libspdm_device_receive_message_func)(
    IN void *spdm_context, IN OUT uintn **message_size, IN OUT void **message,
    IN uint64_t timeout);
```
The message type change from `void *` to `void **` will allow the library user to provide a pointer to the buffer to libspdm and indicate the size of that buffer.

### Introduce Receive Free Function
Introduce a new client registered IO function with the following type:
```c
typedef return_status (*libspdm_device_free_receive_message_func)(
    IN void *spdm_context, IN void *message);
```
This can be used to indicate to the client that the received message buffer is no longer in use and can be reused. This may be necessary in an application where the underlying transport buffer is shared by multiple protocols running on the same transport. For example other protocols running on MCTP or DOE may be sharing this buffer.

## Send
### Introduce Allocate Send Message Function
Introduce a new client registered IO function with the following type:
```c
typedef return_status (*libspdm_device_alloc_message_func)(IN void *spdm_context,
                                                           IN OUT uintn *message_size,
                                                           OUT void **message);
```
This can be used by libspdm to allocate a send message from the underlying transport which can then be used with the `libspdm_device_send_message_func` function.

We can either allow the transport to allocate the largest buffer it can in which case `message_size` would only be an `OUT` or we can use the `message_size` parameter to request a size and use it to indicated size of the allocated buffer in which case it would be an `IN OUT` parameter.

In the latter case where `message_size` is an `IN OUT` parameter we would need to add a `libspdm_set_data` setting to indicate to libspdm what the maximum allowable buffer size is. We would want this to be a run time setting to allow for using the same compiled instance of the library with different transports instances that have different buffer size capabilities.

The latter case is more desirable as it allows the user to limit the size of buffer libspdm can allocate. It would allow for a user to partition underlying transport resources between libspdm and another protocol running on the same transport.

## Allocated Buffer
### `request_response` Context Buffer
The `request_response` buffer can be removed with the above changes as the buffer will be provided by the client. This will come at the cost of calls to `libspdm_device_alloc_message_func` and `libspdm_device_free_receive_message_func` functions.

### Stack Allocated `message` in `libspdm_send_request`
I believe this can also be removed with a call to `libspdm_device_alloc_message_func`.

### Stack Allocated `message` in `libspdm_receive_response`
I believe this can also be removed with a call to `libspdm_device_alloc_message_func`.

> libspdm integrator provides scratch_buffer to libspdm - libspdm can manage the pointer inside of scratch_buffer. Sizeof scratch_buffer can be calculated based upon transport capability.

I will have to look at this one in further detail but wanted to discuss the first 2 points.

CC: @anasarif

**Comment by richkong88** [comment]
Hi @ekohandel. 

Thank you for looking into this. I like the general direction, where libspdm asks the client via callbacks to allocate/free buffers.  

I think libspdm needs to provide a ` message_size` and not leave it wide open, as the the client could in one shot exhaust all of its space in one shot . 

I also feel it's cleaner for libspdm to allocate buffers in only one callback, instead of the two: `libspdm_device_receive_message_func` and `libspdm_device_alloc_message_func`. 
So allocate the buffer only in `libspdm_device_alloc_message_func` and free it in `libspdm_device_free_message_func`.

Then you would not need to change the `libspdm_device_receive_message_func` interface, but libspdm would need to call `libspdm_device_alloc_message_func` first in the flow, in additional to calling `libspdm_device_free_message_func` when complete. 

I seem to remember there being five 4.5K buffers needed in the flows, worst case . We would need to make sure the client/integrator is aware of this minimum requirement.

**Comment by ekohandel** [comment]
> I think libspdm needs to provide a ` message_size` and not leave it wide open, as the the client could in one shot exhaust all of its space in one shot .

I agree, this was also my suggested approach.

> I also feel it's cleaner for libspdm to allocate buffers in only one callback, instead of the two: `libspdm_device_receive_message_func` and `libspdm_device_alloc_message_func`. So allocate the buffer only in `libspdm_device_alloc_message_func` and free it in `libspdm_device_free_message_func`.
> 
> Then you would not need to change the `libspdm_device_receive_message_func` interface, but libspdm would need to call `libspdm_device_alloc_message_func` first in the flow, in additional to calling `libspdm_device_free_message_func` when complete.

The solution I had proposed was intended to also move us towards a zero copy solution. Your suggestion assumes that `libspdm` owns initiating the retrieval of the message from its 0th copy.

In that architecture it makes sense that `libspdm` would allocate a buffer and then request the message to be put in it. However, in some architectures, the underlying layer may have already retrieved the message from its 0th copy location which will have introduced 1 copy already.

My proposal was intended to address both of these architectures. In the first architecture, the client can allocate and do the copy. In the 2nd architecture the client can just provide a pointer to the already allocated and filled buffer.

So in my proposal we would be adopting an allocation by producer and free by consumer model. So for incoming messages, underlying layer allocates and `libspdm` frees. For outgoing messages, `libspdm` allocates and underlying layer frees.

> I seem to remember there being five 4.5K buffers needed in the flows, worst case . We would need to make sure the client/integrator is aware of this minimum requirement.

Yeah, I am hoping to tackle these improvements incrementally so I had only looked at the one for now.

**Comment by richkong88** [comment]
@ekohandel Those are fair points. I can see your desire to eliminate the extra copy. Sometimes these extra copies are just the extra tax paid for abstraction :) Curious if others @steven-bellock @jyao1 have any input on your proposal?

**Comment by steven-bellock** [comment]
I will try and look at this today.

**Comment by steven-bellock** [comment]
@ekohandel 
> This can be used to indicate to the client that the received message buffer is no longer in use and can be reused.

If the client doesn't care they would have to register a function that just returns SUCCCESS, correct?

> For outgoing messages, libspdm allocates and underlying layer frees.

So libspdm would call `malloc`? In the past we have avoided this as it allows the integrator to reason about heap-allocated memory.

**Comment by jyao1** [comment]
I create a discussion - https://github.com/DMTF/libspdm/discussions/702

**Comment by jyao1** [comment]
> I would argue this only smells like malloc but isn't malloc.
I propose we choose another name to avoid confusion.
I use aquire_buffer() and release_buffer() in #702.

**Comment by jyao1** [comment]
I created WIP tree at https://github.com/jyao1/libspdm/tree/spdm_buffer and https://github.com/jyao1/spdm-emu/tree/spdm_buffer. 

It can run correctly in OS environment. And I need sometime to clean up before final submit.

@richkong88 , @ekohandel , @steven-bellock , in case you have time to review, please do provide feedback.
