### ISSUE TITLE
TestCrypt Failures.

### ISSUE THREAD

**Issue by rkongintel** [DMTF/libspdm#363]
Is anyone else seeing the crypto failures when running test_crypt.exe (Win64)?

Crypto Wrapper Cryptosystem Testing:
--------------------------------------------
 Crypt hash Engine Testing:
- SHA256: Init... Update... Finalize... Check value... HashAll... [Pass]
- SHA384: Init... Update... Finalize... Check value... HashAll... [Pass]
- SHA512: Init... Update... Finalize... Check value... HashAll... [Pass]
- SHA3_256: Update... [Failed]
- SHA3_384: [Failed]
- SHA3_512: [Failed]
- SM3_256: HashAll... [Failed]

Crypto HMAC Engine Testing:
- HMAC-SHA256: Update... Finalize... Check value... [Pass]
- HMAC-SHA3_256: [Fail]

Crypto HKDF Engine Testing:
- HKDF-SHA256: extract... Check value... expand... Check value... extract_and_expand... Check value... [Pass]
- HKDF-SHA3_256: extract... [Fail]

Crypto AEAD Testing:
- AES-GCM Encryption: [Pass]
- AES-GCM Decryption: [Pass]
- ChaCha20Poly1305 Encryption: [Pass]
- ChaCha20Poly1305 Decryption: [Pass]
- SM4-GCM Encryption: [Fail]

Crypto RSA Engine Testing:
- Generate RSA context ... Set/Get RSA key Components ... Clear/Get RSA key Components ... Generate RSA key Components ... Check Invalid RSA key Components ... hash Original message ... PKCS#1 signature ... PKCS#1 signature Verification ... PSS signature ... PSS signature Verification ... Release RSA context ... [Pass]

Crypto RSA key Retrieving Testing:
- Retrieve RSA Private key for PEM ...[Pass]
- Retrieve RSA public key from X509 ... [Pass]
- PKCS#1 signature ... [Pass]
- PKCS#1 signature Verification ... [Pass]
- X509 Certificate Verification with Trusted CA ...[Pass]
- X509 Certificate Chain Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get root certificate Verification ... [Pass]
- X509 Certificate subject Bytes Retrieving ... [Pass]
- X509 Certificate context Retrieving ...
  - Retrieving Common name = "intel test ECP256 intermediate cert" (size = 36) - [PASS]
  - Retrieving Oraganization name - [PASS]
  - Retrieving version = 2 - [Pass]
  - Retrieving serial_number = 1 - [Pass]
  - Retrieving issuer Bytes ...  - [Pass]
  - Retrieving Issuer Common name = "intel test ECP256 CA" (size = 21) - [Pass]
  - Retrieving Issuer Oraganization name - [Pass]
  - Retrieving  SubjectAltName (size = 42) - [Pass]
  - Retrieving Validity - [Pass]
  - Set date_time - [Pass]
  - Set date_time - [Pass]
  - Compare date_time - [Pass]

- X509 Certificate Verification with Trusted CA ...[Pass]
- X509 Certificate Chain Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get root certificate Verification ... [Pass]
- X509 Certificate subject Bytes Retrieving ... [Pass]
- X509 Certificate context Retrieving ...
  - Retrieving Common name = "intel test ECP256 intermediate cert" (size = 36) - [PASS]
  - Retrieving Oraganization name - [PASS]
  - Retrieving version = 2 - [Pass]
  - Retrieving serial_number = 1 - [Pass]
  - Retrieving issuer Bytes ...  - [Pass]
  - Retrieving Issuer Common name = "intel test ECP256 CA" (size = 21) - [Pass]
  - Retrieving Issuer Oraganization name - [Pass]
  - Retrieving  SubjectAltName (size = 42) - [Pass]
  - Retrieving Validity - [Pass]
  - Set date_time - [Pass]
  - Set date_time - [Pass]
  - Compare date_time - [Pass]

- X509 Certificate Verification with Trusted CA ...[Pass]
- X509 Certificate Chain Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get root certificate Verification ... [Pass]
- X509 Certificate subject Bytes Retrieving ... [Pass]
- X509 Certificate context Retrieving ...
  - Retrieving Common name = "intel test RSA intermediate cert" (size = 33) - [PASS]
  - Retrieving Oraganization name - [PASS]
  - Retrieving version = 2 - [Pass]
  - Retrieving serial_number = 1 - [Pass]
  - Retrieving issuer Bytes ...  - [Pass]
  - Retrieving Issuer Common name = "intel test RSA CA" (size = 18) - [Pass]
  - Retrieving Issuer Oraganization name - [Pass]
  - Retrieving  SubjectAltName (size = 42) - [Pass]
  - Retrieving Validity - [Pass]
  - Set date_time - [Pass]
  - Set date_time - [Pass]
  - Compare date_time - [Pass]

- X509 Certificate Verification with Trusted CA ...[Pass]
- X509 Certificate Chain Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get leaf certificate Verification ... [Pass]
- X509 Certificate Chain get root certificate Verification ... [Pass]
- X509 Certificate subject Bytes Retrieving ... [Pass]
- X509 Certificate context Retrieving ...
  - Retrieving Common name = "intel test RSA intermediate cert" (size = 33) - [PASS]
  - Retrieving Oraganization name - [PASS]
  - Retrieving version = 2 - [Pass]
  - Retrieving serial_number = 1 - [Pass]
  - Retrieving issuer Bytes ...  - [Pass]
  - Retrieving Issuer Common name = "intel test RSA CA" (size = 18) - [Pass]
  - Retrieving Issuer Oraganization name - [Pass]
  - Retrieving  SubjectAltName (size = 42) - [Pass]
  - Retrieving Validity - [Pass]
  - Set date_time - [Pass]
  - Set date_time - [Pass]
  - Compare date_time - [Pass]

Crypto DH Engine Testing:
- Context1 ... Context2 ... Generate key1 ... Generate key2 ... Compute key1 ... Compute key2 ... Compare Keys ... [Pass]

Crypto EC-DH key Exchange Testing:
- Context1 ... Context2 ... Generate key1 ... Generate key2 ... Compute key1 ... Compute key2 ... Compare Keys ... [Pass]
- Context1 ... Context2 ... Generate key1 ... Generate key2 ... Compute key1 ... Compute key2 ... Compare Keys ... [Pass]

Crypto EC-DSA Signing Verification Testing:
- Context1 ... Context2 ... Compute key1 ... Compute key2 ...
- EC-DSA Signing ... EC-DSA Verification ... [Pass]
- EC-DSA Signing ... EC-DSA Verification ... [Pass]

Crypto EC-DSA Signing Verification Testing with SetPubKey:
- Context1 ... Context2 ... Compute key in Context1 ... Export key in Context1 ... Import key in Context2 ...
- EC-DSA Signing in Context1 ... EC-DSA Verification in Context2 ... [Pass]

Crypto EC key Retrieving Testing:
- Retrieve EC Private key for PEM ...[Pass]
- Retrieve EC public key from X509 ... [Pass]
- EC-DSA Signing ... [Pass]
- EC-DSA Verification ... [Pass]

Crypto Ed-DSA Signing Verification Testing:
- Context1 ... [Fail]
Crypto Ed key Retrieving Testing:
- Retrieve Ed Private key for PEM ...[Fail]
Crypto Montgomery Curve key Exchange Testing:
- Context1 ... [Fail]
Crypto SM2 key Exchange Testing:
- Context1 ... [Fail]
Crypto sm2 key Retrieving Testing:
- Retrieve sm2 Private key for PEM ...[Fail]
Crypto PRNG Engine Testing:
- Random Generation...[Pass]

**Comment by jyao1** [comment]
that is expected. No all crypt functions are supported in mbedtls or openssl.

**Comment by rkongintel** [comment]
Dec 7-2021. Close as expected.
