### ISSUE TITLE
Build Error in VS2019

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#386]
> C:\Users\sbellock\Documents\GitHub\steven-bellock\libspdm\library\spdm_responder_lib\libspdm_rsp_encap_response.c(410) : warning C4702: unreachable code
> C:\Users\sbellock\Documents\GitHub\steven-bellock\libspdm\library\spdm_responder_lib\libspdm_rsp_encap_response.c(533) : warning C4702: unreachable code

For example

```
if (RETURN_ERROR(status)) {
        return libspdm_generate_error_response(
            spdm_context, SPDM_ERROR_CODE_INVALID_RESPONSE_CODE, 0,
            response_size, response);
        spdm_context->response_state = SPDM_RESPONSE_STATE_NORMAL;
    }
```

@taprinz will fix it.

**Comment by steven-bellock** [comment]
In the future this will be prevented by https://github.com/DMTF/libspdm/issues/381

**Comment by steven-bellock** [comment]
Apparently GCC removed this check: https://gcc.gnu.org/legacy-ml/gcc-help/2011-05/msg00360.html

**Comment by jyao1** [comment]
I think it is time to add windows MSVC build to CI - https://github.com/DMTF/libspdm/issues/381
