### ISSUE TITLE
Remove is_requester parameter from publicly visible functions

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#390]
The integrator should only have to specify, once, with a #define that they're building a Requester or a Responder. This would be accomplished by compiling libspdm_secured_message_lib and libspdm_common_lib directly into the Requester and Responder libraries.

**Comment by jyao1** [comment]
This is only applicable when this is_requester parameter is used consistently by one entity.

If one entity need call is_requester=TRUE in one place and is_requester=FALSE is another place, then it is hard to remove.

I forget if we have such case, we may need carefully review all places.

**Comment by steven-bellock** [comment]
I will provide a list of functions that would benefit from this. One solution would be add a new setting to the spdm context where, at the beginning of time, the integrator specifies whether the context is for a Responder or Requester.

**Comment by steven-bellock** [comment]
I'd like to see this in the Q1 2023 release. If the Integrator specifies at runtime in the `spdm_context` whether its for a Requester or Responder then we can do away with the `is_requester` parameter from all functions that take `spdm_context` as an input.
