### ISSUE TITLE
ASSERT_RETURN_ERROR should handle error status even when debug not enabled

### ISSUE THREAD

**Issue by taprinz** [DMTF/libspdm#393]
Currently, ASSERT_RETURN_ERROR will only check for return success when DEBUG is enabled

See definition here:
```
\#if !defined(MDEPKG_NDEBUG)
#define ASSERT_RETURN_ERROR(status_parameter)                                  \
    do {                                                                   \
        if (RETURN_ERROR(status_parameter)) {                          \
            DEBUG((DEBUG_ERROR,                                    \
                   "\nASSERT_RETURN_ERROR (status = %p)\n",        \
                   status_parameter));                             \
            _ASSERT(!RETURN_ERROR(status_parameter));              \
        }                                                              \
    } while (FALSE)
#else
#define ASSERT_RETURN_ERROR(status_parameter)
#endif
```

It ends up causing use cases as such in the codebase, where it looks like we are checking for error, but we are missing it entirely when debug is disabled:
```
    status = spdm_build_opaque_data_version_selection_data(
        spdm_context, &opaque_psk_exchange_rsp_size, ptr);
    ASSERT_RETURN_ERROR(status);
    ptr += opaque_psk_exchange_rsp_size;
```

ASSERT_RETURN_ERROR should do one of the following:
- Be removed entirely, as ASSERTS should be for configuration mismatches, rather than runtime checks
- Actually return the relevant error, and if debug enabled, throw assert before returning error
- Keep same behavior, but make it clear that it will only throw assert, and error handling should still be done

I think it would be best to remove (as a part of refactoring ASSERT usage in general). If we are going to keep, I'm a fan of the former, although it should be made obvious that the assert will actually return on failure, since any macro that impacts code flow can cause unintended consequences if impact isn't clear.

**Comment by jyao1** [comment]
ASSERT means to be removed entirely in release build.
