### ISSUE TITLE
With incorrect VERSION request_response_code, it should report error indicate the InvalidRequest

### ISSUE THREAD

**Issue by yzhu52** [DMTF/libspdm#40]
Receiving a SPDM message with a VERSION 0x0 request_response_code instead of a GET_VERSION 0x84.
Expected behavior: the responder refuses the VERSION message and produces an ERROR message indicating the InvalidRequest.
But current behavior: it is not refuse this message and works without error.

Test code example:
spdm_get_version_request_t m_spdm_get_version_request4 = {
	{
		SPDM_MESSAGE_VERSION_10,
		0x0,      // Correct value should be SPDM_GET_VERSION 0x84
	},
};
uintn m_spdm_get_version_request4_size = sizeof(m_spdm_get_version_request4);

status = spdm_get_response_version(spdm_context,
		    m_spdm_get_version_request4_size,
		   &m_spdm_get_version_request4,
		   &response_size, response);
assert_int_equal(status, RETURN_SUCCESS);
assert_int_equal(spdm_response->header.request_response_code, SPDM_ERROR);

**Comment by steven-bellock** [comment]
The test should not be calling spdm_get_response_version if the RequestResponseCode is not equal to 0x84.

**Comment by steven-bellock** [comment]
As an aside, this issue inspired https://github.com/DMTF/Security-TF/issues/1384

**Comment by jyao1** [comment]
Add assert to spdm_get_response_version. The test is invalid.
