### ISSUE TITLE
most of the fuzzing test cases have no scenario description

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#401]
most of the fuzzing test cases have no scenario description. It is difficult for future fail analyze and test case maintain.
1. for example:
https://github.com/DMTF/libspdm/blob/5f108919e509eccdc09410e50f85dd804f097eb6/unit_test/fuzzing/test_responder/test_spdm_responder_digests/digests.c#L163-L167
2. the same issue is in [capabilities.c](https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/test_responder/test_spdm_responder_capabilities/capabilities.c), [algorithms.c](https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/test_responder/test_spdm_responder_algorithms/algorithms.c), [certificate.c](https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/test_responder/test_spdm_responder_certificate/certificate.c) and so on.

**Comment by Xiaohanjlll** [comment]
I will check this issue.
