### ISSUE TITLE
Application message could be smaller than spdm_header_t

### ISSUE THREAD

**Issue by rcaalves** [DMTF/libspdm#405]
The check in the line bellow could wrongly yield an error if is_app_message ends up being true and the application message is smaller than spdm_header_t.
https://github.com/DMTF/libspdm/blob/53d3c80a04cfaa79352a9758ce5d25a0367a2119/library/spdm_responder_lib/libspdm_rsp_receive_send.c#L162

**Comment by jyao1** [comment]
agree
