### ISSUE TITLE
Found duplicate content in some script files

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#430]
There are duplicate content in the following script files:
https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/fuzzing.sh
https://github.com/DMTF/libspdm/blob/main/os_stub/openssllib/process_files.pl
https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/tool/transfer_ktest_to_seed.py

this commit https://github.com/DMTF/libspdm/commit/674374968bb9796ba7cfcac360d466384910af6d lead to this issue.

**Comment by jyao1** [comment]
Would you please be more specific on what content is duplicated?

**Comment by Zhiqiang520** [comment]
> Would you please be more specific on what content is duplicated?

For example,  the following Line 199 to end Line is duplicated with the Line 1 to Line 198.
https://github.com/DMTF/libspdm/blob/674374968bb9796ba7cfcac360d466384910af6d/unit_test/fuzzing/fuzzing.sh#L1-L5

https://github.com/DMTF/libspdm/blob/674374968bb9796ba7cfcac360d466384910af6d/unit_test/fuzzing/fuzzing.sh#L198-L203

**Comment by Zhiqiang520** [comment]
Add more information: 
1. It seems that all the binary seeds flies of fuzzing test also have been modified and found some duplicate content.
![image](https://user-images.githubusercontent.com/90754803/146718703-2c7a9a75-65e7-4818-b4bb-00a015ebeb92.png)
2. For example:
the yellow highlight background byte 4-7  `11 FF 81 30` is duplicate with the byte 0-3  `11 FF 81 30`.
https://github.com/DMTF/libspdm/tree/main/unit_test/fuzzing/seeds/test_spdm_responder_if_ready
![image](https://user-images.githubusercontent.com/90754803/146718994-346f535c-f57c-442c-8bb4-734f0ee6ef09.png)

**Comment by jyao1** [comment]
@https://github.com/Wenxing-hou,  need revert change for the fuzzing seed file.

**Comment by Wenxing-hou** [comment]
I will check it.
