### ISSUE TITLE
move "#define SPDM_MAX_VERSION_COUNT 5" from spdm.h back to libspdm_config.h

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#431]
Since SPDM_MAX_VERSION_COUNT is NOT defined in SPDM spec, I think we should move it back to config.h

**Comment by steven-bellock** [comment]
Decided at 20-Dec-2021 meeting that there should be two #defines. One for the maximum number of versions that libspdm supports, which is currently two (1.0 and 1.1). This is checked via an assertion. The other #define is for how many version entries in a VERSION response that a Requester will tolerate. For example if the Responder sends 10 version entries, and they are all the same version, then libspdm will throw an error. This is checked at runtime.
