### ISSUE TITLE
opaque_measurement_rsp should have get/set implementations in spdm_get_data/spdm_set_data

### ISSUE THREAD

**Issue by taprinz** [DMTF/libspdm#439]
opaque_measurement_rsp pointer and the accompanying opaque_measurement_rsp_size value are reset on spdm context init, but spdm_get_data/spdm_set_data functions do not support these values. Therefore, opaque data fields cannot be set without the library integrator directly modifying the context structure.

Would be best to allow the user to set and modify these values via the above interfaces, rather than having to know information about context structure.

There are probably more examples.

**Comment by steven-bellock** [comment]
#1991 removed opaque data from the SPDM context. It is now populated via a function call.
