### ISSUE TITLE
Improve VCA request / response validation

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#44]
Examples include:

- Validate that one-hot fields are actually one-hot.
- In negotiate_algorithms the requester loops over ALGORITHMS.param1 without validating it first.

**Comment by jyao1** [comment]
agree

**Comment by steven-bellock** [comment]
Also in `libspdm_try_get_version` we need to validate that the major / minor version numbers are legal; 1.0, 1.1, 1.2, etc.

**Comment by steven-bellock** [comment]
In `NEGOTIATE_ALGORITHMS` libspdm needs to check `struct_table->alg_type`.

**Comment by steven-bellock** [comment]
This has been sufficiently completed.
