### ISSUE TITLE
unit test: test_spdm_common error 

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#450]
When build pass, run test_spdm_common. The error is found.

```
[ RUN      ] test_spdm_common_context_data_case4
[  ERROR   ] --- 0x0 != 0x80000005
[   LINE   ] --- C:\mywork\code\libspdm\unit_test\test_spdm_common\context_data.c:180: error: Failure!
[  FAILED  ] test_spdm_common_context_data_case4
```

**Comment by jyao1** [comment]
Do you run with X64 arch?
It seems the test assume X64 arch.

**Comment by steven-bellock** [comment]
@raghuncstate introduced these tests. Now that the field is called LIBSPDM_DATA_APP_CONTEXT_DATA instead of OPAQUE_DATA we need to rename the word "opaque".

**Comment by steven-bellock** [comment]
But yes `data_return_size = 4;` should be something like `data_return_size = sizeof(void *) - 1;`

**Comment by jyao1** [comment]
agree

**Comment by Wenxing-hou** [comment]
I will check it.
