### ISSUE TITLE
C89 Compatibility Issues

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#454]
While attempting to enable C89 compilation I ran into the following fundamental issues.
- C89 does not support 64-bit integers (`long long int`). 64-bit integers are mainly used in the secure message lib to keep track of sequence numbers and IVs. The `timeout` parameter is also 64-bit. Luckily GCC supports `long long int` in C89.
- C89 does not support variadic macros. This is mainly a debug library issue, specifically the macro `_DEBUG_PRINT(PrintLevel, ...)`. The benefit of having it as a macro is that it can be optimized away via a #define. The alternative would be to ditch the macro and perform a function call directly to `debug_print(...)` and rely on link-time optimizations to get rid of the function call if not needed.

So the question is how important is it to work around these limitations?

**Comment by jyao1** [comment]
I try to be realistic. The importance depends upon if there is any usage of C89 only compiler for the libspdm project.

My suggest is to check if there is anything broken.
If nothing is broken, then we dont fix.
If something is broken, let's review what is broken is how to fix/work-around it.

**Comment by steven-bellock** [comment]
The use of `static_assert` is also an issue but we can work around that with `#error` which is a c89 construct.

**Comment by steven-bellock** [comment]
I got close to full support, but the 64-bit integers are a sticking point. An integrator will have to do a little work for it to compile under a C89 compiler.
