### ISSUE TITLE
Lack logic in spdm_verify_peer_cert_chain_buffer function

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#462]
In the spdm_verify_peer_cert_chain_buffer function, we use two ways to verify the peer cert chain buffer. 
The two ways is: root_cert and  cert_chain_data. The code is show :
https://github.com/DMTF/libspdm/blob/a75c98423d5a623d9fca3017e90b6a78a1088656/library/spdm_common_lib/libspdm_com_crypto_service.c#L601
https://github.com/DMTF/libspdm/blob/a75c98423d5a623d9fca3017e90b6a78a1088656/library/spdm_common_lib/libspdm_com_crypto_service.c#L649

However, the situation(there is no root_cert and cert_chain_data) we didn't consider.

we should add the new logic path:
```
else {
      DEBUG((DEBUG_INFO, "!!! verify_peer_cert_chain_buffer - FAIL: there is no root_cert and  cert_chain_data!!!\n"));
      return FALSE;
}
```

**Comment by jyao1** [comment]
I think it is expected to return TRUE, because no provision means the caller wants to verify the trust anchor of the cert chain.

Maybe we need some comment to describe the expected behavior to avoid confusing.
