### ISSUE TITLE
Consider supporting encryption-only secure sessions

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#475]
The SPDM specification (DSP0274) allows for a secure session to be encryption-only with no MAC. libspdm currently only supports MAC-only or encryption and MAC. In the spirit of completeness we may want to support encryption-only secure sessions.

**Comment by steven-bellock** [comment]
Although DSP0277 says
> An encryption only session shall be prohibited. 

so, as usual, I am confused. Expect to see an issue filed against DSP0274.

**Comment by steven-bellock** [comment]
>Expect to see an issue filed against DSP0274.

It is done. https://github.com/DMTF/Security-TF/issues/1721

**Comment by steven-bellock** [comment]
After talking with the Security Task Force we confirmed that
1. DSP0274 does allow encryption-only secure sessions.
2. DSP0277 forbids encryption-only secure sessions.

So if libspdm wanted to support encryption-only secure sessions it could
- Use the exact same scheme as DSP0277 and just don't generate the MAC / tag.
- Leave it up to the end users to implement their own libspdm secured_message_lib.

**Comment by jyao1** [comment]
My feeling is:
1) Before DSP0277 describes the encryption only (1.0), we leave it to user-defined secure_message_lib.
2) After DSP0277 describes the encryption only (1.x), we will add it to default secure_message_lib, with configuration_macro to disable it by default.

**Comment by steven-bellock** [comment]
I don't think DSP0277 will ever allow encryption-only. They forbid it for security reasons. @raghuncstate or @xiaoyuruan can comment.

**Comment by jyao1** [comment]
libspdm only follows DSP0277.
If DSP0277 does not describe it, I dont think it is good idea to add it by default.
We have to leave to user defined ecure_message_lib.

**Comment by xiaoyuruan** [comment]
I don't see DSP0277 needing to support encrypt only sessions either.  

Is libspdm implementing general DSP0274 or only the DSP0277-flavored DSP0274?  
If libspdm intends to support general libspdm, it should allow integrator / transport to decide tag size.

**Comment by jyao1** [comment]
I would say this:
libspdm supports general DSP0274 in default libspdm provided requester_lib and responder_lib.
libspdm supports DSP0277 in default libspdm provided secured_message_lib.

If an integrator wants to use its own format (such as encryption only) which is NOT defined in DSP0277, then the integrator must provide its own secured_message_lib. It can still work with requester_lib and responder_lib.

That is how libspdm isolates the role and responsibility.

**Comment by steven-bellock** [comment]
libspdm will not support encryption-only secure sessions. Integrators are free to implement their own secured-message library to provide that functionality.
