### ISSUE TITLE
try_spdm_send_receive_finish does not free session ID on error: session ID leak

### ISSUE THREAD

**Issue by jcahill0** [DMTF/libspdm#476]
Walking through the code for try_spdm_send_receive_key_exchange after allocating a session ID, nearly every error from there on causes the session ID to be freed.  Below is the only case where that does not happen and probably should free the session ID:
```
    opaque_length = *(uint16_t *)ptr;
    if (opaque_length > SPDM_MAX_OPAQUE_DATA_SIZE) {
        return RETURN_SECURITY_VIOLATION;
    }
```

And try_spdm_send_receive_finish doesn't bother to free the session ID in any error, which is session ID allocation leak unless the integrator does this for libspdm.  If an error happens here, it seems like most of the recoveries are to either: start KEY_EXCHANGE again, or redo attestation.  Either case would justify freeing the current session ID as cleanup in try_spdm_send_receive_finish, as try_spdm_send_receive_key_exchange would rightfully allocate a new unique session ID without the freeing of the current session ID.

Only a timeout is difficult in regards to FINISH.  In theory, the command could be retried, but if the transcripts mismatch, the responder would just send an ERROR response.  And using a timeout to jump back to KEY_EXCHANGE with the freed session ID would cause a reuse of the ID, but the responder may think the session ID is already in use by the requestor (as the responder may have sent the FINISH_RSP or missed the original FINISH request).

**Comment by jyao1** [comment]
I think there are several issues:
1) req_key_exchange shall free session_id in SPDM_MAX_OPAQUE_DATA_SIZE errors. (following same error handling pattern)
2) red_psk_exchange shall include SPDM_MAX_OPAQUE_DATA_SIZE check, free session_id and return error. (following same error handling pattern)
3) I agree that finish/psk_finish shall cleanup in case of error. (following same error handling pattern)

Here the "same error handling pattern" means 1) free session_id, 2) free dhe_context if key is not established, 3) zero negotiated keys.

**Comment by Wenxing-hou** [comment]
I will check it.
