### ISSUE TITLE
try_spdm_get_certificate needs to ensure forward progress

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#478]
try_spdm_get_certificate uses a do-while loop to fetch portions of a certificate chain from the Responder:

```
do
{
.
.
} while (spdm_response.remainder_length != 0);
```

However it needs to ensure the response's `remainder_length` field eventually goes to 0, else it can be held in an infinite loop by the Responder.

**Comment by jyao1** [comment]
Any recommendation on what criteria can be used to break the loop ?

**Comment by steven-bellock** [comment]
```
if (remainder_length[n] < remainder_length[n -1])
/* Keep going. */
else
/* Return error. */
```

**Comment by jyao1** [comment]
Makes sense.
And I think we can add more check.
```
total_length = portion_length[0] + remainder_length[0];
if (offset[n] + portion_length[n] + remainder_length[n] == total_length) {
  /* Keep going. */
} else {
  /* Return error. */
}
```

**Comment by Wenxing-hou** [comment]
I will check it.
