### ISSUE TITLE
libspdm_com_opaque_data.c should not hardcode secured message binding version.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#480]
In current code, SPDM_MESSAGE_VERSION_11 is hardcoded in libspdm_com_opaque_data.c as the  secured message binding version.

The secured message version should be from secured_message_version in spdm_local_context_t, and negotiated value should be saved to spdm_connection_info_t.

**Comment by Wenxing-hou** [comment]
I will check it.
