### ISSUE TITLE
improve libspdm_x509_certificate_check()

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#492]
1. x509_get_signature_algorithm() should check the if the algorithm matches the negotiated one, after negotiation is done.

2. x509_get_key_usage() should be moved before x509_get_extended_key_usage(). The former is mandatory, the later is optional.

3. Add check for basic constrains - CA=FALSE

4. x509_get_extended_key_usage() should be optional. Only check if it is present for consistency for DeviceCert or AliasCert
4.1 - Hardware Identity OID.
4.2 - Mutable certificate OID.
4.3 - SPDM Responder Authentication OID
4.4 - SPDM Requester Authentication OID
4.5 - Non Critical OID

**Comment by steven-bellock** [comment]
Why doesn't libspdm parse the certificate once, then store that information in the context? Right now it parses the certificate with every challenge, measurement, key exchange, etc.

**Comment by jyao1** [comment]
> Why doesn't libspdm parse the certificate once, then store that information in the context? Right now it parses the certificate with every challenge, measurement, key exchange, etc.

Is this same issue or new issue?
This issue only addresses missing check. I recommend we file a new issue for store the info in context.

**Comment by Wenxing-hou** [comment]
I will check it.
