### ISSUE TITLE
Requester slot_id checks should be assertions

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#493]
https://github.com/DMTF/libspdm/blob/2a7afd9ed271d9ea3e6e719d59d0325bc2ff15ca/library/spdm_requester_lib/libspdm_req_challenge.c#L86-L92
https://github.com/DMTF/libspdm/blob/2a7afd9ed271d9ea3e6e719d59d0325bc2ff15ca/library/spdm_requester_lib/libspdm_req_get_certificate.c#L81-L83
https://github.com/DMTF/libspdm/blob/2a7afd9ed271d9ea3e6e719d59d0325bc2ff15ca/library/spdm_requester_lib/libspdm_req_key_exchange.c#L101-L107

**Comment by jyao1** [comment]
1/10/2022 - probably need review all check to see if it makes sense to use ASSERT.
