### ISSUE TITLE
responder heartbeat is not handled correct.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#494]
In current libspdm, responder receives heartbeat and just returns the heartbeat_ack back.

Ideally, we need a watchdog for the session. 
1) A heartbeat msg will reset the watchdog.
2) If watchdog timeout, we need terminate the session.

Since watchdog is platform specific,  we may just define API for watchdog.
Then libspdm can call watchdog API to init_watchdog() at start_session() and reset_watchdog() at heartbeat().
A watchdog timeout event can terminate the session directly.

**Comment by qizhangz** [comment]
I will check this

**Comment by jyao1** [comment]
this is also related to timeout, ref #20
