### ISSUE TITLE
SPDM_ERROR_CODE_INVALID_REQUEST is incorrectly returned

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#50]
There are multiple instances where, after spdm_append_message* is called, the requester or responder returns SPDM_ERROR_CODE_INVALID_REQUEST. The error should be SPDM_ERROR_CODE_UNSPECIFIED, since the specification lacks a good error for when the endpoint has run out of resources.

**Comment by taprinz** [comment]
Note - in capabilities.c in spdm_responder_lib, we also don't check whether spdm_append_message* is successful - this should be changed, with the above error codes returned, to be more in line with other message handlers.

**Comment by jyao1** [comment]
Is that duplicated with https://github.com/DMTF/libspdm/issues/23 ?

**Comment by steven-bellock** [comment]
Yes, looks like Yi took care of everything. Closing as duplicate.
