### ISSUE TITLE
Add unit test to cover 1.2 extension

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#502]
REF: https://github.com/DMTF/libspdm/pull/477

1. ack_request_id in spdm_encapsulated_response_ack_response_t.
2. other_params_support in algorithm negotiation and new opaque format_1.
3. session_policy in key_exchange and psk_exchange.
4. data_transfer_size and max_spdm_msg_size in capability, CHUNK and ALIAS_CERT cap in capability.
5. raw_bit request and content change in measurement and new measurement type definition.

**Comment by Xiaohanjlll** [comment]
I will check it.
