### ISSUE TITLE
SPDM 1.2 need handle data_transfer_size and max_spdm_msg_size capability

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#503]
Missing 1.2 feature, after https://github.com/DMTF/libspdm/pull/477

For chunk, ref https://github.com/DMTF/libspdm/issues/504

**Comment by jyao1** [comment]
1/10/2022 - not sure how to use two fields without chunking. Maybe add them together with chunking.

**Comment by qizhangz** [comment]
I will check this

**Comment by jyao1** [comment]
This issue can only handle data_transfer_size.

max_spdm_msg_size  can be done in #504
