### ISSUE TITLE
Add SPDM 1.2 CHUNK support.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#504]
Missing 1.2 feature, after https://github.com/DMTF/libspdm/pull/477

Since this is optional, recommend to define a new LIBSPDM_ENABLE_CAPABILITY_CHUNK

**Comment by jyao1** [comment]
1/10/2022 - add when we have use case.

**Comment by richkong88** [comment]
I'm starting to look at chunking commands now. I'm interested on your thoughts @steven-bellock @jyao1 on how chunking should be exposed to users of the requester library. 

Should requests that allow for chunking automatically fallback to chunk mode on large response errors? 

For example, libspdm requester code issues a get_measurements request. If an error with error code "large response" is returned, should the library issue chunk_get requests behind the scenes, without the consumer of libspdm requester knowing? or should the consumer of libspdm requester code be required to issue the chunk_get request?

**Comment by jyao1** [comment]
Good question.

Yes. I do hope it can be done in in common function, without known by each individual command.
For example, get_measurement just knows it gets a response, but it does not know it is a large response or not.

**Comment by richkong88** [comment]
Ok, from the previous response, I will try to hide the chunking from any consumers of libspdm as much as possible. Now another question.

What level of error handling/restarting of a request should we support? 

For example, suppose the requester is performing get_measurement and needs a large response.  As the libspdm requester code is processing the chunk_get requests, one of the chunks fails with responder busy. Normally, the requester code retries the request on busy, but I think this would complicate the code significantly. 

I was thinking of adding the large message handling into the error handling code path deep in the requester under `libspdm_handle_error_response_main`. And the retry loop on busy errors is at the highest level of the requester. So handling error busy while handling on error large message may not be clean, unless there are multiple places for retries.

Is it sufficient for the libspdm requester code to fail the entire get_measurements request if any chunks fail and return error back to the consumer of libspdm requester, or does libspdm need to be able to restart at only the chunk that fails and keep trying, without the consumer of the requester knowing about the failure?

Perhaps we can discuss this in the task force meeting.

**Comment by jyao1** [comment]
Sure. It seems good topic.

**Comment by richkong88** [comment]
Another question. If there is a large response stored in the responder waiting for CHUNK_GET, is it an invalid usage model to receive a CHUNK_SEND request before the CHUNK_GETs are all requested? I suppose a bad requester could never ask for the large response after the large response error then issues a CHUNK_SEND and responder should be able to handle this situation.

**Comment by steven-bellock** [comment]
The specification is silent on if, after the Requester has received the `LargeResponse` error from the Responder, the Requester has to initiate `CHUNK_GET` to get the response, or if it can ignore the response and send some other request. For libspdm I think it's fine for the Responder to return `UnexpectedRequest` if the Requester fails to get all the chunks via `CHUNK_GET`.
