### ISSUE TITLE
Add SPDM 1.2 GET_CSR support

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#505]
Missing 1.2 feature, after #477

Since this is optional, recommend to define a new LIBSPDM_ENABLE_CAPABILITY_PROVISION

REF: https://github.com/DMTF/libspdm/issues/506

**Comment by jyao1** [comment]
1/10/2022 - add when we have use case.

**Comment by richkong88** [comment]
My team has a use case.
