### ISSUE TITLE
Correct the error code for messages with mismatched version

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#509]
Current code used SPDM_ERROR_CODE_INVALID_REQUEST but 1.2 spec mentioned:

If the Requester uses a
different version than the selected version in other Requests, the Responder should return an ERROR message with
ErrorCode = VersionMismatch or the Responder can silently discard the Request.

**Comment by jyao1** [comment]
agree

**Comment by Wenxing-hou** [comment]
Yes. I will check it.
