### ISSUE TITLE
SPDM 1.0 - What is correct order for the responder to send the GET_CERTIFICATE response?

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#522]
I've the following in my certificate chain (Root_Cert, intermediate_cert, device_cert, alias0_cert, alias1_cert), working on implemting the GET_CERTIFICATE response, so when I receive the GET_CERTIFICATE request, I will be sending the response in the below order..        ​

GET_CERTIFICATE_RESPONSE_HEADER
Certificate_chain_format
root_cert
intermediate_cert
device_Cert
alias0_Cert
alias1_cert

(Please note- alias1_Cert ismy leaf cert)

Am I sending the certificate in the correct order? If not, please correct. Thanks in Advance!!

**Comment by goutham23** [comment]
I’m confused, how can both very be at least significant bytes

**Comment by steven-bellock** [comment]
Edited it. :)

**Comment by goutham23** [comment]
Thank you

**Comment by goutham23** [comment]
@steven-bellock : Sorry for the late reply, according to your reply "root_cert is at the least significant bytes and alias1_cert is at the most significant bytes." then should I  be sending the response in the below order, right ​??

GET_CERTIFICATE_RESPONSE_HEADER
Certificate_chain_format
alias1_cert
alias0_Cert
device_Cert
intermediate_cert
root_cert

"OR this order...

GET_CERTIFICATE_RESPONSE_HEADER
Certificate_chain_format
root_cert
intermediate_cert
device_Cert
alias0_Cert
alias1_cert

**Comment by steven-bellock** [comment]
```
GET_CERTIFICATE_RESPONSE_HEADER
Certificate_chain_format
root_cert
intermediate_cert
device_Cert
alias0_Cert
alias1_cert
```

**Comment by goutham23** [comment]
Thanks

**Comment by rupesh-hpe** [comment]
Shouldn't it be the reverse order ? with the leaf appearing first ( when traversing from top to bottom )- 

GET_CERTIFICATE_RESPONSE_HEADER
Certificate_chain_format
alias1_cert
alias0_Cert
device_Cert
intermediate_cert
root_cert

This is how the other certs exist with root at the bottom of the file. Example - https://www.digicert.com/kb/ssl-support/pem-ssl-creation.htm

**Comment by jyao1** [comment]
Please read SPDM 1.2, 10.6.1 Certificates and certificate chains:

In the context of this specification, a complete certificate chain is one where: (i) the first certificate is either signed by a Root Certificate (a certificate that specifies a trust anchor) or is a Root Certificate itself, (ii) each subsequent certificate is signed by the preceding certificate, and (iii) the final certificate contains the public key used to authenticate the SPDM endpoint. The final certificate is called the leaf certificate.

**Comment by rupesh-hpe** [comment]
> Please read SPDM 1.2, 10.6.1 Certificates and certificate chains:
> 
> In the context of this specification, a complete certificate chain is one where: (i) the first certificate is either signed by a Root Certificate (a certificate that specifies a trust anchor) or is a Root Certificate itself, (ii) each subsequent certificate is signed by the preceding certificate, and (iii) the final certificate contains the public key used to authenticate the SPDM endpoint. The final certificate is called the leaf certificate.

Totally agree on the order of signing and the cert chain creation . My comment was indicative of the non standard way in which the cert file gets generated here when compared to other standard cert files which have cert chain.
