### ISSUE TITLE
SPDM_1.1 - GET_DIGEST response requirement 

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#523]
From the spec, for GET_DIGEST response, we need to return the digest of the entire certificate chain for each slot and not digest of just the root certificate - Is my understanding correct?

**Comment by steven-bellock** [comment]
Yep. It's the digest of a `certificate chain` for a given slot as defined in `Table 28 — Certificate chain format` of the 1.2 specification.
<html>
<body>


Byte offset | Field | Size (bytes) | Description
-- | -- | -- | --
0 | Length | 2 | Total length of the certificate chain, in bytes, including all fields in this table. This field is little endian.
2 | Reserved | 2 | Reserved.
4 | RootHash | H | Digest of the Root Certificate. Note that Root Certificate is ASN.1 DER-encoded for this digest. This field shall be in Hash byte order. H is the output size, in bytes, of the hash algorithm selected by the most recent ALGORITHMS response.
4 + H | Certificates | Length- (4 + H) | A complete certificate chain, consisting of one or more ASN.1 DER-encoded X.509 v3 certificates. This field shall be in Encoded ASN.1 byte order.


</body>
</html>
