### ISSUE TITLE
spdm_general_opaque_data_table_header_t definition error

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#525]
https://github.com/DMTF/libspdm/blob/main/include/industry_standard/spdm.h#L364

```
typedef struct {
    uint8_t total_elements;
    uint16_t reserved;
    /*opaque_element_table_t  opaque_list[];*/
} spdm_general_opaque_data_table_header_t;
```

The reserved field should be 3 bytes, not 2 bytes.

See: SPDM 1.2: Table 92 — General opaque data format

**Comment by Wenxing-hou** [comment]
I will check it.
