### ISSUE TITLE
extend  `last_spdm_error`  to generic requester lib usage

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#541]
Current requester_lib caller can only get libspdm defined error message. It cannot get what the responder returned error code.

We need enable libspdm_get_last_spdm_error_struct() for requester_lib as well, to allow the consumer of requester_lib can also know what error is returned from responder.

This will be used for conformance test in the future.

**Comment by Wenxing-hou** [comment]
I will check it.

**Comment by jyao1** [comment]
It is not needed after I review the code again. Close it.
