### ISSUE TITLE
CI should check that .h and .c files end with newline

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#555]
Possible solution: https://stackoverflow.com/questions/38746/how-to-detect-file-ends-in-newline

**Comment by ekohandel** [comment]
A wholistic solution might be to use a tool like uncrustify to enforce style. It is capable of enforcing new lines at the end of the files as well as much more.

I noticed there is a clang-format file in the repo but it is not enforced and the code is already noncompliant with that style.

I have personally found uncrustify more flexible than clang-format. For example clang-format is not capable of enforcing new lines at the end of the file as far as I can tell.

**Comment by jyao1** [comment]
@ekohandel , would you propose a solution by using uncrustify ?

**Comment by ekohandel** [comment]
@jyao1, I have opened #575 but from my experience style is very contentious so we may have to iterate on the configurations of uncrustify before the style is acceptable. Unfortunately uncrustify is an all or none tool so I couldn't pick to only apply some of its configurations.
