### ISSUE TITLE
Convert the boolean type to bool

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#557]
1. Similar to how we handle `stdint.h`, add `stdbool.h` to processor_bind.h.
2. Remove `typedef unsigned char boolean;` from processor_bind.h.
3. Remove `#define TRUE ((boolean)(1 == 1))` and `#define FALSE ((boolean)(0 == 1))` from base.h.
4. Convert instances of `TRUE` and `FALSE` to `true` and `false`.

**Comment by jyao1** [comment]
what is sizeof(bool) ?

**Comment by steven-bellock** [comment]
The C standard says
> An object declared as type _Bool is large enough to store the values 0 and 1.

which means that `sizeof(bool)` could be > 1 although in practice it's always 1.

**Comment by jyao1** [comment]
May I suggest to add build time ASSERT for sizeof(bool) == 1 ?

**Comment by steven-bellock** [comment]
Sure, if we decide to support `static_assert`.
