### ISSUE TITLE
Is it mandatory that the requester must support DMTF measurement?

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#558]
In spdm_get_response_algorithms(), the responder checks that the requester must also support DMTF Measurement if the responder supports MEAS_CAP.

https://github.com/DMTF/libspdm/blob/529224184c4f5ee7fb33d191d0985690944418f8/library/spdm_responder_lib/libspdm_rsp_algorithms.c#L494-L502

But in spec, it seems not mandatory that the requester must support DMTF measurement.
In Table 15 — NEGOTIATE_ALGORITHMS request message format, it didn't require the requester to set at least one bit in MeasurementSpecification. It only says the requester can set more than one bit.
Bit mask. The MeasurementSpecification field in Table 44 — Measurement block
format defines the values in this field. The Requester can set more than one bit to
indicate multiple measurement specification support.

However, the spec also asks that the responder "shall" select one of the measurement specifications supported by the Requester. 

It becomes ambiguous if there is no measurement specification the responder could select, especially if the requester didn't even support or need measurement.

Spec-wise, could people here help clarify my understanding above?
Implementation-wise, I was wondering if the responder should be that restricted.
It should be okay for the responder to allow MeasurementSpecificationSel to be zero in ALGORITHMS response and return errors if later the requester sends commands requiring the measurements.
I seemed to see this issue in openspdm issues but I couldn't find it now.
Appreciate if someone could help clarify this.

**Comment by steven-bellock** [comment]
> I seemed to see this issue in openspdm issues but I couldn't find it now.

It's in https://github.com/DMTF/libspdm/issues/329.

**Comment by richard-chien** [comment]
May I know the status of this issue? In libspdm_rsp_algorithms.c, the responder assumes the requester always supports one and only one measurement specification, which is DMTF measurement. This would cause problems (see line 517) when the requester doesn't support any measurement specification or supports multiple measurement specifications in the future. Should this be taken into account?

**Comment by jyao1** [comment]
I agree it is a problem.
@richard-chien, do you have a real use case that we need resolve immediately?

**Comment by richard-chien** [comment]
> I agree it is a problem. @richard-chien, do you have a real use case that we need resolve immediately?
HPE iLO currently doesn't support measurement capabilities so it set bit 0 of MeasurementSpecification to 0. However, the device (responder) implements the same logic as mentioned above and therefore hits the error at line 517. This has resulted in interoperability issues.

**Comment by steven-bellock** [comment]
> > I agree it is a problem. @richard-chien, do you have a real use case that we need resolve immediately?
> 
> HPE iLO currently doesn't support measurement capabilities so it set bit 0 of MeasurementSpecification to 0. However, the device (responder) implements the same logic as mentioned above and therefore hits the error at line 517. This has resulted in interoperability issues.

Even if the Requester doesn't support measurements it can still set `MeasurementSpecification` to 1 and then not request the `MeasurementSummaryHash` for `CHALLENGE`, `KEY_EXCHANGE`, and `PSK_EXCHANGE`.

**Comment by rw8896** [comment]
@steven-bellock 
In spec 1.1.2 (published 26 Apr 2022), the descriptions explicitly mentioned that the Requester can set zero bits if MEASUREMENTS are not supported.

`Bit mask. The measurement specification is used in the MEASUREMENTS response.
Requester can set all available algorithms defined in the measurement specification
format. The Requester can set zero bits if MEASUREMENTS are not supported.`

**Comment by rw8896** [comment]
On the responder side, if the Requester didn't support MEASUREMENT,
then in ALGORITHMS response,
- MeasurementSpecificationSel should be zero.
- MeasurementHashAlgo? The spec only mentioned `If the Responder supports GET_MEASUREMENTS , exactly one bit in this bit field shall be set. Otherwise, the Responder shall set this field to 0 .` It becomes ambiguous when the Requester didn't not support MEASUREMENT.  I hope the spec could also address this by changing the descriptions to `If the Requester and Responder support MEASUREMENT` or something similar to clarify it.

**Comment by steven-bellock** [comment]
Yeah we can add that to the specification. If you have access to https://github.com/DMTF/Security-TF you can file an issue, else I can do it.

**Comment by steven-bellock** [comment]
@rw8896 I've filed https://github.com/DMTF/Security-TF/issues/2014
