### ISSUE TITLE
Consider to remove IN, OUT, OPTIONAL and replace them by const.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#570]
Current code is using IN, OUT, OPTIONAL macro to provide description on parameter.
This cannot be enforced by compiler. A better way is to use const.
IN == const.
OUT == no const.
OPTIONAL - discard.

**Comment by richkong88** [comment]
Code is also using INOUT. We should be using const anyway, but I do like the IN, INOUT, OUT. Perhaps it should be specified in the comments?

**Comment by jyao1** [comment]
Agree. We don't need update comment.
This issue only need remove IN/OUT/OPTIONAL modifier in the code.

**Comment by qizhangz** [comment]
I will check this
