### ISSUE TITLE
Need enable compiler warning for discards qualifiers

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#572]
Related fix:
#566 
#565 
#563 
#561 

We need enable such warning treat error by default, and catch them in CI in the future.

**Comment by ekohandel** [comment]
This can be achieved by enabling `-Wcast-qual` but applying this is a bit more tricky than I expected. Currently the compile configurations are set at the main CMakeLists.txt and passed down to the crypto library's compilation step. This results in compiling the crypto library with this warning enabled as well which at least in the case of mbedtls results in errors.

We might have to decouple compiling of the crypto libraries and their build configuration from the compilation of libspdm itself and just define a dependency on a crypto library from libspdm's configuration.

**Comment by steven-bellock** [comment]
>We might have to decouple compiling of the crypto libraries and their build configuration from the compilation of libspdm itself and just define a dependency on a crypto library from libspdm's configuration.

Yes, that has been floating in my mind for a while; `libspdm/os_stub` as well.

**Comment by jyao1** [comment]
Agree. Crypto lib such as openssl, mbedtls can be handled later.
The primary work to enforce the policy to libspdm libraries.
