### ISSUE TITLE
Need add LIBSPDM_ or libspdm_ for any external symbol or MACRO

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#576]
For example, https://github.com/DMTF/libspdm/issues/222

**Comment by steven-bellock** [comment]
In addition, symbols and MACROS that are currently publicly viewable but don't need to be should be moved to an internal header so that the integrator doesn't have to see them and we don't have to document them.

**Comment by qizhangz** [comment]
I will check this

**Comment by jyao1** [comment]
Please also resolve missing camel case issue. such as:
```
SpdmGetEncapResponseFuncViaRequestCode
SpdmProcessEncapsulatedRequest
mSpdmGetResponseStruct
SpdmRequesterSendMessage
SpdmRequesterReceiveMessage
SpdmResponderSendMessage
SpdmResponderReceiveMessage
mSpdmRequesterGetVersionTestContext
```

Also remove unused `SPDM_TEST_CONTEXT_FROM_SPDM_PROTOCOL` and `SpdmGetResponseFinish`.
