### ISSUE TITLE
Limit buffer usage in transcript hash calculations to save stack space.

### ISSUE THREAD

**Issue by taprinz** [DMTF/libspdm#58]
In functions where a transcript hash is required, we frequently allocate more buffers than necessary, and we can save on stack space by being more prudent with how buffers are utilized. Since these functions can be the culprit of largest stack usage, lowering this stack space is valuable for running on any resource-limited platforms.

For example, in spdm_generate_key_exchange_rsp_signature, we allocate "th_curr_data", a buffer of MAX_SPDM_MESSAGE_BUFFER_SIZE. Later, we pass "th_curr_data" as the output buffer when calling the function spdm_calculate_th_for_exchange.

https://github.com/DMTF/libspdm/blob/631028abb33ab22d318e5ffcd43b0a87fcda89df/library/spdm_common_lib/crypto_service_session.c#L226-L243

The function spdm_calculate_th_for_exchange allocates its own large_managed_buffer_t, "th_curr", to hold the transcript.
https://github.com/DMTF/libspdm/blob/631028abb33ab22d318e5ffcd43b0a87fcda89df/library/spdm_common_lib/crypto_service_session.c#L31

Once the transcript is copied into the temporary "th_curr", it is copied out into "th_curr_data" at the end of the function.
https://github.com/DMTF/libspdm/blob/631028abb33ab22d318e5ffcd43b0a87fcda89df/library/spdm_common_lib/crypto_service_session.c#L82-L84

On the stack, this requires two MAX_SPDM_MESSAGE_BUFFER_SIZE byte buffers to be allocated on the stack. In this scenario, "th_curr" is redundant, and we could simply utilize "th_curr_data" directly as the output buffer in spdm_calculate_th_for_exchange, removing one of the large buffers from the stack.

This usage pattern is typical for transcript calculation functions, so we could make this improvement in multiple areas.

**Comment by taprinz** [comment]
The main issue I could see with making this change is that we could write a partially completed transcript to the output buffer, then encounter an issue, leading to error being returned and a buffer filled with incomplete data, rather than empty.

This can be resolved by clearing the output buffer in case of failure.

**Comment by steven-bellock** [comment]
Approved.

**Comment by jyao1** [comment]
@taprinz, do you still see the issue with new LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT ?

**Comment by taprinz** [comment]
ack request - I need to re-integrate latest in order to analyze stack space usage before and afterwards. might take me a sec to formally measure.

looking at the changes, though, I would feel pretty confident that this greatly addresses extraneous memory and stack usage.

**Comment by taprinz** [comment]
Consider issue resolved by #22
