### ISSUE TITLE
PIE options used in makefile

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#583]
Hi All,

I am a little confused why the the cflags has -fpie but the link flag uses -no-pie in the CMakeLists for example
https://github.com/DMTF/libspdm/blob/9c601cdec10846851264c55daa7ef5948f6ab763/CMakeLists.txt#L187-L204

Would you help explain the intention here?

Thanks!

**Comment by rw8896** [comment]
@jyao1 Do you know the effect of not specifying -fpie in CFLAGS? Or could we replace it with -fpic?

**Comment by jyao1** [comment]
I think it is a copy-paste error. Feel free to make a proposal.

**Comment by steven-bellock** [comment]
This is part of a larger issue on auditing and providing rationale for the different compiler flags, and to also allow the integrator to override flags to match their environment.
