### ISSUE TITLE
Update Documentation related to Toolchain option

### ISSUE THREAD

**Issue by alokprasad** [DMTF/libspdm#594]
Documentation related to TOOLCHAIN needs to be updated 
e.g while reading README.md its looks like only Two TOOLCHAIN option for Linux is supported i.e
CLANG or GCC 
so if you want to try compiling on aarch64 with GCC  based on the documentation you 
will use the below command

```cmake -DARCH=aarch64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=mbedtls ..```
but this will fail in the compilation

Looking at the CMAKElist.txt actual command should  be 
```cmake -DARCH=aarch64 -DTOOLCHAIN=AARCH64_GCC -DTARGET=Release -DCRYPTO=mbedtls ..```
( and this worked.)

**Comment by jyao1** [comment]
I think we should always use GCC and remove AARCH64_GCC.

**Comment by alokprasad** [comment]
Agree, its not cross-compilation and internally we should assign right gcc and only keep clang and gcc as option.

**Comment by steven-bellock** [comment]
I can start a discussion on host-compilation vs cross-compilation use cases. We may want to specify `DHOST=x64` and `DCROSS=AARCH64`.

**Comment by alokprasad** [comment]
@steven-bellock  sounds good.
Also was interested if we can compile libspdm with arm-none-eabi  toolchains.

**Comment by steven-bellock** [comment]
> `cmake -DARCH=aarch64 -DTOOLCHAIN=GCC -DTARGET=Release -DCRYPTO=mbedtls ..`
but this will fail in the compilation

@alokprasad How does it fail? Are you compiling on a x86 or ARM host?

**Comment by steven-bellock** [comment]
Started discussion at https://github.com/DMTF/libspdm/discussions/612.

**Comment by alokprasad** [comment]
@steven-bellock compiling on Ampere Sever ( aarch64) u cant use GCC u have to use AARCH64_GCC

**Comment by steven-bellock** [comment]
Ah I see now. @alokprasad are you seeing errors like 
> gcc: error: unrecognized command line option ‘-mno-red-zone’

This is a GCC compiler option for x86 and should be controlled by `ARCH` in CMake.

**Comment by alokprasad** [comment]
Yes correct.
