### ISSUE TITLE
Can SPDM requester ever issue GET_DIGEST command before GET_CERTIFICATE command?

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#600]
From the spec 1.0, "Section 4.9.2 - "The GET_DIGESTS request message and DIGESTS response message may optimize the amount of data required to be transferred from the Responder to the Requester, due to the potentially large size of a certificate chain. The cryptographic hash values of each of the certificate chains stored on an endpoint is returned with the DIGESTS response message, such that the Requester can cache the previously retrieved certificate chain hash values to detect any change to the certificate  chains stored on the device before issuing  the GET_CERTIFICATE request message."

Can SPDM requester ever issue GET_DIGEST command before GET_CERTIFICATE command? or it have to be always that SPDM requester will send GET_DIGEST after GET_CERTIFICATE command in the flow?

**Comment by steven-bellock** [comment]
> Can SPDM requester ever issue GET_DIGEST command before GET_CERTIFICATE command?

Correct. `DIGESTS` is also valuable because `Param2` specifies which slots actually have certificates in them. Without that information the Requester has to guess which slot to fetch in `GET_CERTIFICATE`.

**Comment by goutham23** [comment]
@steven-bellock  Thanks for the quick response. Second/followup question...

Let's say, SPDM requester sent GET_DIGEST received the response and then GET_CERTIFICATE received the response successfully.

Now, can SPDM requester immediately send another GET_DIGEST cmd again after GET_CERTIFICATE? or the SPDM requester has to send SPDM GET_VERSION, GET_CAPABILITIES, NEGOTIATE_ALGO commands before they can send GET_DIGEST command again?

**Comment by steven-bellock** [comment]
> Now, can SPDM requester immediately send another GET_DIGEST cmd again after GET_CERTIFICATE?

Correct. The SPDM specification has a bug where `GET_DIGEST` and `GET_CERTIFICATE` cannot be issued during a secure session, but that will be resolved in the specification and libspdm, see https://github.com/DMTF/libspdm/issues/586.

**Comment by goutham23** [comment]
@steven-bellock - WE are only implementing based on SPDM 1.0 spec and still confused whether to allow below case or responder should reply "invalid request" if responder receives another GET_DIGEST cmd again after GET_CERTIFICATE?

**Comment by steven-bellock** [comment]
In 1.0, after VCA, the Responder should reply with the appropriate DIGESTS / CERTIFICATES response to any GET_DIGESTS / GET_CERTIFICATES request. There are no sequencing restrictions.

**Comment by goutham23** [comment]
@steven-bellock - Thank you!!

**Comment by rw8896** [comment]
The message sequence restrictions kind of came from the M1/M2 calculation in spec 10.9.
If Authentication is not supported in your application, theoretically yes, you could issue GET_DIGESTS ->  GET_CERTIFACTE -> GET_DIGESTS after VCA and the responder shouldn't reject them.

But to comply with the sequences for M1/M2 calculation, my understanding is that GET_DIGESTS ->  GET_CERTIFACTE -> GET_DIGESTS is invalid where the last GET_DIGESTS will be rejected.

Spec 1.2 did allow a new sequence "GET_DIGESTS skipped, GET_CERTIFICATE issued" as B4 in the table, but that doesn't make your sequence valid.

**Comment by goutham23** [comment]
> The message sequence restrictions kind of came from the M1/M2 calculation in spec 10.9. If Authentication is not supported in your application, theoretically yes, you could issue GET_DIGESTS -> GET_CERTIFACTE -> GET_DIGESTS after VCA and the responder shouldn't reject them.
> 
> But to comply with the sequences for M1/M2 calculation, my understanding is that GET_DIGESTS -> GET_CERTIFACTE -> GET_DIGESTS is invalid where the last GET_DIGESTS will be rejected.
> 
> Spec 1.2 did allow a new sequence "GET_DIGESTS skipped, GET_CERTIFICATE issued" as B4 in the table, but that doesn't make your sequence valid.

We do support CHALLENGE_AUTH - How is GET_DIGESTS -> GET_CERTIFACTE -> GET_DIGESTS is invalid? Please explain

**Comment by rw8896** [comment]
Please search the following in spec.
"The possible request orderings after Reset leading up to and including CHALLENGE shall be:"

**Comment by steven-bellock** [comment]
@rw8896 That's a different issue and gets into the `General ordering rules` and "what is a retry?" issue. One of the questions is, in the sequence `GET_DIGESTS -> GET_CERTIFICATE -> GET_DIGESTS` can the second `GET_DIGEST` be considered a retry if it is the same request as the first `GET_DIGESTS`? If it's a retry then the second `GET_DIGEST` would not be a part of the M1/M2 transcript, as the specification was recently clarified to state
> Because a retried message is identical to the first, a retried message shall not be used in transcript hash calculations.

I can file an issue against the specification to clarify this.

**Comment by jyao1** [comment]
>  in the sequence GET_DIGESTS -> GET_CERTIFICATE -> GET_DIGESTS can the second GET_DIGEST be considered a retry if it is the same request as the first GET_DIGESTS?

I don't believe it is a try, because both entities already get GET_CERTIFICATE in the middle.

I think we need clarify:
1) if the second GET_DIGEST is legal?
2) if it is legal, then does it reset MESSAGE B?

**Comment by jyao1** [comment]
Second GET_DIGEST is legal. And it need reset MESSAGE B.

**Comment by rw8896** [comment]
> Second GET_DIGEST is legal. And it need reset MESSAGE B.

@jyao1 Will this be updated into spec to reset MESSAGE B?

Thanks!
