### ISSUE TITLE
Need support GET_DIGEST/GET_CERTIFICATE after CHALLENGE

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#605]
SPDM spec allows the requester to send GET_DIGESTS/GET_CERTIFICATE after a complete CHALLENGE.

But the current implementation uses "if (spdm_context->connection_info.connection_state !=        LIBSPDM_CONNECTION_STATE_NEGOTIATED) {" to determine if GET_DIGEST/GET_CERTIFICATE can be sent.

**Comment by rw8896** [comment]
@jyao1 Will this change be applied when negotiated version < 1.2?
Especially "GET_DIGESTS skipped, GET_CERTIFICATE issued" is added in 1.2.

**Comment by jyao1** [comment]
I would add such support for < 1.2 as well to achieve maximum compatibility.
At least, 1.0/1.1 does not forbid it.

**Comment by rw8896** [comment]
1.2 clarifies the reset definitions and add "GET_DIGESTS skipped, GET_CERTIFICATE issued" sequence.

If our implementation goal is maximum compatibility, then when negotiated version is < 1.2,
we probably should not allow the requester to explicitly support 1.2 changes,
but the responder could follow 1.2 changes to calculate M1/M2 and accept the new message sequences.

So libspdm requester could work with other responder which didn't implement the 1.2 changes.
And libspdm responder could work with other requester which implements the 1.2 changes.

Any thoughts?

**Comment by jyao1** [comment]
In general, I agree.
Please note: "libspdm requester" is just a library. The integrator controls the flow - not libspdm.

**Comment by rw8896** [comment]
And how about the state change?
It will be no longer Authenticated until the next challenge successfully
completes.
Is it correct?

**Comment by jyao1** [comment]
Very good question.

The reason is I designed the state to meet suggestion in SPDM:
"Because issuing GET_MEASUREMENTS clears the M1/M2 message transcript, it is recommended that a Requester
does not send this message until it has received at least one successful CHALLENGE_AUTH response message from
the Responder. This ensures that the information in message pairs GET_DIGESTS / DIGESTS and
GET_CERTIFICATES / CERTIFICATES has been authenticated at least once."

Since it is authenticated once, I think we can keep it as Authenticated.

**Comment by rw8896** [comment]
@jyao1 @steven-bellock  yes, it makes senses to me to stay Authenticated.
Thanks for the clarification.

**Comment by rw8896** [comment]
I re-think about this design change.

The current code uses the state to validate the message sequence.
If we start to allow the responder to accept GET_DIGESTS and/or GET_CERTIFICATES while staying Authenticated state, how will we track the message sequence to calculate M1/M2 for the next Challenge command?

**Comment by steven-bellock** [comment]
State will need to span multiple Request / Response pairs to allow the Responder to accept or reject a `CHALLENGE` request.

**Comment by rw8896** [comment]
@jyao1 @steven-bellock 

From #600 conclusion where 
> Second GET_DIGEST is legal. And it need reset MESSAGE B.

It looks like GET_DIGESTS and GET_CERTIFICATE could be accepted as long as connection state > `LIBSPDM_CONNECTION_STATE_NEGOTIATED` and state `AFTER_DIGESTS` and `AFTER_CERTIFICATE` are not needed anymore?

**Comment by hiption** [comment]
.
