### ISSUE TITLE
When is the plan to support ext logo in LIBSPDM?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#606]
For reference, I see that it is already specified in https://github.com/DMTF/libspdm/blob/main/library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c file that, 

/* current version libspdm does not support any ext algo.
 * the requester will not build ext algo in request.
 * the requester will ignore the ext algo in response.*/

May I know is there any plan to add this in LIBSPDM library?

**Comment by jyao1** [comment]
No plan so far. Do you have any use case?

**Comment by PrakashK94** [comment]
No, I was just comparing the [SPDM spec](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.0.pdf) with the LIBSPDM library sources, so I found out this gap, so listed there to check when it will be supported in the LIBSPDM library sources.

**Comment by jyao1** [comment]
No plan so far, because we dont know what/how to support, without a clear use case.

I suggest to close it now. If there is a clear use case, we can open a new one.
Unless you want to be the volunteer to take it.

**Comment by PrakashK94** [comment]
I have one more issue to discuss, regarding this, I see that these fileds are commented out in spdm_vendor_defined_request_msg_t stucture, which is there in this file, https://github.com/DMTF/libspdm/blob/main/include/industry_standard/spdm.h

//uint8                vendor_id[len];
//uint16               payload_length;
//uint8                vendor_defined_payload[payload_length];

May I know when is the plan to support this?

**Comment by jyao1** [comment]
Usually, we discuss one topic in one issue.

Would you please close this one and file a new issue on vendor defined message?

**Comment by PrakashK94** [comment]
sure, I will close this and will open a new issue.
