### ISSUE TITLE
Need reset watchdog in any session messages.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#608]
Background: https://github.com/DMTF/libspdm/issues/494

Follow up for https://github.com/DMTF/libspdm/pull/521 - "there will need to be a follow-up pull request to address issues such as number of watchdog timers available and resetting the watchdog."

In current code, the libspdm_reset_watchdog() is called in heartbeat.
It is wrong, because any session in message is an indicator to reset the watchdog.
We need call libspdm_reset_watchdog() in any session messages.

**Comment by qizhangz** [comment]
I will check this.
