### ISSUE TITLE
spdm_vendor_defined structure doesn't matches with SPDM spec

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#609]
I see that these fileds are commented out in spdm_vendor_defined_request_msg_t & spdm_vendor_defined_response_msg_t structure, which is there in this file, https://github.com/DMTF/libspdm/blob/main/include/industry_standard/spdm.h

//uint8 vendor_id[len];
//uint16 payload_length;
//uint8 vendor_defined_payload[payload_length];

May I know when is the plan to support this?

**Comment by jyao1** [comment]
1) I checked the spec again. I think the definition matches the spec.
Would please clarify why you think it does not match spec???

2) The vendor defined message is out of scope of libspdm.
I give some examples on how to send/receive at https://github.com/DMTF/spdm-emu

For example, 
https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_requester_emu/spdm_requester_session.c
https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_responder_emu/spdm_responder_session.c

**Comment by PrakashK94** [comment]
As per the SPDM spec, https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.0.pdf, it has these fields vendor_id, payload_length and vendor_defined_payload in vendor defined request and response structure, but I see in LIBSPDM these fields are commented out in vendor defined request/response structure.

See, Table 56 — VENDOR_DEFINED_REQUEST request message format.

**Comment by jyao1** [comment]
I comment it because C language does not support variable size structure definition.

**Comment by PrakashK94** [comment]
ok, I think we can close this because as "The vendor defined message is out of scope of libspdm" so we don't need to support this in LIBSPDM right?

**Comment by jyao1** [comment]
I would say:
1) libspdm allows the consumer to send/receive vendor define message. Such as PCI IDE, MCTP PLDM, etc.
2) But libspdm itself does not support parsing any vendor define message.
