### ISSUE TITLE
Encapsulated request response structure doesn't include encapsulated_request field as per SPDM spec 

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#610]
May I know why these fields(encapsulated_request,  encapsulated_response) are commented out in https://github.com/DMTF/libspdm/blob/main/include/industry_standard/spdm.h?

/* SPDM ENCAPSULATED_REQUEST response*/

typedef struct {
    spdm_message_header_t header;
  /* uint8_t                encapsulated_request[];*/
} spdm_encapsulated_request_response_t;

/* SPDM DELIVER_ENCAPSULATED_RESPONSE request*/

typedef struct {
    spdm_message_header_t header;
     /* uint8_t                encapsulated_response[];*/
} spdm_deliver_encapsulated_response_request_t;

/* SPDM ENCAPSULATED_RESPONSE_ACK response*/

typedef struct {
    spdm_message_header_t header;

    /* below 4 bytes are added in 1.2.*/
    uint8_t ack_request_id;
    uint8_t reserved[3];

    /*uint8_t                encapsulated_request[];*/
} spdm_encapsulated_response_ack_response_t;

**Comment by jyao1** [comment]
same reason - not all c compiler support empty array.

**Comment by PrakashK94** [comment]
This can be addressed right by defining a MACRO and then using that MACRO in structure or it can be addressed using pointer right? Are you not going to add this in future?

**Comment by jyao1** [comment]
NO.

**Comment by PrakashK94** [comment]
So, when we will send GET_ENCAPSULATED_REQUEST command to the responder then responder should send the encapsulated_request to the requester so how the requester will store that encapsulated_request in spdm_encapsulated_request_response_t structure?

**Comment by jyao1** [comment]
You may need read the source code to understand how it works. see libspdm_req_encap_xxx and  libspdm_rsp_encap_xxx.
