### ISSUE TITLE
Heartbeat timeout should be twice HeartbeatPeriod

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#614]
>The Responder shall terminate the session if session traffic is not received in twice HeartbeatPeriod.

Applies to `libspdm_start_watchdog` and `libspdm_reset_watchdog`.

**Comment by qizhangz** [comment]
I will check this

**Comment by qizhangz** [comment]
" Session traffic includes encrypted data at the transport layer. How SPDM is informed of encrypted data at the transport layer is outside of the scope of this specification."

I think this should be implemented in libspdm integrater and not in libspdm.

**Comment by qizhangz** [comment]
Understood. The timeout passed to watchdog should be twice HeartbeatPeriod.
