### ISSUE TITLE
Follow up for SPDM_ERROR_CODE_DECRYPT_ERROR.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#622]
Background: https://github.com/DMTF/libspdm/issues/488, https://github.com/DMTF/libspdm/issues/489

This is follow up for https://github.com/DMTF/libspdm/pull/519.

There are more cases to close session, such as GetMeasurement in session.
I think we need ensure all session messages handle this.

Or a better way is to have a generic place to handle SPDM_ERROR_CODE_DECRYPT_ERROR .

**Comment by Wenxing-hou** [comment]
I will check it.
