### ISSUE TITLE
Compile time setting of constants

### ISSUE THREAD

**Issue by richkong88** [DMTF/libspdm#623]
Some constants are known at compile time, such as capabilities and algorithms an integrator wishes to support. Currently these are set at runtime via the libspdm_set_data function. Can we have an option to set these at compile time and eliminate the unnecessary runtime code?

**Comment by jyao1** [comment]
Please also evaluate the size difference before and after, then we can know if there is value to do that.

**Comment by richkong88** [comment]
I experimented with this change [here](https://github.com/richkong88/libspdm/blob/rkong_compile_time_values/library/spdm_common_lib/libspdm_com_context_data.c). I didn't see any improvement in library code space. It actually went up a little. Code space for integrator's code would likely go down a little, making it a wash. It then is just more of a stylistic issue, to set at compile time vs runtime for some integrators, in my view. I don't feel the complications of this change and lack of value make it worth doing.

**Comment by jyao1** [comment]
Then can we close it?

**Comment by richkong88** [comment]
Yes. Closing.
