### ISSUE TITLE
The change in CMakeLists.txt need to be ported to spdm-emu.

### ISSUE THREAD

**Issue by ekohandel** [DMTF/libspdm#628]
The change in CMakeLists.txt need to be ported to spdm-emu.

_Originally posted by @qizhangz in https://github.com/DMTF/libspdm/issues/617#issuecomment-1034650018_

**Comment by ekohandel** [comment]
Ideally the CMakeLists.txt from `libspdm` should just be used by `spdm-emu` instead of having a separate copy.

**Comment by steven-bellock** [comment]
@ekohandel Are you able to take this issue?

**Comment by ekohandel** [comment]
Sure @steven-bellock, I am doing some prototyping with the `spdm-emu` and had to make these changes to make it work. I will just clean those up and submit a PR to `spdm-emu`. You can assign it to me.

I believe we are blocked on updating the `spdm-emu` -> `libspdm` submodule hash until this is done so I will make it a higher priority.

**Comment by ekohandel** [comment]
https://github.com/DMTF/spdm-emu/pull/54 created to address this.

**Comment by jyao1** [comment]
Merged. Close it.

**Comment by jyao1** [comment]
For further spdm-emu issue, please report to spdm-emu repo.
