### ISSUE TITLE
Use of uintn

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#63]
The type uintn is defined in processor_bind.h, and is described as

> Unsigned value of native width.  (4 bytes on supported 32-bit processor instructions,
> 8 bytes on supported 64-bit processor instructions)

There is a latent issue that may arise due to the use of uintn. libspdm may be ported to 8-bit or 16-bit microcontrollers, in which case uintn is not large enough to hold certain values. For example the function

```
/**
  Return the size in bytes of the SPDM context.

  @return the size in bytes of the SPDM context.
**/
uintn spdm_get_context_size(void);
```

returns the size of the internal context and is most assuredly greater than 255 bytes and, sometimes, even greater than 65535 bytes.

**Comment by jyao1** [comment]
Current arch only supports 32bit and 64bit.

Do we have use case to support 8bit or 16bit system?

**Comment by steven-bellock** [comment]
Either say libpsdm only supports 32-bit or 64-bit systems, or give guidance on how to adapt to 8 and 16 bit systems.

**Comment by jyao1** [comment]
Need a solution for uintn usage

**Comment by jyao1** [comment]
can we use size_t to replace uintn, instead of uint32_t ?

**Comment by steven-bellock** [comment]
Yes, probably size_t for sizes. We need to have at least one instance of 32-bit support in CI/CD when making this change to make sure we don't break 32-bit systems.

**Comment by jyao1** [comment]
Goal is to change integrator visible size to size_t. We may defer to internal change.
We can try to use replace-all.
Concern: how to make sure 32bit system still work. Maybe add CI.
