### ISSUE TITLE
question of get_digests verification

### ISSUE THREAD

**Issue by liyi77** [DMTF/libspdm#64]
In spec, responder will return digests of its local certchains one by one when received a valid get_digests request,
and requester should compare cached digests to digests in response(spec 214 and 234).
![image](https://user-images.githubusercontent.com/10961794/127620605-b0a5e24e-fcac-4d40-adf4-5f9e51d95155.png)
In libspdm, this implemented by compare digest of local peer_cert_chain_provision to digests in response.
But now it looks like that treated all digests as a whole and finally only compared first digest in response.
Is it a bug?
https://github.com/DMTF/libspdm/blob/ad088c17ca2d7aa4ef36b07be7e805dd13f7a793/library/spdm_requester_lib/get_digests.c#L150-L157

https://github.com/DMTF/libspdm/blob/ad088c17ca2d7aa4ef36b07be7e805dd13f7a793/library/spdm_common_lib/crypto_service.c#L361-L378

**Comment by steven-bellock** [comment]
As usual @liyi77 your issue with libspdm has inspired me to file an issue with the specification. https://github.com/DMTF/Security-TF/issues/1425
