### ISSUE TITLE
spdm_get_random_number should indicate whether random number generation succeeded

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#65]
random_bytes returns a boolean value to indicate whether random number generation was successful. However spdm_get_random_number does not convey this information to the caller. On the responder side this would more than likely result in an Unspecified error.

```
void spdm_get_random_number(IN uintn size, OUT uint8 *rand)
{
	random_bytes(rand, size);

	return;
}
```

**Comment by jyao1** [comment]
agree, we should return boolean.

**Comment by steven-bellock** [comment]
That stray "return" makes it look like it once returned a value.

**Comment by steven-bellock** [comment]
Closing due to broader issue https://github.com/DMTF/libspdm/issues/75
