### ISSUE TITLE
SPDM spec 1.0: CHALLENGE completion - Completion of CHALLENGE resets M1 and M2.

### ISSUE THREAD

**Issue by goutham23** [DMTF/libspdm#655]
As a responder, when I send the response to CHALLENGE_AUTH request, spec says we should reset the message transcript buffer, but, if the requester did not receive my response then the requester might send CHALLENGE_AUTH cmd again and by that time my transcript buffer will be null as I cleared it at the end of my challenge_auth_response API.

What is expected? requester cannot send challenge auth command back to back?

**Comment by jyao1** [comment]
if this is a retry, you need catch the response. see https://github.com/DMTF/libspdm/issues/491

if this is not a retry, then it is (A2, B2, C1), you need recalculate M1/M2.
