### ISSUE TITLE
Function types `spdm_device_send_message_func` and `spdm_device_receive_message_func` could receive opaque pointer.

### ISSUE THREAD

**Issue by rcaalves** [DMTF/libspdm#66]
The functions registered trough `spdm_register_device_io_func` may need extra information that is not available in spdm_context (therefore not easily obtainable).

Would it be the case to pass an opaque pointer to these function calls?
The opaque pointer could be registered in `spdm_register_device_io_func` along with the functions.

**Comment by jyao1** [comment]
Agree. How about we use:

typedef return_status (*spdm_device_send_message_func)(
						       IN void *spdm_device_io_context, // new field.
						       IN void *spdm_context,
						       IN uintn message_size,
						       IN void *message,
						       IN uint64 timeout);

**Comment by rcaalves** [comment]
Sounds good to me.

An alternative would be to just store the pointer inside spdm_context, without modifying the function signature.
Not sure what is best.

**Comment by jyao1** [comment]
It is also OK to store the pointer to spdm_context, then we need define a new API to get the context.

**Comment by steven-bellock** [comment]
I prefer having the pointer inside spdm_context.

**Comment by steven-bellock** [comment]
Approved. Will discuss later on actual implementation.
