### ISSUE TITLE
Some question about Cert formation

### ISSUE THREAD

**Issue by Wenxing-hou** [DMTF/libspdm#678]
It is a question not a issue. 
For Cert formation, I was a little confused by reading SPDM spec:  [1.2.0](https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.2.0.pdf)

The SPDM spec isn't clear for the cert SPDM OID part. I think there are two situation in cert formation. 
In the SPDM spec, it may be situation 2. 

But in the spec x.509 [RFC5280](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.2), it may not be allowed for other standard Extensions. It may be situation 1.
![image](https://user-images.githubusercontent.com/87060980/155499812-ae2c3af4-6208-4dd0-8f50-e081457f7432.png)

**Comment by xiaoyuruan** [comment]
situation 2 is correct.
RFC5280 allows extensions defined outside of RFC5280.
refer to 4.2:
_Conforming CAs MAY support extensions that are not identified within this specification..._

**Comment by Wenxing-hou** [comment]
Thanks.  It is very helpful for me.  I will fix other issues with this guide.
