### ISSUE TITLE
How libspdm supports muti-endpoints connection

### ISSUE THREAD

**Issue by liyi77** [DMTF/libspdm#69]
Currently a spdm_context only have one connection info field,
It seems that another context is needed If want to connect with another Responder,
And this may cause the same session-ID to be assigned.
Or one connection will bind one transport layer channel?

**Comment by jyao1** [comment]
Yes, another context is needed if one endpoint need connect with another responder.

Both requester and responder will contribute half of Session-ID. One connection is between one pair of requester and responder.
