### ISSUE TITLE
test_spdm_responder_psk_exchange_rsp hang with the AFL generated specific mutation seed

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#698]
1. verify on https://github.com/DMTF/libspdm/commit/e1fd33f8ad01b9c56c8b188e3c3457e938d51f1e
Ubuntu 20.04.2 LTS
```
cd libspdm
mkdir build_fuzz_mbedtls_e1fd33f
cd build_fuzz_mbedtls_e1fd33f
export AFL_PATH=~/afl-2.52b/
export PATH=$PATH:$AFL_PATH
cmake -DARCH=x64 -DTOOLCHAIN=AFL -DTARGET=Release -DCRYPTO=mbedtls -DGCOV=ON ..
make copy_sample_key
make
cd bin
./test_spdm_responder_psk_exchange_rsp ./test_spdm_responder_psk_exchange_rsp_hang
LIBSPDM_ASSERT: /home/test/libspdm/os_stub/memlib/copy_mem.c(77): 0
^C
```
2. the AFL generated specific mutation seed file "**test_spdm_responder_psk_exchange_rsp_hang**":
[test_spdm_responder_psk_exchange_rsp_hang.zip](https://github.com/DMTF/libspdm/files/8184752/test_spdm_responder_psk_exchange_rsp_hang.zip)

**Comment by Xiaohanjlll** [comment]
I will check it.
