### ISSUE TITLE
Need handle the situation that the first cert in returned cert chain is NOT root cert

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#70]
Current spdm_verify_peer_cert_chain_buffer() assumes the first cert is root cert.

**Comment by steven-bellock** [comment]
Also the responder has the freedom to supply either the root certificate or a certificate signed by the root. The specification requires that the responder store the "complete certificate chain" and that includes the root certificate, so, barring performance reasons, there is no good reason for the responder to not supply the root certificate.

**Comment by steven-bellock** [comment]
See https://github.com/DMTF/Security-TF/issues/1432 for the corresponding issue on the SPDM whitepaper side.

**Comment by steven-bellock** [comment]
Approved.
