### ISSUE TITLE
Is it possible to make one .a library file for the entire libSPDM? 

### ISSUE THREAD

**Issue by yexiaoji001** [DMTF/libspdm#71]
It will be easier to integrate one .a file into another code base instead of integrating a list of .lib files:
![image](https://user-images.githubusercontent.com/35279695/128264460-9b9874ba-f081-4731-b5cb-dec90c2d4b7c.png)

**Comment by jyao1** [comment]
No, we cannot.
Different libraries are for different purposely.

**Comment by yexiaoji001** [comment]
Crypto libs are from third party. They may be harder to combine. But the way to break down libspdm into separate spdm_xxx_libs and other small libs like memlib, malloclib, etc is the architectural decision authors make. You can still organize code into separate folders, but reducing the number of libraries would make it easier for users to integrate libspdm.

**Comment by jyao1** [comment]
I think only spdm_common.lib is common one and required for all.

Other libs are optional, such as malloc lib, it is needed by crypto, but not needed by spmd_*lib.
Some of them are designed to be changed, such as transport_lib or crypto_lib, or spdm_device_lib.
Some of them are two different instance of same lib class, and used in different environment, such as debug_lib, debug_lib_null

We cannot put them together.

**Comment by jyao1** [comment]
a better way to feedback: 
1) We cannot bind *all* to one lib.
2) If you want to bind *some* to one lib, let's discuss case by case. Please describe your requirement as clear as possible.
