### ISSUE TITLE
Request for comments on Linux kernel SPDM implementation.

### ISSUE THREAD

**Issue by jic23** [DMTF/libspdm#73]
Very much early days given limited functionality etc, but any review of proposed kernel support would be appreciated.  Testing currently against QEMU device that chats to openSPDM (link in patch)

https://lore.kernel.org/linux-cxl/20210804161839.3492053-1-Jonathan.Cameron@huawei.com/T/#m9244d614ba06073be1ea1b056ae3b054a638ee0c

Thanks in advance!

**Comment by steven-bellock** [comment]
Hey that's pretty neat. We've been so focused on the lower layers of the stack that it's nice to see the view from above. @jic23 would you be willing to talk about this effort at the SPDM Code task force meeting?

**Comment by jic23** [comment]
@steven-bellock Sure. I'd be happy to talk about these.

**Comment by steven-bellock** [comment]
Thanks for presenting Jonathan!
