### ISSUE TITLE
Validating Responder's asymmetric algorithm

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#731]
Currently libspdm only validates the Responder's choice of asymmetric algorithm if `CHAL_CAP` is enabled: https://github.com/DMTF/libspdm/blob/c689b7b00e05bfc27b96972723837dfdb6b842e8/library/spdm_requester_lib/libspdm_req_negotiate_algorithms.c#L263-L275 However libspdm should be validating this field regardless of Requester / Responder capabilities. In particular
- If Requester / Responder don't support asymmetric algorithms then this should be `0`.
- Other capabilities may require asymmetric algorithms besides `CHAL_CAP`, like `MEAS_CAP`.

**Comment by jyao1** [comment]
agree

**Comment by steven-bellock** [comment]
This was fixed by #1220.
