### ISSUE TITLE
libspdm Context Parameter Consistency

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#748]
libspdm should be consistent with how spdm_context is used as a parameter, both it's name and it's type.

Name:
1. spdm_context OR
2. context

Type:
1. void
2. libspdm_context_t

**Comment by jyao1** [comment]
Existing Rule:
* The external API must use "void"

The rest is flexible:
* Internal API may use "void" or "libspdm_context_t"
* The name may be context or spdm_context.


Maybe we can define rule below:
* external API - "void *context".
* internal API - "libspdm_context_t *spdm_context"

**Comment by jyao1** [comment]
agree

**Comment by steven-bellock** [comment]
I'd reverse that.
* External - `void *spdm_context`
* Internal - `libspdm_context_t *context`
