### ISSUE TITLE
consider to add basic fuzzing function to CI.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#749]
Current problem is that CI does not include CI test running.
The code modification may cause fuzzing test fail.

**Comment by Zhiqiang520** [comment]
I will check it.

**Comment by steven-bellock** [comment]
GitHub Actions supports `cron` to do, for example, nightly builds and fuzz testing. According to https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration a job can run up to six hours. I don't think fuzzing should be run on pull requests unless it's very short, like five minutes or so.

**Comment by jyao1** [comment]
I fully agree that we should NOT run all fuzzing test, such as AFL or libfuzzer.

My thought is that: 
we should run one program one time, with a known good seed, to ensure it can pass the flow without any exception.

**Comment by jyao1** [comment]
https://github.com/DMTF/libspdm/blob/main/unit_test/fuzzing/run_initial_seed.sh need to be improved:

The fundamental problem is that it mixed "build" with "run".

The script will delete the build dir and rebuild everything.

The requirement is just "run".

**Comment by jyao1** [comment]
I feel we can 
1) add a new command "copy_seed" (similar to "copy_sample_key")

2) the test script just does:
```
for ((i=0;i<${#cmds[*]};i++))
do
    echo ++++++++++ ${cmds[$i]} starting ++++++++++
        echo ./${cmds[$i]} ./seeds/${cmds[$i]}/*.raw
        ./${cmds[$i]} ./seeds/${cmds[$i]}/*.raw
    echo ++++++++++ ${cmds[$i]} success ++++++++++
done
```
