### ISSUE TITLE
Many crypto (and crypto reliant) functions do not have their return values properly checked.

### ISSUE THREAD

**Issue by taprinz** [DMTF/libspdm#75]
Many crypto functions, or functions that rely on crypto, have their return values entirely ignored. Discovered this when playing around with GCC's __attribute__((warn_unused_result).

Especially as we leave the crypto & other implementation's up to the user to provide, we should be sure that we check the return values, as a user's error may be quietly ignored. 

Crypto functions:
- random_seed
- random_bytes
- spdm_hash_all
- spdm_hmac_all_with_response_finished_key
- spdm_hmac_all_with_request_finished_key

Crypto-reliant functions:
- spdm_generate_cert_chain_hash
- spdm_secured_message_dhe_generate_key
- spdm_create_update_session_data_key
- spdm_activate_update_session_data_key
- spdm_generate_finished_key
- spdm_generate_aead_key_and_iv

There are other functions that do not have their return values properly checked - I limited this issue to crypto functions in order to try and limit the scope. I may have missed others as well, as manually adding __attribute__((warn_unused_result)) isn't a perfect method.

**Comment by jyao1** [comment]
Agree.

**Comment by jyao1** [comment]
random function issue is also reported at https://github.com/DMTF/libspdm/issues/65

**Comment by taprinz** [comment]
I have started work on this again. My plan was to check every function with a return value to ensure it does not have any case where the return value isn't checked. Currently working via GCC's \_\_attribute\_\_((warn_unused_result)) - unfortunately, has to be done manually.

My thinking for doing so for all functions is as such: if a function is capable of failing, regardless of how unlikely it is, we NEED to be checking its return value. If we think checking the return of a given function is unnecessary, that function should return void and be incapable of failing by design.

**Comment by taprinz** [comment]
To follow up on the above, I can limit the scope to just crypto & adjacent functions. But I would really argue for the need to handle all return values.

**Comment by jyao1** [comment]
Agree - "if a function is capable of failing, regardless of how unlikely it is, we NEED to be checking its return value."

**Comment by taprinz** [comment]
I'm going by, header by header, adding the GCC attribute to all functions. Currently, only include/library/spdm_crypt_lib.h is remaining as last file to process.

Then, need to address:
- spdm_hmac_*with*_finished_key
- append_managed_buffer

The reason for the above three is that I need to be careful with the currently missing retvals, as they might need to handle structure deallocation (like spdm_hash_free) on failure. Want to make sure I don't miss anything.

However, I've also realized that there's some functions defined in files that might not be defined in header files. So I will do my best to check for these as well. But will prioritize the crypto and session functions first.

If we could find some way to check (library-wide) at compile time, it would be fantastic. Otherwise, going forward, we might just have to rely on static analysis and dilligence.

**Comment by jyao1** [comment]
> adding the GCC attribute to all functions

Please ensure the MSVC build can have similar check or at least pass build. Maybe use a MACRO.

**Comment by taprinz** [comment]
Oh - that was meant for how I was discovering instances. I didn't intend on doing this for check-in - just locally for the sake of resolving this item.

Might be worth discussing though, at least for critical functions.

**Comment by jyao1** [comment]
Ah, I see. If we want to do that, let's file a new issue. :)

**Comment by taprinz** [comment]
Yeah agreed.

**Comment by taprinz** [comment]
After https://github.com/DMTF/libspdm/pull/417 and https://github.com/DMTF/libspdm/pull/418/files, the only two remaining functions that need work are:
- libspdm_append_message_k
- libspdm_append_message_f

This is because these two functions perform a lot of operations on the message_k and message_f transcript buffers. If either fails midway through, we might end up putting the message buffer in an unrecoverable state.

I am not sure whether we want to file a separate issue for fixing those two, or whether one large PR to add return value checks and do some minor reorganizing would be good enough.

**Comment by jyao1** [comment]
@taprinz, agree.
We can address libspdm_append_message_k/libspdm_append_message_f later.

**Comment by steven-bellock** [comment]
Closing for 1.0 release. A new issue can be opened post 1.0.
