### ISSUE TITLE
All functions that access the cryptography module need to return libspdm_return_t

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#751]
The cryptography module may be an entirely distinct subsystem within the Requester / Responder. Its availability may not be guaranteed due to it being a shared resource, failure of a self-test, or system security lockdown. Currently most of the functions that access the cryptography module return `bool` instead of `libspdm_return_t`. For example https://github.com/DMTF/libspdm/blob/470105492df5b7392a76bba0b73993bb9ed22ec3/library/spdm_common_lib/libspdm_com_crypto_service.c#L806-L809 The caller does not whether the operation failed due to a mismatch in hashes or due to unavailability of the cryptography module.

**Comment by jyao1** [comment]
This seems incompatible change.  I think we can fix in this 2.0.0.
Do we have a list?

**Comment by steven-bellock** [comment]
I no longer care about this issue. Returning `bool` is fine.
