### ISSUE TITLE
Add return values to spdm_session_state_callback_func and spdm_connection_state_callback_func

### ISSUE THREAD

**Issue by taprinz** [DMTF/libspdm#76]
Currently, libspdm provides the ability for a user to add callback functions. However, these functions only return void, and the callback dispatcher does not return a value either. The utility of callbacks is limited if they cannot return error.

Perhaps this is by design, to intentionally limit callbacks to operations that will not fail, or to prevent the library from failing due to issue with a user callback. But it would allow for much greater utility if a user could implement more complicated callbacks.

**Comment by jyao1** [comment]
We can add error status. But I am not sure how the libspdm uses the error status.

Do you have any thought?

**Comment by taprinz** [comment]
I was thinking about having spdm_trigger_session_state_callback and spdm_trigger_connection_state_callback monitor for error responses from the callback functions.  Then the calling function could see failure.

However, I don't quite know how we want this to fit into the entire SPDM flow.  If these functions return failure, as it currently stands, it looks like it would be treated same as other errors in function handler - and we would return generic SPDM error via transport layer (rather than failing out of the library).

That doesn't seem like right response, since it's not the message that fails, its the callback.  And it wouldn't be clear to user that callback failed.

**Comment by jyao1** [comment]
OK. So you want to allow the callback to return error to terminate the connection or session? That works for me.

We need clearly document the impact of the error status code, to ensure the user makes right choice to return success or failure.

We shall also document if we want to call the next callback if the previous one returns error.

If we need stop, then the order matters. We also need document the callback order and register order.

The order brings more questions, what is some callback want to be register to be first or last? Or would like to know if it is first or last? Do we want to support that use case?

**Comment by taprinz** [comment]
Yeah - after looking back at this, I feel like this is too complex and don't see a clear benefit to implementing.

For example - as you said, it is hard to really tell what the expected behavior should be - since callbacks can be very vague, it would get quite confusing to determine whether we should return error, continue processing, etc. We can enforce a specific pattern - such as "always execute all" or "stop executing after failure", and leave it up to implementer to write functions that abide by this, but it would require us to document quite a bit of information, and take an arbitrary stance on what is preferred.

We can just keep status quo which requires that an implementer must only write callbacks that cannot fail. Or require that they devise their own error detection mechanism, outside of the libspdm failures. If the user wants a more complicated action, they should consider application messages or VENDOR_DEFINED_MESSAGEs to do achieve them.

I am fine to close this issue, unless anyone else has any ideas here.
