### ISSUE TITLE
Redundant libspdm_x509_get_cert_from_cert_chain() in libspdm_read_responder_public_certificate_chain()

### ISSUE THREAD

**Issue by manishc88** [DMTF/libspdm#767]
In function libspdm_read_responder_public_certificate_chain(), libspdm_x509_get_cert_from_cert_chain() is called in libspdm_verify_cert_chain_data() already, so follow up call seems redundant.  

[diff.txt](https://github.com/DMTF/libspdm/files/8345934/diff.txt)

**Comment by jyao1** [comment]
Could you please submit PR directly ?

**Comment by manishc88** [comment]
I will close this issue out as it seems it is not really redundant call, after removing this call I saw some errors on requester side when running spdm-emu-responder and spdm-emu-requester. 

0200: ab f8 3b 07 8b e0 ce 26 6f
**!!! VerifyCertificateChainBuffer - FAIL (cert root hash mismatch) !!!**
do_authentication_via_spdm - 1a
Platform port Transmit command: 00 00 ff fe
Platform port Transmit transport_type: 00 00 00 01
Platform port Transmit size: 00 00 00 00
Platform port Transmit buffer:

Platform port Receive command: 00 00 ff fe
Platform port Receive transport_type: 00 00 00 01
Platform port Receive size: 00 00 00 00
Client stopped
