### ISSUE TITLE
Ensure that hashes / signatures over transcripts are consistent

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#774]
`LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT` is a compile-time configuration setting that, when enabled, stores the entire transcript in memory before it is hashed / signed. To reduce memory requirements `LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT` can be disabled, in which case a running calculation is made over the transcript. We need to ensure that the two methods produce the same results.

**Comment by jyao1** [comment]
agree. I think we can enable CI to test:
1) requester (DATA_SUPPORT = 0) <=> responder (DATA_SUPPORT = 1)
2) requester (DATA_SUPPORT = 1) <=> responder (DATA_SUPPORT = 2)

**Comment by Wenxing-hou** [comment]
The spdm-emu patch [Add CI check for enable LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT](https://github.com/DMTF/spdm-emu/pull/117) has been merged and checked the consistent successfully.

I think this issue can be closed.
