### ISSUE TITLE
Need update export master secrete during key update.

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#809]
Current code does not change export master secrete when key update.

**Comment by steven-bellock** [comment]
[We talked about this at the VF2F ](https://github.com/DMTF/Security-TF/issues/1900) and it is considered implementation-defined behavior.

**Comment by steven-bellock** [comment]
Will probably need a VDM to accomplish this since the specification will (soon) explicitly state that update and use of the Export Master Secret is implementation-defined. libspdm should be able to handle this flow.

**Comment by jyao1** [comment]
@steven-bellock Can we close this one after https://github.com/DMTF/libspdm/pull/1274 ?

**Comment by steven-bellock** [comment]
This is still to-be-decided. Our options are
1. Do nothing.
2. Create a vendor-defined message that updates the export master secret.
3. Provide an option to update the export master secret through `KEY_UPDATE` and the `UpdateAllKeys`.

Ultimately I think we'll go with 1, but we can discuss it at the next meeting.
