### ISSUE TITLE
libspdm crashing 

### ISSUE THREAD

**Issue by PoojaGaur1708** [DMTF/libspdm#819]
Hello , i am using libspdm package to send spdm packet .

I follow spdm_client_init function in a application (following Doc README as well)
But when it calls , my code crash i, i checked internall it crash in libspdm_acquire_sender_buffer function.
As debug , value in this field of structure which is function pointer , having value 0x0. So pls help me urgently / suggest me where and how to fill the value in this function pointer.

libspdm_return_t libspdm_acquire_sender_buffer (
libspdm_context_t *spdm_context, size_t *max_msg_size, void **msg_buf_ptr)
{
libspdm_return_t status;

LIBSPDM_ASSERT (spdm_context->sender_buffer == NULL);
LIBSPDM_ASSERT (spdm_context->sender_buffer_size == 0);
 status = spdm_context->acquire_sender_buffer (spdm_context, max_msg_size, msg_buf_ptr);  /**### /CRASH AT THIS POINT**
if (status != LIBSPDM_STATUS_SUCCESS) {
    return status;
}
spdm_context->sender_buffer = *msg_buf_ptr;
spdm_context->sender_buffer_size = *max_msg_size;
return LIBSPDM_STATUS_SUCCESS;

**Comment by steven-bellock** [comment]
There's a few issues here:
1. The user guide doc has a bad link for `spdm_client_init` in spdm-emu.
2. libspdm also has its own `spdm_client_init` that needs to be updated.

@PoojaGaur1708 Check out https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_requester_emu/spdm_requester_spdm.c for spdm_client_init and https://github.com/DMTF/libspdm/blob/main/unit_test/spdm_unit_test_common/common.c on some reference implementations of the acquire and release functions. The reference implementations could probably go into `libspdm/os_stub`.

**Comment by jyao1** [comment]
> 1. The user guide doc has a bad link for spdm_client_init in spdm-emu.
What is bad link? I can access it without problem.

> 2. libspdm also has its own spdm_client_init that needs to be updated.
Agree. We need update it.

@PoojaGaur1708, besides https://github.com/DMTF/libspdm/blob/main/doc/user_guide.md, I also added more description at https://github.com/DMTF/libspdm/blob/main/doc/design.md on the internal design. See "device IO" section.

The sample spdm_device_acquire_sender_buffer() is at https://github.com/DMTF/spdm-emu/blob/main/spdm_emu/spdm_emu_common/command.c#L312

It is hard for me to know what is the problem, unless you post your code.

**Comment by steven-bellock** [comment]
I already updated the links in https://github.com/DMTF/libspdm/commit/648023b5d6957d76df54c4291d5b4b1739df5c01 and https://github.com/DMTF/libspdm/commit/33244eedc39f8a2c434525db0d6e0b51b3e45b42

**Comment by jyao1** [comment]
> I already updated the links in [648023b](https://github.com/DMTF/libspdm/commit/648023b5d6957d76df54c4291d5b4b1739df5c01) and [33244ee](https://github.com/DMTF/libspdm/commit/33244eedc39f8a2c434525db0d6e0b51b3e45b42)

Ah. Good to know you fixed it.

**Comment by PoojaGaur1708** [comment]
Hello i am getting below error could you pls help me out.

Spdm response is received for get version , but getting below error: 

libspdm_receive_spdm_response[0] (0x1240): 
libspdm_receive_spdm_response[0] status - 0xffffffff80010002
libspdm_init_connection - 0x80010002

**Comment by PoojaGaur1708** [comment]
Hello, can you pls help , 

In libspdm_receive_response function, check session id and message session ID is coming null. 

Can you pls tell , when the value to this pointer is assigned and how. At which function?

**Comment by jyao1** [comment]
See https://github.com/DMTF/libspdm/discussions/837.
