### ISSUE TITLE
libspdm_ prefix still needed

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#823]
The symbols in `base.h` and `processor_bind.h`  need to be
- deleted if they are not being used OR
- renamed with the libspdm_ prefix

**Comment by steven-bellock** [comment]
`MAX_BIT` is used only once in https://github.com/DMTF/libspdm/blob/5ae2c537c10fc0d092ffb432fd9abc0a817d7cfd/os_stub/openssllib/include/openssl/opensslconf.h#L30-L34 Isn't there a better way for OpenSSL to get this information?

**Comment by steven-bellock** [comment]
Similarly `MAX_INTN` is only used in OpenSSL to define `OSSL_SSIZE_MAX`.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/5ae2c537c10fc0d092ffb432fd9abc0a817d7cfd/include/hal/base.h#L210-L225 should be deleted and we can use the standard `UINTN_MAX` / `INTN_MAX` macros from `stdint.h`.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/5ae2c537c10fc0d092ffb432fd9abc0a817d7cfd/include/hal/base.h#L203-L205 should come from `stddef.h`.

**Comment by steven-bellock** [comment]
https://github.com/DMTF/libspdm/blob/5ae2c537c10fc0d092ffb432fd9abc0a817d7cfd/include/hal/base.h#L292-L400 can be deleted if we're not using any of it.

**Comment by jyao1** [comment]
NULL definition is removed. It is already there.

**Comment by jyao1** [comment]
MAX_BIT and MAX_ADDRESS are removed.
MAX_INTN is moved to openssl internal.
