### ISSUE TITLE
peer_used_cert_chain_buffer is not implemented correctly

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#836]
Currently, peer_used_cert_chain_buffer is updated in libspdm_try_get_certificate(). It cached the *latest* cert request.

However, it is not right way, because in challenge/get_measurement/key_exchange, the requester indicates the slot number. The slot_id might not be the latest one.

I believe we need
1) cache all certificate from the libspdm_try_get_certificate() to a new field. It need to be an array.
2) change peer_used_cert_chain_buffer to a pointer, to point to the slot_id indicated by challenge/get_measurement/key_exchange.

NOTE:
Same thing for peer_used_cert_chain_buffer_hash.
Same thing for encapsulated get_certificate.

**Comment by steven-bellock** [comment]
The Requester just needs one certificate chain that works and the corresponding slot ID, so I'm not sure if the context needs to store multiple certificate chains.

**Comment by jyao1** [comment]
The problem is that, you don't know which "corresponding slot ID" is, in the GET_CERTIFICATE. The "corresponding slot ID" is sent in CHALLENGE, GET_MEASUREMENT, and KEY_EXCHANGE, after GET_CERTIFICATE.

If LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT==1, the whole 8 cert chains are required.
If LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT==0, we just need store the HASH of 8 cert chains.
