### ISSUE TITLE
A, B and C while defining transcript message M1 - need clarity on concatenation and signature

### ISSUE THREAD

**Issue by lr-mrvl** [DMTF/libspdm#838]
Need for concatenation while defining terms A, B and C is not consistent in Table 38

A1 = VCA
A2 = VCA
B1=Concatenate(GET_DIGESTS, DIGESTS, GET_CERTFICATE, CERTIFICATE)
B3=(GET DIGESTS, DIGESTS)
B4=(GET CERTIFICATE, CERTIFICATE)
C1=(CHALLENGE, CHALLENGE_AUTH\Signature)

Also do we need \Signature in C1, considering, description reads -  "The Signature bytes of CHALLENGE_AUTH **shall not** be included in C" ? please kindly clarify

**Comment by steven-bellock** [comment]
You can file issues against the SPDM specification [here]( https://github.com/DMTF/Security-TF/issues).

**Comment by lr-mrvl** [comment]
Thanks Steven - that was intention. Got the repo mixed up - Apologize
