### ISSUE TITLE
libspdm_random_bytes() copies of 64-bits or greater incorrectly assumes CPU support for non-64-bit alignment copy

### ISSUE THREAD

**Issue by jcahill0** [DMTF/libspdm#849]
The function libspdm_random_bytes() has a copy path that performs a 64-bit copy if the buffer passed in has greater than or equal to 64-bits of space.  This assumes the CPU libspdm is running on supports non-64-bit alignment 64-bit copies.  While many CPU architectures allow this, they take a performance hit; at least the hit is small here for each message.  Some require or can add strict alignment checking, and many ARM chipsets are configurable.  In my case, it was hit on an ARM.

Example usage that does not guarantee the alignment is below, where `app_message_size` can be nearly any value > 1.  This allows for all sorts of possible alignments for the location to store the random number.  And `rand_count` may be <4 bytes or >= 4 bytes.
~~~
libspdm_return_t libspdm_encode_secured_message(
…
        enc_msg_header =
            (void *)((uint8_t *)app_message - sizeof(spdm_secured_message_cipher_header_t));
        enc_msg_header->application_data_length =
            (uint16_t)app_message_size;
        result = libspdm_get_random_number(rand_count,
                                           (uint8_t *)enc_msg_header +
                                           sizeof(spdm_secured_message_cipher_header_t) +
                                           app_message_size);
        if (!result) {
            return LIBSPDM_STATUS_LOW_ENTROPY;
        }
~~~

Code path in libspdm_random_bytes() causing the problem is below.  One solution is to check `output` against an ANDing of 0x3, and if it is non-zero, then drop to the else statement with libspdm_copy_mem().
~~~
bool libspdm_random_bytes(uint8_t *output, size_t size)
{
    bool ret;
    uint64_t temp_rand;
 
    ret = false;
 
    while (size > 0) {
        /* Use rnglib to get random number*/
        ret = libspdm_get_random_number_64(&temp_rand);
 
        if (!ret) {
            return ret;
        }
        if (size >= sizeof(temp_rand)) {
            *((uint64_t *)output) = temp_rand;
            output += sizeof(uint64_t);
            size -= sizeof(temp_rand);
        } else {
            libspdm_copy_mem(output, size, &temp_rand, size);
            size = 0;
        }
    }
~~~

**Comment by jcahill0** [comment]
@bhenning10

**Comment by steven-bellock** [comment]
We can use `libspdm_copy_mem` for everything. No need for the `if-else`.

**Comment by jcahill0** [comment]
> We can use `libspdm_copy_mem` for everything. No need for the `if-else`.

Works for me.  I assumed there was some specific reason it was still there.  Probably just older code.
