### ISSUE TITLE
Report error when Windows Build with -DTARGET=Release -DCRYPTO=mbedtls

### ISSUE THREAD

**Issue by yzhu52** [DMTF/libspdm#86]
cmake -G"NMake Makefiles" -DARCH=x64 -DTOOLCHAIN=VS2019 -DTARGET=Release -DCRYPTO=mbedtls .. 
nmake copy_sample_key
nmake

Error:
[ 99%] Linking C executable ..\..\..\bin\test_size_of_spdm_requester.exe
LINK: command "C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1428~1.29~\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\test_size_of_spdm_requester.dir\objects1.rsp /out:..\..\..\bin\test_size_of_spdm_requester.exe /implib:..\..\..\bin\test_size_of_spdm_requester.lib /pdb:D:\SPDM\0816\libspdm\build\bin\test_size_of_spdm_requester.pdb /version:0.0 /DLL /ENTRY:ModuleEntryPoint /NOLOGO /SUBSYSTEM:EFI_BOOT_SERVICE_DRIVER /NODEFAULTLIB /IGNORE:4086 /OPT:REF /LTCG /subsystem:console ..\..\..\lib\memlib.lib ..\..\..\lib\debuglib.lib ..\..\..\lib\spdm_requester_lib.lib ..\..\..\lib\spdm_common_lib.lib ..\..\..\lib\cryptstublib_dummy.lib ..\..\..\lib\mbedtlslib.lib ..\..\..\lib\rnglib.lib ..\..\..\lib\cryptlib_mbedtls.lib ..\..\..\lib\malloclib_null.lib ..\..\..\lib\spdm_crypt_lib.lib ..\..\..\lib\spdm_secured_message_lib.lib ..\..\..\lib\spdm_transport_mctp_lib.lib ..\..\..\lib\spdm_device_secret_lib_null.lib ..\..\..\lib\intrinsiclib.lib Kernel32.lib MSVCRTD.lib vcruntimed.lib ucrtd.lib Gdi32.lib User32.lib Winmm.lib Advapi32.lib ws2_32.lib /MANIFEST /MANIFESTFILE:..\..\..\bin\test_size_of_spdm_requester.exe.manifest" failed (exit code 1257) with the following output:
Generating code
D:\SPDM\0816\libspdm\os_stub\mbedtlslib\mbedtls\library\cipher.c(713) : error C2268: 'memset' is a compiler predefined library helper. Library helpers are not supported with /GL; compile object file 'd:\spdm\0816\libspdm\build\unit_test\test_size\intrinsiclib\cmakefiles\intrinsiclib.dir\memory_intrinsics.c.obj' without /GL.
D:\SPDM\0816\libspdm\os_stub\mbedtlslib\mbedtls\library\camellia.c(373) : error C2268: 'memcpy' is a compiler predefined library helper. Library helpers are not supported with /GL; compile object file 'd:\spdm\0816\libspdm\build\unit_test\test_size\intrinsiclib\cmakefiles\intrinsiclib.dir\copy_mem.c.obj' without /GL.
LINK : fatal error LNK1257: code generation failed
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by yzhu52** [comment]
Also tried other two config:
-DTARGET=Debug -DCRYPTO=mbedtls,  it is build success.
-DTARGET=Release -DCRYPTO=openssl,  it is build success.

**Comment by steven-bellock** [comment]
@steven-bellock to add Windows build to CI.

**Comment by liyi77** [comment]
seems that we should disable GL at CMAKE_C_FLAGS_RELEASE instead of CMAKE_C_FLAGS
