### ISSUE TITLE
Inconsistency of message_k and temp_message_k buffer size

### ISSUE THREAD

**Issue by LeeTroy** [DMTF/libspdm#861]
Per discussion in #858 , the message_k reserves with large buffer where temp_message_k is medium, and this result in runtime error. Changing the temp_message_k to large will resolve this issue.
```libspdm_append_managed_buffer 0x1e6 fail, rest 0x7a only```

Reference:
https://github.com/DMTF/libspdm/blob/d9a07ede65a818236411abfe5d580e9e49024f4e/include/internal/libspdm_common_lib.h#L236-L242

**Comment by steven-bellock** [comment]
Issue was fixed by https://github.com/DMTF/libspdm/pull/862
