### ISSUE TITLE
Comparison string typo on 'Openssl' vs 'openssl'

### ISSUE THREAD

**Issue by LeeTroy** [DMTF/libspdm#864]
The CRYPTO value should be `openssl`, however the comparison below checks with `Openssl`:
https://github.com/DMTF/libspdm/blob/79c187688a6e857a5e9589ea315442ec4011e7bb/CMakeLists.txt#L128

https://github.com/DMTF/libspdm/blob/79c187688a6e857a5e9589ea315442ec4011e7bb/CMakeLists.txt#L121

**Comment by steven-bellock** [comment]
Can probably enable that option in CI. I assume Github's Ubuntu VM comes with OpenSSL.
