### ISSUE TITLE
(Potentially) remove processer_bind.h

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#867]
Most of the `processor_bind.h` files are in a state where they can be removed, leaving only `base.h`. The question is whether we would have a need, in the future, for processor-specific files. `libspdm/library/` and its headers are processor agnostic, as is most of `libspdm/os_stub/`. Hopefully we'll never write any assembly language, although if we did it would probably go under `libspdm/os_stub/` or a new `libspdm/arch/` directory. Additionally processor-specific `#define`s can be defined via the makefiles / compiler.

We do have the "OpenSSL on Windows" issue in `ia32` and `x64` that would need to be resolved: https://github.com/DMTF/libspdm/blob/acf5e97f41279fdeaaf25f61c7bfc68dd8bfef46/include/hal/x64/processor_bind.h#L101-L124

**Comment by jyao1** [comment]
@steven-bellock will make a proposal.

**Comment by jyao1** [comment]
@steven-bellock , may I know if you have plan to implement this?

We are going to add new arch, if there is no plan to remove arch dir.
