### ISSUE TITLE
test_spdm_encode_secured_message hang with the AFL generated specific mutation seed 

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/libspdm#870]
1. Verified on https://github.com/DMTF/libspdm/commit/acf5e97f41279fdeaaf25f61c7bfc68dd8bfef46
Ubuntu 20.04.4 LTS

cd libspdm
mkdir build_afl
cd build_afl
export AFL_PATH=~/afl-2.52b/
export PATH=$PATH:$AFL_PATH
cmake -DARCH=x64 -DTOOLCHAIN=AFL -DTARGET=Release -DCRYPTO=mbedtls ..
make copy_sample_key
make
cd bin
./test_spdm_encode_secured_message ./test_spdm_encode_secured_message_hang1
LIBSPDM_ASSERT: /home/gyh/libspdm/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c(255): *secured_message_size >= total_secured_message_size
^C

./test_spdm_encode_secured_message ./test_spdm_encode_secured_message_hang2
LIBSPDM_ASSERT: /home/gyh/libspdm/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c(255): *secured_message_size >= total_secured_message_size
^C

./test_spdm_encode_secured_message ./test_spdm_encode_secured_message_hang3
LIBSPDM_ASSERT: /home/gyh/libspdm/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c(255): *secured_message_size >= total_secured_message_size
^C

./test_spdm_encode_secured_message ./test_spdm_encode_secured_message_hang4
LIBSPDM_ASSERT: /home/gyh/libspdm/library/spdm_secured_message_lib/libspdm_secmes_encode_decode.c(255): *secured_message_size >= total_secured_message_size
^C

2. the AFL generated specific mutation seed files:
[test_spdm_encode_secured_message_hang1~4.zip](https://github.com/DMTF/libspdm/files/8588825/test_spdm_encode_secured_message_hang1.4.zip)

**Comment by yaohuixguo** [comment]
I will check it.

**Comment by Xiaohanjlll** [comment]
I will check it.
