### ISSUE TITLE
test_spdm_transport_pci_doe_encode_message hang with the AFL generated specific mutation seed 

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/libspdm#872]
1. Verified on https://github.com/DMTF/libspdm/commit/acf5e97f41279fdeaaf25f61c7bfc68dd8bfef46
Ubuntu 20.04.4 LTS

cd libspdm
mkdir build_afl
cd build_afl
export AFL_PATH=~/afl-2.52b/
export PATH=$PATH:$AFL_PATH
cmake -DARCH=x64 -DTOOLCHAIN=AFL -DTARGET=Release -DCRYPTO=mbedtls ..
make copy_sample_key
make
cd bin
./test_spdm_transport_pci_doe_encode_message ./test_spdm_transport_pci_doe_encode_message_hang1
LIBSPDM_ASSERT: /home/gyh/libspdm/library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c(75): *transport_message_size >= aligned_message_size + sizeof(pci_doe_data_object_header_t)
^C

./test_spdm_transport_pci_doe_encode_message ./test_spdm_transport_pci_doe_encode_message_hang2
LIBSPDM_ASSERT: /home/gyh/libspdm/library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c(75): *transport_message_size >= aligned_message_size + sizeof(pci_doe_data_object_header_t)
^C

./test_spdm_transport_pci_doe_encode_message ./test_spdm_transport_pci_doe_encode_message_hang3
LIBSPDM_ASSERT: /home/gyh/libspdm/library/spdm_transport_pcidoe_lib/libspdm_doe_pcidoe.c(75): *transport_message_size >= aligned_message_size + sizeof(pci_doe_data_object_header_t)
^C

2. the AFL generated specific mutation seed files:
[test_spdm_transport_pci_doe_encode_message_hang1~3.zip](https://github.com/DMTF/libspdm/files/8589325/test_spdm_transport_pci_doe_encode_message_hang1.3.zip)

**Comment by Xiaohanjlll** [comment]
I will check it.
