### ISSUE TITLE
How to run the unit tests ? - do not see any help option

### ISSUE THREAD

**Issue by manishc88** [DMTF/libspdm#890]
Hello,

I was trying to run some unit tests built default with libspdm compilation but I am not sure how to run them exactly ? I don't see any help option as well on how to run these tests, specifically looking for details what types of arguments needs to be supplied, if it's a file then what should be the contents of those files which will be provided as arguments to some of these test binaries. Is there any document with details on this ?

For example - there are quite of responder related tests,  please see below a test was run but it's asking about some file args.
So unsure what contents should be put in file and what it represent to the test.

root@dpdk-1:~/manish/libspdm/build/bin# ls test_spdm_responder*
test_spdm_responder                 test_spdm_responder_encap_challenge        test_spdm_responder_finish_rsp     test_spdm_responder_psk_exchange_rsp
test_spdm_responder_algorithms      test_spdm_responder_encap_get_certificate  test_spdm_responder_heartbeat_ack  test_spdm_responder_psk_finish_rsp
test_spdm_responder_capabilities    test_spdm_responder_encap_get_digests      test_spdm_responder_if_ready       test_spdm_responder_version
test_spdm_responder_certificate     test_spdm_responder_encap_key_update       test_spdm_responder_key_exchange
test_spdm_responder_challenge_auth  test_spdm_responder_encap_response         test_spdm_responder_key_update
test_spdm_responder_digests         test_spdm_responder_end_session            test_spdm_responder_measurements

**/root/libspdm/build/bin# ./test_spdm_responder_version
error - missing input file**

/root/libspdm/build/bin# ./test_spdm_responder_version --help
file error

/root/libspdm/build/bin# ./test_spdm_responder_version -h
file error

Thanks,
Manish

**Comment by jyao1** [comment]
The unit test is [test_spdm_requester](https://github.com/DMTF/libspdm/tree/main/unit_test/test_spdm_requester) and [test_spdm_responder](https://github.com/DMTF/libspdm/tree/main/unit_test/test_spdm_responder)

The [test_spdm_requester_get_version](https://github.com/DMTF/libspdm/tree/main/unit_test/fuzzing/test_requester/test_spdm_requester_get_version) is for fuzzing, and it expects a seed.

**Comment by jyao1** [comment]
For unit test, please refer to https://github.com/DMTF/libspdm#run-unit_test

For test related topic in libspdm, please refer to https://github.com/DMTF/libspdm/blob/main/doc/test.md

You may also refer to spdm_emu, please refer to https://github.com/DMTF/libspdm#run-spdm_emu
