### ISSUE TITLE
Combined send/receive buffer in unit_test?

### ISSUE THREAD

**Issue by richkong88** [DMTF/libspdm#896]
It looks like the unit test code is using a combined send/receive buffer. Based on the separate sender/receiver aquire/release interfaces, I thought these were supposed to be different buffers and not one shared one? My understanding is we should be able to hold separate send and receive buffers concurrently.  Is my understanding correct and the unit test is wrong for merging these two buffers?

This may not have been caught because of the standard way libspdm uses the buffers. I have a different usage model in the chunking code, which revealed this issue.

```
bool m_send_receive_buffer_acquired = false;
uint8_t m_send_receive_buffer[LIBSPDM_MAX_MESSAGE_BUFFER_SIZE];
size_t m_send_receive_buffer_size;

libspdm_return_t spdm_device_acquire_sender_buffer (
    void *context, size_t *max_msg_size, void **msg_buf_ptr)
{
    LIBSPDM_ASSERT (!m_send_receive_buffer_acquired);
    *max_msg_size = sizeof(m_send_receive_buffer);
    *msg_buf_ptr = m_send_receive_buffer;
    libspdm_zero_mem (m_send_receive_buffer, sizeof(m_send_receive_buffer));
    m_send_receive_buffer_acquired = true;
    return LIBSPDM_STATUS_SUCCESS;
}

void spdm_device_release_sender_buffer (
    void *context, const void *msg_buf_ptr)
{
    LIBSPDM_ASSERT (m_send_receive_buffer_acquired);
    LIBSPDM_ASSERT (msg_buf_ptr == m_send_receive_buffer);
    m_send_receive_buffer_acquired = false;
    return;
}

libspdm_return_t spdm_device_acquire_receiver_buffer (
    void *context, size_t *max_msg_size, void **msg_buf_ptr)
{
    LIBSPDM_ASSERT (!m_send_receive_buffer_acquired);
    *max_msg_size = sizeof(m_send_receive_buffer);
    *msg_buf_ptr = m_send_receive_buffer;
    libspdm_zero_mem (m_send_receive_buffer, sizeof(m_send_receive_buffer));
    m_send_receive_buffer_acquired = true;
    return LIBSPDM_STATUS_SUCCESS;
}

void spdm_device_release_receiver_buffer (
    void *context, const void *msg_buf_ptr)
{
    LIBSPDM_ASSERT (m_send_receive_buffer_acquired);
    LIBSPDM_ASSERT (msg_buf_ptr == m_send_receive_buffer);
    m_send_receive_buffer_acquired = false;
    return;
}
```

**Comment by jyao1** [comment]
I think current design supports single buffer for send/receive, it also supports different buffers.
There is no restriction.

**Comment by richkong88** [comment]
Right, but the unit test implementation is not allowing me to allocate and hold both simultaneously. I'm holding both simultaneously in the chunk get code.  Is it ok to change this code to be two separate buffers?

**Comment by jyao1** [comment]
Do you mean you want to include a design that *requires* two separate buffer?
If that is the case, we need clearly document it and we also need update spdm_emu.

**Comment by steven-bellock** [comment]
Having the send and receive buffers share the same space in memory is "worst case" and can expose memory corruption issues during testing that wouldn't be exposed if they were separate. Why does chunking need them to be separate?

**Comment by jyao1** [comment]
after merge chunking PR, we can close this one.
