### ISSUE TITLE
Minor bug in get_certificate test?

### ISSUE THREAD

**Issue by richkong88** [DMTF/libspdm#904]
I think there's a bug in the get_certificate tests, where it calculates the minimum number of sub blocks needed. Should the +1 be -1?

count = (m_libspdm_local_certificate_chain_size +
                 LIBSPDM_MAX_CERT_CHAIN_BLOCK_LEN + 1) /
                LIBSPDM_MAX_CERT_CHAIN_BLOCK_LEN;

**Comment by jyao1** [comment]
yes. it seems a bug.
