### ISSUE TITLE
[Support GET_DIGEST/GET_CERTIFICATE after CHALLENGE] follow-up

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#916]
@jyao1 @qizhangz @steven-bellock 

Hi All,

I was checking the new commit #902 and it seems to have some issues.
Would you help clarify my questions?

Thanks!

1) Receiving GET_DIGESTS/GET_CERTIFICATE in Authenticated state will change the state to not Authenticated.
Not sure if it's valid from spec perspective?

2) GET_DIGESTS -> GET_CERTIFICATE -> GET_DIGESTS sequence is now allowed.
The second GET_DIGESTS won't reset message_b and that will cause an invalid message sequence in message_b.

**Comment by jyao1** [comment]
Thank you @rw8896 .

For 1), Agree it is a bug.
Since recently we allowed GET_DIGEST/GET_CERTIFICATE at any time. The state is not useful. We have to way to fix it. 
A) We deprecate those state, do not assign those two states any more.
B) We still assign the state, with check:
```
if (connection_state < LIBSPDM_CONNECTION_STATE_AFTER_DIGESTS) {
    connection_state < LIBSPDM_CONNECTION_STATE_AFTER_DIGESTS;
}
```
```
if (connection_state < LIBSPDM_CONNECTION_STATE_AFTER_CERTIFICATE) {
    connection_state < LIBSPDM_CONNECTION_STATE_AFTER_CERTIFICATE;
}
```
What do you think?

2. I think we need enhance the unit test to cover.

**Comment by qizhangz** [comment]
@rw8896 second GET_DIGESTS reset message_b via libspdm_reset_message_buffer_via_request_code().

void libspdm_reset_message_buffer_via_request_code(void *context, void *session_info,
                                                   uint8_t request_code)
{
...
    case SPDM_GET_DIGESTS:
    case SPDM_GET_CERTIFICATE:
        if (spdm_context->connection_info.connection_state ==
            LIBSPDM_CONNECTION_STATE_AUTHENTICATED) {
            libspdm_reset_message_b(spdm_context);
        }
        break;
    default:
        break;

**Comment by jyao1** [comment]
@qizhangz , this check does not work, because it requires connection_state  to be AUTHENTICATED.

If the sequence is GET_DIGEST, GET_CERTIFICATE, GET_DIGEST, the connection_status is AFTER_CERTIFIACET.
Why this can reset message_b?

Do you have test to trigger such flow?

**Comment by rw8896** [comment]
@jyao1 Not sure if this could cover all the scenarios. Please help review this idea.

1) Don't change state when receiving GET_DIGESTS and GET_CERTIFICATE under Authenticated state
2) GET_DIGESTS could be accepted if state is Negotiated or Authenticated. 
3) GET_CERTIFICATE could be accepted if state > Negotiated.
4) Every time when receiving GET_DIGESTS, reset message_b. 
5) GET_CERTIFICATE doesn't reset message_b

So
1) GET_DIGESTS/GET_CERTIFICATE won't make device not Authenticated
2) GET_DIGESTS is only accepted when (after NEGOTIATE_ALGORITHMS
request completion, or after a completed CHALLENGE_AUTH
response), i.e. before Authenticated, GET_DIGESTS -> GET_CERTIFICATE -> GET_DIGESTS is not allowed.
3) + 4) + 5) is to make sure message_b is correct.

Thanks!

**Comment by jyao1** [comment]
Your idea is 1.B.
Agree.

**Comment by jyao1** [comment]
> * before Authenticated, GET_DIGESTS -> GET_CERTIFICATE -> GET_DIGESTS is not allowed.

I disagree.
Before Authenticated, GET_DIGESTS -> GET_CERTIFICATE -> GET_DIGESTS should be allowed, and message_b should be reset.
