### ISSUE TITLE
certificate chain in transcript hash should include the CERT_CHAIN header returned in GET_CERTIFICATE

### ISSUE THREAD

**Issue by jyao1** [DMTF/libspdm#92]
Current implement only includes from root to leaf certificate. Instead, spdm_generate_cert_chain_hash() should be used.

**Comment by steven-bellock** [comment]
Issue on the specification side: https://github.com/DMTF/Security-TF/issues/1443

**Comment by liyi77** [comment]
> Current implement only includes from root to leaf certificate. Instead, spdm_generate_cert_chain_hash() should be used.

When it is time to calculate the transcript, it is difficult to get the slot_id in current code, so it is inconvenient to use spdm_generate_cert_chain_hash() .
I recommend that use spdm_get_local_cert_chain_buffer() instead of spdm_get_local_cert_chain_data() to fix this issue.

**Comment by jyao1** [comment]
Currently, hash in GET_DIGEST == hash of cert chai in GET_CERTIFICATE == hash in CHALLENGE_AUTH.
For remote, we can cache the hash of cert chain from peer directly, instead of recalculate.
For local, yes, or you can cache the local hash of cert chain too.

**Comment by jyao1** [comment]
> > Current implement only includes from root to leaf certificate. Instead, spdm_generate_cert_chain_hash() should be used.
> 
> When it is time to calculate the transcript, it is difficult to get the slot_id in current code, so it is inconvenient to use spdm_generate_cert_chain_hash() .
> I recommend that use spdm_get_local_cert_chain_buffer() instead of spdm_get_local_cert_chain_data() to fix this issue.

Yes, you are right. I will use spdm_get_local_cert_chain_buffer()
