### ISSUE TITLE
Out of bounds array access in many requester_encap tests.

### ISSUE THREAD

**Issue by richkong88** [DMTF/libspdm#940]
It looks like many of the encap_request tests incorrectly access a "temp_buf" stack based array.  The array is MAX_MESSAGE_BUFFER_SIZE (0x1200). The start of this array is passed into libspdm_transport_test_encode_message as the "message" parameter. This "message" parameter is then passed to libspdm_test_encode_message where it subtracts the libspdm_test_message_header_t for transport header from the "message" pointer.

    *transport_message = (uint8_t *)message - sizeof(libspdm_test_message_header_t);

However, no room was initially left in "temp_buf" for the transport test header. Therefore the access is invalid. 

I caught this running the unit tests in compiled within a VC++ workspace. VC++ complained of stack corruption. Not sure why this isn't caught by our default VC++ command line builds.

**Comment by jyao1** [comment]
Would you please be specific, where is the code? link?

**Comment by steven-bellock** [comment]
Should also check if this can be enabled in CI to cause a test failure.

**Comment by richkong88** [comment]
The function error starts here in [libspdm_requester_encap_request_test_receive_message](https://github.com/DMTF/libspdm/blob/main/unit_test/test_spdm_requester/encap_request.c#L45):

The function test cases declare a temp_buf variable:
[uint8_t temp_buf[LIBSPDM_MAX_MESSAGE_BUFFER_SIZE];](https://github.com/DMTF/libspdm/blob/main/unit_test/test_spdm_requester/encap_request.c#L180)

The libspdm_requester_encap_request_test_receive_message calls [libspdm_transport_test_encode_message](https://github.com/DMTF/libspdm/blob/main/unit_test/spdm_transport_test_lib/common.c#L78) with the 6th parameter as the temp_buf.

This `message` parameter in [`libspdm_transport_test_encode_message`](https://github.com/DMTF/libspdm/blob/main/unit_test/spdm_transport_test_lib/common.c#L78) holds the `temp_buf` pointer.
This `message` parameter is now passed to  [`libspdm_test_encode_message`](https://github.com/DMTF/libspdm/blob/main/unit_test/spdm_transport_test_lib/test.c#L61) as the `message` parameter.
Inside `libspdm_test_encode_message`, the `message `parameter is used incorrectly as if it had memory before the message parameter.

`message` holds the `temp_buf `pointer, and the header is subtracted from it, but there was no space allocated for the header earlier in the flow.
`*transport_message = (uint8_t *)message - sizeof(libspdm_test_message_header_t);`

```
libspdm_return_t libspdm_requester_encap_request_test_receive_message(
    void *spdm_context, size_t *response_size,
    void **response, uint64_t timeout)
{
    ...
   case 0x4:
    {
        spdm_digest_response_t *spdm_response;
        uint8_t temp_buf[LIBSPDM_MAX_MESSAGE_BUFFER_SIZE];
        size_t temp_buf_size;

        ((libspdm_context_t *)spdm_context)
        ->connection_info.algorithm.base_hash_algo =
            m_libspdm_use_hash_algo;
        temp_buf_size = sizeof(spdm_get_encapsulated_request_request_t);
        spdm_response = (void *)temp_buf;
        spdm_response->header.spdm_version = SPDM_MESSAGE_VERSION_10;
        spdm_response->header.request_response_code = SPDM_ENCAPSULATED_REQUEST;
        spdm_response->header.param1 = 0;
        spdm_response->header.param2 = 0;

        libspdm_transport_test_encode_message(spdm_context, NULL, false,
                                              false, temp_buf_size,
                                              temp_buf, response_size,
                                              response);
    }
    ...
}

// "temp_buf" becomes the "message" parameter in libspdm_transport_test_encode_message:
libspdm_return_t libspdm_transport_test_encode_message(
    void *spdm_context, const uint32_t *session_id, bool is_app_message,
    bool is_requester, size_t message_size, void *message,
    size_t *transport_message_size, void **transport_message)
{
    ...
            status = libspdm_test_encode_message(NULL, message_size, message,
                                             transport_message_size,
                                             transport_message); 
    ...
}

// "temp_buf" again is the "message" parameter in libspdm_test_encode_message
// Bug occurs because this function subtracts from "message" to get the transport header at the beginning.
//     *transport_message = (uint8_t *)message - sizeof(libspdm_test_message_header_t);

libspdm_return_t libspdm_test_encode_message(const uint32_t *session_id, size_t message_size,
                                             void *message,
                                             size_t *transport_message_size,
                                             void **transport_message)
{
    size_t aligned_message_size;
    size_t alignment;
    libspdm_test_message_header_t *test_message_header;

    alignment = LIBSPDM_TEST_ALIGNMENT;
    aligned_message_size =
        (message_size + (alignment - 1)) & ~(alignment - 1);

    *transport_message_size =
        aligned_message_size + sizeof(libspdm_test_message_header_t);
    *transport_message = (uint8_t *)message - sizeof(libspdm_test_message_header_t); // Bug here.
    test_message_header = *transport_message;
    if (session_id != NULL) {
        test_message_header->message_type =
            LIBSPDM_TEST_MESSAGE_TYPE_SECURED_TEST;
        LIBSPDM_ASSERT(*session_id == *(uint32_t *)(message));
        if (*session_id != *(uint32_t *)(message)) {
            return LIBSPDM_STATUS_INVALID_MSG_FIELD;
        }
    } else {
        test_message_header->message_type = LIBSPDM_TEST_MESSAGE_TYPE_SPDM;
    }
    libspdm_zero_mem((uint8_t *)message + message_size,
                     aligned_message_size - message_size);
    return LIBSPDM_STATUS_SUCCESS;
}
```
