### ISSUE TITLE
question about LIBSPDM_MAX_REQUSET_INFO_SIZE 

### ISSUE THREAD

**Issue by hiption** [DMTF/libspdm#945]
Hi, all

I want to know why LIBSPDM_MAX_REQUSET_INFO_SIZE is 0x300?

**Comment by jyao1** [comment]
Ummm. Maybe no need to define LIBSPDM_MAX_REQUSET_INFO_SIZE in libspdm.

It could be defined in the device secret lib as implementation choice.
