### ISSUE TITLE
Document the macros used by libspdm

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#950]
For the upcoming checkpoint we should document the macros consumed by libspdm and how the integrator can use them.

**Comment by jyao1** [comment]
@steven-bellock , this seems the last issue. When you can create a PR?

**Comment by steven-bellock** [comment]
I'll work on that this week.

**Comment by jyao1** [comment]
@steven-bellock , any progress on this?

**Comment by steven-bellock** [comment]
Yes, but I am realizing that a lot of the `_LENGTH` macros can be removed / refactored, especially now that we have `LIBSPDM_SENDER_RECEIVE_BUFFER_SIZE`. So what I think I'll do is just add comments to `spdm_lib_confg.h` for the Q2 tag and then propose how they can be refactored for the Q3 tag. Once that's solid then I can do a more formal (and binding) document for the macros for Q3.

**Comment by jyao1** [comment]
Now, let's finish Q2 tag.
I think we can discuss refactor later.

**Comment by jyao1** [comment]
Merged.
Do you want to keep the issue and remove STABLE tag? or close the issue and open a new one?
Either is OK for me.

**Comment by steven-bellock** [comment]
Let's close this one and I'll open new ones for refactoring and documenting.
