### ISSUE TITLE
Why we are using large buffers to store message b and message m data?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#962]
I see when LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT is enabled, this is structure for spdm_transcript_t,

typedef struct {
    /* the message_a must be plan text because we do not know the algorithm yet.*/
    small_managed_buffer_t message_a;
#if LIBSPDM_RECORD_TRANSCRIPT_DATA_SUPPORT
    large_managed_buffer_t message_b;
    small_managed_buffer_t message_c;
    large_managed_buffer_t message_mut_b;
    small_managed_buffer_t message_mut_c;
    large_managed_buffer_t message_m;
#else
    void                   *digest_context_m1m2;
    void                   *digest_context_mut_m1m2;
    void                   *digest_context_l1l2;
#endif
} spdm_transcript_t;

I see they are using large buffers for message b and message m. Message b is because it will store the certificate chain but what about message m? Is it going to hold large data? whether measurement blocks are large to be stored?

**Comment by jyao1** [comment]
message_b includes the whole certificate chain, which will be big.

**Comment by PrakashK94** [comment]
Yes, that I understand it, what about message m? whether this also will be big?

**Comment by jyao1** [comment]
message_m is measurement data. A device may include multiple measurement records, which might be big.

The definition record length is even in 3 bytes.

**Comment by PrakashK94** [comment]
Whether measurement block length will be big or it will be opaque data length which will be big in case of message M?
