### ISSUE TITLE
spdm_generate_measurement_signature function creates l1l2 buffer of large size on stack and then it calls to spdm_calculate_l1l2() which also uses large buffer and copy large buffer data to caller variable?

### ISSUE THREAD

**Issue by PrakashK94** [DMTF/libspdm#963]
Could you please let me know why we are maintaining two copies of l1l2 buffer? One in spdm_generate_measurement_signature function and other in spdm_calculate_l1l2()? Can we not use single buffer to pass in and get the data in that buffer and then return back that buffer directly?

**Comment by jyao1** [comment]
Where is the copy in libspdm_calculate_l1l2() ? Can you give a link?
