### ISSUE TITLE
Unneeded and unwanted #includes

### ISSUE THREAD

**Issue by steven-bellock** [DMTF/libspdm#98]
https://github.com/DMTF/libspdm/blob/8daea2f4f61673ca39ef8a10100917c483e1125c/library/spdm_requester_lib/get_capabilities.c#L8

**Comment by jyao1** [comment]
agree

**Comment by steven-bellock** [comment]
Also 

https://github.com/DMTF/libspdm/blob/77c33789864cdd55d2738ff64ecf5ce80db95eb2/os_stub/cryptlib_mbedtls/sys_call/mem_allocation.c#L14
