### ISSUE TITLE
Master-Secret calculation inconsistent with SPDM specification

### ISSUE THREAD

**Issue by annarossa** [DMTF/libspdm#987]
In master_secret calculation salt and IKM seem to have swapped places.
In  DSP0274_1.2.0 (paragraph 738 & 742) for Master-Secret salt is Salt_1 and IKM is 0_filled, and in the code it is otherwise.
master_secret calculation:
https://github.com/DMTF/libspdm/blob/97d23cbedeac85fa24e59de8c38e313509634752/library/spdm_secured_message_lib/libspdm_secmes_session.c#L424-L427

https://github.com/DMTF/libspdm/blob/97d23cbedeac85fa24e59de8c38e313509634752/include/library/spdm_crypt_lib.h#L722-L724

**Comment by jyao1** [comment]
@annarossa , good catch!

**Comment by steven-bellock** [comment]
@jyao1 In the specification `HMAC-Hash` is ill-defined, but assuming that `HMAC-Hash` is defined as `HMAC-Hash(key, data)` libspdm is correct no?

**Comment by jyao1** [comment]
Checking https://github.com/DMTF/libspdm/blob/97d23cbedeac85fa24e59de8c38e313509634752/library/spdm_secured_message_lib/libspdm_secmes_session.c#L237-L242

They must be consistent.

**Comment by jyao1** [comment]
Since they are not consistent, one of them is wrong.

**Comment by steven-bellock** [comment]
The SPDM specification says
>A key schedule describes how the various keys such as encryption keys used by a session are derived, and when each key is used. The default SPDM key schedule makes heavy use of HMAC, which [RFC2104](https://tools.ietf.org/html/rfc2104) defines, and HKDF-Expand, which [RFC5869](https://tools.ietf.org/html/rfc5869) describes.

So 5869 is only used for `HKDF-Expand`. 5869 doesn't define `HMAC` or `HMAC-Hash` but it does define `hmac_md5(text, text_len, key, key_len, digest)` in which case the text / data is the first parameter and the key is the second parameter.

**Comment by jyao1** [comment]
I am filing SPDM spec issue to get it clarified.

**Comment by steven-bellock** [comment]
>Assuming HMAC-Hash(salt, IKM) == HMAC(key, input data), we need fix handshake secret calculation, right?

Correct, though we should delay the Q2 checkpoint until the specification is resolved and this issue needs to be broadcast widely since it effects interoperability and (possibly) security. It seems like folks that are implementing non-libspdm endpoints haven't made it to session establishment, and that's why we haven't run into this issue sooner.
