### ISSUE TITLE
Error handling for CHALLENGE_AUTH signature generation

### ISSUE THREAD

**Issue by rw8896** [DMTF/libspdm#99]
This is a follow-up issue of #24 .

1. Before returning Error response, we should also reset message_C buffer.
https://github.com/DMTF/libspdm/blob/8daea2f4f61673ca39ef8a10100917c483e1125c/library/spdm_responder_lib/challenge_auth.c#L202-L208

2. For the Responder, the error handling of appending response should also remove the previously appended request message.

**Comment by jyao1** [comment]
agree

**Comment by steven-bellock** [comment]
Approved.
